force-app/main/default/objects/SAP_Staging__c/SAP_Staging__c.object-meta.xml
<CustomObject>
    <label>SAP Staging</label>
    <nameField>
        <displayFormat>D-{0}</displayFormat>
        <label>SAP Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAP Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAP_Staging__c/fields/CreationInd__c.field-meta.xml
<CustomField>
    <fullName>CreationInd__c</fullName>
    <label>CreationInd</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/Error_Processing_to_GSAP__c.field-meta.xml
<CustomField>
    <fullName>Error_Processing_to_GSAP__c</fullName>
    <label>Error Processing to GSAP</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/Processing_Indicator__c.field-meta.xml
<CustomField>
    <fullName>Processing_Indicator__c</fullName>
    <label>Processing Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>New</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Processed</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Error</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RV_GSAPContractFailureEmailNotify_Test.cls
/*****************************************************************************************
* @author       Abhilash     
* @date         2021-02-11
* @description  Test class for: RV_GSAPContractFailureEmailNotify (SAP_Staging__c object)
*
* --------------------------------------------------------------------------
*   Developer                  Date                Description
* --------------------------------------------------------------------------* 
*   Abhilash                  2021-02-11          Test class for RV_GSAPContractFailureEmailNotify class
******************************************************************************************/
@isTest
public class RV_GSAPContractFailureEmailNotify_Test {

    @testSetup static void setup(){        
        SAP_Staging__c sapStaging = new SAP_Staging__c();
        sapStaging.SfItemShtNo__c = 'SHT - 145057';
        sapStaging.Processing_Indicator__c = '01';
        insert sapStaging;        
    }    
    
    static testmethod void GSAPContractFailureEmail_forCreation()
    {
        test.startTest();     
        SAP_Staging__c sapStagingData = new SAP_Staging__c();
        List<SAP_Staging__c> sapStagingError = new List<SAP_Staging__c> ();
        List<Id> sapStagingIds = new List<Id>();
        for(SAP_Staging__c sapStaging : [Select Id, SfItemShtNo__c, Processing_Indicator__c, Error_Processing_to_GSAP__c, createdby.Email, LastModifiedBy.Email from SAP_Staging__c limit 1])
        {
            sapStagingData.Id = sapStaging.Id;
            sapStagingData.Processing_Indicator__c = '03';
            sapStagingData.Error_Processing_to_GSAP__c = 'Test Error';
            sapStagingData.CreationInd__c = 'C';
            sapStagingIds.add(sapStaging.Id);
            sapStagingError.add(sapStagingData);
        }
        
        if(sapStagingError.size()>0)
           update sapStagingError;
        
        RV_GSAPContractFailureEmailNotify.GSAPContractFailureEmailNotify(sapStagingIds);
        
        test.stopTest();
    }
    
    static testmethod void GSAPContractFailureEmail_forCancellation()
    {
        test.startTest();     
        SAP_Staging__c sapStagingData = new SAP_Staging__c();
        List<SAP_Staging__c> sapStagingError = new List<SAP_Staging__c> ();
        List<Id> sapStagingIds = new List<Id>();
        for(SAP_Staging__c sapStaging : [Select Id, SfItemShtNo__c, Processing_Indicator__c, Error_Processing_to_GSAP__c, createdby.Email, LastModifiedBy.Email from SAP_Staging__c limit 1])
        {
            sapStagingData.Id = sapStaging.Id;
            sapStagingData.Processing_Indicator__c = '03';
            sapStagingData.Error_Processing_to_GSAP__c = 'Test Error';
            sapStagingData.CreationInd__c = 'D';
            sapStagingIds.add(sapStaging.Id);
            sapStagingError.add(sapStagingData);
        }
        
        if(sapStagingError.size()>0)
           update sapStagingError;
        
        RV_GSAPContractFailureEmailNotify.GSAPContractFailureEmailNotify(sapStagingIds);
        
        test.stopTest();
    }
    
}