force-app/main/default/objects/SAP_Staging__c/SAP_Staging__c.object-meta.xml
<CustomObject>
    <label>SAP Staging</label>
    <nameField>
        <displayFormat>D-{0}</displayFormat>
        <label>SAP Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAP Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAP_Staging__c/fields/Processing_Indicator__c.field-meta.xml
<CustomField>
    <fullName>Processing_Indicator__c</fullName>
    <label>Processing Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>New</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Processed</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Error</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RV_SAPStagingNoResponseEmailBatchTest.cls
/**
 * Created by Dharmendra.Singh2 on 11/12/2020.
 */
@IsTest
public class RV_SAPStagingNoResponseEmailBatchTest {

    @TestSetup
    public static void setup(){
        List<SAP_Staging__c> sapStagings = new List<SAP_Staging__c>();
        SAP_Staging__c sapStaging = new SAP_Staging__c();
        //sapStaging.Sent_to_GSAP__c = true;
        sapStaging.SendEmailNoGSAPResponse__c = false;
        sapStaging.Processing_Indicator__c = '01';
        insert sapStaging;
        sapStagings.add(sapStaging);

    }
    public static testMethod void sendEmailBatch(){

        Test.startTest();
        RV_SAPStagingNoResponseEmailSchl emailSchl= new RV_SAPStagingNoResponseEmailSchl();
        String cronExpr = '0 0 23 * * ?';
        String jobId = System.schedule('EmailBatchJob', cronExpr, emailSchl);
        emailSchl.execute(null);
        Test.stopTest();
    }

}