force-app/main/default/objects/IK_Location__c/IK_Location__c.object-meta.xml
<CustomObject>
    <label>IK_Location</label>
    <nameField>
        <label>IK_Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IK_Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IK_Location__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <label>Plant Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/InfoKiosk_Alert__c.object-meta.xml
<CustomObject>
    <label>InfoKiosk Alert</label>
    <nameField>
        <displayFormat>Alert-{0000}</displayFormat>
        <label>Email Alert Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InfoKiosk Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/All_Changes__c.field-meta.xml
<CustomField>
    <fullName>All_Changes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>All Changes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/Anything_changes__c.field-meta.xml
<CustomField>
    <fullName>Anything_changes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Anything changes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/Existing_items_are_modified__c.field-meta.xml
<CustomField>
    <fullName>Existing_items_are_modified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Existing items are modified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/Items_are_deleted__c.field-meta.xml
<CustomField>
    <fullName>Items_are_deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Items are deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/New_items_are_added__c.field-meta.xml
<CustomField>
    <fullName>New_items_are_added__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New items are added</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/Select_Location__c.field-meta.xml
<CustomField>
    <fullName>Select_Location__c</fullName>
    <label>Select Location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aberdeen</fullName>
                <isActive>false</isActive>
                <label>Aberdeen</label>
            </value>
            <value>
                <fullName>Altmannshofen Shell Depot</fullName>
            </value>
            <value>
                <fullName>Andernach Dötsch Depot</fullName>
            </value>
            <value>
                <fullName>Aschaffenburg Baywa Depot</fullName>
            </value>
            <value>
                <fullName>Augsburg Präg depot</fullName>
            </value>
            <value>
                <fullName>Avonmouth</fullName>
                <isActive>false</isActive>
                <label>Avonmouth</label>
            </value>
            <value>
                <fullName>Bendorf Oiltanking Depot</fullName>
            </value>
            <value>
                <fullName>Berlin Oiltanking Depot</fullName>
            </value>
            <value>
                <fullName>Berlin Unitank depot</fullName>
            </value>
            <value>
                <fullName>Bertrange</fullName>
            </value>
            <value>
                <fullName>Birmingham Airport</fullName>
                <isActive>false</isActive>
                <label>Birmingham Airport</label>
            </value>
            <value>
                <fullName>Birsfdn Rhytank depot</fullName>
            </value>
            <value>
                <fullName>Birsfdn Varo depot</fullName>
            </value>
            <value>
                <fullName>Bramhall</fullName>
                <isActive>false</isActive>
                <label>Bramhall</label>
            </value>
            <value>
                <fullName>Braunschwg Varo depot</fullName>
            </value>
            <value>
                <fullName>Bremen HGM Depot</fullName>
            </value>
            <value>
                <fullName>Shell/OMV Burghausen</fullName>
                <label>Burghausen OMV Depot</label>
            </value>
            <value>
                <fullName>Clydebank</fullName>
                <isActive>false</isActive>
                <label>Clydebank</label>
            </value>
            <value>
                <fullName>Collombey Tamoil depot</fullName>
            </value>
            <value>
                <fullName>Cressier Varo depot</fullName>
            </value>
            <value>
                <fullName>Cunnersdorf Tabeg Depot</fullName>
            </value>
            <value>
                <fullName>Dortmund-Lünen Varo Depot</fullName>
            </value>
            <value>
                <fullName>Duisburg Tanquid</fullName>
                <label>Duisburg Tanquid Depot</label>
            </value>
            <value>
                <fullName>Duisburg Total Depot</fullName>
            </value>
            <value>
                <fullName>Duisburg Varo Depot</fullName>
            </value>
            <value>
                <fullName>Emleben Unitank depot</fullName>
            </value>
            <value>
                <fullName>Erlangen Varo Depot</fullName>
            </value>
            <value>
                <fullName>Essen UTG Depot</fullName>
            </value>
            <value>
                <fullName>Esso West London</fullName>
                <isActive>false</isActive>
                <label>Esso West London</label>
            </value>
            <value>
                <fullName>Shell/OMV Feldkirchen</fullName>
                <label>Feldkirchen OMV Depot</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/Select_Products__c.field-meta.xml
<CustomField>
    <fullName>Select_Products__c</fullName>
    <label>Select Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All Products</fullName>
            </value>
            <value>
                <fullName>AGO</fullName>
            </value>
            <value>
                <fullName>AGO Austria</fullName>
            </value>
            <value>
                <fullName>AGO VPD</fullName>
            </value>
            <value>
                <fullName>Avgas</fullName>
            </value>
            <value>
                <fullName>GTL</fullName>
            </value>
            <value>
                <fullName>IGO 50ppm</fullName>
            </value>
            <value>
                <fullName>Jet-A1</fullName>
            </value>
            <value>
                <fullName>ULG100 VP</fullName>
            </value>
            <value>
                <fullName>ULG95 E10</fullName>
            </value>
            <value>
                <fullName>ULG95 E5</fullName>
            </value>
            <value>
                <fullName>ULG98</fullName>
            </value>
            <value>
                <fullName>AD10</fullName>
                <isActive>false</isActive>
                <label>AD10</label>
            </value>
            <value>
                <fullName>AGO B0</fullName>
                <isActive>false</isActive>
                <label>AGO B0</label>
            </value>
            <value>
                <fullName>AGO B0 CH</fullName>
                <isActive>false</isActive>
                <label>AGO B0 CH</label>
            </value>
            <value>
                <fullName>AGO B7</fullName>
                <isActive>false</isActive>
                <label>AGO B7</label>
            </value>
            <value>
                <fullName>Dry Base</fullName>
                <isActive>false</isActive>
                <label>Dry Base</label>
            </value>
            <value>
                <fullName>Ethanol</fullName>
                <isActive>false</isActive>
                <label>Ethanol</label>
            </value>
            <value>
                <fullName>FAME</fullName>
                <isActive>false</isActive>
                <label>FAME</label>
            </value>
            <value>
                <fullName>GTL B0</fullName>
                <isActive>false</isActive>
                <label>GTL B0</label>
            </value>
            <value>
                <fullName>IGO 1000ppm</fullName>
                <isActive>false</isActive>
                <label>IGO 1000ppm</label>
            </value>
            <value>
                <fullName>PU10</fullName>
                <isActive>false</isActive>
                <label>PU10</label>
            </value>
            <value>
                <fullName>ULG95 E0</fullName>
                <isActive>false</isActive>
                <label>ULG95 E0</label>
            </value>
            <value>
                <fullName>ULG95_BOB_E10</fullName>
                <isActive>false</isActive>
                <label>ULG95_BOB_E10</label>
            </value>
            <value>
                <fullName>ULG95_BOB_E5</fullName>
                <isActive>false</isActive>
                <label>ULG95_BOB_E5</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/Someone_changes_an_item_created_by_me__c.field-meta.xml
<CustomField>
    <fullName>Someone_changes_an_item_created_by_me__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Someone changes an item created by me</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/Someone_changes_item_last_modified_by_me__c.field-meta.xml
<CustomField>
    <fullName>Someone_changes_item_last_modified_by_me__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Someone changes item last modified by me</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/User_Selection__c.field-meta.xml
<CustomField>
    <fullName>User_Selection__c</fullName>
    <label>User Selection</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All Changes</fullName>
            </value>
            <value>
                <fullName>New items are added</fullName>
            </value>
            <value>
                <fullName>Existing items are modified</fullName>
            </value>
            <value>
                <fullName>Items are deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IK_InfoKioskAlertHandler.cls
/*****************************************************************************
@Name:  IK_InfoKioskAlertHandler     
@=========================================================================
@Purpose: Trigger handler will execute on insert and update and delete to assign the  user in particular user group 
         
@=========================================================================
@History                                                            
@---------                                                            
@VERSION AUTHOR                            DATE                DETAIL                                 
@1.0 - Dhriti Krishna Ghosh Moulick      12/10/2017         INITIAL DEVELOPMENT

******************************************************************************/
public class IK_InfoKioskAlertHandler {
    
    public static void onbeforeinsertInfoKioskAlert(List<InfoKiosk_Alert__c> alertnewlst){
        
        Map<String,List<String>> locationcodeMap = new Map<String,List<String>>();
        Set<String> locationCodeSet = new Set<String>();
        
        for(InfoKiosk_Alert__c alertDetails : alertnewlst){
       	  	  if(alertDetails.All_Changes__c == true ){
       	  	  	 alertDetails.User_Selection__c = 'All Changes';
              }
              if(alertDetails.New_items_are_added__c == true){
       	  	  	 alertDetails.User_Selection__c = 'New items are added';
              }
              if(alertDetails.Existing_items_are_modified__c == true){
       	  	  	 alertDetails.User_Selection__c = 'Existing items are modified';
              }
              if(alertDetails.Items_are_deleted__c == true){
       	  	  	 alertDetails.User_Selection__c = 'Items are deleted';
              }
              List<String> locationCodeLst = new List<String>();
              if(alertDetails.Select_Location__c <> null){
             		locationCodeLst.addall(alertDetails.Select_Location__c.split(';'));
                    locationcodeMap.put(alertDetails.createdById,locationCodeLst);
              }else{
                  locationcodeMap.put(alertDetails.createdById,new List<String>{'All Location'});
              }
              if(alertDetails.Select_Location__c <> null){
              		locationCodeSet.addall(alertDetails.Select_Location__c.split(';'));
              }
        }
        System.debug('------locationCodeSet-------'+locationCodeSet);
        if(!locationcodeMap.values().isEmpty()){
             List<IK_location__c> locationLst = [Select id,Name,Plant_Code__c
                                             from IK_location__c where Name in:locationCodeSet];
            Map<String,String> locationNameCodeMap = new Map<String,String>();
            if(!locationLst.isEmpty()){
                for(IK_location__c loc : locationLst){
                    locationNameCodeMap.put(loc.Name, loc.Plant_Code__c);
                }
            }
            
            for(InfoKiosk_Alert__c alertDetails : alertnewlst){
                if(locationcodeMap.containskey(alertDetails.CreatedById)){
                    List<String> locNameLst = locationcodeMap.get(alertDetails.CreatedById);
                    String locCode = '';
                    for(String locName : locNameLst){
                        if(locationNameCodeMap.containskey(locName)){
                            locCode+=locationNameCodeMap.get(locName)+';';
                        }
                    }
                    if(locCode.endsWith(';')){
                        locCode = locCode.removeEnd(';');
                        System.debug('-----------'+locCode);
                    }
                   
                    alertDetails.Location_Code__c = locCode;
                }
            }
        }
    }
    
    public static void onafterinsertInfoKioskAlert(List<InfoKiosk_Alert__c> alertnewlst){
           
           List<String> infoLst = new List<String>();
           for(InfoKiosk_Alert__c alrt : alertnewlst){
               
               infoLst.add(alrt.ID);
           }
           
       	   createpublicGroup(infoLst);
       }
    
    @future
    public static void createpublicGroup(List<String> alertID){
        
          Map<String,Group> groupMap = new Map<String,Group>();
          Set<String> setOfGroupName = new Set<String>();
          setOfGroupName = fetchGroupDevName();
       	  List<Group> groupLst = IK_DAL.fetchGroup(setOfGroupName);
       	  if(groupLst <> null && groupLst.size() > 0){
              
       	  	  for(Group grpLst:groupLst){
       	  	  	groupMap.put(grpLst.DeveloperName,grpLst);
       	  	  }
       	  } 
           List<InfoKiosk_Alert__c> infoLst = new List<InfoKiosk_Alert__c>();
          infoLst = IK_DAL.fetchInfoKioskAlert(alertID);
       	  List<GroupMember> addlistGroupMember =new List<GroupMember>();  
       	  for(InfoKiosk_Alert__c alertDetails : infoLst){
       	  	
       	  	  
       	  	  if(alertDetails.All_Changes__c == true || alertDetails.Anything_changes__c == true){
       	  	  	 alertDetails.User_Selection__c = 'All Changes';
                  
       	  	  	 if(groupMap.containskey(Label.All_Changes_c)){
       	  	  	 	GroupMember gm= new GroupMember(); 
       	  	  	 	gm.GroupId = groupMap.get(Label.All_Changes_c).Id;
       	  	  	 	gm.UserOrGroupId = UserInfo.getUserId();
       	  	  	 	addlistGroupMember.add(gm);
       	  	  	 }
       	  	  }
       	  	  if(alertDetails.New_items_are_added__c == true){
       	  	  	 alertDetails.User_Selection__c = 'New items are added';
       	  	  	 if(groupMap.containskey(Label.New_items_are_added_c)){
       	  	  	 	GroupMember gm= new GroupMember(); 
       	  	  	 	gm.GroupId = groupMap.get(Label.New_items_are_added_c).Id;
       	  	  	 	gm.UserOrGroupId = UserInfo.getUserId();
       	  	  	 	addlistGroupMember.add(gm);
       	  	  	 }
       	  	  }
       	  	  if(alertDetails.Existing_items_are_modified__c == true){
       	  	  	 alertDetails.User_Selection__c = 'Existing items are modified';
       	  	  	 if(groupMap.containskey(Label.Existing_items_are_modified_c)){
       	  	  	 	GroupMember gm= new GroupMember(); 
       	  	  	 	gm.GroupId = groupMap.get(Label.Existing_items_are_modified_c).Id;
       	  	  	 	gm.UserOrGroupId = UserInfo.getUserId();
       	  	  	 	addlistGroupMember.add(gm);
       	  	  	 }
       	  	  }
              if(alertDetails.Items_are_deleted__c == true){
       	  	  	 alertDetails.User_Selection__c = 'Items are deleted';
       	  	  	 if(groupMap.containskey(Label.Items_are_deleted_c)){
       	  	  	 	GroupMember gm= new GroupMember(); 
       	  	  	 	gm.GroupId = groupMap.get(Label.Items_are_deleted_c).Id;
       	  	  	 	gm.UserOrGroupId = UserInfo.getUserId();
       	  	  	 	addlistGroupMember.add(gm);
       	  	  	 }
       	  	  }
              /*if(alertDetails.Someone_changes_item_last_modified_by_me__c == true){
       	  	  	
       	  	  	 if(groupMap.containskey(Label.Info_Kiosk_Last_Modfied_By_me)){
       	  	  	 	GroupMember gm= new GroupMember(); 
       	  	  	 	gm.GroupId = groupMap.get(Label.Info_Kiosk_Last_Modfied_By_me).Id;
       	  	  	 	gm.UserOrGroupId = UserInfo.getUserId();
       	  	  	 	addlistGroupMember.add(gm);
       	  	  	 }
       	  	  }
              if(alertDetails.Someone_changes_an_item_created_by_me__c == true){
       	  	  	 System.debug('$$$$$$$$$$$$$$$'+alertDetails.Someone_changes_an_item_created_by_me__c);
       	  	  	 if(groupMap.containskey(Label.Info_Kiosk_Items_Created_By_Me)){
       	  	  	 	System.debug('$$$$$$$$$$$$$$$'+Label.Info_Kiosk_Items_Created_By_Me);
                    GroupMember gm= new GroupMember(); 
       	  	  	 	gm.GroupId = groupMap.get(Label.Info_Kiosk_Items_Created_By_Me).Id;
       	  	  	 	gm.UserOrGroupId = UserInfo.getUserId();
       	  	  	 	addlistGroupMember.add(gm);
       	  	  	 }
       	  	  }*/
       	  }
       	  System.debug('&&&&&&&addlistGroupMember&&&&&'+addlistGroupMember);
       	  if(addlistGroupMember <> null && addlistGroupMember.size() > 0){
       	  	 try{
       	  	 	insert addlistGroupMember;
       	  	 }catch(Exception e){
       	  	 	System.debug('$$$$$$$$$$$$$$$'+e);
       	  	 }
       	  }
    }
    
    public static void onbeforeUpdateInfoKioskAlert(List<InfoKiosk_Alert__c> alertnewlst,List<InfoKiosk_Alert__c> alertoldlst,
    Map<Id,InfoKiosk_Alert__c> alertnewMap,Map<Id,InfoKiosk_Alert__c> alertoldMap){
        
        Map<String,List<String>> locationcodeMap = new Map<String,List<String>>();
        Set<String> locationCodeSet = new Set<String>();
        
        for(InfoKiosk_Alert__c alertDetails : alertnewlst){
            
       	  	  if(alertDetails.All_Changes__c == true ){
       	  	  	 alertDetails.User_Selection__c = 'All Changes';
              }
              if(alertDetails.New_items_are_added__c == true){
       	  	  	 alertDetails.User_Selection__c = 'New items are added';
              }
              if(alertDetails.Existing_items_are_modified__c == true){
       	  	  	 alertDetails.User_Selection__c = 'Existing items are modified';
              }
              if(alertDetails.Items_are_deleted__c == true){
       	  	  	 alertDetails.User_Selection__c = 'Items are deleted';
              }
            
              List<String> locationCodeLst = new List<String>();
              if(alertDetails.Select_Location__c <> null){
             		locationCodeLst.addall(alertDetails.Select_Location__c.split(';'));
                    locationcodeMap.put(alertDetails.createdById,locationCodeLst);
              }else{
                  locationcodeMap.put(alertDetails.createdById,new List<String>{'All Location'});
              }
              if(alertDetails.Select_Location__c <> null){
              	locationCodeSet.addall(alertDetails.Select_Location__c.split(';'));
              }
        }
        
        System.debug('------locationCodeSet-------'+locationCodeSet);
        System.debug('------locationcodeMap.values()-------'+locationcodeMap.values());
        if(!locationcodeMap.values().isEmpty()){
            List<IK_location__c> locationLst = [Select id,Name,Plant_Code__c
                                             from IK_location__c where Name in:locationCodeSet];
            Map<String,String> locationNameCodeMap = new Map<String,String>();
            if(!locationLst.isEmpty()){
                for(IK_location__c loc : locationLst){
                    locationNameCodeMap.put(loc.Name, loc.Plant_Code__c);
                }
            }
            
            for(InfoKiosk_Alert__c alertDetails : alertnewlst){
                if(locationcodeMap.containskey(alertDetails.CreatedById)){
                    List<String> locNameLst = locationcodeMap.get(alertDetails.CreatedById);
                    String locCode = '';
                    for(String locName : locNameLst){
                        if(locationNameCodeMap.containskey(locName)){
                            locCode+=locationNameCodeMap.get(locName)+';';
                        }
                    }
                    if(locCode.endsWith(';')){
                        locCode = locCode.removeEnd(';');
                        System.debug('-----------'+locCode.removeEnd(';'));
                    }
                   
                    alertDetails.Location_Code__c = locCode;
                }
            }
        }
    }
    
    public static void onafterupdateInfoKioskAlert(List<InfoKiosk_Alert__c> alertnewlst,List<InfoKiosk_Alert__c> alertoldlst,
    Map<Id,InfoKiosk_Alert__c> alertnewMap,Map<Id,InfoKiosk_Alert__c> alertoldMap){
          List<String> updateinfoLst = new List<String>();
          for(InfoKiosk_Alert__c iterateValue :alertnewlst){
              if((alertnewMap.get(iterateValue.ID).All_Changes__c <> alertoldMap.get(iterateValue.ID).All_Changes__c) ||
                 (alertnewMap.get(iterateValue.ID).New_items_are_added__c <> alertoldMap.get(iterateValue.ID).New_items_are_added__c) ||
                 (alertnewMap.get(iterateValue.ID).Existing_items_are_modified__c <> alertoldMap.get(iterateValue.ID).Existing_items_are_modified__c) ||
                (alertnewMap.get(iterateValue.ID).Items_are_deleted__c <> alertoldMap.get(iterateValue.ID).Items_are_deleted__c) ||
                
                (alertnewMap.get(iterateValue.ID).Someone_changes_item_last_modified_by_me__c <> alertoldMap.get(iterateValue.ID).Someone_changes_item_last_modified_by_me__c) ||
                (alertnewMap.get(iterateValue.ID).Someone_changes_an_item_created_by_me__c <> alertoldMap.get(iterateValue.ID).Someone_changes_an_item_created_by_me__c)){
                     if(iterateValue.All_Changes__c == true ||iterateValue.New_items_are_added__c == true || iterateValue.Existing_items_are_modified__c == true ||
                       iterateValue.Items_are_deleted__c == true  || iterateValue.Someone_changes_item_last_modified_by_me__c == true ||
                       iterateValue.Someone_changes_an_item_created_by_me__c == true){
                         System.debug('&&&&&iterateValue.Id&&&&&'+iterateValue.Id);
                         updateinfoLst.add(iterateValue.Id);
                     }
                 }                            
          }   
         if(!updateinfoLst.isEmpty()){
             
         		updatepublicGroupUsers(updateinfoLst);
         }
    }
    @future
    
    public static void updatepublicGroupUsers(List<String> alertID) {
        List<InfoKiosk_Alert__c> infoLst = new List<InfoKiosk_Alert__c>();
        infoLst = IK_DAL.fetchInfoKioskAlert(alertID);
        Map<String,Group> groupMap = new Map<String,Group>();
          Set<String> setOfGroupName = new Set<String>();
          setOfGroupName = fetchGroupDevName();
       	  List<Group> groupLst = IK_DAL.fetchGroup(setOfGroupName);
       	  if(groupLst <> null && groupLst.size() > 0){
       	  	  for(Group grpLst:groupLst){
       	  	  	groupMap.put(grpLst.DeveloperName,grpLst);
       	  	  } 
       	  } 
        List<GroupMember> gmUser= new List<GroupMember>(); 
        gmUser = IK_DAL.fetchGroupMember(groupMap.keySet(),UserInfo.getUserId());
        try{
            delete gmUser;
        }catch(Exception de){
            System.debug('$$$$$$$$$$$$$'+de);
        }
        List<GroupMember> addlistGroupMember =new List<GroupMember>(); 
        if(infoLst <> null && infoLst.size() > 0){
            
            for(InfoKiosk_Alert__c alertDetails : infoLst){
            	   
       	  	  if(alertDetails.All_Changes__c == true || alertDetails.Anything_changes__c == true){
       	  	  	 alertDetails.User_Selection__c = 'All Changes';
       	  	  	 if(groupMap.containskey(Label.All_Changes_c)){
       	  	  	 	GroupMember gm= new GroupMember();
       	  	  	 	gm.GroupId = groupMap.get(Label.All_Changes_c).Id;
       	  	  	 	gm.UserOrGroupId = UserInfo.getUserId();
       	  	  	 	addlistGroupMember.add(gm);
       	  	  	 }
       	  	  }
       	  	  if(alertDetails.New_items_are_added__c == true){
       	  	  	 alertDetails.User_Selection__c = 'New items are added';
       	  	  	 if(groupMap.containskey(Label.New_items_are_added_c)){
       	  	  	 	GroupMember gm= new GroupMember();
       	  	  	 	gm.GroupId = groupMap.get(Label.New_items_are_added_c).Id;
       	  	  	 	gm.UserOrGroupId = UserInfo.getUserId();
       	  	  	 	addlistGroupMember.add(gm);
       	  	  	 }
       	  	  }
       	  	  if(alertDetails.Existing_items_are_modified__c == true){
       	  	  	 alertDetails.User_Selection__c = 'Existing items are modified';
       	  	  	 if(groupMap.containskey(Label.Existing_items_are_modified_c)){
       	  	  	 	GroupMember gm= new GroupMember();
       	  	  	 	gm.GroupId = groupMap.get(Label.Existing_items_are_modified_c).Id;
       	  	  	 	gm.UserOrGroupId = UserInfo.getUserId();
       	  	  	 	addlistGroupMember.add(gm);
       	  	  	 }
       	  	  }
              if(alertDetails.Items_are_deleted__c == true){
       	  	  	 alertDetails.User_Selection__c = 'Items are deleted';
       	  	  	 if(groupMap.containskey(Label.Items_are_deleted_c)){
       	  	  	 	GroupMember gm= new GroupMember();
       	  	  	 	gm.GroupId = groupMap.get(Label.Items_are_deleted_c).Id;
       	  	  	 	gm.UserOrGroupId = UserInfo.getUserId();
       	  	  	 	addlistGroupMember.add(gm);
       	  	  	 }
       	  	  }
                /*if(alertDetails.Someone_changes_item_last_modified_by_me__c == true){
       	  	  	 System.debug('$$$$$$$$$$$$$$$'+alertDetails.Someone_changes_item_last_modified_by_me__c);
       	  	  	 if(groupMap.containskey(Label.Info_Kiosk_Last_Modfied_By_me)){
                     System.debug('$$$$$$$$$$$$$$$'+alertDetails.Someone_changes_item_last_modified_by_me__c);
       	  	  	 	GroupMember gm= new GroupMember();
       	  	  	 	gm.GroupId = groupMap.get(Label.Info_Kiosk_Last_Modfied_By_me).Id;
       	  	  	 	gm.UserOrGroupId = UserInfo.getUserId();
       	  	  	 	addlistGroupMember.add(gm);
       	  	  	 }
       	  	  }
              if(alertDetails.Someone_changes_an_item_created_by_me__c == true){
       	  	  	
       	  	  	 if(groupMap.containskey(Label.Info_Kiosk_Items_Created_By_Me)){
       	  	  	 	GroupMember gm= new GroupMember();
       	  	  	 	gm.GroupId = groupMap.get(Label.Info_Kiosk_Items_Created_By_Me).Id;
       	  	  	 	gm.UserOrGroupId = UserInfo.getUserId();
       	  	  	 	addlistGroupMember.add(gm);
       	  	  	 }
       	  	  }*/

            }
            if(addlistGroupMember <> null && addlistGroupMember.size() > 0){
                 try{
                    insert addlistGroupMember;
                 }catch(Exception e){
                    System.debug('$$$$$$$$$$$$$$$'+e);
                 }
       	    }
        }  
    }
    
    public static void onafterdeleteInfoKiosk(List<InfoKiosk_Alert__c> alertnewlst,
                                              List<InfoKiosk_Alert__c> alertoldlst,
    										  Map<Id,InfoKiosk_Alert__c> alertnewMap,
                                              Map<Id,InfoKiosk_Alert__c> alertoldMap){
                                                  
          List<String> updateinfoLst = new List<String>();
          Map<String,InfoKiosk_Alert__c> createdByIdMap = new Map<String,InfoKiosk_Alert__c>();                                        
          for(InfoKiosk_Alert__c iterateValue :alertoldlst){
              updateinfoLst.add(iterateValue.Id);
              createdByIdMap.put(iterateValue.CreatedById,iterateValue);                               
          }   
 
          List<InfoKiosk_Alert__c> fetchInfoKioskLst = [Select id,createdById,All_Changes__c,New_items_are_added__c,Existing_items_are_modified__c,Items_are_deleted__c,
               Anything_changes__c,Someone_changes_item_last_modified_by_me__c,Someone_changes_an_item_created_by_me__c,
               User_Selection__c,Select_Location__c,Select_Products__c,Location_Code__c from InfoKiosk_Alert__c 
                                                        where createdById in:createdByIdMap.keySet()];
          Boolean deleteUser = false; 
          Map<String,List<InfoKiosk_Alert__c>> fetchExistingInfoKioskMap = new Map<String,List<InfoKiosk_Alert__c>>();                                       
          for(InfoKiosk_Alert__c info : fetchInfoKioskLst){

              if(!fetchExistingInfoKioskMap.containskey(info.CreatedById)){
                  fetchExistingInfoKioskMap.put(info.CreatedById,new List<InfoKiosk_Alert__c> {info});
              }else{
                  List<InfoKiosk_Alert__c> infoKioskNewLst = fetchExistingInfoKioskMap.get(info.CreatedById);
                  infoKioskNewLst.add(info);
                  fetchExistingInfoKioskMap.put(info.CreatedById,infoKioskNewLst);
              }
          }

          if(!alertoldMap.isEmpty()){                                        
              for(InfoKiosk_Alert__c create : alertoldMap.values()){
                  if(fetchExistingInfoKioskMap.containskey(create.CreatedById)){
                      List<InfoKiosk_Alert__c> infoKioskLst = fetchExistingInfoKioskMap.get(create.CreatedById);
                      for(InfoKiosk_Alert__c infoKiosk : infoKioskLst){
                          if(infoKiosk.Id <> create.Id){
                              if(infoKiosk.User_Selection__c ==  create.User_Selection__c){
                                  deleteUser = true;
                              }
                          }
                      }
                  }                                     
              }  
          }
                                                  
          if(deleteUser == false){                                        
          		deletepublicGroupUsers(updateinfoLst);
          }
    }
    
    @future
    public static void deletepublicGroupUsers(List<String> alertID){
          Map<String,Group> groupMap = new Map<String,Group>();
          Set<String> setOfGroupName = new Set<String>();
          setOfGroupName = fetchGroupDevName();
       	  List<Group> groupLst = IK_DAL.fetchGroup(setOfGroupName);
       	  if(groupLst <> null && groupLst.size() > 0){
       	  	  for(Group grpLst:groupLst){
       	  	  	groupMap.put(grpLst.DeveloperName,grpLst);
       	  	  } 
       	  } 
          List<GroupMember> gmUser= new List<GroupMember>(); 
          gmUser =IK_DAL.fetchGroupMember(groupMap.keySet(),UserInfo.getUserId());
          try{
            delete gmUser;
          }catch(Exception de){
            System.debug('$$$$$$$$$$$$$'+de);
          }
    }
    
    public static Set<String> fetchGroupDevName(){
        Set<String> setOfGroupDevName = new Set<String>();
        setOfGroupDevName.add(Label.All_Changes_c);
        setOfGroupDevName.add(Label.New_items_are_added_c);
        setOfGroupDevName.add(Label.Existing_items_are_modified_c);
        setOfGroupDevName.add(Label.Items_are_deleted_c);
        setOfGroupDevName.add(Label.Info_Kiosk_Last_Modfied_By_me);
        setOfGroupDevName.add(Label.Info_Kiosk_Items_Created_By_Me);
        return setOfGroupDevName;
    }
}