force-app/main/default/objects/IK_Location__c/IK_Location__c.object-meta.xml
<CustomObject>
    <label>IK_Location</label>
    <nameField>
        <label>IK_Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IK_Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IK_Location__c/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE01</fullName>
            </value>
            <value>
                <fullName>AT01</fullName>
            </value>
            <value>
                <fullName>CH01</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IK_Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IK_Location__c/fields/LOC_Type__c.field-meta.xml
<CustomField>
    <fullName>LOC_Type__c</fullName>
    <label>LOC Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IK_Location__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Depot Location</fullName>
            </value>
            <value>
                <fullName>Shell Own Location</fullName>
            </value>
            <value>
                <fullName>3rd Party Rail Sources</fullName>
            </value>
            <value>
                <fullName>3rd Party Truck Sources</fullName>
            </value>
            <value>
                <fullName>Depot</fullName>
            </value>
            <value>
                <fullName>Refinery</fullName>
            </value>
            <value>
                <fullName>Gantry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IK_Location__c/fields/OMR_Region__c.field-meta.xml
<CustomField>
    <fullName>OMR_Region__c</fullName>
    <label>OMR Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>Rhine-Main</fullName>
            </value>
            <value>
                <fullName>Seefeld</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>South East</fullName>
            </value>
            <value>
                <fullName>South West</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Mid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IK_Location__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <label>Plant Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/IK_Location__c/fields/Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Region_Name__c</fullName>
    <label>Region Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>Mid</fullName>
            </value>
            <value>
                <fullName>SW</fullName>
            </value>
            <value>
                <fullName>OTHER-DE</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>SWITZERLAND</fullName>
            </value>
            <value>
                <fullName>LUXEMBOURG</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IK_Location__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>Rhine-Main</fullName>
            </value>
            <value>
                <fullName>Seefeld</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
            <value>
                <fullName>South-East</fullName>
            </value>
            <value>
                <fullName>South-West</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IK_Location__c/fields/Scenario_Type__c.field-meta.xml
<CustomField>
    <fullName>Scenario_Type__c</fullName>
    <label>Scenario Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Import</fullName>
            </value>
            <value>
                <fullName>Export</fullName>
            </value>
            <value>
                <fullName>Balanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IK_Location__c/fields/Shipping_Conditions_Name__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Conditions_Name__c</fullName>
    <formula>CASE(Shipping_Conditions__c,
10, &quot;Road Pickup&quot;,
11, &quot;Road Delivery&quot;,
21, &quot;Rail Delivery&quot;,
30, &quot;Vessel Pickup&quot;,
31, &quot;Vessel Delivery&quot;,
20, &quot;Rail Pickup&quot;,
80, &quot;In-Tank&quot;,
Null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shipping Conditions Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IK_Location__c/fields/Source_Location__c.field-meta.xml
<CustomField>
    <fullName>Source_Location__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Source Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/InfoKiosk_Alert__c.object-meta.xml
<CustomObject>
    <label>InfoKiosk Alert</label>
    <nameField>
        <displayFormat>Alert-{0000}</displayFormat>
        <label>Email Alert Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InfoKiosk Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/All_Changes__c.field-meta.xml
<CustomField>
    <fullName>All_Changes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>All Changes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/Enter_Internal_Email_Addresses__c.field-meta.xml
<CustomField>
    <fullName>Enter_Internal_Email_Addresses__c</fullName>
    <label>Enter Internal Email Addresses</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/Existing_items_are_modified__c.field-meta.xml
<CustomField>
    <fullName>Existing_items_are_modified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Existing items are modified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/External_Stakeholder_Email_addresses__c.field-meta.xml
<CustomField>
    <fullName>External_Stakeholder_Email_addresses__c</fullName>
    <inlineHelpText>Enter external stakeholder email address separated by each email address with ;</inlineHelpText>
    <label>External Stakeholder Email addresses</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/Items_are_deleted__c.field-meta.xml
<CustomField>
    <fullName>Items_are_deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Items are deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/New_items_are_added__c.field-meta.xml
<CustomField>
    <fullName>New_items_are_added__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New items are added</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/Send_notification_immediately__c.field-meta.xml
<CustomField>
    <fullName>Send_notification_immediately__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Send notification immediately</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Live_Disruption__c/Live_Disruption__c.object-meta.xml
<CustomObject>
    <label>Live Disruption</label>
    <nameField>
        <displayFormat>LDN-{0000}</displayFormat>
        <label>Live Disruption Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Live Disruptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Live_Disruption__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <label>Cause</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delayed Primary Transport</fullName>
            </value>
            <value>
                <fullName>Delayed 3rd Party Delivery</fullName>
            </value>
            <value>
                <fullName>Overlifting</fullName>
            </value>
            <value>
                <fullName>Hydrocarbon Availability</fullName>
            </value>
            <value>
                <fullName>3rd Party Information</fullName>
            </value>
            <value>
                <fullName>Planned Maintenance</fullName>
            </value>
            <value>
                <fullName>Unplanned Maintenance</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>CSO Cover</fullName>
            </value>
            <value>
                <fullName>Spec Change</fullName>
            </value>
            <value>
                <fullName>Weather Conditions</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Opening Hour</fullName>
            </value>
            <value>
                <fullName>Cancelled Primary transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Live_Disruption__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
            <value>
                <fullName>United kingdom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Live_Disruption__c/fields/IK_Locations__c.field-meta.xml
<CustomField>
    <fullName>IK_Locations__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>IK_Location__c</referenceTo>
    <relationshipLabel>Live Disruptions (IKLocation)</relationshipLabel>
    <relationshipName>Live_Disruptions2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Disruption__c/fields/IK_Option_1__c.field-meta.xml
<CustomField>
    <fullName>IK_Option_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Option 1</label>
    <referenceTo>IK_Location__c</referenceTo>
    <relationshipLabel>Live Disruptions</relationshipLabel>
    <relationshipName>Live_Disruptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Disruption__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <formula>TEXT(IK_Locations__r.Region_Name__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Live_Disruption__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Constraint</fullName>
            </value>
            <value>
                <fullName>Physical Product Outage</fullName>
            </value>
            <value>
                <fullName>Non-Physical Product Outage</fullName>
            </value>
            <value>
                <fullName>Outage</fullName>
                <isActive>false</isActive>
                <label>Outage</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IK_InfoKioskTestHelper.cls
public class IK_InfoKioskTestHelper {
  
    public static Group CreateGroupAllChanges(Group grpAllChanges){
        
         grpAllChanges.Name = 'Info Kiosk All Changes';
         return grpAllChanges;
    }
    
    public static Group CreateGroupItemsCreated(Group grpNewChanges){
          grpNewChanges.Name = 'Info Kiosk New Changes';
          return grpNewChanges;
    }
    
    public static Group CreateGroupItemsModified(Group grpExistingItems){
          grpExistingItems.Name = 'Info Kiosk Existing Items';
          return grpExistingItems;
    }
    
    public static Group CreateGroupItemsDeleted(Group grpDeletedItems){
          grpDeletedItems.Name = 'Info Kiosk Deleted Items';
          return grpDeletedItems;
    }
    
    public static InfoKiosk_Alert__c createInfoKioskAllChanges(InfoKiosk_Alert__c insertInfoKioskAllChanges){
        insertInfoKioskAllChanges.All_Changes__c = true;
        insertInfoKioskAllChanges.External_Stakeholder_Email_addresses__c = 'abc@gmailrde.com;cde@gmwsedail.com';
        insertInfoKioskAllChanges.Enter_Internal_Email_Addresses__c = 'qwe@gmailzq.com';
        insertInfoKioskAllChanges.Send_notification_immediately__c = true;
        return insertInfoKioskAllChanges;
    }
    
   
    
    public static InfoKiosk_Alert__c createInfoKioskNewCreate(InfoKiosk_Alert__c insertInfoKioskNewItems){
        insertInfoKioskNewItems.New_items_are_added__c = true;
        insertInfoKioskNewItems.External_Stakeholder_Email_addresses__c = 'abc@gmail.com;cde@gmail.com';
        insertInfoKioskNewItems.Send_notification_immediately__c = true;
        return insertInfoKioskNewItems;
    }
    
    public static InfoKiosk_Alert__c createInfoKioskItemsModified(InfoKiosk_Alert__c insertInfoKioskExistingItems){
        insertInfoKioskExistingItems.Existing_items_are_modified__c = true;
        insertInfoKioskExistingItems.External_Stakeholder_Email_addresses__c = 'abc@gmail.com;cde@gmail.com';
        insertInfoKioskExistingItems.Send_notification_immediately__c = true;
        return insertInfoKioskExistingItems;
    }
    
    public static InfoKiosk_Alert__c createInfoKioskItemsDeleted(InfoKiosk_Alert__c insertInfoKioskDeleteItems){
        insertInfoKioskDeleteItems.Items_are_deleted__c = true;
        insertInfoKioskDeleteItems.External_Stakeholder_Email_addresses__c = 'abc@gmail.com;cde@gmail.com';
        insertInfoKioskDeleteItems.Send_notification_immediately__c = true;
        return insertInfoKioskDeleteItems;
    }
    
    public static IK_Location__c insertLocation(IK_Location__c loc){
        
        loc.Name = 'Duisburg Varo depot';
        loc.Plant_Code__c = 'D140';
        loc.Source_Location__c = true;
        loc.Company_Code__c = 'DE01';
        loc.OMR_Region__c = 'West';
        loc.Sales_Region__c = 'West';
        loc.Location_Type__c = 'Shell Own Location';
        loc.LOC_Type__c = 'COO Barge';
        loc.Region_Name__c = 'East';
        //loc.Shipping_Conditions_Name__c = 'Road Pickup';
        //loc.Custom_Record_Type__c = 'InfoKiosk';
        loc.Scenario_Type__c = 'Import';
        return loc;
    }
    
    public static Live_Disruption__c insertLiveDisruptionAllProduct(Live_Disruption__c liveDisruption,IK_Location__c loc){
        
        liveDisruption.Status__c = 'Physical Product Outage';
        liveDisruption.Cause__c  = 'Delayed Primary Transport';
        liveDisruption.IK_Locations__c = loc.Id;
        liveDisruption.Country__c = 'Germany';
        liveDisruption.IK_Option_1__c = loc.Id;
        liveDisruption.Product__c = 'All Products';
        liveDisruption.Begin_Date__c = System.now();
        liveDisruption.Estimated_End_Date__c = System.now().addDays(1);
        liveDisruption.Comment__c = 'Live Disruption';  
        return liveDisruption;
    }
    
    public static Live_Disruption__c insertLiveDisruptionInProduct(Live_Disruption__c liveDisruption,IK_Location__c loc){
        
        liveDisruption.Status__c = 'Physical Product Outage';
        liveDisruption.Cause__c  = 'Delayed Primary Transport';
        liveDisruption.IK_Locations__c = loc.Id;
        liveDisruption.Country__c = 'Germany';
        liveDisruption.IK_Option_1__c = loc.Id;
        liveDisruption.Product__c = 'AGO;AGO VPD';
        liveDisruption.Begin_Date__c = System.now();
        liveDisruption.Estimated_End_Date__c = System.now().addDays(1);
        liveDisruption.Comment__c = 'Live Disruption';  
        return liveDisruption;
    }
}