force-app/main/default/objects/InfoKiosk_Alert__c/InfoKiosk_Alert__c.object-meta.xml
<CustomObject>
    <label>InfoKiosk Alert</label>
    <nameField>
        <displayFormat>Alert-{0000}</displayFormat>
        <label>Email Alert Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InfoKiosk Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/All_Changes__c.field-meta.xml
<CustomField>
    <fullName>All_Changes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>All Changes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/Anything_changes__c.field-meta.xml
<CustomField>
    <fullName>Anything_changes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Anything changes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/Existing_items_are_modified__c.field-meta.xml
<CustomField>
    <fullName>Existing_items_are_modified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Existing items are modified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/Items_are_deleted__c.field-meta.xml
<CustomField>
    <fullName>Items_are_deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Items are deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/New_items_are_added__c.field-meta.xml
<CustomField>
    <fullName>New_items_are_added__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New items are added</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/Select_Location__c.field-meta.xml
<CustomField>
    <fullName>Select_Location__c</fullName>
    <label>Select Location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aberdeen</fullName>
                <isActive>false</isActive>
                <label>Aberdeen</label>
            </value>
            <value>
                <fullName>Altmannshofen Shell Depot</fullName>
            </value>
            <value>
                <fullName>Andernach Dötsch Depot</fullName>
            </value>
            <value>
                <fullName>Aschaffenburg Baywa Depot</fullName>
            </value>
            <value>
                <fullName>Augsburg Präg depot</fullName>
            </value>
            <value>
                <fullName>Avonmouth</fullName>
                <isActive>false</isActive>
                <label>Avonmouth</label>
            </value>
            <value>
                <fullName>Bendorf Oiltanking Depot</fullName>
            </value>
            <value>
                <fullName>Berlin Oiltanking Depot</fullName>
            </value>
            <value>
                <fullName>Berlin Unitank depot</fullName>
            </value>
            <value>
                <fullName>Bertrange</fullName>
            </value>
            <value>
                <fullName>Birmingham Airport</fullName>
                <isActive>false</isActive>
                <label>Birmingham Airport</label>
            </value>
            <value>
                <fullName>Birsfdn Rhytank depot</fullName>
            </value>
            <value>
                <fullName>Birsfdn Varo depot</fullName>
            </value>
            <value>
                <fullName>Bramhall</fullName>
                <isActive>false</isActive>
                <label>Bramhall</label>
            </value>
            <value>
                <fullName>Braunschwg Varo depot</fullName>
            </value>
            <value>
                <fullName>Bremen HGM Depot</fullName>
            </value>
            <value>
                <fullName>Shell/OMV Burghausen</fullName>
                <label>Burghausen OMV Depot</label>
            </value>
            <value>
                <fullName>Clydebank</fullName>
                <isActive>false</isActive>
                <label>Clydebank</label>
            </value>
            <value>
                <fullName>Collombey Tamoil depot</fullName>
            </value>
            <value>
                <fullName>Cressier Varo depot</fullName>
            </value>
            <value>
                <fullName>Cunnersdorf Tabeg Depot</fullName>
            </value>
            <value>
                <fullName>Dortmund-Lünen Varo Depot</fullName>
            </value>
            <value>
                <fullName>Duisburg Tanquid</fullName>
                <label>Duisburg Tanquid Depot</label>
            </value>
            <value>
                <fullName>Duisburg Total Depot</fullName>
            </value>
            <value>
                <fullName>Duisburg Varo Depot</fullName>
            </value>
            <value>
                <fullName>Emleben Unitank depot</fullName>
            </value>
            <value>
                <fullName>Erlangen Varo Depot</fullName>
            </value>
            <value>
                <fullName>Essen UTG Depot</fullName>
            </value>
            <value>
                <fullName>Esso West London</fullName>
                <isActive>false</isActive>
                <label>Esso West London</label>
            </value>
            <value>
                <fullName>Shell/OMV Feldkirchen</fullName>
                <label>Feldkirchen OMV Depot</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/Select_Products__c.field-meta.xml
<CustomField>
    <fullName>Select_Products__c</fullName>
    <label>Select Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All Products</fullName>
            </value>
            <value>
                <fullName>AGO</fullName>
            </value>
            <value>
                <fullName>AGO Austria</fullName>
            </value>
            <value>
                <fullName>AGO VPD</fullName>
            </value>
            <value>
                <fullName>Avgas</fullName>
            </value>
            <value>
                <fullName>GTL</fullName>
            </value>
            <value>
                <fullName>IGO 50ppm</fullName>
            </value>
            <value>
                <fullName>Jet-A1</fullName>
            </value>
            <value>
                <fullName>ULG100 VP</fullName>
            </value>
            <value>
                <fullName>ULG95 E10</fullName>
            </value>
            <value>
                <fullName>ULG95 E5</fullName>
            </value>
            <value>
                <fullName>ULG98</fullName>
            </value>
            <value>
                <fullName>AD10</fullName>
                <isActive>false</isActive>
                <label>AD10</label>
            </value>
            <value>
                <fullName>AGO B0</fullName>
                <isActive>false</isActive>
                <label>AGO B0</label>
            </value>
            <value>
                <fullName>AGO B0 CH</fullName>
                <isActive>false</isActive>
                <label>AGO B0 CH</label>
            </value>
            <value>
                <fullName>AGO B7</fullName>
                <isActive>false</isActive>
                <label>AGO B7</label>
            </value>
            <value>
                <fullName>Dry Base</fullName>
                <isActive>false</isActive>
                <label>Dry Base</label>
            </value>
            <value>
                <fullName>Ethanol</fullName>
                <isActive>false</isActive>
                <label>Ethanol</label>
            </value>
            <value>
                <fullName>FAME</fullName>
                <isActive>false</isActive>
                <label>FAME</label>
            </value>
            <value>
                <fullName>GTL B0</fullName>
                <isActive>false</isActive>
                <label>GTL B0</label>
            </value>
            <value>
                <fullName>IGO 1000ppm</fullName>
                <isActive>false</isActive>
                <label>IGO 1000ppm</label>
            </value>
            <value>
                <fullName>PU10</fullName>
                <isActive>false</isActive>
                <label>PU10</label>
            </value>
            <value>
                <fullName>ULG95 E0</fullName>
                <isActive>false</isActive>
                <label>ULG95 E0</label>
            </value>
            <value>
                <fullName>ULG95_BOB_E10</fullName>
                <isActive>false</isActive>
                <label>ULG95_BOB_E10</label>
            </value>
            <value>
                <fullName>ULG95_BOB_E5</fullName>
                <isActive>false</isActive>
                <label>ULG95_BOB_E5</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/Someone_changes_an_item_created_by_me__c.field-meta.xml
<CustomField>
    <fullName>Someone_changes_an_item_created_by_me__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Someone changes an item created by me</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/Someone_changes_item_last_modified_by_me__c.field-meta.xml
<CustomField>
    <fullName>Someone_changes_item_last_modified_by_me__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Someone changes item last modified by me</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoKiosk_Alert__c/fields/User_Selection__c.field-meta.xml
<CustomField>
    <fullName>User_Selection__c</fullName>
    <label>User Selection</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All Changes</fullName>
            </value>
            <value>
                <fullName>New items are added</fullName>
            </value>
            <value>
                <fullName>Existing items are modified</fullName>
            </value>
            <value>
                <fullName>Items are deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IK_DAL.cls
/*****************************************************************************
@Name:  IK_DAL     
@=========================================================================
@Purpose: DAL class for info kiosk    test                   
@=========================================================================
@History                                                            
@---------                                                            
@VERSION AUTHOR                            DATE                DETAIL                                 
@1.0 - Dhriti Krishna Ghosh Moulick      14/11/2017           INITIAL DEVELOPMENT
  
******************************************************************************/  
public class IK_DAL {
    public static List<InfoKiosk_Alert__c> fetchInfoKioskAlert(List<String> alertID){
        return[select id,All_Changes__c,New_items_are_added__c,Existing_items_are_modified__c,Items_are_deleted__c,
               Anything_changes__c,Someone_changes_item_last_modified_by_me__c,Someone_changes_an_item_created_by_me__c,
               User_Selection__c,Select_Location__c,Select_Products__c,Location_Code__c
               from InfoKiosk_Alert__c where ID in:alertID];
    }
    public static List<Group> fetchGroup(Set<String> setOfGroupName){
        return [SELECT Id,DeveloperName FROM Group where DeveloperName in:setOfGroupName];
    }
    
    public static List<GroupMember> fetchGroupMember(Set<String> keyset,String userId){
        return[select id,Group.DeveloperName,GroupId,UserOrGroupId from Groupmember where Group.DeveloperName in:keySet AND UserOrGroupId=:userId];
    }
}