force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Object to store all OU, Region and Location information for Trading and Supply - ATP/AMV/SCHT</description>
    <label>Location</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <description>Plant Number of Depot Code of the particular Plant/Depot</description>
    <label>Plant Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MRC__c/MRC__c.object-meta.xml
<CustomObject>
    <label>MRC</label>
    <nameField>
        <label>MRC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MRC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MRC__c/fields/Material_Description__c.field-meta.xml
<CustomField>
    <fullName>Material_Description__c</fullName>
    <formula>TEXT(Product__r.Commodity_Grade_L2__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Material Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MRC__c/fields/Mode_Of_Transport__c.field-meta.xml
<CustomField>
    <fullName>Mode_Of_Transport__c</fullName>
    <label>Mode Of Transport(MOT)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MRC__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>MRC</relationshipLabel>
    <relationshipName>MRC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRC__c/fields/PO_Type__c.field-meta.xml
<CustomField>
    <fullName>PO_Type__c</fullName>
    <label>PO Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TSFP</fullName>
            </value>
            <value>
                <fullName>TTTT</fullName>
            </value>
            <value>
                <fullName>TRFP</fullName>
            </value>
            <value>
                <fullName>TTTI</fullName>
            </value>
            <value>
                <fullName>TSTM</fullName>
            </value>
            <value>
                <fullName>TTTM</fullName>
            </value>
            <value>
                <fullName>TSFD</fullName>
            </value>
            <value>
                <fullName>Dummy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MRC__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material Number</label>
    <referenceTo>Product_Catalogue__c</referenceTo>
    <relationshipLabel>MRC</relationshipLabel>
    <relationshipName>MRC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRC__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MRC__c/fields/Ship_to_Name__c.field-meta.xml
<CustomField>
    <fullName>Ship_to_Name__c</fullName>
    <label>Ship-to Name</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MRC__c/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold-To Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected customer is not a valid customer. Please select a valid customer type.</errorMessage>
        <filterItems>
            <field>Account.Customer_Type__c</field>
            <operation>equals</operation>
            <value>Sold To</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MRC</relationshipLabel>
    <relationshipName>MRC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRC__c/fields/Valid_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Valid_To_Date__c</fullName>
    <label>Valid To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MRC__c/recordTypes/DI_Dashboard.recordType-meta.xml
<RecordType>
    <fullName>DI_Dashboard</fullName>
    <active>true</active>
    <description>Created for Revolution Dashboard</description>
    <label>DI-Dashboard</label>
</RecordType>

force-app/main/default/objects/Product_Catalogue__c/Product_Catalogue__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <label>Material Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Catalogue__c/fields/BEHG_Value_100l__c.field-meta.xml
<CustomField>
    <fullName>BEHG_Value_100l__c</fullName>
    <label>CO2 Value €/100l</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Catalogue__c/fields/Commodity_Grade_L2__c.field-meta.xml
<CustomField>
    <fullName>Commodity_Grade_L2__c</fullName>
    <label>Grade(L2)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Additive</fullName>
                <isActive>false</isActive>
                <label>Additive</label>
            </value>
            <value>
                <fullName>AGO B0</fullName>
            </value>
            <value>
                <fullName>AGO B0 CH</fullName>
            </value>
            <value>
                <fullName>AGO B7</fullName>
            </value>
            <value>
                <fullName>AGO B7 CH</fullName>
                <isActive>false</isActive>
                <label>AGO B7 CH</label>
            </value>
            <value>
                <fullName>AGO VPD</fullName>
            </value>
            <value>
                <fullName>Alkalyte</fullName>
                <isActive>false</isActive>
                <label>Alkalyte</label>
            </value>
            <value>
                <fullName>AVGAS</fullName>
                <isActive>false</isActive>
                <label>AVGAS</label>
            </value>
            <value>
                <fullName>Cokerfeed</fullName>
                <isActive>false</isActive>
                <label>Cokerfeed</label>
            </value>
            <value>
                <fullName>EBV- Crude-Mix</fullName>
                <isActive>false</isActive>
                <label>EBV- Crude-Mix</label>
            </value>
            <value>
                <fullName>ETHANOL</fullName>
                <isActive>false</isActive>
                <label>ETHANOL</label>
            </value>
            <value>
                <fullName>FAME</fullName>
                <isActive>false</isActive>
                <label>FAME</label>
            </value>
            <value>
                <fullName>FO</fullName>
                <isActive>false</isActive>
                <label>FO</label>
            </value>
            <value>
                <fullName>GTL B0</fullName>
            </value>
            <value>
                <fullName>GTL B7</fullName>
            </value>
            <value>
                <fullName>High Sulphur Gasoil</fullName>
                <isActive>false</isActive>
                <label>High Sulphur Gasoil</label>
            </value>
            <value>
                <fullName>IGO 1000ppm</fullName>
            </value>
            <value>
                <fullName>IGO 10ppm</fullName>
            </value>
            <value>
                <fullName>IGO 50ppm</fullName>
            </value>
            <value>
                <fullName>Jet A1</fullName>
                <isActive>false</isActive>
                <label>Jet A1</label>
            </value>
            <value>
                <fullName>Kerosene</fullName>
                <isActive>false</isActive>
                <label>Kerosene</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>ULG100 VP</fullName>
            </value>
            <value>
                <fullName>ULG95_BOB_E10</fullName>
            </value>
            <value>
                <fullName>ULG95_BOB_E5</fullName>
            </value>
            <value>
                <fullName>ULG95 E0</fullName>
            </value>
            <value>
                <fullName>ULG95 E10</fullName>
            </value>
            <value>
                <fullName>ULG95 E5</fullName>
            </value>
            <value>
                <fullName>ULG98</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Catalogue__c/fields/Current_BEHG_valid_from_date__c.field-meta.xml
<CustomField>
    <fullName>Current_BEHG_valid_from_date__c</fullName>
    <label>Current CO2 valid from date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Catalogue__c/fields/Current_BEHG_valid_to_date__c.field-meta.xml
<CustomField>
    <fullName>Current_BEHG_valid_to_date__c</fullName>
    <label>Current CO2 valid to date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Catalogue__c/fields/Future_BEHG_valid_from_date__c.field-meta.xml
<CustomField>
    <fullName>Future_BEHG_valid_from_date__c</fullName>
    <label>Future CO2 valid from date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Catalogue__c/fields/Future_BEHG_valid_to_date__c.field-meta.xml
<CustomField>
    <fullName>Future_BEHG_valid_to_date__c</fullName>
    <label>Future CO2 valid to date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Catalogue__c/fields/Future_BEHG_value_in_100l__c.field-meta.xml
<CustomField>
    <fullName>Future_BEHG_value_in_100l__c</fullName>
    <label>Future CO2 value (in €/100l)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RV_DI_DashboardBatch.cls
global class RV_DI_DashboardBatch  implements Database.Batchable<sObject>{
	global Database.QueryLocator start(Database.BatchableContext BC){

        String recTypeId = Schema.SObjectType.MRC__c.getRecordTypeInfosByDeveloperName().get('DI_Dashboard').getRecordTypeId();
        System.debug('--------'+recTypeId);
        String query = 'Select Id, Ship_to_Name__c, Shipping_Condition__c, Sales_Organization__c,Material_Description__c,'+
                 'Plant__r.Name,Product__r.Name,Product__r.Commodity_Grade_L2__c,Product__r.BEHG_Value_100l__c,Product__r.Current_BEHG_valid_from_date__c,Product__r.Current_BEHG_valid_to_date__c,Product__r.Future_BEHG_value_in_100l__c,Product__r.Future_BEHG_valid_from_date__c,Product__r.Future_BEHG_valid_to_date__c, Sold_To__c, Plant__c, Plant_Code__c,Valid_From_Date__c,PO_Type__c,Handling_Type__c,'+
                 'Valid_To_Date__c, Name, Product__c,Mode_Of_Transport__c from MRC__c where  RecordTypeId =\''+ ''+recTypeId+'\'';       
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<MRC__c> mrcLst){ 
        
        RV_DI_Dashboard evDIDashboard = new RV_DI_Dashboard();
        System.debug('-----------'+mrcLst.size());
        Date contractStratDate = Date.Today();
        Date contractEndDate = Date.Today().addDays(14);
        if(!mrcLst.isEmpty()){
            Map<Id,MRC__c> mrcMap = new Map<Id,MRC__c>(mrcLst);
            evDIDashboard.getPriceForDashboard('Fixed', contractStratDate, contractEndDate,mrcMap);
        }
    }
    global void finish(Database.BatchableContext BC){
        Datetime sysTime = System.now();
        sysTime = sysTime.addSeconds(30 );
        String chronExpression = '' + sysTime.second() + ' ' + sysTime.minute() + ' ' + sysTime.hour() + ' ' + sysTime.day() + ' ' + sysTime.month() + ' ? ' + sysTime.year();

        System.schedule('Dashboard excution every 30 seconds' + sysTime.getTime(), chronExpression, new RV_DI_DashboardScheduler());
    }
}