force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Object to store all OU, Region and Location information for Trading and Supply - ATP/AMV/SCHT</description>
    <label>Location</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MRC__c/MRC__c.object-meta.xml
<CustomObject>
    <label>MRC</label>
    <nameField>
        <label>MRC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MRC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Catalogue__c/Product_Catalogue__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <label>Material Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Catalogue__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipName>Product_Catalogues_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SHT__c/SHT__c.object-meta.xml
<CustomObject>
    <label>SHT</label>
    <nameField>
        <displayFormat>SHT - {0}</displayFormat>
        <label>SHT Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SHT</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SHT__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>SHTS</relationshipLabel>
    <relationshipName>SHTS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/MRC__c.field-meta.xml
<CustomField>
    <fullName>MRC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MRC</label>
    <referenceTo>MRC__c</referenceTo>
    <relationshipLabel>SHT</relationshipLabel>
    <relationshipName>SHT</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Product_Catalogue__c.field-meta.xml
<CustomField>
    <fullName>Product_Catalogue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Catalogue</label>
    <referenceTo>Product_Catalogue__c</referenceTo>
    <relationshipLabel>SHTS</relationshipLabel>
    <relationshipName>SHTS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Rv_PriceAuditControllerTest.cls
@isTest
public class Rv_PriceAuditControllerTest {
    @isTest
    static void doTest()
    {
        Location__c loc = new Location__c();
        RV_TestHelper.insertLocation(loc);
        insert loc;

     	Product_Catalogue__c productCat = new Product_Catalogue__c();
        RV_TestHelper.insertProductCat(productCat);
        insert productCat;
         
    	Account accLst= new Account(); 
        RV_TestHelper.insertAccount(accLst);
        insert accLst;

    	MRC__c insertmrc = new MRC__c();
        RV_TestHelper.insertMRC(insertmrc,accLst,loc,productCat);
        insert insertmrc;
        
        SHT__c insertSHTRec = new SHT__c();
        RV_TestHelper.insertSHT(insertSHTRec,loc,accLst,insertmrc);
        insert insertSHTRec;
        
        
        List<RV_SPCalculationController.priceAuditWrap> priceAdtWrpLst = new List<RV_SPCalculationController.priceAuditWrap>();
        RV_SPCalculationController.priceAuditWrap paw = new RV_SPCalculationController.priceAuditWrap();
        
        paw.mrcNo =insertmrc.Name;
        paw.shtId=insertSHTRec.id;
        paw.salesOrg='';
        paw.materialId=productCat.id;
        paw.shippingCond = 1;
        paw.landedCostEuroMt =0;
        paw.depotSteer =0;
        paw.finalAMVEuroMt=0;
        paw.finalAMVEuro100L=0;
        paw.applyThroughput='';
        paw.throughputCost=0;
        paw.energyFees=0;
        paw.cso=0;
        paw.iwoMember=false;
        paw.unionFees=0;
        paw.calculatedBSP=0;
        paw.salesMargin=0;
        paw.minMargin=0;
        paw.calculatedMSP=0;
        paw.exchangeRate=0;
        
        List<RV_SPCalculationController.backboneAMVpriceCompWrap> prcBAMVLst = new List<RV_SPCalculationController.backboneAMVpriceCompWrap>();
        RV_SPCalculationController.backboneAMVpriceCompWrap baw = new RV_SPCalculationController.backboneAMVpriceCompWrap();
        
        baw.mrcNo=insertmrc.Name;    
        baw.routeName='';  
        baw.routeUtilizationPercent =0;       
        baw.hcv=0;
        baw.coSteer=0;
        baw.freight=0;
        baw.freightPercentage=0;
        baw.freightQuoteValue=0;
        baw.freightToSource=0;
        baw.freightToDepot=0;
        baw.bioCost=0;
        baw.thirdParty=false;
        baw.bioSplit=false;
        baw.wasa=0;
        baw.additiveCost=0;
        baw.landedBAMVvalue=0;
        baw.finalBAMVvalue=0;
        baw.Depot=loc.id;
        
        prcBAMVLst.add(baw);
        
        paw.bavWrp = prcBAMVLst;
        
        priceAdtWrpLst.add(paw);
        
        Rv_PriceAuditController.insertPriceAuditWrap(priceAdtWrpLst);
    }

}