force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/Fixed_Price_Staging_Table__c.object-meta.xml
<CustomObject>
    <label>Fixed Price Staging Table</label>
    <nameField>
        <displayFormat>GSAP-{000000000}</displayFormat>
        <label>Fixed Price Staging Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fixed Price Staging Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_Application__c.field-meta.xml
<CustomField>
    <fullName>RE_Application__c</fullName>
    <label>Application</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_Calculation_type__c.field-meta.xml
<CustomField>
    <fullName>RE_Calculation_type__c</fullName>
    <label>Calculation type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_Change__c.field-meta.xml
<CustomField>
    <fullName>RE_Change__c</fullName>
    <label>Change</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_Cond_table_no__c.field-meta.xml
<CustomField>
    <fullName>RE_Cond_table_no__c</fullName>
    <label>Cond table no</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_Cond_Usage_Table__c.field-meta.xml
<CustomField>
    <fullName>RE_Cond_Usage_Table__c</fullName>
    <label>Cond Usage Table</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_condRecordnumber__c.field-meta.xml
<CustomField>
    <fullName>RE_condRecordnumber__c</fullName>
    <label>condRecordnumber</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_Currency_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Currency_Unit__c</fullName>
    <label>Currency Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_Error__c.field-meta.xml
<CustomField>
    <fullName>RE_Error__c</fullName>
    <label>Error</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_IdnForFix__c.field-meta.xml
<CustomField>
    <fullName>RE_IdnForFix__c</fullName>
    <label>IdnForFix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_Job_Run_Audit__c.field-meta.xml
<CustomField>
    <fullName>RE_Job_Run_Audit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RE Job Run Audit</label>
    <referenceTo>RE_Job_Run_Audit__c</referenceTo>
    <relationshipLabel>Fixed Price Staging Table</relationshipLabel>
    <relationshipName>Fixed_Price_Staging_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_Material_Description__c.field-meta.xml
<CustomField>
    <fullName>RE_Material_Description__c</fullName>
    <label>Material Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_Quantity__c.field-meta.xml
<CustomField>
    <fullName>RE_Quantity__c</fullName>
    <label>Quantity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_Report_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Report_Type__c</fullName>
    <label>Report Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>YD07</fullName>
            </value>
            <value>
                <fullName>YD04</fullName>
            </value>
            <value>
                <fullName>YD03</fullName>
            </value>
            <value>
                <fullName>YP01</fullName>
            </value>
            <value>
                <fullName>YP02</fullName>
            </value>
            <value>
                <fullName>YP07</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_Scale_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Scale_Type__c</fullName>
    <label>Scale Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_ScaleAmount__c.field-meta.xml
<CustomField>
    <fullName>RE_ScaleAmount__c</fullName>
    <label>ScaleAmount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_ScaleDate__c.field-meta.xml
<CustomField>
    <fullName>RE_ScaleDate__c</fullName>
    <label>ScaleDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_ScaleQuantity__c.field-meta.xml
<CustomField>
    <fullName>RE_ScaleQuantity__c</fullName>
    <label>ScaleQuantity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_ScaleTime__c.field-meta.xml
<CustomField>
    <fullName>RE_ScaleTime__c</fullName>
    <label>ScaleTime</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_ScaleUOM__c.field-meta.xml
<CustomField>
    <fullName>RE_ScaleUOM__c</fullName>
    <label>ScaleUOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>RE_Sequence_No__c</fullName>
    <label>Sequence No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_Status__c.field-meta.xml
<CustomField>
    <fullName>RE_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_Uom__c.field-meta.xml
<CustomField>
    <fullName>RE_Uom__c</fullName>
    <label>Uom</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_Valid_End_date__c.field-meta.xml
<CustomField>
    <fullName>RE_Valid_End_date__c</fullName>
    <label>Valid End date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_Valid_start_date__c.field-meta.xml
<CustomField>
    <fullName>RE_Valid_start_date__c</fullName>
    <label>Valid start date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_Value__c.field-meta.xml
<CustomField>
    <fullName>RE_Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Price_Staging_Table__c/fields/RE_Varkey__c.field-meta.xml
<CustomField>
    <fullName>RE_Varkey__c</fullName>
    <label>Varkey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Email_Recipient__mdt/RE_Email_Recipient__mdt.object-meta.xml
<CustomObject>
    <description>Email recipient for Revolution.</description>
    <label>RE Email Recipient</label>
    <pluralLabel>RE Email Recipients</pluralLabel>
</CustomObject>

force-app/main/default/objects/RE_Email_Recipient__mdt/fields/Bcc_List__c.field-meta.xml
<CustomField>
    <fullName>Bcc_List__c</fullName>
    <label>Bcc List</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RE_Email_Recipient__mdt/fields/Cc_List__c.field-meta.xml
<CustomField>
    <fullName>Cc_List__c</fullName>
    <label>Cc List</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RE_Email_Recipient__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Canada</fullName>
                <default>true</default>
                <label>Canada</label>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Email_Recipient__mdt/fields/To_List__c.field-meta.xml
<CustomField>
    <fullName>To_List__c</fullName>
    <label>To List</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RE_Email_Recipient__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>7 DAY Canadian Rack Prices</fullName>
            </value>
            <value>
                <fullName>Canada GSAP</fullName>
            </value>
            <value>
                <fullName>Canada Quote Movement</fullName>
            </value>
            <value>
                <fullName>Canadian Rack Prices</fullName>
            </value>
            <value>
                <fullName>Canadian Rack Pricing and rack pricing Files</fullName>
            </value>
            <value>
                <fullName>Internal Rack Notification</fullName>
            </value>
            <value>
                <fullName>Internal Shell Canada BRPP Notification</fullName>
            </value>
            <value>
                <fullName>MY Monthly CBU Costing and Chart</fullName>
            </value>
            <value>
                <fullName>No Revised Pricing</fullName>
            </value>
            <value>
                <fullName>Ready to Upload Notification</fullName>
            </value>
            <value>
                <fullName>SFJ Rack notification</fullName>
            </value>
            <value>
                <fullName>Shell Canada - Branded Customer Notification</fullName>
            </value>
            <value>
                <fullName>Shell Canada Rack Notification</fullName>
            </value>
            <value>
                <fullName>Shell Rack Customer Notification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/RE_Job_Run_Audit__c.object-meta.xml
<CustomObject>
    <label>Job Run Audit</label>
    <nameField>
        <displayFormat>JR-{00000000}</displayFormat>
        <label>Job Run Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Run Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_IsSuccess__c.field-meta.xml
<CustomField>
    <fullName>RE_IsSuccess__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSuccess</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Job_Status__c.field-meta.xml
<CustomField>
    <fullName>RE_Job_Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Partial Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FixedPriceDataInsertBatch.cls
global class FixedPriceDataInsertBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {    
    
    public List<Id> fixPriceIds;
    public integer counter;
    public String country;
    Public  RE_Job_Run_Audit__c jre;
    public FixedPriceDataInsertBatch(List<Id> fixPriceIdtoBatch, integer counter, String country , RE_Job_Run_Audit__c jre) {
        this.fixPriceIds = fixPriceIdtoBatch;
        this.counter =  counter;
        this.country = country;
        this.jre = jre;
    }
    global Iterable<Sobject> start(Database.BatchableContext BC) { 
        System.debug('FixedPriceDataInsertBatch start called--');
        return ([
            SELECT Id, OwnerId,RE_Error__c, IsDeleted, Name, CreatedDate, 
            CreatedById, LastModifiedDate, LastModifiedById, 
            SystemModstamp, RE_Application__c, RE_Calculation_type__c,
            RE_Cond_Usage_Table__c, RE_Cond_table_no__c, RE_Currency_Unit__c,
            RE_Quantity__c, RE_Report_Type__c, RE_Scale_Type__c, RE_Sequence_No__c,
            RE_Status__c, RE_Uom__c, RE_Valid_End_date__c, RE_Valid_start_date__c,
            RE_Value__c, RE_Varkey__c, RE_IdnForFix__c, RE_condRecordnumber__c,
            RE_Change__c, RE_ScaleAmount__c, RE_ScaleQuantity__c, RE_ScaleUOM__c,
            RE_ScaleDate__c, RE_ScaleTime__c, RE_Material_Description__c
            FROM Fixed_Price_Staging_Table__c where id IN: fixPriceIds AND RE_Status__c = '']);        
    }
    
    global void execute(Database.BatchableContext BC, List<Fixed_Price_Staging_Table__c> fpstlist) { 
            System.debug('FixedPriceDataInsertBatch EXECUTE called--');
            Rev_GSAPStagingTableClass.onafterInsert(fpstlist);       
    }   
    
    global void finish(Database.BatchableContext BC) {        
        //check if any failures and execute the batch again
        System.debug('FixedPriceDataInsertBatch finish called--');
        list<AsyncApexJob> jobDetails = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id =:BC.getJobId()];
        System.debug('jobDetails--'+jobDetails);
        if(!jobDetails.isEmpty() && jobDetails[0].NumberOfErrors > 0 && counter <= 2){
            counter += 1;
            FixedPriceDataInsertBatch batch2 = new FixedPriceDataInsertBatch(fixPriceIds,counter,country ,jre);
            //database.executeBatch(batch2,85);
            System.scheduleBatch(batch2, 'Re execute batch', 1, 100); 
        }
        else{
            system.debug('inside send email -- finish method');
        try{
            jre.RE_Job_Status__c ='Completed';
            jre.RE_IsSuccess__c = true;
            update jre;            
            List<String> idList = new List<String>();
            List<String> mailToAddresses = new List<String>(); 
            EmailTemplate template;
            Group gp;
            if(country == 'Malaysia'){
                gp = [SELECT (SELECT UserOrGroupId FROM GroupMembers) FROM Group WHERE DeveloperName = 'RE_MY_Customer_Ops'];
                template =[SELECT Id,Body,Subject FROM EmailTemplate WHERE Name = 'MY Customer Ops Email'];                
                
                
                for (GroupMember gm : gp.GroupMembers) {
                    idList.add(gm.UserOrGroupId);
                }
                List<User> userList = [SELECT Email FROM User WHERE Id IN :idList];
                for(User u : userList) {
                    mailToAddresses.add(u.email);               
                } 
                mailToAddresses.add(Userinfo.getUserEmail());
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 
                mail.setTargetObjectId(UserInfo.getUserId()); 
                mail.setTemplateId(template.Id); 
                mail.setBccSender(false); 
                mail.setUseSignature(false); 
                mail.setSenderDisplayName('Revolution East Team'); 
                mail.setSaveAsActivity(false); 
                mail.setToAddresses(mailToAddresses);
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            }
            
            if(country == 'Canada')
            {               
                String [] ToEmail;
                String [] ccEmail;
                String [] BCCList;
                for(RE_Email_Recipient__mdt rec : [SELECT id, Cc_List__c, To_List__c,Bcc_List__c FROM RE_Email_Recipient__mdt 
                                                    WHERE Country__c =: 'Canada' AND Type__c =: 'Canada GSAP' AND Is_Active__c =: TRUE LIMIT 1])
                {
                    if(rec.To_List__c != NULL){ToEmail = rec.To_List__c.split(';');}				
                    if(rec.Cc_List__c != NULL){ccEmail = rec.Cc_List__c.split(';');}				
                    if(rec.Bcc_List__c != NULL){BCCList = rec.Bcc_List__c.split(';');}                    
                }
                
                template =[select id, HtmlValue, Subject from EmailTemplate where DeveloperName ='Canada_GSAP_Email'];                
                RE_CND_Utility.sendEmail(ToEmail,ccEmail,BCCList,template.Subject,template.HtmlValue,jre);
            }                
        }    
        catch(Exception ex){
            System.debug(ex.getMessage()+'\n'+ex.getLineNumber()+'\n'+ex.getCause()+'\n'+ex.getStackTraceString());            
        }
    }

  }
    
}