force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}-{00}</displayFormat>
        <label>Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Currency_Conversion__c/RE_Currency_Conversion__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Revolution Currency Conversion Formula</description>
    <label>RE Currency Conversion</label>
</CustomObject>

force-app/main/default/objects/RE_Default_Unit_Rate_Settings__c/RE_Default_Unit_Rate_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Revolution Default Unit Rate Settings</description>
    <label>RE Default Unit Rate Settings</label>
</CustomObject>

force-app/main/default/objects/RE_FX_Rates__c/RE_FX_Rates__c.object-meta.xml
<CustomObject>
    <label>RE FX Rates</label>
    <nameField>
        <displayFormat>FXR-{000000}</displayFormat>
        <label>FX_Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE FX Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Job_Run_Audit__c/RE_Job_Run_Audit__c.object-meta.xml
<CustomObject>
    <label>Job Run Audit</label>
    <nameField>
        <displayFormat>JR-{00000000}</displayFormat>
        <label>Job Run Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Run Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/Other_Comments__c.field-meta.xml
<CustomField>
    <fullName>Other_Comments__c</fullName>
    <description>Other comments related to job Audit</description>
    <label>Other Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Exception__c.field-meta.xml
<CustomField>
    <fullName>RE_Exception__c</fullName>
    <label>Exception</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Job_Status__c.field-meta.xml
<CustomField>
    <fullName>RE_Job_Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Partial Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Job_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Malaysia Output</fullName>
            </value>
            <value>
                <fullName>Singapore Output</fullName>
            </value>
            <value>
                <fullName>SG Midday Output</fullName>
            </value>
            <value>
                <fullName>Malaysia AMV Output</fullName>
            </value>
            <value>
                <fullName>Thailand Output</fullName>
            </value>
            <value>
                <fullName>CustomerOps Output</fullName>
            </value>
            <value>
                <fullName>New Contract Pricing Output</fullName>
            </value>
            <value>
                <fullName>Thailand AMV Output</fullName>
            </value>
            <value>
                <fullName>MY Export Report</fullName>
            </value>
            <value>
                <fullName>MY Customer Opps CBU</fullName>
            </value>
            <value>
                <fullName>Philippines Output</fullName>
            </value>
            <value>
                <fullName>Canada Daily Reuters Quote Move</fullName>
            </value>
            <value>
                <fullName>Canada Execute Depo Pricing</fullName>
            </value>
            <value>
                <fullName>Canada Pricing Recalculation</fullName>
            </value>
            <value>
                <fullName>Canada SFJ Record Creation</fullName>
            </value>
            <value>
                <fullName>Canada Live OPIS Spot Ticker Processing</fullName>
            </value>
            <value>
                <fullName>Canada Market Move Calculation</fullName>
            </value>
            <value>
                <fullName>Canada Competitor Data Processing</fullName>
            </value>
            <value>
                <fullName>Canada GSAP Upload</fullName>
            </value>
            <value>
                <fullName>Canada Email Output</fullName>
            </value>
            <value>
                <fullName>MY Data Analysis Report</fullName>
            </value>
            <value>
                <fullName>PH Customer Opps CBU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Run_Time__c.field-meta.xml
<CustomField>
    <fullName>RE_Run_Time__c</fullName>
    <label>Run Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Run_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Run_Type__c</fullName>
    <label>Run Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automate</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_JobControls__c/RE_JobControls__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting to enable/disable functions in classes</description>
    <label>RE Job Controls</label>
</CustomObject>

force-app/main/default/objects/RE_JobControls__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Name of the country for which the process is enabled or disabled</description>
    <label>Country</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/RE_Market_Quotes__c.object-meta.xml
<CustomObject>
    <label>RE Market Quotes</label>
    <nameField>
        <displayFormat>MarketQuote-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Market Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Rate_Unit_Manager__c/RE_Rate_Unit_Manager__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RE Rate Unit Manager</label>
</CustomObject>

force-app/main/default/objects/RE_Zema_Quotes_Settings__c/RE_Zema_Quotes_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Zema Quotes for Canada</description>
    <label>RE Zema Quotes Settings</label>
</CustomObject>

force-app/main/default/objects/RE_Zema_Quotes_Settings__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <label>Display Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RE_Zema_Quotes_Settings__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Zema_Quotes_Settings__c/fields/Price_to_be_converted__c.field-meta.xml
<CustomField>
    <fullName>Price_to_be_converted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Price to be converted?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RE_Zema_Quotes_Settings__c/fields/Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>Quote_Name__c</fullName>
    <label>Quote Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RE_Zema_Quotes_Settings__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>differentiate between settlement quotes and fx rates</description>
    <label>Type</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reuters_History__c/Reuters_History__c.object-meta.xml
<CustomObject>
    <label>Reuters History</label>
    <nameField>
        <displayFormat>Reut-Hist-{00000000}</displayFormat>
        <label>Reuters History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reuters Historys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reuters_History__c/fields/CurrencyCode__c.field-meta.xml
<CustomField>
    <fullName>CurrencyCode__c</fullName>
    <description>Field to store Currency code related to Reuters Quote</description>
    <label>CurrencyCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reuters_History__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reuters_History__c/fields/Unit_Of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_Of_Measure__c</fullName>
    <label>Unit Of Measure</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reuters_Quotes__c/Reuters_Quotes__c.object-meta.xml
<CustomObject>
    <label>Reuters Quotes</label>
    <nameField>
        <displayFormat>RQ-{00000}</displayFormat>
        <label>Reuters Quotes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ReutersQuotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RE_CND_QuotesqueueHandler_Test.cls
/******************************************************************************************************************
className           :    RE_CND_QuotesqueueHandler_Test
Description         :    Test class for RE_CN_Quotes_Queue, RE_CND_QuotesqueueHandler and RE_CND_CanadaQuoteScheduler
Author              :    Aasiya Siraj
Date				:	 10-May-2021 
*******************************************************************************************************************/
@isTest
public class RE_CND_QuotesqueueHandler_Test {
    
    @testSetup 
    static void setup() {
        List<RE_Zema_Quotes_Settings__c> zemaListCreated = RE_CND_TestDataFactory.createZemaQuotes();
        RE_Job_Run_Audit__c jra = RE_CND_TestDataFactory.createJobRunAudit('Automate','Canada Daily Reuters Quote Move','CA');
        
               
        RE_JobControls__c jobControl1 =  RE_CND_TestDataFactory.createJobControlSetting('JC1','RE_CND_QuotesQueueHandler','getTodaysCanadianQuotes','Canada',true);
        RE_JobControls__c jobControl2 =  RE_CND_TestDataFactory.createJobControlSetting('JC2','RE_CND_QuotesQueueHandler','moveToMarketQuotes','Canada',true);
        RE_JobControls__c jobControl3 =  RE_CND_TestDataFactory.createJobControlSetting('JC3','RE_CND_QuotesQueueHandler','moveToReutersHistory','Canada',true);
        RE_JobControls__c jobControl4 =  RE_CND_TestDataFactory.createJobControlSetting('JC4','RE_CND_QuotesQueueHandler','deleteCanadaQuotes','Canada',true);
        RE_JobControls__c jobControl5 =  RE_CND_TestDataFactory.createJobControlSetting('JC5','RE_CND_QuotesQueueHandler','deleteCommonQuotes','Canada',true);
        RE_JobControls__c jobControl6 =  RE_CND_TestDataFactory.createJobControlSetting('JC6','RE_CND_QuotesQueueHandler','sendJobReportMail','Canada',true);
        RE_JobControls__c jobControl7 =  RE_CND_TestDataFactory.createJobControlSetting('JC7','RE_CND_QuotesQueueHandler','sendSuccessReportMail','Canada',true);
        RE_JobControls__c jobControl8 =  RE_CND_TestDataFactory.createJobControlSetting('JC8','RE_CND_QuotesQueueHandler','sendFailureReportMail','Canada',true);
        RE_JobControls__c jobControl9 =  RE_CND_TestDataFactory.createJobControlSetting('JC9','RE_CND_QuotesQueueHandler','moveToFXRates','Canada',true);

        Reuters_Quotes__c rqs=RE_CND_TestDataFactory.createReutersQuote('Test Quote', System.today()+6, 25.00,'l','CAD');
        Reuters_Quotes__c rqs2=RE_CND_TestDataFactory.createReutersQuote
            ('Argus US east coast Gasoline 83.5 CBOB NYH barge Daily (low) barge Nymex Gasoline RBOB USC/USG Interpolation: previous',
             System.today()+8, 16.00,'BBL','USD');
        Reuters_Quotes__c rqs3=RE_CND_TestDataFactory.createReutersQuote
            ('ICE Cleared Settle Oil (Futures) Settlement Price North Sea Brent Crude',System.today()+5, 32.00,'l','CAD');
        Reuters_Quotes__c rqs4=RE_CND_TestDataFactory.createReutersQuote('test',System.today()+2, 26.00,'GAL','USD');
        Reuters_Quotes__c rqs5=RE_CND_TestDataFactory.createReutersQuote('Reuters 12 Noon USD Exchange Benckmark USD Mid Canada Dollar CAD Interpolation: previous',
                                                                         System.today()+2, 0,'l','CAD');
        RE_Market_Quotes__c mqs =RE_CND_TestDataFactory.createMarketQuotes('Test Display',System.today()+6, 25.00,'CA');
        RE_Market_Quotes__c mqs2 =RE_CND_TestDataFactory.createMarketQuotes('ICE Brent M+0',System.today()+5, 25.00,null);
        
        RE_FX_Rates__c fxRate= RE_CND_TestDataFactory.createFXRate('Live FX Rate',1.5,System.today(),'CAD');
        RE_Rate_Unit_Manager__c rum=RE_CND_TestDataFactory.createRateUnitManager('RUM1','CAD CTS/LTR','CAD CTS','LTR');
        RE_Rate_Unit_Manager__c rum2=RE_CND_TestDataFactory.createRateUnitManager('RUM2','USD/BBL','USD','BBL');
        RE_Currency_Conversion__c cc= RE_CND_TestDataFactory.createCurrencyConversion('CC1','USD','CAD CTS','100*FxRate');
        RE_Default_Unit_Rate_Settings__c defaultunit =
            RE_CND_TestDataFactory.createDefaultUnit('DS1','Settlement Quote','CAD CTS/LTR','Canada','RE_Market_Quotes__c',true);
        Reuters_History__c rhs=RE_CND_TestDataFactory.createReutersHistrory('Test Display',rqs.Quote_Name__c,rqs.CreatedDate,rqs.Frequency__c,rqs.Id,rqs.Price__c,rqs.Pricing_Date__c,'TU');
    }
    
   
   @isTest
    static  void quoteSchedular(){
        Test.startTest();
        RE_CND_CanadaQuoteScheduler p = new RE_CND_CanadaQuoteScheduler(); 
        String sch = '0 30 * * * ? 2099'; 
        String jobID=system.schedule('canada Queue Schedular', sch, p);
        p.execute(null);
        System.assertNotEquals(null, jobID);
        Test.stopTest();
    }
    
 @isTest
    static  void canadaQuoteQueueTest(){
        Test.startTest();
        RE_Job_Run_Audit__c jobAudit=[SELECT RE_Run_Time__c,RE_Job_Status__c,Other_Comments__c,RE_Exception__c,RE_Run_Type__c,RE_Job_Type__c 
                                      FROM RE_Job_Run_Audit__c WHERE RE_Run_Type__c='Automate' LIMIT 1];
        ID jobID=System.enqueueJob(new RE_CND_Quotes_Queue(jobAudit));
        System.assertNotEquals(null, jobID);
        Test.stopTest();
    }
    
    @isTest
    static  void canadaQuoteQueueException(){
        Test.startTest();
        RE_Job_Run_Audit__c jobAudit=[SELECT RE_Run_Time__c,RE_Job_Status__c,Other_Comments__c,RE_Exception__c,RE_Run_Type__c,RE_Job_Type__c 
                                      FROM RE_Job_Run_Audit__c WHERE RE_Run_Type__c='Automate' LIMIT 1];
        ID jobID=System.enqueueJob(new RE_CND_Quotes_Queue(jobAudit));
        System.assertNotEquals(null, jobID);
        Test.stopTest();
    }
    
    @isTest
    static  void deletionException(){
        Test.startTest();
        RE_Job_Run_Audit__c jobAudit=[SELECT RE_Run_Time__c,RE_Job_Status__c,RE_Exception__c,Other_Comments__c,RE_Run_Type__c,RE_Job_Type__c 
                                      FROM RE_Job_Run_Audit__c WHERE RE_Run_Type__c='Automate' LIMIT 1];
        List<Reuters_Quotes__c> reuterlist=[SELECT Id,Price__c,Pricing_Date__c,Quote_Name__c FROM Reuters_Quotes__c WHERE CreatedDate=TODAY];
        Set<Id>canadaQuoteIds = new Set<Id>();
        Set<Id>commonQuoteIds = new Set<Id>();
        for (Reuters_Quotes__c rq :reuterlist)
        {
            canadaQuoteIds.add(rq.Id);
            commonQuoteIds.add(rq.Id);
        }
        RE_CND_QuotesQueueHandler.deleteQuotes(canadaQuoteIds,commonQuoteIds,true,true, jobAudit);
        RE_CND_QuotesQueueHandler.deleteQuotes(canadaQuoteIds,commonQuoteIds,true,true, jobAudit);
        List<Reuters_Quotes__c> reuterlist1=[SELECT Id,Price__c,Pricing_Date__c,Quote_Name__c FROM Reuters_Quotes__c WHERE CreatedDate=TODAY];
        System.assertEquals(0, reuterlist1.size());
        Test.stopTest();
    }
    
    @isTest
    static  void partialdeletionException(){
        Test.startTest();
        RE_Job_Run_Audit__c jobAudit=[SELECT RE_Run_Time__c,RE_Exception__c,RE_Job_Status__c,Other_Comments__c,RE_Run_Type__c,RE_Job_Type__c 
                                      FROM RE_Job_Run_Audit__c WHERE RE_Run_Type__c='Automate' LIMIT 1];
        List<Reuters_Quotes__c> reuterlist=[SELECT Id,Price__c,Pricing_Date__c,Quote_Name__c FROM Reuters_Quotes__c WHERE CreatedDate=TODAY];
        Set<Id>canadaQuoteIds = new Set<Id>();
        Set<Id>commonQuoteIds = new Set<Id>();
        for (Reuters_Quotes__c rq :reuterlist)
        {
            canadaQuoteIds.add(rq.Id);
            commonQuoteIds.add(rq.Id);
        }
        RE_CND_QuotesQueueHandler.partialDeleteCanadaQuotes(canadaQuoteIds,commonQuoteIds,true,true, jobAudit,canadaQuoteIds);
        List<Reuters_Quotes__c> reuterlist1=[SELECT Id,Price__c,Pricing_Date__c,Quote_Name__c FROM Reuters_Quotes__c WHERE CreatedDate=TODAY];
        System.assertEquals(0, reuterlist1.size());
        Test.stopTest();
    }
    
    @isTest
    static  void moveToMarketQuotesDatabaseUpsertException(){
        Test.startTest();
        Set<String> canadianQuoteName = new Set<String>();
        Map<Id,String> idDisplayMap = new Map<Id,String>();
        Map<String,String> displayMap = new Map<String,String>();
        Map<String,String> frequencyNameMap = new Map<String,String>();
        Map<String,Boolean> pricetobeconvrtdMap = new Map<String,Boolean>();
        Map<Id, RE_CND_QuotesQueueHandler.StatusWrapper>  isMovedtoMarket = new Map<Id, RE_CND_QuotesQueueHandler.StatusWrapper> ();
        Map<Id, RE_CND_QuotesQueueHandler.StatusWrapper>  isMovedtoHistory = new Map<Id, RE_CND_QuotesQueueHandler.StatusWrapper> ();
        RE_CND_QuotesQueueHandler.StatusWrapper sw = new RE_CND_QuotesQueueHandler.StatusWrapper();
        sw.isCreated=false;
        sw.isUpdated=false;
        sw.isFailed=false;
        sw.noActionRequired=false;
        
        List<Id> reuterIdList = new List<Id>();
        RE_Job_Run_Audit__c jobAudit=[SELECT RE_Run_Time__c,RE_Exception__c,RE_Job_Status__c,Other_Comments__c,RE_Run_Type__c,RE_Job_Type__c 
                                      FROM RE_Job_Run_Audit__c WHERE RE_Run_Type__c='Automate' LIMIT 1];
        List<Reuters_Quotes__c> reuterlist=[SELECT Id,Price__c,CurrencyCode__c,Unit_Of_Measure__c,Pricing_Date__c,Quote_Name__c FROM Reuters_Quotes__c WHERE CreatedDate=TODAY];
        for (Reuters_Quotes__c rq :reuterlist)
        {
            idDisplayMap.put(rq.Id,rq.Quote_Name__c);
            displayMap.put(rq.Quote_Name__c,'Testing long quote dispaly name in move toMarketQuotes Testing long quote dispaly name in move toMarketQuotes');
            isMovedtoMarket.put(rq.Id,sw);
            isMovedtoHistory.put(rq.Id,sw);
            reuterIdList.add(rq.Id);
        }
        for(RE_Zema_Quotes_Settings__c zemaQuote:[SELECT Quote_Name__c,Country__c,Frequency__c,Type__c,Display_Name__c,Price_to_be_converted__c FROM RE_Zema_Quotes_Settings__c WHERE Country__c LIKE '%Canada%'])
            {
                frequencyNameMap.put(zemaQuote.Quote_Name__c, zemaQuote.Frequency__c);
                pricetobeconvrtdMap.put(zemaQuote.Quote_Name__c, zemaQuote.Price_to_be_converted__c);
            }
        isMovedtoMarket = 	RE_CND_QuotesQueueHandler.moveToMarketQuotes(1.2,reuterlist,displayMap,idDisplayMap,jobAudit,isMovedtoMarket,frequencyNameMap,pricetobeconvrtdMap);
        isMovedtoHistory = 	RE_CND_QuotesQueueHandler.moveToReutersHistory(reuterlist,displayMap,reuterIdList,jobAudit,isMovedtoHistory);
        Test.stopTest();
    }

      
}