force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/RE_Depot_Pricing_Backbone__c.object-meta.xml
<CustomObject>
    <label>Depot Pricing Backbone</label>
    <nameField>
        <displayFormat>DPB-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depot Pricing Backbone</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Depot_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Depot_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Depot Name</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Final_Price_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Final_Price_Unit__c</fullName>
    <label>Final Price Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RE_Rate_Unit_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Location__c/RE_Location__c.object-meta.xml
<CustomObject>
    <label>RE Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Location__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipName>Locations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Location__c/fields/RE_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Region_Name__c</fullName>
    <label>Region Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/RE_Product__c.object-meta.xml
<CustomObject>
    <label>RE Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Product__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipName>Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AGO</fullName>
            </value>
            <value>
                <fullName>IGO</fullName>
            </value>
            <value>
                <fullName>MOGAS</fullName>
            </value>
            <value>
                <fullName>KERO</fullName>
            </value>
            <value>
                <fullName>MGO</fullName>
            </value>
            <value>
                <fullName>Marine RFO</fullName>
            </value>
            <value>
                <fullName>Fuel By-Products</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_Product_Subgroup__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Subgroup__c</fullName>
    <label>Product Subgroup</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AGO B7</fullName>
            </value>
            <value>
                <fullName>AGO B0</fullName>
            </value>
            <value>
                <fullName>MOGAS 95</fullName>
            </value>
            <value>
                <fullName>MOGAS 97</fullName>
            </value>
            <value>
                <fullName>Kerosene</fullName>
            </value>
            <value>
                <fullName>IGO B0</fullName>
            </value>
            <value>
                <fullName>IGO B7</fullName>
            </value>
            <value>
                <fullName>IGO B10</fullName>
            </value>
            <value>
                <fullName>Dual Purpose AGO</fullName>
            </value>
            <value>
                <fullName>Gas Oil</fullName>
            </value>
            <value>
                <fullName>Gas Oil Bunker</fullName>
            </value>
            <value>
                <fullName>Hydrogen Refinery</fullName>
            </value>
            <value>
                <fullName>High Octane</fullName>
            </value>
            <value>
                <fullName>IGO</fullName>
            </value>
            <value>
                <fullName>KERO</fullName>
            </value>
            <value>
                <fullName>Low Octane</fullName>
            </value>
            <value>
                <fullName>Medium Octane</fullName>
            </value>
            <value>
                <fullName>Off-road AGO</fullName>
            </value>
            <value>
                <fullName>On-road AGO</fullName>
            </value>
            <value>
                <fullName>RFO Bunker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_TH_Sales_Tax_Duty_1__c.field-meta.xml
<CustomField>
    <fullName>RE_TH_Sales_Tax_Duty_1__c</fullName>
    <label>Sales Tax/Duty-1</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_TH_Sales_Tax_Duty_2__c.field-meta.xml
<CustomField>
    <fullName>RE_TH_Sales_Tax_Duty_2__c</fullName>
    <formula>RE_TH_Sales_Tax_Duty_1__c /10</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Tax/Duty- 2</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_TH_Sales_Tax_Duty_3__c.field-meta.xml
<CustomField>
    <fullName>RE_TH_Sales_Tax_Duty_3__c</fullName>
    <label>Sales Tax/Duty-3</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_TH_Sales_Tax_Duty_4__c.field-meta.xml
<CustomField>
    <fullName>RE_TH_Sales_Tax_Duty_4__c</fullName>
    <label>Sales Tax/Duty-4</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Sales_Tax__c/RE_Sales_Tax__c.object-meta.xml
<CustomObject>
    <label>Sales Tax</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Sales Tax Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Tax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Sales_Tax__c/fields/RE_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Type__c</fullName>
    <label>Product Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Sales_Tax__c/fields/RE_Region__c.field-meta.xml
<CustomField>
    <fullName>RE_Region__c</fullName>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Peninsular</fullName>
            </value>
            <value>
                <fullName>Sabah</fullName>
            </value>
            <value>
                <fullName>Sarawak</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Sales_Tax__c/fields/RE_Tax_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Tax_Unit__c</fullName>
    <label>Tax Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RE_Rate_Unit_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Sales_Tax__c/fields/RE_Tax_Value__c.field-meta.xml
<CustomField>
    <fullName>RE_Tax_Value__c</fullName>
    <label>Tax Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/RE_Rate_Unit_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MYR CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/TON</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>USD/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>USD/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>USD/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>BBL</fullName>
    </customValue>
    <customValue>
        <fullName>LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR</fullName>
    </customValue>
    <customValue>
        <fullName>THB/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>STG/LTR</fullName>
    </customValue>
    <description>Rate Units to be used in  Revolution East Applicaion</description>
    <masterLabel>RE_Rate_Unit_Set</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RE_MY_RecoverySalesTaxController.cls
public class RE_MY_RecoverySalesTaxController { 
    public Map<String, String> prodMap = new Map<String, String>();    
    public RE_MY_RecoverySalesTaxController(){}
    //Constructor to fetch latest Sales Tax data
    public RE_MY_RecoverySalesTaxController(List<RE_Product__c> productlist){
        List<RE_Sales_Tax__c> salestaxdata = RE_SOQLController.fetchsalesTaxData();
        for(RE_Product__c proddata : productlist){                       
            if(proddata.RE_Product_Subgroup__c != null){
                prodMap.put(proddata.Id, proddata.RE_Product_Subgroup__c);
            }                    
    	}
    }
    
    //Preparing formula data and adding to wrapper list
    public RE_UtilitywrapperController.lineitemwraapper recoverySalesTaxPreparation(List<RE_Depot_Pricing_Backbone__c> depotpricinglist,
                                                                                    Map<String, Double> curConvMap){		        
        String location;
        String product;        
        RE_UtilitywrapperController.lineitemwraapper finalineitemval = new RE_UtilitywrapperController.lineitemwraapper();
        Map<Id, Double> rSTCalculation = new Map<Id, Double>();
        RE_unitConversion conv = new RE_unitConversion();
        try{
            for(RE_Depot_Pricing_Backbone__c dpbData : depotpricinglist){          
                Double salesVal = 0;
                String taxUnit =  '';
                location = dpbData.RE_Depot_Name__r.Name;
                product = dpbData.RE_Product_Name__r.Name;
                for(RE_Sales_Tax__c salesdata : RE_SOQLController.fetchsalesTaxData()){
                    List<String> regionlist = salesdata.RE_Region__c.split(';');                    
                    if(prodMap.get(dpbData.RE_Product_Name__c) == salesdata.RE_Product_Type__c && 
					regionlist.contains(dpbData.RE_Depot_Name__r.RE_Region_Name__c)){                        
						taxUnit = salesdata.RE_Tax_Unit__c;
						salesVal = salesdata.RE_Tax_Value__c;
						break;
				    }                                      
                }
                if(salesVal != 0 && taxUnit != ''){
                    List<String> baseparts = RE_unitConversion.unitBreakUp(taxUnit);
                    Double conversionmultiplier = conv.unitConversionMultiplier(taxUnit,dpbData.RE_Final_Price_Unit__c,dpbData.RE_Country__r.Name,
                                                                               dpbData.RE_Product_Name__r.Name,curConvMap);                    
                    salesVal = salesVal * conversionmultiplier;                    
                }  
                rSTCalculation.put(dpbData.Id,salesVal);  
            }
            finalineitemval.errorMessage = '';
            finalineitemval.finalval = rSTCalculation;
        }
        catch(Exception ex){
            finalineitemval.errorMessage = 'Error at RE_MY_RecoverySalesTaxController for '+ location +' and '+ product + ' ' + ex.getMessage();
            finalineitemval.finalval = new Map<Id, Double>();
        }
        return finalineitemval;
    }
    
    //Preparing formula data and adding to wrapper list
    public RE_UtilitywrapperController.lineitemwraapper recoverySalesTaxTHPreparation(List<RE_Depot_Pricing_Backbone__c> depotpricinglist,
                                                                                    Map<String, Double> curConvMap,List<RE_Product__c> prodlist){		        
        String location;
        String product;        
        RE_UtilitywrapperController.lineitemwraapper finalineitemval = new RE_UtilitywrapperController.lineitemwraapper();
        Map<Id, Double> rSTCalculation = new Map<Id, Double>();
        RE_unitConversion conv = new RE_unitConversion();
        Map<String,RE_Product__c> prodMaps = new Map<String,RE_Product__c>();
        for(RE_Product__c prod : prodlist){
            prodMaps.put(prod.Name,prod);
        }
                                                                                        
        try{
            for(RE_Depot_Pricing_Backbone__c dpbData : depotpricinglist){          
                Double salesVal_1 = 0;
                Double salesVal_2 = 0;
                Double salesVal_3 = 0;
                Double salesVal_4 = 0;
                Double salesVal_5 = 0;
                String taxUnit =  '';
                location = dpbData.RE_Depot_Name__r.Name;
                product = dpbData.RE_Product_Name__r.Name;
                
                if(prodMaps.containsKey(product)){
                    RE_Product__c	prodRef = prodMaps.get(product);
                    salesVal_1 = prodRef.RE_TH_Sales_Tax_Duty_1__c != null ? prodRef.RE_TH_Sales_Tax_Duty_1__c : salesVal_1;
                    salesVal_2 = prodRef.RE_TH_Sales_Tax_Duty_2__c != null ? prodRef.RE_TH_Sales_Tax_Duty_2__c : salesVal_2;
                    salesVal_3 = prodRef.RE_TH_Sales_Tax_Duty_3__c != null ? prodRef.RE_TH_Sales_Tax_Duty_3__c : salesVal_3;
                    salesVal_4 = prodRef.RE_TH_Sales_Tax_Duty_4__c	 != null ? prodRef.RE_TH_Sales_Tax_Duty_4__c : salesVal_4;
                }
                salesVal_5 = dpbData.RE_TH_Sales_Tax_Duty_5__c != null ? dpbData.RE_TH_Sales_Tax_Duty_5__c : salesVal_5;

               // if(taxUnit != ''){
                   // List<String> baseparts = RE_unitConversion.unitBreakUp(taxUnit);
                   // Double conversionmultiplier = conv.unitConversionMultiplier(taxUnit,dpbData.RE_Final_Price_Unit__c,dpbData.RE_Country__r.Name,
                                                              //                 dpbData.RE_Product_Name__r.Name,curConvMap);                    
                    if(salesVal_1 != 0)
                    salesVal_1 = salesVal_1 ;//* conversionmultiplier;   
                    if(salesVal_2 != 0)
                    salesVal_2 = salesVal_2 ;//* conversionmultiplier;   
                    if(salesVal_3 != 0)
                    salesVal_3 = salesVal_3 ;//* conversionmultiplier;   
                    if(salesVal_4 != 0)
                    salesVal_4 = salesVal_4;// * conversionmultiplier;   
                    if(salesVal_5 != 0)
                    salesVal_5 = salesVal_5 ;//* conversionmultiplier;   
               // }  
                rSTCalculation.put(dpbData.Id,(salesVal_1 + salesVal_2 + salesVal_3 + salesVal_4 + salesVal_5));  
            }
            finalineitemval.errorMessage = '';
            finalineitemval.finalval = rSTCalculation;
        }
        catch(Exception ex){
            finalineitemval.errorMessage = 'Error at RE_MY_RecoverySalesTaxController for '+ location +' and '+ product + ' ' + ex.getMessage();
            finalineitemval.finalval = new Map<Id, Double>();
        }
        return finalineitemval;
    }
    //Preparing PH formula data and adding to wrapper list
   
    public RE_UtilitywrapperController.lineitemwraapper SalesTaxPHPreparation(List<RE_Depot_Pricing_Backbone__c> depotpricinglist,
                                                                                    Map<String, Double> curConvMap,List<RE_Product__c> prodlist){		        
        String location;
        String product;        
        RE_UtilitywrapperController.lineitemwraapper finalineitemval = new RE_UtilitywrapperController.lineitemwraapper();
        Map<Id, Double> rSTCalculation = new Map<Id, Double>();
        RE_unitConversion conv = new RE_unitConversion();
        Map<String,RE_Product__c> prodMaps = new Map<String,RE_Product__c>();
        //Map<String,RE_Sales_Tax__c> salesTaxList = RE_SOQLController.fetchsalesTaxData();
		List<RE_Sales_Tax__c> salesTaxList = RE_SOQLController.fetchsalesTaxData();
        for(RE_Product__c prod : prodlist){
            prodMaps.put(prod.Name,prod);
        }
                                                                                        
        try{
            for(RE_Depot_Pricing_Backbone__c dpbData : depotpricinglist){          
                Double salesVal = 0;
                String taxUnit =  '';
                location = dpbData.RE_Depot_Name__r.Name;
                product = dpbData.RE_Product_Name__r.Name;
                
                if(prodMaps.containsKey(product)){
				
                    String	prodgrp = prodMaps.get(product).RE_Product_Group__c;
					String	prodcntry = prodMaps.get(product).RE_Country__r.Name;
                    for(RE_Sales_Tax__c salesdata : salesTaxList){
                                       
                    if( prodgrp == salesdata.RE_Product_Type__c && prodcntry == salesdata.RE_Region__c)
					{                        
						taxUnit = salesdata.RE_Tax_Unit__c;
						salesVal = salesdata.RE_Tax_Value__c;
						break;
				    }   
                }
				if(salesVal != 0 && taxUnit != ''){
                    List<String> baseparts = RE_unitConversion.unitBreakUp(taxUnit);
                    Double conversionmultiplier = conv.unitConversionMultiplier(taxUnit,dpbData.RE_Final_Price_Unit__c,dpbData.RE_Country__r.Name,
                                                                               prodgrp,curConvMap);                    
                    salesVal = salesVal * conversionmultiplier;                    
                }  
                rSTCalculation.put(dpbData.Id,salesVal);
              }
               
                
            }
            finalineitemval.errorMessage = '';
            finalineitemval.finalval = rSTCalculation;
        }
        catch(Exception ex){
            finalineitemval.errorMessage = 'Error at SalesTaxPHPreparation for '+ location +' and '+ product + ' ' + ex.getMessage();
            finalineitemval.finalval = new Map<Id, Double>();
        }
        return finalineitemval;
    }
}