force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/RE_Depot_Pricing_Backbone__c.object-meta.xml
<CustomObject>
    <label>Depot Pricing Backbone</label>
    <nameField>
        <displayFormat>DPB-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depot Pricing Backbone</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Depot_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Depot_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Depot Name</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Final_Price_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Final_Price_Unit__c</fullName>
    <label>Final Price Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RE_Rate_Unit_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Location__c/RE_Location__c.object-meta.xml
<CustomObject>
    <label>RE Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Location__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipName>Locations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Location__c/fields/RE_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Region_Name__c</fullName>
    <label>Region Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Malaysian_Formula_Table__mdt/RE_Malaysian_Formula_Table__mdt.object-meta.xml
<CustomObject>
    <label>RE_MY_Malaysian Formula Table</label>
    <pluralLabel>RE_MY_Malaysian Formula Table</pluralLabel>
</CustomObject>

force-app/main/default/objects/RE_Malaysian_Formula_Table__mdt/fields/RE_MY_Plant__c.field-meta.xml
<CustomField>
    <fullName>RE_MY_Plant__c</fullName>
    <label>Plant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tawau</fullName>
            </value>
            <value>
                <fullName>Bintulu</fullName>
            </value>
            <value>
                <fullName>IOT Senari</fullName>
            </value>
            <value>
                <fullName>Bagan Luar</fullName>
            </value>
            <value>
                <fullName>KVDT</fullName>
            </value>
            <value>
                <fullName>Port Dickson</fullName>
            </value>
            <value>
                <fullName>Pasir Gudang</fullName>
            </value>
            <value>
                <fullName>Tanjung Gelang</fullName>
            </value>
            <value>
                <fullName>Labuan</fullName>
            </value>
            <value>
                <fullName>Kota Kinabalu</fullName>
            </value>
            <value>
                <fullName>Sandakan</fullName>
            </value>
            <value>
                <fullName>Tg Manis</fullName>
            </value>
            <value>
                <fullName>Westport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Malaysian_Formula_Table__mdt/fields/RE_MY_Product__c.field-meta.xml
<CustomField>
    <fullName>RE_MY_Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BF ULG95</fullName>
            </value>
            <value>
                <fullName>Gasoil B0 0.001% S</fullName>
                <isActive>false</isActive>
                <label>Gasoil B0 0.001% S</label>
            </value>
            <value>
                <fullName>Gasoil B0 0.05% S</fullName>
            </value>
            <value>
                <fullName>Gasoil B7 0.001% S</fullName>
                <isActive>false</isActive>
                <label>Gasoil B7 0.001% S</label>
            </value>
            <value>
                <fullName>Gasoil B7 0.05% S</fullName>
            </value>
            <value>
                <fullName>Gasoil E2 B10</fullName>
            </value>
            <value>
                <fullName>Gasoil E5 B10</fullName>
                <isActive>false</isActive>
                <label>Gasoil E5 B10</label>
            </value>
            <value>
                <fullName>Gasoil E5 B20</fullName>
                <isActive>false</isActive>
                <label>Gasoil E5 B20</label>
            </value>
            <value>
                <fullName>IGO 10 ppm B0</fullName>
            </value>
            <value>
                <fullName>IGO 10 ppm B10</fullName>
            </value>
            <value>
                <fullName>IGO 10 ppm B20</fullName>
            </value>
            <value>
                <fullName>IGO 10 ppm B7</fullName>
            </value>
            <value>
                <fullName>Kerosene</fullName>
            </value>
            <value>
                <fullName>MOGAS 95</fullName>
                <isActive>false</isActive>
                <label>MOGAS 95</label>
            </value>
            <value>
                <fullName>MOGAS 97</fullName>
                <isActive>false</isActive>
                <label>MOGAS 97</label>
            </value>
            <value>
                <fullName>SH ULG97</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Malaysian_Formula_Table__mdt/fields/RE_MY_Region__c.field-meta.xml
<CustomField>
    <fullName>RE_MY_Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sabah</fullName>
            </value>
            <value>
                <fullName>Sarawak</fullName>
            </value>
            <value>
                <fullName>Peninsular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Product__c/RE_Product__c.object-meta.xml
<CustomObject>
    <label>RE Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Product__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipName>Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Route_Backbone__c/RE_Route_Backbone__c.object-meta.xml
<CustomObject>
    <label>RE Route Backbone</label>
    <nameField>
        <displayFormat>RE_RB-{0000000}</displayFormat>
        <label>Route Backbone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Route Backbones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Route_Backbone__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipName>Route_Backbones1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Route_Backbone__c/fields/RE_Depot_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Depot_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Depot Name</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipName>Route_Backbones1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Route_Backbone__c/fields/RE_Destination_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Destination_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Name</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipName>Route_Backbones1_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Route_Backbone__c/fields/RE_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipName>Route_Backbones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_SG_Cost_Price_Manager__mdt/RE_SG_Cost_Price_Manager__mdt.object-meta.xml
<CustomObject>
    <label>RE_SG_Cost Price Manager</label>
    <pluralLabel>RE_SG_Cost Price Manager</pluralLabel>
</CustomObject>

force-app/main/default/objects/RE_SG_Cost_Price_Manager__mdt/fields/RE_SG_Plant__c.field-meta.xml
<CustomField>
    <fullName>RE_SG_Plant__c</fullName>
    <label>Plant</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Pandan</fullName>
                <default>true</default>
                <label>Pandan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_SG_Cost_Price_Manager__mdt/fields/RE_SG_Product__c.field-meta.xml
<CustomField>
    <fullName>RE_SG_Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>FuelSave95</fullName>
                <default>true</default>
                <label>FuelSave95</label>
            </value>
            <value>
                <fullName>FuelSave98</fullName>
            </value>
            <value>
                <fullName>Fuelsave Diesel</fullName>
            </value>
            <value>
                <fullName>IGO 10ppm</fullName>
            </value>
            <value>
                <fullName>Kero</fullName>
            </value>
            <value>
                <fullName>MGO 0.1%</fullName>
            </value>
            <value>
                <fullName>MGO 0.5%</fullName>
            </value>
            <value>
                <fullName>Vpower</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/RE_Rate_Unit_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MYR CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/TON</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>USD/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>USD/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>USD/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>BBL</fullName>
    </customValue>
    <customValue>
        <fullName>LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR</fullName>
    </customValue>
    <customValue>
        <fullName>THB/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>STG/LTR</fullName>
    </customValue>
    <description>Rate Units to be used in  Revolution East Applicaion</description>
    <masterLabel>RE_Rate_Unit_Set</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RE_MY_FormulaFetchController.cls
public class RE_MY_FormulaFetchController { 
    public Map<Id,formulaWrapper> formulaformedMap = new Map<Id,formulaWrapper>();
    public Map<Id,formulaWrapperSG> formulaformedMapSG = new Map<Id,formulaWrapperSG>();
    public Map<Id,formulaWrapperAMVMY> formulaformedMapAMVMY = new Map<Id,formulaWrapperAMVMY>();
    public Map<Id,formulaWrapperTH>	formulaformedMapTH	= new Map<Id,formulaWrapperTH>();
    
	public List<formulaWrapper> formulaforDepotData(List<RE_Depot_Pricing_Backbone__c> depotpricinglist, List<RE_Malaysian_Formula_Table__mdt> malformulalist){
		//Preparing formula data and adding to wrapper list		
		for(RE_Depot_Pricing_Backbone__c dpbData : depotpricinglist){
			formulaWrapper formwrapData = new formulaWrapper();  
			formwrapData.depoId = dpbData.Id;
            formwrapData.location = dpbData.RE_Depot_Name__r.Name;
            formwrapData.product = dpbData.RE_Product_Name__r.Name;
			formwrapData.country = dpbData.RE_Country__r.Name;
			formwrapData.finalUnit = dpbData.RE_Final_Price_Unit__c;
			for(RE_Malaysian_Formula_Table__mdt formulaData : malformulalist){
				if(dpbData.RE_Product_Name__r.Name == formulaData.RE_MY_Product__c && dpbData.RE_Depot_Name__r.RE_Region_Name__c == formulaData.RE_MY_Region__c){					
					if(formulaData.RE_MY_Plant__c != null && dpbData.RE_Depot_Name__r.Name == formulaData.RE_MY_Plant__c ){
						if(formulaformedMap.containsKey(dpbData.Id))
							formulaformedMap.remove(dpbData.Id);						
						formwrapData.hcfObj = formulaData;
						formulaformedMap.put(dpbData.Id, formwrapData);  
						break;
					}				
					else if(formulaData.RE_MY_Plant__c == null){										
						formwrapData.hcfObj = formulaData;
						formulaformedMap.put(dpbData.Id, formwrapData);   
					}
				}                
			}
		}
		return formulaformedMap.Values();
	}
    
	public List<formulaWrapperSG> formulaforDepotDataSG(List<RE_Depot_Pricing_Backbone__c> depotpricinglist, List<RE_SG_Cost_Price_Manager__mdt> sgformulalist){
		//Preparing formula data and adding to wrapper list	
		for(RE_Depot_Pricing_Backbone__c dpbData : depotpricinglist){
			formulaWrapperSG formwrapData = new formulaWrapperSG();  
			formwrapData.depoId = dpbData.Id;
			formwrapData.country = dpbData.RE_Country__r.Name;
            formwrapData.location = dpbData.RE_Depot_Name__r.Name;
            formwrapData.product = dpbData.RE_Product_Name__r.Name;
			formwrapData.finalUnit = dpbData.RE_Final_Price_Unit__c;
			for(RE_SG_Cost_Price_Manager__mdt formulaData : sgformulalist){
				if(dpbData.RE_Product_Name__r.Name == formulaData.RE_SG_Product__c && dpbData.RE_Depot_Name__r.Name == formulaData.RE_SG_Plant__c ){										
					formwrapData.hcfObj = formulaData;
					formulaformedMapSG.put(dpbData.Id, formwrapData);
					break;														
				}                
			}
		}
		return formulaformedMapSG.Values();
	}
    
    public List<formulaWrapperAMVMY> formulaforDepotDataAMVMY(List<RE_Depot_Pricing_Backbone__c> depotpricinglist, List<RE_Route_Backbone__c> rbblist){
		//Preparing formula data and adding to wrapper list			
        for(RE_Route_Backbone__c formulaData : rbblist){ 
            formulaWrapperAMVMY formwrapData = new formulaWrapperAMVMY();              
            formwrapData.hcfObj = formulaData;
            for(RE_Depot_Pricing_Backbone__c dpbData : depotpricinglist){
                if(dpbData.RE_Product_Name__c == formulaData.RE_Product_Name__c && dpbData.RE_Depot_Name__c == formulaData.RE_Destination_Name__c ){
                    formwrapData.depoId = dpbData.Id;
                    formwrapData.country = dpbData.RE_Country__r.Name;
                    formwrapData.location = dpbData.RE_Depot_Name__r.Name;
                    formwrapData.product = dpbData.RE_Product_Name__r.Name;
                    formwrapData.finalUnit = dpbData.RE_Final_Price_Unit__c;
                }
            }        
            formulaformedMapAMVMY.put(formulaData.Id, formwrapData);
        }
		return formulaformedMapAMVMY.Values();
	}
    public List<formulaWrapperTH> formulaforDepotDataTH(List<RE_Depot_Pricing_Backbone__c> depotpricinglist){
		//Preparing formula data and adding to wrapper list			
        for(RE_Depot_Pricing_Backbone__c formulaData : depotpricinglist){ 
            
            formulaWrapperTH formwrapData = new formulaWrapperTH();              
            formwrapData.hcfObj = formulaData;
            formwrapData.depoId = formulaData.Id;
            formwrapData.country = formulaData.RE_Country__r.Name;
            formwrapData.location = formulaData.RE_Depot_Name__r.Name;
            formwrapData.product = formulaData.RE_Product_Name__r.Name;
            formwrapData.finalUnit = formulaData.RE_Final_Price_Unit__c;                    
            formulaformedMapTH.put(formulaData.Id, formwrapData);
        }
		return formulaformedMapTH.Values();
	}
    public class formulaWrapperSG{
		public Id depoId;
		public String finalUnit;
		Public RE_SG_Cost_Price_Manager__mdt hcfObj;
        public String country;
        public String location;
        public String product;
	}
    public class formulaWrapper{
		public Id depoId;
		public String finalUnit;
		Public RE_Malaysian_Formula_Table__mdt hcfObj;
        public String country;
        public String location;
        public String product;
	}
    public class formulaWrapperAMVMY{
		public Id depoId;
		public String finalUnit;
		Public RE_Route_Backbone__c hcfObj;
        public String country;
        public String location;
        public String product;
	}
    public class formulaWrapperTH{
		public Id depoId;
		public String finalUnit;
		Public RE_Depot_Pricing_Backbone__c hcfObj;
        public String country;
        public String location;
        public String product;
	}
}