force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Bio_Quotes__c/RE_Bio_Quotes__c.object-meta.xml
<CustomObject>
    <label>RE Bio Quotes</label>
    <nameField>
        <displayFormat>BioQuote-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Bio Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Bio_Quotes__c/recordTypes/Thailand.recordType-meta.xml
<RecordType>
    <fullName>Thailand</fullName>
    <active>true</active>
    <label>Thailand</label>
</RecordType>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/RE_Depot_Pricing_Backbone__c.object-meta.xml
<CustomObject>
    <label>Depot Pricing Backbone</label>
    <nameField>
        <displayFormat>DPB-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depot Pricing Backbone</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_TH_Oil_Loss_Percent__c.field-meta.xml
<CustomField>
    <fullName>RE_TH_Oil_Loss_Percent__c</fullName>
    <label>Oil Loss %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/recordTypes/Thailand.recordType-meta.xml
<RecordType>
    <fullName>Thailand</fullName>
    <active>true</active>
    <description>Use for Thailand CBU calculation</description>
    <label>Thailand</label>
</RecordType>

force-app/main/default/objects/RE_ExternalQuoteMapping__c/RE_ExternalQuoteMapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RE_ExternalQuoteMapping</label>
</CustomObject>

force-app/main/default/objects/RE_ExternalQuoteMapping__c/fields/External_Quotation_Number__c.field-meta.xml
<CustomField>
    <fullName>External_Quotation_Number__c</fullName>
    <label>External Quotation Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_ExternalQuoteMapping__c/fields/External_Quote_Source__c.field-meta.xml
<CustomField>
    <fullName>External_Quote_Source__c</fullName>
    <label>External Quote Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_ExternalQuoteMapping__c/fields/External_Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>External_Quote_Type__c</fullName>
    <label>External Quote Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_ExternalQuoteMapping__c/fields/RE_Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Name__c</fullName>
    <label>RE_Quote Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_ExternalQuoteMapping__c/fields/RE_Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Type__c</fullName>
    <label>RE_Quote Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/RE_FX_Rates__c.object-meta.xml
<CustomObject>
    <label>RE FX Rates</label>
    <nameField>
        <displayFormat>FXR-{000000}</displayFormat>
        <label>FX_Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE FX Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Name__c</fullName>
    <description>quote display name is stored</description>
    <label>Quote Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Location__c/RE_Location__c.object-meta.xml
<CustomObject>
    <label>RE Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Location__c/recordTypes/Thailand.recordType-meta.xml
<RecordType>
    <fullName>Thailand</fullName>
    <active>true</active>
    <label>Thailand</label>
</RecordType>

force-app/main/default/objects/RE_Market_Quotes__c/RE_Market_Quotes__c.object-meta.xml
<CustomObject>
    <label>RE Market Quotes</label>
    <nameField>
        <displayFormat>MarketQuote-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Market Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Name__c</fullName>
    <label>Quote Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Type__c</fullName>
    <label>Quote Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Market Premium</fullName>
            </value>
            <value>
                <fullName>Assessed Premium</fullName>
            </value>
            <value>
                <fullName>Midday</fullName>
            </value>
            <value>
                <fullName>Forward Swap</fullName>
            </value>
            <value>
                <fullName>Spot</fullName>
            </value>
            <value>
                <fullName>Freight</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Product__c/RE_Product__c.object-meta.xml
<CustomObject>
    <label>RE Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Product__c/fields/RE_TH_Oil_Loss_Percent__c.field-meta.xml
<CustomField>
    <fullName>RE_TH_Oil_Loss_Percent__c</fullName>
    <label>Oil Loss %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_TH_TP_Premium__c.field-meta.xml
<CustomField>
    <fullName>RE_TH_TP_Premium__c</fullName>
    <label>TP Premium</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_TH_TP_PremiumHCV2__c.field-meta.xml
<CustomField>
    <fullName>RE_TH_TP_PremiumHCV2__c</fullName>
    <label>TH TP PremiumHCV2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_TH_TP_PremiumHCV__c.field-meta.xml
<CustomField>
    <fullName>RE_TH_TP_PremiumHCV__c</fullName>
    <inlineHelpText>Value should be (HCV1:HCV2) EX: 20.46 :2.68, 0:0</inlineHelpText>
    <label>TH TP PremiumHCV1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/TH_TP_PremiumHCV2_UNIT__c.field-meta.xml
<CustomField>
    <fullName>TH_TP_PremiumHCV2_UNIT__c</fullName>
    <label>TH TP PremiumHCV2 UNIT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD/BBL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/TP_Premium_Unit__c.field-meta.xml
<CustomField>
    <fullName>TP_Premium_Unit__c</fullName>
    <label>TP Premium Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RE_Rate_Unit_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Product__c/recordTypes/Thailand.recordType-meta.xml
<RecordType>
    <fullName>Thailand</fullName>
    <active>true</active>
    <label>Thailand</label>
</RecordType>

force-app/main/default/globalValueSets/RE_Rate_Unit_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MYR CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/TON</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>USD/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>USD/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>USD/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>BBL</fullName>
    </customValue>
    <customValue>
        <fullName>LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR</fullName>
    </customValue>
    <customValue>
        <fullName>THB/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>STG/LTR</fullName>
    </customValue>
    <description>Rate Units to be used in  Revolution East Applicaion</description>
    <masterLabel>RE_Rate_Unit_Set</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RE_TH_CostCalculationtTest.cls
@isTest(SeeAllData = False)
public class RE_TH_CostCalculationtTest { 
    public static testmethod void testUtility()
    {
        //Country Data
        List<Country__c> count = new List<Country__c>();
        Country__c country = RE_UtilityClass.getCountryCode('Thailand');
        count.add(country);
        
        //Location Data
        List<RE_Location__c> location = new List<RE_Location__c>();
        RE_Location__c loctn = RE_UtilityClass.getLocation('Bandon','LB','Thailand');
        RE_Location__c loctn1 = RE_UtilityClass.getLocation('Chongnonsri','BK','Thailand');
        RE_Location__c loctn2 = RE_UtilityClass.getLocation('Lumlukka','LB','Thailand');
        location.add(loctn);
        location.add(loctn1);
        location.add(loctn2);
        
        //Product Data
        List<RE_Product__c> prod = new List<RE_Product__c>();
        RE_Product__c product = RE_UtilityClass.getProduct('Kerosene','Thailand','STG/LTR');
        RE_Product__c product1 = RE_UtilityClass.getProduct('Fuel Oil A 2%S-80 CST','Thailand','STG/LTR');
        product.TP_Premium_Unit__c	=	'USD/BBL';
        product.RE_TH_TP_PremiumHCV__c=0;
        product.RE_TH_TP_Premium__c='1.8';
        product.TH_TP_PremiumHCV2_UNIT__c='USD/BBL';
        product.RE_TH_Oil_Loss_Percent__c=0.1;
        product1.TP_Premium_Unit__c	=	'USD/BBL';
        product1.RE_TH_TP_Premium__c='1.8';
        product1.RE_TH_TP_PremiumHCV2__c=0;
        product1.TH_TP_PremiumHCV2_UNIT__c='USD/BBL';
        product1.RE_TH_Oil_Loss_Percent__c=0.1;
        prod.add(product);
        prod.add(product1);
        update prod;
        //Fetch Custom Setting Data For Rate
        RE_UtilityClass.fetchRateUnitData();
        
        //Fetch Custom Setting Data For Volume
        RE_UtilityClass.fetchVolumeConversionData();
        
        RE_ExternalQuoteMapping__c extQuote = new RE_ExternalQuoteMapping__c();
        extQuote.name='Kero';
        extQuote.External_Quote_Source__c = 'PP';
        extQuote.External_Quote_Type__c = 'M';
        extQuote.External_Quotation_Number__c = 'SING FOB KERO';
        extQuote.RE_Quote_Name__c = 'Kero';
        extQuote.RE_Quote_Type__c = 'Settlement';
        insert extQuote;
        
        //Market Quote Data
        List<RE_Market_Quotes__c> mQuotes = new List<RE_Market_Quotes__c>();
        RE_Market_Quotes__c createMQ1  = RE_UtilityClass.getMarketQuotes(23.6560,'USD/TON','BBL','Marine FuelOil 180');
        createMQ1.RE_Quote_Type__c = 'Settlement';
        RE_Market_Quotes__c createMQ2  = RE_UtilityClass.getMarketQuotes(57.4658,'USD/BBL','BBL','Gasoil 0.05% S');
        createMQ2.RE_Quote_Type__c = 'Settlement';
        RE_Market_Quotes__c createMQ3  = RE_UtilityClass.getMarketQuotes(54.4658,'USD/BBL','BBL','Kero');
        createMQ3.RE_Quote_Type__c = 'Settlement';       
        mQuotes.add(createMQ1);
        mQuotes.add(createMQ2);
        mQuotes.add(createMQ3);       
		update mQuotes;
        
        //Forex Rate Data
        //List<RE_FX_Rates__c> fRates = new List<RE_FX_Rates__c>();
        //RE_FX_Rates__c FXrate2 = RE_UtilityClass.createFXRecordsYday('THB/USD',4.3720,'USD','MYR','Thailand');
       // RE_FX_Rates__c FXrate1 = RE_UtilityClass.createFXRecordsYday('MYR CTS/USD',437.20,'USD','MYR CTS','Thailand');        
  
        //Bio Quote Data
		
        List<RE_Bio_Quotes__c> bQuotes = new List<RE_Bio_Quotes__c>();
        RE_Bio_Quotes__c bQ1 = RE_UtilityClass.getBioQuotes(76.4200,'USD/BBL','BBL','HDGO','Thailand');
        bQuotes.add(bQ1); 
       /* RE_Bio_Quotes__c bQ2 = RE_UtilityClass.getBioQuotes(75.4200,'MYR/TON','TON','POME (SBH)','Thailand');
        bQuotes.add(bQ2);
        RE_Bio_Quotes__c bQ3 = RE_UtilityClass.getBioQuotes(75.4200,'USD/BBL','BBL','Green Palm (SBH)','Thailand');  //'MYR/TON',
        bQuotes.add(bQ3);
        */
        //Depot Pricing Backbone data
        List<RE_Depot_Pricing_Backbone__c> dPricing = new List<RE_Depot_Pricing_Backbone__c>();
        RE_Depot_Pricing_Backbone__c dP = RE_UtilityClass.createDPB('Thailand','Chongnonsri','Kerosene','THB/LTR');
        RE_Depot_Pricing_Backbone__c dP1 = RE_UtilityClass.createDPB('Thailand','Chongnonsri','Kerosene','THB/LTR');
        dPricing.add(dP);
        dPricing.add(dP1);
        dp.RE_TH_HCV_Quote1__c = 'SING FOB KERO';
        dp.RE_TH_HCV_Quote2__c = null;
        
        update dp;
        System.debug('dP   '+dP);
      update product;         
        test.startTest();     
        RE_FX_Rates__c FXrate3 = RE_UtilityClass.createFXRecords('THB/USD',1.3629,'USD','THB','Thailand','D');
        RE_MalayasiaOutputController.jobExecute('Thailand Output'); 
        //RE_MalayasiaOutputController.AMVjobExecute();
        test.stopTest();        
    }
}