force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Depot_Based_Costing__c/RE_Depot_Based_Costing__c.object-meta.xml
<CustomObject>
    <label>AMV Depot Costing</label>
    <nameField>
        <displayFormat>DBC-{000000000}</displayFormat>
        <label>Depot Based Costing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AMV Depot Costings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Depot_Based_Costing__c/fields/RE_Bio_Value__c.field-meta.xml
<CustomField>
    <fullName>RE_Bio_Value__c</fullName>
    <label>Bio Value</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Based_Costing__c/fields/RE_Comments__c.field-meta.xml
<CustomField>
    <fullName>RE_Comments__c</fullName>
    <label>Comments</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Based_Costing__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>AMV Depot Costings</relationshipLabel>
    <relationshipName>AMV_Depot_Costings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Based_Costing__c/fields/RE_Depot_Pricing_Backbone__c.field-meta.xml
<CustomField>
    <fullName>RE_Depot_Pricing_Backbone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Depot Pricing Backbone</label>
    <referenceTo>RE_Depot_Pricing_Backbone__c</referenceTo>
    <relationshipName>Depot_Based_Costings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Based_Costing__c/fields/RE_HCV_Value__c.field-meta.xml
<CustomField>
    <fullName>RE_HCV_Value__c</fullName>
    <label>HCV Value</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Based_Costing__c/fields/RE_IsLatest__c.field-meta.xml
<CustomField>
    <fullName>RE_IsLatest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsLatest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Based_Costing__c/fields/RE_S_N_H_Cost__c.field-meta.xml
<CustomField>
    <fullName>RE_S_N_H_Cost__c</fullName>
    <label>S&amp;H Cost</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Based_Costing__c/fields/RE_Sales_Tax__c.field-meta.xml
<CustomField>
    <fullName>RE_Sales_Tax__c</fullName>
    <label>Sales Tax</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Based_Costing__c/fields/RE_Spot_Price_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>RE_Spot_Price_Adjustment__c</fullName>
    <label>Spot Price Adjustment</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Based_Costing__c/fields/RE_Weighted_Avg__c.field-meta.xml
<CustomField>
    <fullName>RE_Weighted_Avg__c</fullName>
    <label>Weighted Avg</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Based_Costing__c/recordTypes/Malaysia.recordType-meta.xml
<RecordType>
    <fullName>Malaysia</fullName>
    <active>true</active>
    <label>Malaysia</label>
</RecordType>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/RE_Depot_Pricing_Backbone__c.object-meta.xml
<CustomObject>
    <label>Depot Pricing Backbone</label>
    <nameField>
        <displayFormat>DPB-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depot Pricing Backbone</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Depot_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Depot_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Depot Name</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Valid_From__c.field-meta.xml
<CustomField>
    <fullName>RE_Valid_From__c</fullName>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/recordTypes/Malaysia.recordType-meta.xml
<RecordType>
    <fullName>Malaysia</fullName>
    <active>true</active>
    <label>Malaysia</label>
</RecordType>

force-app/main/default/objects/RE_Location__c/RE_Location__c.object-meta.xml
<CustomObject>
    <label>RE Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Location__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipName>Locations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Location__c/fields/RE_Location_Code__c.field-meta.xml
<CustomField>
    <fullName>RE_Location_Code__c</fullName>
    <label>Location Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Location__c/recordTypes/Malaysia.recordType-meta.xml
<RecordType>
    <fullName>Malaysia</fullName>
    <active>true</active>
    <label>Malaysia</label>
</RecordType>

force-app/main/default/objects/RE_MOA__c/RE_MOA__c.object-meta.xml
<CustomObject>
    <label>MOA</label>
    <nameField>
        <displayFormat>MOA-{000000000}</displayFormat>
        <label>MOA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MOA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_MOA__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>MOA</relationshipLabel>
    <relationshipName>MOA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_MOA__c/fields/RE_Depot_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Depot_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Depot Name</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipLabel>MOA</relationshipLabel>
    <relationshipName>MOA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_MOA__c/fields/RE_IsLatest__c.field-meta.xml
<CustomField>
    <fullName>RE_IsLatest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsLatest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RE_MOA__c/fields/RE_Product__c.field-meta.xml
<CustomField>
    <fullName>RE_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipLabel>MOA</relationshipLabel>
    <relationshipName>MOA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_MOA__c/fields/RE_Remark__c.field-meta.xml
<CustomField>
    <fullName>RE_Remark__c</fullName>
    <label>Remark</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RE_MOA__c/fields/RE_Today_s_BSP__c.field-meta.xml
<CustomField>
    <fullName>RE_Today_s_BSP__c</fullName>
    <label>Today&apos;s BSP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MOA__c/fields/RE_valid_from__c.field-meta.xml
<CustomField>
    <fullName>RE_valid_from__c</fullName>
    <label>RE valid from</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_MOA__c/fields/RE_valid_to__c.field-meta.xml
<CustomField>
    <fullName>RE_valid_to__c</fullName>
    <label>RE valid to</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_MOA__c/recordTypes/Malaysia.recordType-meta.xml
<RecordType>
    <fullName>Malaysia</fullName>
    <active>true</active>
    <label>Malaysia</label>
</RecordType>

force-app/main/default/objects/RE_Product__c/RE_Product__c.object-meta.xml
<CustomObject>
    <label>RE Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Product__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipName>Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/recordTypes/Malaysia.recordType-meta.xml
<RecordType>
    <fullName>Malaysia</fullName>
    <active>true</active>
    <label>Malaysia</label>
</RecordType>

force-app/main/default/objects/RE_Sales_Tax__c/RE_Sales_Tax__c.object-meta.xml
<CustomObject>
    <label>Sales Tax</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Sales Tax Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Tax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Sales_Tax__c/fields/RE_Valid_From__c.field-meta.xml
<CustomField>
    <fullName>RE_Valid_From__c</fullName>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_Sales_Tax__c/fields/RE_Valid_To__c.field-meta.xml
<CustomField>
    <fullName>RE_Valid_To__c</fullName>
    <label>Valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/RE_Depot_Based_Costing_TriggerHelperTest.cls
@isTest
public class RE_Depot_Based_Costing_TriggerHelperTest { 
    public static testmethod void testUtility()
    {
        //Country Data 
        Country__c country = new Country__c(Name='Malaysia');
        insert country;
        
        //Location Data
        List<RE_Location__c> location = new List<RE_Location__c>();
        RE_Location__c loctn =  new RE_Location__c(Name='Labuan',RE_Location_Code__c='LB',RE_Country__c = country.id);
        RE_Location__c loctn1 = new RE_Location__c(Name='Bagan Luar',RE_Location_Code__c='BK',RE_Country__c = country.id);
        location.add(loctn);
        location.add(loctn1);
        insert location;
        
        //Product Data
        List<RE_Product__c> prod = new List<RE_Product__c>();
        RE_Product__c product = new RE_Product__c(Name='Gasoil B7 0.05% S',RE_Country__c= country.Id);
        RE_Product__c product1 = new RE_Product__c(Name='MOGAS 95',RE_Country__c= country.Id);
        RE_Product__c product2 = new RE_Product__c(Name='MOGAS 97',RE_Country__c= country.Id);
        prod.add(product);
        prod.add(product1);
        prod.add(product2);
        insert prod;
        
        //RE_Depot_Pricing_Backbone__c data
        List<RE_Depot_Pricing_Backbone__c> dpbLst = new  List<RE_Depot_Pricing_Backbone__c>();
        RE_Depot_Pricing_Backbone__c dpb1 = new  RE_Depot_Pricing_Backbone__c(RE_Country__c = country.Id,RE_Product_Name__c = prod[1].Id, RE_Depot_Name__c = location[0].Id,RE_Spot_Price_Adjustment__c= 2.23,RE_Target_Margin__c = 3.1,RE_Valid_From__c = System.Today(), RE_Valid_To__c = System.Today());  
        RE_Depot_Pricing_Backbone__c dpb2 = new  RE_Depot_Pricing_Backbone__c(RE_Country__c = country.Id,RE_Product_Name__c = prod[0].Id, RE_Depot_Name__c = location[1].Id,RE_Spot_Price_Adjustment__c= 1.23,RE_Target_Margin__c = 4.1,RE_Valid_From__c = System.Today(), RE_Valid_To__c = System.Today()); 
        dpbLst.add(dpb1);
        dpbLst.add(dpb2);
        insert dpbLst;
        
        //RE_MOA__c data
        List<RE_MOA__c> moaList = new List<RE_MOA__c>();
        RE_MOA__c moaData1 = new RE_MOA__c(RE_Depot_Name__c = location[0].Id, RE_Product__c = prod[1].Id, RE_IsLatest__c = True,RE_Today_s_BSP__c=3.45,RE_Remark__c='abc');
        RE_MOA__c moaData2 = new RE_MOA__c(RE_Depot_Name__c = location[1].Id, RE_Product__c = prod[0].Id, RE_IsLatest__c = True,RE_Today_s_BSP__c=7.45,RE_Remark__c='mbc');
        moaList.add(moaData1);
        moaList.add(moaData2);
        
        //Depot based costing data
        List<RE_Depot_Based_Costing__c> dpcLst = new  List<RE_Depot_Based_Costing__c>();
        RE_Depot_Based_Costing__c dpc1 = new  RE_Depot_Based_Costing__c(RE_HCV_Value__c= 24.45,RE_Bio_Value__c=16.73,RE_S_N_H_Cost__c= 33.26 ,RE_Spot_Price_Adjustment__c= 45.21 ,RE_Sales_Tax__c= 26.34 ,RE_Weighted_Avg__c= 12.64,RE_Comments__c='mno',RE_Depot_Pricing_Backbone__c= dpbLst[0].id,RE_IsLatest__c = True);  
        RE_Depot_Based_Costing__c dpc2 = new  RE_Depot_Based_Costing__c(RE_Comments__c='mps',RE_HCV_Value__c= 42.45,RE_Bio_Value__c=21.78,RE_S_N_H_Cost__c= 38.26 ,RE_Spot_Price_Adjustment__c= 24.27 ,RE_Sales_Tax__c= 35.21 ,RE_Weighted_Avg__c= 26.64,RE_Depot_Pricing_Backbone__c= dpbLst[1].id,RE_IsLatest__c = True);                                                                             
        dpcLst.add(dpc1);
        dpcLst.add(dpc2);
              
        Test.startTest();
        insert moaList;
        insert dpcLst;
        //System.debug('moaList@@@'+moaList);
        Test.stopTest();
    }
}