force-app/main/default/objects/RE_External_Exchange_Rate__c/RE_External_Exchange_Rate__c.object-meta.xml
<CustomObject>
    <label>RE External Exchange Rate</label>
    <nameField>
        <displayFormat>RFX-{0000000000}</displayFormat>
        <label>RE External Exchange Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE External Exchange Rate</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_External_Exchange_Rate__c/fields/RE_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>RE_Effective_Date__c</fullName>
    <label>Effective Date</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_External_Exchange_Rate__c/fields/RE_Exchange_Rate_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Exchange_Rate_Type__c</fullName>
    <label>Exchange Rate Type</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_External_Exchange_Rate__c/fields/RE_Rate__c.field-meta.xml
<CustomField>
    <fullName>RE_Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_External_Exchange_Rate__c/fields/RE_To_Currency__c.field-meta.xml
<CustomField>
    <fullName>RE_To_Currency__c</fullName>
    <label>To Currency</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_ExternalFXMappings__c/RE_ExternalFXMappings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RE_ExternalFXMappings</label>
</CustomObject>

force-app/main/default/objects/RE_ExternalFXMappings__c/fields/RE_Base_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Base_Unit__c</fullName>
    <label>RE Base Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_ExternalFXMappings__c/fields/RE_Conversion_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Conversion_Unit__c</fullName>
    <label>RE Conversion Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_ExternalFXMappings__c/fields/RE_External_Currency__c.field-meta.xml
<CustomField>
    <fullName>RE_External_Currency__c</fullName>
    <label>RE External Currency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_ExternalFXMappings__c/fields/RE_Forex_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Forex_Name__c</fullName>
    <label>RE Forex Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_ExternalFXMappings__c/fields/RE_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Type__c</fullName>
    <label>RE Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/RE_FX_Rates__c.object-meta.xml
<CustomObject>
    <label>RE FX Rates</label>
    <nameField>
        <displayFormat>FXR-{000000}</displayFormat>
        <label>FX_Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE FX Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Base_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Base_Unit__c</fullName>
    <label>Base Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Conversion_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Conversion_Unit__c</fullName>
    <label>Conversion Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Forex_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Forex_Name__c</fullName>
    <label>Forex Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Forex_Rate__c.field-meta.xml
<CustomField>
    <fullName>RE_Forex_Rate__c</fullName>
    <label>Forex Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Pricing_Date__c.field-meta.xml
<CustomField>
    <fullName>RE_Pricing_Date__c</fullName>
    <label>Published Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Tracker__c.field-meta.xml
<CustomField>
    <fullName>RE_Tracker__c</fullName>
    <label>Tracker</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>D-1</fullName>
            </value>
            <value>
                <fullName>D-2</fullName>
            </value>
            <value>
                <fullName>D+1</fullName>
            </value>
            <value>
                <fullName>MTD</fullName>
            </value>
            <value>
                <fullName>WTD</fullName>
            </value>
            <value>
                <fullName>W-1</fullName>
            </value>
            <value>
                <fullName>W-2</fullName>
            </value>
            <value>
                <fullName>M-1</fullName>
            </value>
            <value>
                <fullName>M-2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Trade_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Trade_Type__c</fullName>
    <label>Trade Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
            <value>
                <fullName>Exchange Rate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RE_ExternalExchangeRateTriggerHelper.cls
public class RE_ExternalExchangeRateTriggerHelper {
    /*
Version : 0.0 
Author	: Souvik
Date	: 24-Sep-2020
Details	: GSAP Integration
*/
    
    public static void onAfterExternalFXRatesHelper(List<RE_External_Exchange_Rate__c> newExternalFXRateList
                                                    ,Map<ID,RE_External_Exchange_Rate__c> newExternalFXRateMap
                                                    ,Map<ID,RE_External_Exchange_Rate__c> oldExternalFXRateMap)
    {
        
        Map<String,RE_ExternalFXMappings__c> extFXRateCustSetting = RE_ExternalFXMappings__c.getAll();
        List<RE_FX_Rates__c> sFXRate = new List<RE_FX_Rates__c>();
        
        for(RE_External_Exchange_Rate__c extFXRateObj : newExternalFXRateList)
        {
            for(String str : extFXRateCustSetting.keySet())
            {                
                RE_ExternalFXMappings__c extFXRateValue = extFXRateCustSetting.get(str); 
                if(extFXRateValue.RE_External_Currency__c == extFXRateObj.RE_To_Currency__c && extFXRateValue.RE_Type__c == extFXRateObj.RE_Exchange_Rate_Type__c)
                {
                    
                    List<String> sTradeType = new List<String>{'Buy','Sell','Exchange Rate'};
                        for(Integer i=0; i<sTradeType.size(); i++)
                    {
                        RE_FX_Rates__c FXDataCTS   = new RE_FX_Rates__c();
                        FXDataCTS.RE_Tracker__c = 'D+1';
                        FXDataCTS.RE_Conversion_Unit__c = extFXRateValue.RE_Conversion_Unit__c;
                        FXDataCTS.RE_Base_Unit__c  =  extFXRateValue.RE_Base_Unit__c; 
                        FXDataCTS.RE_Forex_Name__c = extFXRateValue.RE_Forex_Name__c;
                        FXDataCTS.RE_Trade_Type__c = sTradeType[i];
                        FXDataCTS.RE_Pricing_Date__c = RE_ExternalTriggerHelper.convertToDate(extFXRateObj.RE_Effective_Date__c,'ExFX');   
                        
                        if(extFXRateValue.RE_Conversion_Unit__c.contains('CTS') || extFXRateValue.RE_Conversion_Unit__c == 'STG'){                            
                            if(sTradeType[i]=='Buy')
                                FXDataCTS.RE_Forex_Rate__c = extFXRateObj.RE_Rate__c*100;                            
                            if(sTradeType[i]=='Sell')                            
                                FXDataCTS.RE_Forex_Rate__c = extFXRateObj.RE_Rate__c*100;                              
                            if(sTradeType[i]=='Exchange Rate')                            
                                FXDataCTS.RE_Forex_Rate__c = extFXRateObj.RE_Rate__c*100;                                                           
                        }
                        else{                            
                            if(sTradeType[i]=='Buy')
                                FXDataCTS.RE_Forex_Rate__c = extFXRateObj.RE_Rate__c;
                            if(sTradeType[i]=='Sell')
                                FXDataCTS.RE_Forex_Rate__c = extFXRateObj.RE_Rate__c;  
                            if(sTradeType[i]=='Exchange Rate')
                                FXDataCTS.RE_Forex_Rate__c = extFXRateObj.RE_Rate__c;
                        }
                        sFXRate.add(FXDataCTS);
                    } 
                }
            }
        }
        if(sFXRate.size()>0)
        {
            try{insert sFXRate;}
            catch(Exception e)
            {System.debug('Failed while inserting to Exchange Rates '+e.getMessage());}
        }
    }  
}