force-app/main/default/objects/RE_External_Exchange_Rate__c/RE_External_Exchange_Rate__c.object-meta.xml
<CustomObject>
    <label>RE External Exchange Rate</label>
    <nameField>
        <displayFormat>RFX-{0000000000}</displayFormat>
        <label>RE External Exchange Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE External Exchange Rate</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_External_Exchange_Rate__c/fields/RE_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>RE_Effective_Date__c</fullName>
    <label>Effective Date</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_External_Exchange_Rate__c/fields/RE_Exchange_Rate_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Exchange_Rate_Type__c</fullName>
    <label>Exchange Rate Type</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_External_Exchange_Rate__c/fields/RE_From_Currency__c.field-meta.xml
<CustomField>
    <fullName>RE_From_Currency__c</fullName>
    <label>From Currency</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_External_Exchange_Rate__c/fields/RE_Rate__c.field-meta.xml
<CustomField>
    <fullName>RE_Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_External_Exchange_Rate__c/fields/RE_To_Currency__c.field-meta.xml
<CustomField>
    <fullName>RE_To_Currency__c</fullName>
    <label>To Currency</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RE_FxRateController.cls
@RestResource(urlMapping='/RE_FX_Rates/*')
global class RE_FxRateController {  
    @HttpPost
    global static void createFxRate() {
		RestResponse res = RestContext.response;
        RestRequest req = RestContext.request;
        List<jsonFxWrap> jsonWrapList = (List<jsonFxWrap>)JSON.deserialize(req.requestbody.tostring(),List<jsonFxWrap>.class);
        List<RE_External_Exchange_Rate__c> fxdatalist = new List<RE_External_Exchange_Rate__c>();
        for(jsonFxWrap jsondata : jsonWrapList){
            if(jsondata.exchangeRateType != null && jsondata.fromCurrency != null && jsondata.toCurrency != null && jsondata.effectiveDate != null){
                RE_External_Exchange_Rate__c exfxdata = new RE_External_Exchange_Rate__c();
                exfxdata.RE_Exchange_Rate_Type__c = jsondata.exchangeRateType;
                exfxdata.RE_From_Currency__c = jsondata.fromCurrency;
                exfxdata.RE_To_Currency__c = jsondata.toCurrency;
                exfxdata.RE_Effective_Date__c = jsondata.effectiveDate;
                exfxdata.RE_Rate__c = jsondata.rate;
                fxdatalist.add(exfxdata);
            }
        }
        if(!fxdatalist.isEmpty()){
            try{ 
                Database.insert(fxdatalist, True);
            	res.statusCode = 201;
                res.responseBody = Blob.valueOf('Success');
            }
            catch(Exception e){
                res.statusCode = 403;
                res.responseBody = Blob.valueOf('Failure - '+e.getMessage());
                System.debug('Failed Fx load');
            }
        }
        else{
            res.statusCode = 400;
            res.responseBody = Blob.valueOf('Failure'); 
        }
        
    } 
    
    public class jsonFxWrap{
        String exchangeRateType;
        String fromCurrency;
        String toCurrency;
        String effectiveDate;
        Double rate;
    }
}