force-app/main/default/objects/RE_Market_Quotes__c/RE_Market_Quotes__c.object-meta.xml
<CustomObject>
    <label>RE Market Quotes</label>
    <nameField>
        <displayFormat>MarketQuote-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Market Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Price__c.field-meta.xml
<CustomField>
    <fullName>RE_Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Name__c</fullName>
    <label>Quote Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Type__c</fullName>
    <label>Quote Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Market Premium</fullName>
            </value>
            <value>
                <fullName>Assessed Premium</fullName>
            </value>
            <value>
                <fullName>Midday</fullName>
            </value>
            <value>
                <fullName>Forward Swap</fullName>
            </value>
            <value>
                <fullName>Spot</fullName>
            </value>
            <value>
                <fullName>Freight</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Rate_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Rate_Unit__c</fullName>
    <label>Rate Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RE_Rate_Unit_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Tracker__c.field-meta.xml
<CustomField>
    <fullName>RE_Tracker__c</fullName>
    <label>Tracker</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>D-1</fullName>
            </value>
            <value>
                <fullName>MTD</fullName>
            </value>
            <value>
                <fullName>WTD</fullName>
            </value>
            <value>
                <fullName>W-1</fullName>
            </value>
            <value>
                <fullName>W-2</fullName>
            </value>
            <value>
                <fullName>M-1</fullName>
            </value>
            <value>
                <fullName>M-2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/RE_Rate_Unit_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MYR CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/TON</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>USD/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>USD/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>USD/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>BBL</fullName>
    </customValue>
    <customValue>
        <fullName>LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR</fullName>
    </customValue>
    <customValue>
        <fullName>THB/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>STG/LTR</fullName>
    </customValue>
    <description>Rate Units to be used in  Revolution East Applicaion</description>
    <masterLabel>RE_Rate_Unit_Set</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RE_PH_WeekMonthScheduler.cls
public class RE_PH_WeekMonthScheduler implements schedulable{
	
    public void execute(System.SchedulableContext sc){
        Datetime dt = System.today();
    	Integer dayOfmonth = dt.day();                                   
    	string dayOfWeek = dt.format('EEEE');
        System.debug('--Dt--'+dt);
        System.debug('--dayOfWeek--'+dayOfWeek);
		List<RE_Market_Quotes__c> quotedata = new List<RE_Market_Quotes__c>();
        List<RE_Market_Quotes__c> oldquotedata = new List<RE_Market_Quotes__c>();
     	if(dayOfWeek =='Monday' || Test.isRunningTest()){            
			//calculating W-1
			for(AggregateResult mopsdatalastweek : [
				SELECT AVG(RE_Price__c) pravgval,RE_Quote_Name__c,RE_Rate_Unit__c,RE_Quote_Type__c FROM RE_Market_Quotes__c 
				WHERE RE_Pricing_Date__c = LAST_WEEK AND RE_Quote_Type__c IN('Settlement','Market Premium','Freight') AND RE_Is_MTDWTD__c = False AND RE_Country_Name__c INCLUDES ('SG','PH','TH','MY')
				GROUP BY RE_Quote_Name__c,RE_Rate_Unit__c, RE_Quote_Type__c
			]){
				RE_Market_Quotes__c markQuote = new RE_Market_Quotes__c();                    
				markQuote.RE_Quote_Name__c = (String)mopsdatalastweek.get('RE_Quote_Name__c');
				markQuote.RE_Quote_Type__c = (String)mopsdatalastweek.get('RE_Quote_Type__c');                    
				markQuote.RE_Rate_Unit__c = (String)mopsdatalastweek.get('RE_Rate_Unit__c');
				markQuote.RE_Price__c = (Decimal) mopsdatalastweek.get('pravgval');
				markQuote.RE_Pricing_Date__c = System.today();
				markQuote.RE_Tracker__c = 'W-1';
                markQuote.RE_Is_MTDWTD__c = True;
                markQuote.RE_Country_Name__c = 'SG;PH;TH;MY';
				quotedata.add(markQuote);
			}
		} 
    
        if(dayOfmonth == 1  || Test.isRunningTest()){
			//calculating M-1   			
			for(AggregateResult mopsdatalastweek : [
				SELECT AVG(RE_Price__c) pravgval,RE_Quote_Name__c,RE_Rate_Unit__c,RE_Quote_Type__c FROM RE_Market_Quotes__c 
				WHERE RE_Pricing_Date__c = LAST_MONTH AND RE_Quote_Type__c IN('Settlement','Market Premium','Freight') AND RE_Is_MTDWTD__c = False AND RE_Country_Name__c INCLUDES ('SG','PH','TH','MY')
				GROUP BY RE_Quote_Name__c,RE_Rate_Unit__c, RE_Quote_Type__c
			]){
				RE_Market_Quotes__c markQuote = new RE_Market_Quotes__c();                    
				markQuote.RE_Quote_Name__c = (String)mopsdatalastweek.get('RE_Quote_Name__c');
				markQuote.RE_Quote_Type__c = (String)mopsdatalastweek.get('RE_Quote_Type__c');                    
				markQuote.RE_Rate_Unit__c = (String)mopsdatalastweek.get('RE_Rate_Unit__c');
				markQuote.RE_Price__c = (Decimal) mopsdatalastweek.get('pravgval');
				markQuote.RE_Pricing_Date__c = System.today();
				markQuote.RE_Tracker__c = 'M-1';
                markQuote.RE_Is_MTDWTD__c = True;
                markQuote.RE_Country_Name__c = 'SG;PH;TH;MY';
				quotedata.add(markQuote);
			}
		}
        
        if(!quotedata.isEmpty()){
            try{insert quotedata;}
        	catch(Exception ex){system.debug(ex.getCause());}
        }
    }
}