force-app/main/default/objects/RE_External_FX_Rates__c/RE_External_FX_Rates__c.object-meta.xml
<CustomObject>
    <label>External FX Rates</label>
    <nameField>
        <label>External FX Rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External FX Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_External_FX_Rates__c/fields/RE_Buy_Rate__c.field-meta.xml
<CustomField>
    <fullName>RE_Buy_Rate__c</fullName>
    <label>Buy</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_External_FX_Rates__c/fields/RE_Currency__c.field-meta.xml
<CustomField>
    <fullName>RE_Currency__c</fullName>
    <label>Query Currency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_External_FX_Rates__c/fields/RE_Date__c.field-meta.xml
<CustomField>
    <fullName>RE_Date__c</fullName>
    <label>Date</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_External_FX_Rates__c/fields/RE_Mean_Rate__c.field-meta.xml
<CustomField>
    <fullName>RE_Mean_Rate__c</fullName>
    <label>Mean</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_External_FX_Rates__c/fields/RE_Sell_Rate__c.field-meta.xml
<CustomField>
    <fullName>RE_Sell_Rate__c</fullName>
    <label>Sell</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_ExternalFXMappings__c/RE_ExternalFXMappings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RE_ExternalFXMappings</label>
</CustomObject>

force-app/main/default/objects/RE_ExternalFXMappings__c/fields/RE_Base_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Base_Unit__c</fullName>
    <label>RE Base Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_ExternalFXMappings__c/fields/RE_Conversion_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Conversion_Unit__c</fullName>
    <label>RE Conversion Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_ExternalFXMappings__c/fields/RE_External_Currency__c.field-meta.xml
<CustomField>
    <fullName>RE_External_Currency__c</fullName>
    <label>RE External Currency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_ExternalFXMappings__c/fields/RE_Forex_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Forex_Name__c</fullName>
    <label>RE Forex Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/RE_FX_Rates__c.object-meta.xml
<CustomObject>
    <label>RE FX Rates</label>
    <nameField>
        <displayFormat>FXR-{000000}</displayFormat>
        <label>FX_Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE FX Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Base_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Base_Unit__c</fullName>
    <label>Base Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Conversion_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Conversion_Unit__c</fullName>
    <label>Conversion Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Forex_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Forex_Name__c</fullName>
    <label>Forex Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Forex_Rate__c.field-meta.xml
<CustomField>
    <fullName>RE_Forex_Rate__c</fullName>
    <label>Forex Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Pricing_Date__c.field-meta.xml
<CustomField>
    <fullName>RE_Pricing_Date__c</fullName>
    <label>Published Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Tracker__c.field-meta.xml
<CustomField>
    <fullName>RE_Tracker__c</fullName>
    <label>Tracker</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>D-1</fullName>
            </value>
            <value>
                <fullName>D-2</fullName>
            </value>
            <value>
                <fullName>D+1</fullName>
            </value>
            <value>
                <fullName>MTD</fullName>
            </value>
            <value>
                <fullName>WTD</fullName>
            </value>
            <value>
                <fullName>W-1</fullName>
            </value>
            <value>
                <fullName>W-2</fullName>
            </value>
            <value>
                <fullName>M-1</fullName>
            </value>
            <value>
                <fullName>M-2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Trade_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Trade_Type__c</fullName>
    <label>Trade Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
            <value>
                <fullName>Exchange Rate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RE_ExternalFXRatesHelper.cls
public class RE_ExternalFXRatesHelper {     
    public static void onAfterExternalFXRatesHelper(List<RE_External_FX_Rates__c> newExternalFXRateList){
        Map<String,RE_ExternalFXMappings__c> extFXRateCustSetting = RE_ExternalFXMappings__c.getAll();
        List<RE_FX_Rates__c> sFXRate = new List<RE_FX_Rates__c>();
        for(RE_External_FX_Rates__c extFXRateObj : newExternalFXRateList){
            for(String str : extFXRateCustSetting.keySet()){  //iterating through the custom settings
                
                RE_ExternalFXMappings__c extFXRateValue = extFXRateCustSetting.get(str); //getting the key value 
                System.debug('extFXRateValue :'+ extFXRateValue);
                //comparing the GSAP data with the custom settings data
                if(extFXRateValue.RE_External_Currency__c == extFXRateObj.RE_Currency__c){
                    System.debug('extFXRateValue.RE_External_Currency__c :'+ extFXRateValue.RE_External_Currency__c);
                    List<String> sTradeType = new List<String>{'Buy','Sell','Exchange Rate'};
                    for(Integer i=0; i<sTradeType.size(); i++){
                        RE_FX_Rates__c FXDataCTS   = new RE_FX_Rates__c();
                        FXDataCTS.RE_Conversion_Unit__c = extFXRateValue.RE_Conversion_Unit__c;
                        FXDataCTS.RE_Base_Unit__c  =  extFXRateValue.RE_Base_Unit__c; 
                        FXDataCTS.RE_Forex_Name__c = extFXRateValue.RE_Forex_Name__c;
                        FXDataCTS.RE_Trade_Type__c = sTradeType[i];
                        //FXDataCTS.RE_Tracker__c = 'D';
                        FXDataCTS.RE_Pricing_Date__c = RE_ExternalTriggerHelper.convertToDate(extFXRateObj.RE_Date__c,'FX');                 
                        if(extFXRateValue.RE_Conversion_Unit__c.contains('CTS')){                            
                            if(sTradeType[i]=='Buy')
                                FXDataCTS.RE_Forex_Rate__c = extFXRateObj.RE_Buy_Rate__c*100;                            
                            if(sTradeType[i]=='Sell')                            
                                FXDataCTS.RE_Forex_Rate__c = extFXRateObj.RE_Sell_Rate__c*100;                              
                            if(sTradeType[i]=='Exchange Rate')                            
                                FXDataCTS.RE_Forex_Rate__c = extFXRateObj.RE_Mean_Rate__c*100;                               
                            
                        }
                        else{                            
                            if(sTradeType[i]=='Buy')
                            FXDataCTS.RE_Forex_Rate__c = extFXRateObj.RE_Buy_Rate__c;
                            if(sTradeType[i]=='Sell')
                            FXDataCTS.RE_Forex_Rate__c = extFXRateObj.RE_Sell_Rate__c;  
                            if(sTradeType[i]=='Exchange Rate')
                            FXDataCTS.RE_Forex_Rate__c = extFXRateObj.RE_Mean_Rate__c;
                        }
                        sFXRate.add(FXDataCTS);
                    } 
                }
            }            
        }
        insert sFXRate;        
    }  
}