force-app/main/default/objects/SF_SAP_DataSet__x/SF_SAP_DataSet__x.object-meta.xml
<CustomObject>
    <description>SF_SAP_DataSet</description>
    <externalDataSource>GSAP_Connect</externalDataSource>
    <externalName>SF_SAP_DataSet</externalName>
    <label>SF_SAP_DataSet</label>
    <pluralLabel>SF_SAP_DataSet</pluralLabel>
</CustomObject>

force-app/main/default/objects/SF_SAP_DataSet__x/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Action</description>
    <externalDeveloperName>Action</externalDeveloperName>
    <label>Action</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SF_SAP_DataSet__x/fields/MsgTxt__c.field-meta.xml
<CustomField>
    <fullName>MsgTxt__c</fullName>
    <description>MsgTxt</description>
    <externalDeveloperName>MsgTxt</externalDeveloperName>
    <label>MsgTxt</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SF_SAP_DataSet__x/fields/SapSalesContNo__c.field-meta.xml
<CustomField>
    <fullName>SapSalesContNo__c</fullName>
    <description>SapSalesContNo</description>
    <externalDeveloperName>SapSalesContNo</externalDeveloperName>
    <label>SapSalesContNo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SF_SAP_DataSet__x/fields/SfHeaderShtNo__c.field-meta.xml
<CustomField>
    <fullName>SfHeaderShtNo__c</fullName>
    <description>SfHeaderShtNo</description>
    <externalDeveloperName>SfHeaderShtNo</externalDeveloperName>
    <label>SfHeaderShtNo</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SF_SAP_DataSet__x/fields/SfItemShtNo__c.field-meta.xml
<CustomField>
    <fullName>SfItemShtNo__c</fullName>
    <description>SfItemShtNo</description>
    <externalDeveloperName>SfItemShtNo</externalDeveloperName>
    <label>SfItemShtNo</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RV_GSAPMockExternalRequestModel.cls
public with sharing class RV_GSAPMockExternalRequestModel {

    @TestVisible private static List<SF_SAP_DataSet__x> mockedRequests = new List<SF_SAP_DataSet__x>();
    public static SF_SAP_DataSet__x findById(Id requestId) {
        List<SF_SAP_DataSet__x> requests = (!mockedRequests.isEmpty()) ? mockedRequests :[
            SELECT  id,SfHeaderShtNo__c, SfItemShtNo__c, SapSalesContNo__c,Status__c,MsgTxt__c,Action__c
            FROM SF_SAP_DataSet__x
            WHERE Id =: requestId
        ];
        return (requests.size() > 0) ? requests[0] : null;
    }
}