force-app/main/default/objects/Revolution_Dashboard__c/Revolution_Dashboard__c.object-meta.xml
<CustomObject>
    <description>This object is used to create the dashboard of Revolution.</description>
    <label>Sales Dashboard</label>
    <nameField>
        <displayFormat>RV-{0000}</displayFormat>
        <label>Revolution Dashboard Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Dashboard</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revolution_Dashboard__c/fields/ATP1_Live_AGO__c.field-meta.xml
<CustomField>
    <fullName>ATP1_Live_AGO__c</fullName>
    <label>ATP1 Live (AGO)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/ATP1_Live_IGO__c.field-meta.xml
<CustomField>
    <fullName>ATP1_Live_IGO__c</fullName>
    <label>ATP1 Live (IGO)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/ATP1_Live_MOGAS__c.field-meta.xml
<CustomField>
    <fullName>ATP1_Live_MOGAS__c</fullName>
    <label>ATP1 Live (MOGAS)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/BSP_AGO__c.field-meta.xml
<CustomField>
    <fullName>BSP_AGO__c</fullName>
    <label>BSP (AGO)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/BSP_GTL__c.field-meta.xml
<CustomField>
    <fullName>BSP_GTL__c</fullName>
    <label>BSP (GTL)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/BSP_IGO__c.field-meta.xml
<CustomField>
    <fullName>BSP_IGO__c</fullName>
    <label>BSP (IGO)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/BSP_MOGAS__c.field-meta.xml
<CustomField>
    <fullName>BSP_MOGAS__c</fullName>
    <label>BSP (MOGAS)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/MOT__c.field-meta.xml
<CustomField>
    <fullName>MOT__c</fullName>
    <label>MOT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>Rail</fullName>
            </value>
            <value>
                <fullName>Barge</fullName>
            </value>
            <value>
                <fullName>ITT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/MRC_Name__c.field-meta.xml
<CustomField>
    <fullName>MRC_Name__c</fullName>
    <externalId>true</externalId>
    <label>MRC Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/OTM_AGO__c.field-meta.xml
<CustomField>
    <fullName>OTM_AGO__c</fullName>
    <label>OTM (AGO)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/OTM_IGO__c.field-meta.xml
<CustomField>
    <fullName>OTM_IGO__c</fullName>
    <label>OTM (IGO)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/OTM_MOGAS__c.field-meta.xml
<CustomField>
    <fullName>OTM_MOGAS__c</fullName>
    <label>OTM (MOGAS)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <formula>Plant_Name__r.Plant_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plant Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/Plant_Name__c.field-meta.xml
<CustomField>
    <fullName>Plant_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Name</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipName>Revolution_Dashboards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/PSP_AGO__c.field-meta.xml
<CustomField>
    <fullName>PSP_AGO__c</fullName>
    <label>PSP (AGO)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/PSP_IGO__c.field-meta.xml
<CustomField>
    <fullName>PSP_IGO__c</fullName>
    <label>PSP (IGO)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/PSP_MOGAS__c.field-meta.xml
<CustomField>
    <fullName>PSP_MOGAS__c</fullName>
    <label>PSP (MOGAS)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AT01</fullName>
            </value>
            <value>
                <fullName>DE01</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/Total_Tax_AGO__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_AGO__c</fullName>
    <label>Total Tax AGO</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/Total_Tax_IGO__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_IGO__c</fullName>
    <label>Total Tax IGO</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/Total_Tax_MOGAS__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_MOGAS__c</fullName>
    <label>Total Tax MOGAS</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/recordTypes/Dashboard.recordType-meta.xml
<RecordType>
    <fullName>Dashboard</fullName>
    <active>true</active>
    <label>Dashboard</label>
</RecordType>

force-app/main/default/objects/Revolution_Dashboard__c/recordTypes/Snapshot.recordType-meta.xml
<RecordType>
    <fullName>Snapshot</fullName>
    <active>true</active>
    <label>Snapshot</label>
</RecordType>

force-app/main/default/classes/RV_DI_Dashboard_Snapshot.cls
global class RV_DI_Dashboard_Snapshot implements Database.Batchable<sObject>{
    public static String snapShotRecId;
    global Database.QueryLocator start(Database.BatchableContext BC){
        String recTypeId = Schema.SObjectType.Revolution_Dashboard__c.getRecordTypeInfosByName().get('Dashboard').getRecordTypeId();

        String query = 'Select Id,RecordTypeId, ATP1_Live_AGO__c, ATP1_Live_IGO__c, ATP1_Live_MOGAS__c, BSP_AGO__c, BSP_GTL__c, ' +
                        'BSP_IGO__c, BSP_MOGAS__c, MOT__c, MRC_Name__c, OTM_AGO__c, OTM_IGO__c, ' +
                        'OTM_MOGAS__c, Plant_Code__c, Plant_Name__c, PSP_AGO__c, ' +
                        'PSP_IGO__c, PSP_MOGAS__c, Sales_Channel__c, Shipping_Condition__c, Total_Tax_AGO__c, ' +
                        'Total_Tax_IGO__c, Total_Tax_MOGAS__c from Revolution_Dashboard__c where RecordTypeId =\''+ ''+recTypeId+'\'';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Revolution_Dashboard__c> scope){ 
        snapShotRecId = Schema.SObjectType.Revolution_Dashboard__c.getRecordTypeInfosByName().get('Snapshot').getRecordTypeId();
		List<Revolution_Dashboard__c> rdSnapshotList = new List<Revolution_Dashboard__c>();       
        for(Revolution_Dashboard__c sObj : scope){
            Revolution_Dashboard__c rd = new Revolution_Dashboard__c();//(Revolution_Dashboard__c)sObj;
            rd = sObj.clone(false,false,false,false);
            rd.RecordTypeId = snapShotRecId;
            rdSnapshotList.add(rd);
        }
        if(!rdSnapshotList.isEmpty()){
            insert rdSnapshotList;
        }
    }
    
    global void finish(Database.BatchableContext BC){
    }

}