force-app/main/default/objects/RE_Job_Run_Audit__c/RE_Job_Run_Audit__c.object-meta.xml
<CustomObject>
    <label>Job Run Audit</label>
    <nameField>
        <displayFormat>JR-{00000000}</displayFormat>
        <label>Job Run Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Run Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Job_Status__c.field-meta.xml
<CustomField>
    <fullName>RE_Job_Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Partial Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/RE_MY_CostPrice__c.object-meta.xml
<CustomObject>
    <label>Cost Price</label>
    <nameField>
        <displayFormat>RE-MY-C{000000}</displayFormat>
        <label>Costing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Price</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_MY_CostPrice__c/recordTypes/Canada.recordType-meta.xml
<RecordType>
    <fullName>Canada</fullName>
    <active>true</active>
    <label>Canada</label>
</RecordType>

force-app/main/default/objects/RT_Price_Book__c/RT_Price_Book__c.object-meta.xml
<CustomObject>
    <label>REV Price Book</label>
    <nameField>
        <displayFormat>PPI-{0000000}</displayFormat>
        <label>Price Index</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REV Price Books</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RV_Exception__c/RV_Exception__c.object-meta.xml
<CustomObject>
    <description>This object is used in revolution app to create exception records</description>
    <label>RV_Exception</label>
    <nameField>
        <displayFormat>Exception{0}</displayFormat>
        <label>RV_Exception Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RV_Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RE_CND_CostPriceBatchUpdate.cls
/**************************************************************************************************
* Name: RE_CND_CostPriceBatchUpdate
* Object: RE_MY_CostPrice__c
* Purpose: Cost Price Batch Update Class for Revolution Canada
* Author: Abhilash KT (abhilash.kt@shell.com)
* Create Date: 2021-10-01
* Modify History: 
* 2021-10-01		Abhilash		Created
**************************************************************************************************/
public class RE_CND_CostPriceBatchUpdate implements Database.Batchable<SObject>, Database.Stateful 
{
  List<RT_Price_Book__c> pbLst = New List<RT_Price_Book__c>();
  RE_Job_Run_Audit__c jrAudit = New RE_Job_Run_Audit__c();
  String jrAuditStatus;
  Boolean IsSuccessJobAudit;   
  SObject[] records;
    
  public RE_CND_CostPriceBatchUpdate(SObject[] source, List<RT_Price_Book__c> pbLst, RE_Job_Run_Audit__c jrAudit, String jrAuditStatus, Boolean IsSuccessJobAudit) {
    records = source;
    this.pbLst = pbLst;
    this.jrAudit = jrAudit;   
    this.jrAuditStatus = jrAuditStatus;  
    this.IsSuccessJobAudit = IsSuccessJobAudit;    
  }
  
  public SObject[] start(Database.BatchableContext context) {
    return records;
  }
    
  public void execute(Database.BatchableContext context, SObject[] scope) {     
     Database.SaveResult[] updateCpList = Database.update(scope, false);
     Boolean updateSuccess = RE_CND_Utility.handleUpdateResult('RE_CND_ExecuteDepoPricingController','startCalculatingDepoPricing-UpdateCostPriceBatch-NoPB',updateCpList,false, jrAudit);                                           
  }
    
  public void finish(Database.BatchableContext context) {

      if(pbLst.Size() > 0)
      {
         RE_CND_PriceBookBatchUpdate updatePB = New RE_CND_PriceBookBatchUpdate(pbLst, jrAudit, jrAuditStatus, IsSuccessJobAudit);
         Database.executeBatch(updatePB);
      }
      else if((jrAuditStatus == 'Processing') && (IsSuccessJobAudit))
      {          
          jrAudit.RE_Job_Status__c = 'Completed';  
          update jrAudit;          
      }
      else
      {       
          String comments = 'Refer RV_Exception__c record for more details with jobAudit :'+jrAudit.Id;
          RE_CND_Utility.updateJobAuditPartialSuccess(jrAudit,'Issue while generating Canada Depo Pricing Job',comments);                          
      }
  }
    
}