force-app/main/default/objects/RE_Job_Run_Audit__c/RE_Job_Run_Audit__c.object-meta.xml
<CustomObject>
    <label>Job Run Audit</label>
    <nameField>
        <displayFormat>JR-{00000000}</displayFormat>
        <label>Job Run Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Run Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_IsSuccess__c.field-meta.xml
<CustomField>
    <fullName>RE_IsSuccess__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSuccess</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Job_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Malaysia Output</fullName>
            </value>
            <value>
                <fullName>Singapore Output</fullName>
            </value>
            <value>
                <fullName>SG Midday Output</fullName>
            </value>
            <value>
                <fullName>Malaysia AMV Output</fullName>
            </value>
            <value>
                <fullName>Thailand Output</fullName>
            </value>
            <value>
                <fullName>CustomerOps Output</fullName>
            </value>
            <value>
                <fullName>New Contract Pricing Output</fullName>
            </value>
            <value>
                <fullName>Thailand AMV Output</fullName>
            </value>
            <value>
                <fullName>MY Export Report</fullName>
            </value>
            <value>
                <fullName>MY Customer Opps CBU</fullName>
            </value>
            <value>
                <fullName>Philippines Output</fullName>
            </value>
            <value>
                <fullName>Canada Daily Reuters Quote Move</fullName>
            </value>
            <value>
                <fullName>Canada Execute Depo Pricing</fullName>
            </value>
            <value>
                <fullName>Canada Pricing Recalculation</fullName>
            </value>
            <value>
                <fullName>Canada SFJ Record Creation</fullName>
            </value>
            <value>
                <fullName>Canada Live OPIS Spot Ticker Processing</fullName>
            </value>
            <value>
                <fullName>Canada Market Move Calculation</fullName>
            </value>
            <value>
                <fullName>Canada Competitor Data Processing</fullName>
            </value>
            <value>
                <fullName>Canada GSAP Upload</fullName>
            </value>
            <value>
                <fullName>Canada Email Output</fullName>
            </value>
            <value>
                <fullName>MY Data Analysis Report</fullName>
            </value>
            <value>
                <fullName>PH Customer Opps CBU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Run_Time__c.field-meta.xml
<CustomField>
    <fullName>RE_Run_Time__c</fullName>
    <label>Run Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Run_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Run_Type__c</fullName>
    <label>Run Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automate</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RV_OLF_MRC_Data__c/RV_OLF_MRC_Data__c.object-meta.xml
<CustomObject>
    <description>The object is created to store the precomputed prices to send to OLF</description>
    <label>OLF Precomputed Data</label>
    <nameField>
        <label>OLF MRC Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OLF Precomputed Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RV_OLF_MRC_Data__c/fields/LastModifiedTime__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedTime__c</fullName>
    <label>LastModifiedTime</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_OLF_MRC_Data__c/fields/RV_ContractEndDate__c.field-meta.xml
<CustomField>
    <fullName>RV_ContractEndDate__c</fullName>
    <label>ContractEndDate</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_OLF_MRC_Data__c/fields/RV_ContractStartDate__c.field-meta.xml
<CustomField>
    <fullName>RV_ContractStartDate__c</fullName>
    <label>ContractStartDate</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_OLF_MRC_Data__c/fields/RV_Grade__c.field-meta.xml
<CustomField>
    <fullName>RV_Grade__c</fullName>
    <label>Grade</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_OLF_MRC_Data__c/fields/RV_LocationName__c.field-meta.xml
<CustomField>
    <fullName>RV_LocationName__c</fullName>
    <label>LocationName</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_OLF_MRC_Data__c/fields/RV_MaterialName__c.field-meta.xml
<CustomField>
    <fullName>RV_MaterialName__c</fullName>
    <label>MaterialName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_OLF_MRC_Data__c/fields/RV_MrcId__c.field-meta.xml
<CustomField>
    <fullName>RV_MrcId__c</fullName>
    <label>MrcId</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_OLF_MRC_Data__c/fields/RV_OLF_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>RV_OLF_Contact_Email__c</fullName>
    <label>OLF Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/RV_OLF_MRC_Data__c/fields/RV_OLFAccountName__c.field-meta.xml
<CustomField>
    <fullName>RV_OLFAccountName__c</fullName>
    <label>AccountName</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_OLF_MRC_Data__c/fields/RV_PricePerVol__c.field-meta.xml
<CustomField>
    <fullName>RV_PricePerVol__c</fullName>
    <label>PricePerVol</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RV_OLF_MRC_Data__c/fields/RV_VolumeCBM__c.field-meta.xml
<CustomField>
    <fullName>RV_VolumeCBM__c</fullName>
    <label>VolumeCBM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RV_OLF_MRC_Data__c/fields/tranche__c.field-meta.xml
<CustomField>
    <fullName>tranche__c</fullName>
    <label>tranche</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_OLF_MRC_Data__c/fields/UniqueMRCId__c.field-meta.xml
<CustomField>
    <fullName>UniqueMRCId__c</fullName>
    <externalId>true</externalId>
    <label>UniqueMRCId</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/OLF_MRCATP1Queueable.cls
public class OLF_MRCATP1Queueable implements Queueable{
    Set<Id> accountIdsFirstBatch = new Set<Id>();
    String query;
    OLFWrapper.OlfTrancheWrap olfTrancheWrap;
    OLFWrapper.ContractDateWindowWrap dateWrap;
    String startDate;
    String endDate;
    public OLF_MRCATP1Queueable(Set<Id> ids,OLFWrapper.OlfTrancheWrap olfTrancheWrap,OLFWrapper.ContractDateWindowWrap dateWrap,String startDate,String endDate){
        this.accountIdsFirstBatch=ids; // Set of Account Ids
        this.olfTrancheWrap= olfTrancheWrap; //tranche,isOlfActive,startday,endday
        this.dateWrap=dateWrap;//start and end date in datatime datatype
        this.startDate=startDate;
        this.endDate=endDate;
    //   query ='Select Id from Account where Id IN :accountIdsFirstBatch';
        
    }

    
    public void execute(QueueableContext context) {
        try{
         	List<RV_OLF_MRC_Data__c> olfUpdatedList = new List<RV_OLF_MRC_Data__c>();
     
           List<RV_OLF_MRC_Data__c> olfWrapperList = new List<RV_OLF_MRC_Data__c>();
          List<RV_SHT_CreateController.MRCDataWrap> mrcMasterData = OLF_MRCDataHelper.getMRCRecordsData(olfTrancheWrap.tranche,this.accountIdsFirstBatch,startDate, endDate) ;
   		
        List<OLFWrapper.MrcPriceWrap> mrcPriceWrapVar = new List<OLFWrapper.MrcPriceWrap>();
        System.debug('Master Data'+mrcMasterData);
        if(mrcMasterData != null){
            Set<String> plantCodeSet = new Set<String>();           
            for(RV_SHT_CreateController.MRCDataWrap wrp : mrcMasterData){
                plantCodeSet.add(wrp.location); 
            }
            Map<String,Decimal> atpLocMap = OLF_MRCDataHelper.getAtpforPlant(plantCodeSet, null, new List<String>{olfTrancheWrap.tranche});

            for(RV_SHT_CreateController.MRCDataWrap wrp : mrcMasterData){
                   
                String uniqueId=wrp.mrcName+olfTrancheWrap.tranche;
                RV_OLF_MRC_Data__c olfMRCUpdated = new RV_OLF_MRC_Data__c();
                   if(atpLocMap.get(wrp.location+wrp.grade+olfTrancheWrap.tranche)<1){
                   olfMRCUpdated.RV_VolumeCBM__c=0;  
                }else{
                    olfMRCUpdated.RV_VolumeCBM__c=Integer.valueOf(atpLocMap.get(wrp.location+wrp.grade+olfTrancheWrap.tranche)); 
                }
                    olfMRCUpdated.RV_PricePerVol__c=wrp.OTM;
                olfMRCUpdated.RV_MrcId__c = wrp.mrcName;
                 olfMRCUpdated.UniqueMRCId__c=wrp.mrcName+olfTrancheWrap.tranche;
                olfMRCUpdated.tranche__c = olfTrancheWrap.tranche;
                olfMRCUpdated.RV_LocationName__c = wrp.locationName;
                olfMRCUpdated.RV_MaterialName__c = wrp.materialName;
            	olfMRCUpdated.RV_OLF_Contact_Email__c = wrp.contactEmail;
                olfMRCUpdated.RV_Grade__c = wrp.grade;
                olfMRCUpdated.RV_ContractEndDate__c=endDate;
                olfMRCUpdated.RV_ContractStartDate__c=startDate;
                olfMRCUpdated.tranche__c = olfTrancheWrap.tranche;
                olfMRCUpdated.RV_OLFAccountName__c=wrp.accName;
                 olfMRCUpdated.LastModifiedTime__c=String.valueOf(System.now());


                olfUpdatedList.add(olfMRCUpdated);
           
        }
        if(!olfUpdatedList.isEmpty()){
            Schema.SObjectField ftoken = RV_OLF_MRC_Data__c.Fields.UniqueMRCId__c;
			Database.UpsertResult[] srList = Database.upsert(olfUpdatedList,ftoken,false);
			for (Database.UpsertResult sr : srList) {  
        		for(Database.Error err : sr.getErrors()) {
            		System.debug('error has occurred.' + err.getStatusCode() + ': ' + err.getMessage());                    
            		System.debug('fields that affected this error: ' + err.getFields());
            
        		}
    
			} 
          
        }
            System.debug('OLF Updated List'+olfUpdatedList);
            /*    RE_Job_Run_Audit__c reJ = new RE_Job_Run_Audit__c();
        reJ.RE_IsSuccess__c = true;
        reJ.RE_Run_Time__c = System.now();
        reJ.RE_Run_Type__c = 'Automate';
        reJ.RE_Job_Type__c='OLF Precomputation ATP1 Job';
        if(reJ != null){
            insert reJ;
        }*/

   
    }
        }catch(Exception ex){
            System.debug('gshaujSHxajkDHNak');
            OLF_MRCDataHelper.sendEmailandDeactivate('OLF_MRCATP1Queueable',ex.getMessage());
            System.debug('OLF_MRCATP1Queueable'+ex.getMessage());
            
        }
    
    }
}