force-app/main/default/objects/RE_Job_Run_Audit__c/RE_Job_Run_Audit__c.object-meta.xml
<CustomObject>
    <label>Job Run Audit</label>
    <nameField>
        <displayFormat>JR-{00000000}</displayFormat>
        <label>Job Run Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Run Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Country_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Country_Name__c</fullName>
    <label>Country Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RT_Revolution_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Job_Status__c.field-meta.xml
<CustomField>
    <fullName>RE_Job_Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Partial Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Job_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Malaysia Output</fullName>
            </value>
            <value>
                <fullName>Singapore Output</fullName>
            </value>
            <value>
                <fullName>SG Midday Output</fullName>
            </value>
            <value>
                <fullName>Malaysia AMV Output</fullName>
            </value>
            <value>
                <fullName>Thailand Output</fullName>
            </value>
            <value>
                <fullName>CustomerOps Output</fullName>
            </value>
            <value>
                <fullName>New Contract Pricing Output</fullName>
            </value>
            <value>
                <fullName>Thailand AMV Output</fullName>
            </value>
            <value>
                <fullName>MY Export Report</fullName>
            </value>
            <value>
                <fullName>MY Customer Opps CBU</fullName>
            </value>
            <value>
                <fullName>Philippines Output</fullName>
            </value>
            <value>
                <fullName>Canada Daily Reuters Quote Move</fullName>
            </value>
            <value>
                <fullName>Canada Execute Depo Pricing</fullName>
            </value>
            <value>
                <fullName>Canada Pricing Recalculation</fullName>
            </value>
            <value>
                <fullName>Canada SFJ Record Creation</fullName>
            </value>
            <value>
                <fullName>Canada Live OPIS Spot Ticker Processing</fullName>
            </value>
            <value>
                <fullName>Canada Market Move Calculation</fullName>
            </value>
            <value>
                <fullName>Canada Competitor Data Processing</fullName>
            </value>
            <value>
                <fullName>Canada GSAP Upload</fullName>
            </value>
            <value>
                <fullName>Canada Email Output</fullName>
            </value>
            <value>
                <fullName>MY Data Analysis Report</fullName>
            </value>
            <value>
                <fullName>PH Customer Opps CBU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Run_Time__c.field-meta.xml
<CustomField>
    <fullName>RE_Run_Time__c</fullName>
    <label>Run Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Run_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Run_Type__c</fullName>
    <label>Run Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automate</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_User__c.field-meta.xml
<CustomField>
    <fullName>RE_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Job_Run_Audit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/RE_MY_Output__c.object-meta.xml
<CustomObject>
    <label>MY Output</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Costing Output Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MY Output</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_Job_Run_Count__c.field-meta.xml
<CustomField>
    <fullName>RE_Job_Run_Count__c</fullName>
    <label>Job Run Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/RT_Revolution_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TU</fullName>
        <label>Turkey</label>
    </customValue>
    <customValue>
        <fullName>MY</fullName>
        <label>Malaysia</label>
    </customValue>
    <customValue>
        <fullName>TH</fullName>
        <label>Thailand</label>
    </customValue>
    <customValue>
        <fullName>PH</fullName>
        <label>Philippines</label>
    </customValue>
    <customValue>
        <fullName>SG</fullName>
        <label>Singapore</label>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
        <label>Canada</label>
    </customValue>
    <masterLabel>Revolution Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RE_MY_DataAnalysisReportScheduler.cls
/**************************************************************************************************
* Name: RE_MY_DataAnalysisReportScheduler
* Object: RE_MY_Output__c
* Purpose: Used for Malaysis Data Analysis Report geneartion
* Author: Abhilash KT (abhilash.kt@shell.com)
* Create Date: 2022-09-19
* Modify History: 
* 2022-09-19		Abhilash		Created
**************************************************************************************************/
global class RE_MY_DataAnalysisReportScheduler implements schedulable
{
    global void execute(SchedulableContext sc) 
    {               
        RE_Job_Run_Audit__c jrAuditMY = new RE_Job_Run_Audit__c();
        
        try
        {
            Integer maxJobRunCount = 0;
            // Get the latest MY Data Analysis Report Job type for today
            List<RE_Job_Run_Audit__c> jobDataToday = [SELECT RE_Job_Run_Count__c FROM RE_Job_Run_Audit__c 
                                                      WHERE createddate = Today AND RE_Job_Type__c =: 'MY Data Analysis Report' ORDER BY RE_Job_Run_Count__c DESC LIMIT 1];
            if(!jobDataToday.isEmpty())
                maxJobRunCount = Integer.valueOf(jobDataToday[0].RE_Job_Run_Count__c)+1;  
            
            jrAuditMY.RE_Run_Type__c = 'Automate';
            jrAuditMY.RE_Run_Time__c = System.now();
            jrAuditMY.RE_Job_Type__c = 'MY Data Analysis Report';
            jrAuditMY.RE_User__c = UserInfo.getUserId();
            jrAuditMY.RE_Job_Run_Count__c = maxJobRunCount;
            jrAuditMY.RE_Job_Status__c = 'Processing';
            jrAuditMY.RE_Country_Name__c = 'MY';
            insert jrAuditMY;               
            
            System.enqueueJob(new RE_MY_DataAnalysisReportQueue(jrAuditMY));
        }
        Catch(Exception ex)
        {
            System.debug('RE_MY_DataAnalysisReportScheduler-Error-->'+ex.getMessage());
            System.debug('RE_MY_DataAnalysisReportScheduler-LN-->'+ex.getLineNumber());
            RV_ClassException.insertExceptionRecord('RE_MY_DataAnalysisReportScheduler-',ex.getMessage()+'-'+ex.getLineNumber(),'RE_MY_DataAnalysisReportScheduler','execute','Exception'); 
            RE_CND_Utility.updateJobAudit(jrAuditMY,'Failed',ex);
        }         
    }    
}