force-app/main/default/objects/RE_CND_Base_Reference_Rack_Settings__c/RE_CND_Base_Reference_Rack_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used for Base and Reference Rack Settings for Revolution Canada. And the calculation would be &apos;Rack - Base Rack&apos;</description>
    <label>RE CND Base Reference Rack Settings</label>
</CustomObject>

force-app/main/default/objects/RE_CND_Base_Reference_Rack_Settings__c/fields/Base_Rack__c.field-meta.xml
<CustomField>
    <fullName>Base_Rack__c</fullName>
    <label>Base Rack</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_CND_Base_Reference_Rack_Settings__c/fields/Product_Classification_L0__c.field-meta.xml
<CustomField>
    <fullName>Product_Classification_L0__c</fullName>
    <label>Product Classification(L0)</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_CND_Base_Reference_Rack_Settings__c/fields/Rack__c.field-meta.xml
<CustomField>
    <fullName>Rack__c</fullName>
    <label>Rack</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Default_Unit_Rate_Settings__c/RE_Default_Unit_Rate_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Revolution Default Unit Rate Settings</description>
    <label>RE Default Unit Rate Settings</label>
</CustomObject>

force-app/main/default/objects/RE_Default_Unit_Rate_Settings__c/fields/Default_Unit_Rate__c.field-meta.xml
<CustomField>
    <fullName>Default_Unit_Rate__c</fullName>
    <label>Default Unit Rate</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/RE_Depot_Pricing_Backbone__c.object-meta.xml
<CustomObject>
    <label>Depot Pricing Backbone</label>
    <nameField>
        <displayFormat>DPB-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depot Pricing Backbone</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_CND_Group__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Branded</fullName>
            </value>
            <value>
                <fullName>Unbranded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/recordTypes/Canada.recordType-meta.xml
<RecordType>
    <fullName>Canada</fullName>
    <active>true</active>
    <description>Record type for Revolution Canada</description>
    <label>Canada</label>
</RecordType>

force-app/main/default/objects/RE_FX_Rates__c/RE_FX_Rates__c.object-meta.xml
<CustomObject>
    <label>RE FX Rates</label>
    <nameField>
        <displayFormat>FXR-{000000}</displayFormat>
        <label>FX_Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE FX Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Forex_Rate__c.field-meta.xml
<CustomField>
    <fullName>RE_Forex_Rate__c</fullName>
    <label>Forex Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Pricing_Date__c.field-meta.xml
<CustomField>
    <fullName>RE_Pricing_Date__c</fullName>
    <label>Published Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Name__c</fullName>
    <description>quote display name is stored</description>
    <label>Quote Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Trade_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Trade_Type__c</fullName>
    <label>Trade Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
            <value>
                <fullName>Exchange Rate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/RE_Job_Run_Audit__c.object-meta.xml
<CustomObject>
    <label>Job Run Audit</label>
    <nameField>
        <displayFormat>JR-{00000000}</displayFormat>
        <label>Job Run Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Run Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/Other_Comments__c.field-meta.xml
<CustomField>
    <fullName>Other_Comments__c</fullName>
    <description>Other comments related to job Audit</description>
    <label>Other Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Exception__c.field-meta.xml
<CustomField>
    <fullName>RE_Exception__c</fullName>
    <label>Exception</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Job_Status__c.field-meta.xml
<CustomField>
    <fullName>RE_Job_Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Partial Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/RE_Market_Quotes__c.object-meta.xml
<CustomObject>
    <label>RE Market Quotes</label>
    <nameField>
        <displayFormat>MarketQuote-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Market Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_CND_Rack__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_Rack__c</fullName>
    <label>Rack</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Name__c</fullName>
    <label>Quote Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_MOA__c/RE_MOA__c.object-meta.xml
<CustomObject>
    <label>MOA</label>
    <nameField>
        <displayFormat>MOA-{000000000}</displayFormat>
        <label>MOA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MOA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_MOA__c/fields/RE_CND_Competitive_Adj__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_Competitive_Adj__c</fullName>
    <label>Competitive Adj</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MOA__c/fields/RE_CND_Group__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gasoline</fullName>
            </value>
            <value>
                <fullName>Gas Oil</fullName>
            </value>
            <value>
                <fullName>Fx Rate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_MOA__c/fields/RE_CND_Market_Move__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_Market_Move__c</fullName>
    <label>Market Move</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MOA__c/fields/RE_CND_Today_s_Price__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_Today_s_Price__c</fullName>
    <label>Today’s Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MOA__c/fields/RE_IsLatest__c.field-meta.xml
<CustomField>
    <fullName>RE_IsLatest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsLatest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RE_MOA__c/recordTypes/Canada_Execute_Pricing.recordType-meta.xml
<RecordType>
    <fullName>Canada_Execute_Pricing</fullName>
    <active>true</active>
    <description>Record type for Revolution Canada Execute Pricing</description>
    <label>Canada Execute Pricing</label>
</RecordType>

force-app/main/default/objects/RE_MY_CostPrice__c/RE_MY_CostPrice__c.object-meta.xml
<CustomObject>
    <label>Cost Price</label>
    <nameField>
        <displayFormat>RE-MY-C{000000}</displayFormat>
        <label>Costing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Price</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_MY_CostPrice__c/fields/RE_CND_Effective_From_Date__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_Effective_From_Date__c</fullName>
    <label>Effective From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/recordTypes/Canada.recordType-meta.xml
<RecordType>
    <fullName>Canada</fullName>
    <active>true</active>
    <label>Canada</label>
</RecordType>

force-app/main/default/objects/RE_Zema_Quotes_Settings__c/RE_Zema_Quotes_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Zema Quotes for Canada</description>
    <label>RE Zema Quotes Settings</label>
</CustomObject>

force-app/main/default/objects/RE_Zema_Quotes_Settings__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <label>Display Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RE_Zema_Quotes_Settings__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Zema_Quotes_Settings__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>differentiate between settlement quotes and fx rates</description>
    <label>Type</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RT_Price_Book__c/RT_Price_Book__c.object-meta.xml
<CustomObject>
    <label>REV Price Book</label>
    <nameField>
        <displayFormat>PPI-{0000000}</displayFormat>
        <label>Price Index</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REV Price Books</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RT_Price_Book__c/fields/RE_CND_Market_Move__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_Market_Move__c</fullName>
    <label>Market Move</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RT_Setting__c/RT_Setting__c.object-meta.xml
<CustomObject>
    <label>REV Country Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REV Country Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RT_Setting__c/fields/RE_CND_Rack__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_Rack__c</fullName>
    <label>Rack</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RE_CND_Racks</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RT_Setting__c/recordTypes/Canada_Pricing_Differential.recordType-meta.xml
<RecordType>
    <fullName>Canada_Pricing_Differential</fullName>
    <active>true</active>
    <description>Record type for Revolution Canada</description>
    <label>Canada Pricing Differential</label>
</RecordType>

force-app/main/default/objects/RV_Exception__c/RV_Exception__c.object-meta.xml
<CustomObject>
    <description>This object is used in revolution app to create exception records</description>
    <label>RV_Exception</label>
    <nameField>
        <displayFormat>Exception{0}</displayFormat>
        <label>RV_Exception Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RV_Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RV_Exception__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/RE_CND_Racks.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AB DEPOTS IT RAIL</fullName>
    </customValue>
    <customValue>
        <fullName>AB TEMP DEPOTS IT RAIL</fullName>
    </customValue>
    <customValue>
        <fullName>Bare Point</fullName>
    </customValue>
    <customValue>
        <fullName>Belleville</fullName>
    </customValue>
    <customValue>
        <fullName>Calgary</fullName>
    </customValue>
    <customValue>
        <fullName>Charlottetown</fullName>
    </customValue>
    <customValue>
        <fullName>Chicoutimi</fullName>
    </customValue>
    <customValue>
        <fullName>Edmonton</fullName>
    </customValue>
    <customValue>
        <fullName>Gaspe</fullName>
    </customValue>
    <customValue>
        <fullName>Halifax</fullName>
    </customValue>
    <customValue>
        <fullName>Hamilton</fullName>
    </customValue>
    <customValue>
        <fullName>Kamloops</fullName>
    </customValue>
    <customValue>
        <fullName>Kingston</fullName>
    </customValue>
    <customValue>
        <fullName>London</fullName>
    </customValue>
    <customValue>
        <fullName>Montreal</fullName>
    </customValue>
    <customValue>
        <fullName>NE Quebec</fullName>
    </customValue>
    <customValue>
        <fullName>Oakville</fullName>
    </customValue>
    <customValue>
        <fullName>Ottawa</fullName>
    </customValue>
    <customValue>
        <fullName>Prince George</fullName>
    </customValue>
    <customValue>
        <fullName>Quebec City</fullName>
    </customValue>
    <customValue>
        <fullName>Regina</fullName>
    </customValue>
    <customValue>
        <fullName>Sarnia</fullName>
    </customValue>
    <customValue>
        <fullName>Saskatoon</fullName>
    </customValue>
    <customValue>
        <fullName>Sault Ste Marie</fullName>
    </customValue>
    <customValue>
        <fullName>Sept Iles</fullName>
    </customValue>
    <customValue>
        <fullName>St. Rom</fullName>
    </customValue>
    <customValue>
        <fullName>Thunder Bay</fullName>
    </customValue>
    <customValue>
        <fullName>Toronto</fullName>
    </customValue>
    <customValue>
        <fullName>Vancouver</fullName>
    </customValue>
    <customValue>
        <fullName>Winnipeg</fullName>
    </customValue>
    <description>Revolution Canada Rack details</description>
    <masterLabel>RE_CND_Racks</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RE_CND_StartCalculatingDepoPricingQueue.cls
/**************************************************************************************************
* Name: RE_CND_StartCalculatingDepoPricingQueue
* Object: RE_Market_Quotes__c, RE_MOA__c, RE_MY_CostPrice__c, RE_Depot_Pricing_Backbone__c
* Purpose: Execute Depo Pricing for Revolution Canada
* Author: Abhilash KT (abhilash.kt@shell.com)
* Create Date: 2022-05-11
* Modify History: 
* 2022-05-11		Abhilash		Created
**************************************************************************************************/
public class RE_CND_StartCalculatingDepoPricingQueue implements Queueable {

    private DateTime requestdDate;
    private date request_Date;
    private date effectiveFromDate;
    private date effectiveToDate;
    private Id jobRunAudId;
    private Map<String,Decimal> latestNtMveGasoline;
    private Map<String,Decimal> latestNtMveDiesel;
    public static Boolean IsSuccessJobAudit = true; 
    
    public RE_CND_StartCalculatingDepoPricingQueue(DateTime requestdDate, date request_Date, date effectiveFromDate, date effectiveToDate, Id jobRunAudId, Map<String,Decimal> latestNtMveGasoline, Map<String,Decimal> latestNtMveDiesel)
    {
        this.requestdDate = requestdDate;
        this.request_Date = request_Date;
        this.effectiveFromDate = effectiveFromDate;
        this.effectiveToDate = effectiveToDate;
        this.jobRunAudId = jobRunAudId;
        this.latestNtMveGasoline = latestNtMveGasoline;
        this.latestNtMveDiesel = latestNtMveDiesel;
    }
    
    public void execute(QueueableContext context) 
    {
        RE_Job_Run_Audit__c jrAudit = new RE_Job_Run_Audit__c();
        jrAudit = [SELECT Id, RE_Job_Status__c, RE_Exception__c, Other_Comments__c FROM RE_Job_Run_Audit__c WHERE Id =: jobRunAudId];
        
        try
        {        
            List<RE_MOA__c> updatedMOA = New List<RE_MOA__c>();   
            List<RT_Setting__c> cndActivePricngDiff = new List<RT_Setting__c>();
            List<RE_Depot_Pricing_Backbone__c> unbrandedExecutePriceBaseProduct  = new List<RE_Depot_Pricing_Backbone__c>();      
            List<RE_Depot_Pricing_Backbone__c> unbrandedAndBrandedDerivedProduct = new List<RE_Depot_Pricing_Backbone__c>();          
            Map<String,RE_MY_CostPrice__c> prevDayCostPrice = new Map<String,RE_MY_CostPrice__c>();
            List<RE_MY_CostPrice__c> currentCostPriceList = new List<RE_MY_CostPrice__c>();            
            Map<String,Decimal> currentNtMveGasoline = new Map<String,Decimal>();
            Map<String,Decimal> currentNtMveDiesel = new Map<String,Decimal>();
            Map<String,Decimal> unBrandedAndBrandedProdCostPrice = new Map<String,Decimal>();
            Map<String,Decimal> unBrandedAndBrandedMV = new Map<String,Decimal>();
            Map<String,Decimal> unBrandBaseProdCostPrice = new Map<String,Decimal>();
            Map<String,Decimal> brandBaseProdCostPrice = new Map<String,Decimal>();
            Set<Id> insertedCostPriceIds = new Set<Id>();
            List<RV_Exception__c> excpList = new List<RV_Exception__c>();
            List<RE_MY_CostPrice__c> initialVersnLst = new List<RE_MY_CostPrice__c>();   
            Map<String,RE_MY_CostPrice__c> oldMapCostPrice = new Map<String,RE_MY_CostPrice__c>();
            List<RE_MY_CostPrice__c> oldCostPrceLst = new List<RE_MY_CostPrice__c>();
            List<RT_Price_Book__c> oldPriceBookLst = new List<RT_Price_Book__c>();
            String fxLiveQuoteName,epDefaultUnitRate; 
            Decimal currtFxRate = 0.00;            
            Map<String,String> baseProdctUnitRate = new Map<String,String>();
            Boolean updateSuccess = False;
            Map<Id,String> diffType = New Map<Id,String>();
            Map<Id,Decimal> diffValue = New Map<Id,Decimal>();
            Map<Id,String> diffUnit = New Map<Id,String>();
             
            Map<String,Decimal> refRackNtMveGasoline = new Map<String,Decimal>();
            Map<String,String> refRackGasoline = new Map<String,String>();           
            Map<String,Decimal> refRackNtMveDiesel = new Map<String,Decimal>();
            Map<String,String> refRackDiesel = new Map<String,String>();
            Decimal baseNtMve = 0.00;
            Decimal refNtMve = 0.00;
            Decimal rackBaseDiff = 0.00;
            String refBaseRack;
            
            Id cndDepotPricingRecdTypId = Schema.SObjectType.RE_Depot_Pricing_Backbone__c.getRecordTypeInfosByDeveloperName().get('Canada').getRecordTypeId();
            Id cndPricngDiffRecdTypId = Schema.SObjectType.RT_Setting__c.getRecordTypeInfosByDeveloperName().get('Canada_Pricing_Differential').getRecordTypeId();
            Id cadMOARecordTypeId = Schema.SObjectType.RE_MOA__c.getRecordTypeInfosByDeveloperName().get('Canada_Execute_Pricing').getRecordTypeId();
            
            updatedMOA = [SELECT Id, RE_CND_Rack__c, RE_CND_Group__c, RE_CND_Today_s_Price__c, RE_CND_Market_Move__c, RE_CND_Competitive_Adj__c, 
                         RE_CND_Net_Move__c, RE_CND_New_End_Price__c, RE_CND_Difference__c FROM RE_MOA__c WHERE recordtypeid =: cadMOARecordTypeId AND RE_CND_Effective_From_Date__c =: effectiveFromDate
                         AND RE_IsLatest__c =: TRUE ORDER BY RE_CND_Group__c];
    
            // Get all the current day's active Cost Price and Price Book records to set Redundant
            RE_CND_ExecuteDepoPricingController.currentDayRecordsWrapper curDayRecrdWrapper = new RE_CND_ExecuteDepoPricingController.currentDayRecordsWrapper(); 
            curDayRecrdWrapper = RE_CND_ExecuteDepoPricingController.getCurentDayAllCostPriceRecords(request_Date);    
            oldMapCostPrice = curDayRecrdWrapper.currtDayMapCostPriceList;            
            oldPriceBookLst = curDayRecrdWrapper.currtDayPrcBookList;
            oldCostPrceLst = curDayRecrdWrapper.currtDayCostPrcList;
            
            Datetime requestedFxStartDt = (DateTime)request_Date;
            Datetime requestedFxEndDt = requestedFxStartDt.AddHours(23).AddMinutes(59).AddSeconds(59);
            
            // Get the Live Fx Rate Quote 
            for(RE_Zema_Quotes_Settings__c fxQuote: [SELECT Display_Name__c FROM RE_Zema_Quotes_Settings__c 
                                                     WHERE Country__c LIKE '%Canada%' AND Type__c =:'FX Rates' 
                                                     AND Frequency__c =: 'Live' AND Is_Active__c =: TRUE LIMIT 1])
            {
                fxLiveQuoteName = fxQuote.Display_Name__c;
            } 
            
            // Get current Fx Rate
            for(RE_FX_Rates__c curfx: [SELECT Id, RE_Forex_Rate__c FROM RE_FX_Rates__c 
                                       WHERE RE_Quote_Name__c =: fxLiveQuoteName AND RE_Trade_Type__c =: 'Exchange Rate' 
                                       AND RE_Pricing_Date__c >=: requestedFxStartDt AND RE_Pricing_Date__c <=: requestedFxEndDt
                                       LIMIT 1])
            {
                currtFxRate = curfx.RE_Forex_Rate__c;
            }
      
            // Get the Base Reference Rack Settings
            for(RE_CND_Base_Reference_Rack_Settings__c bseRefRacks : RE_CND_Base_Reference_Rack_Settings__c.getall().values())
            {
                if((bseRefRacks.Is_Active__c) && (bseRefRacks.Product_Classification_L0__c == 'Gasoline'))
                {                    
                    if(latestNtMveGasoline.containsKey(bseRefRacks.Rack__c+' '+bseRefRacks.Product_Classification_L0__c) 
                       && latestNtMveGasoline.containsKey(bseRefRacks.Base_Rack__c+' '+bseRefRacks.Product_Classification_L0__c))
                    {                       
                        baseNtMve = latestNtMveGasoline.get(bseRefRacks.Rack__c+' '+bseRefRacks.Product_Classification_L0__c);
                        refNtMve = latestNtMveGasoline.get(bseRefRacks.Base_Rack__c+' '+bseRefRacks.Product_Classification_L0__c);
                        rackBaseDiff = baseNtMve - refNtMve;                        
                        refRackNtMveGasoline.put(bseRefRacks.Rack__c+' '+bseRefRacks.Product_Classification_L0__c,rackBaseDiff);
                        refRackGasoline.put(bseRefRacks.Rack__c+' '+bseRefRacks.Product_Classification_L0__c,bseRefRacks.Base_Rack__c);
                    }
                }
                else if((bseRefRacks.Is_Active__c) && (bseRefRacks.Product_Classification_L0__c == 'Gas Oil'))
                {
                    if(latestNtMveDiesel.containsKey(bseRefRacks.Rack__c+' '+bseRefRacks.Product_Classification_L0__c) 
                       && latestNtMveDiesel.containsKey(bseRefRacks.Base_Rack__c+' '+bseRefRacks.Product_Classification_L0__c))
                    {
                        baseNtMve = latestNtMveDiesel.get(bseRefRacks.Rack__c+' '+bseRefRacks.Product_Classification_L0__c);
                        refNtMve = latestNtMveDiesel.get(bseRefRacks.Base_Rack__c+' '+bseRefRacks.Product_Classification_L0__c);
                        rackBaseDiff = baseNtMve - refNtMve;
                        refRackNtMveDiesel.put(bseRefRacks.Rack__c+' '+bseRefRacks.Product_Classification_L0__c,rackBaseDiff);
                        refRackDiesel.put(bseRefRacks.Rack__c+' '+bseRefRacks.Product_Classification_L0__c,bseRefRacks.Base_Rack__c);
                    }               
                }
            }
            
            // Get all the Canada active Pricing Differential           
            RE_CND_ExecuteDepoPricingController.differentialRecordsWrapper diffRecod = New RE_CND_ExecuteDepoPricingController.differentialRecordsWrapper();
            diffRecod = RE_CND_ExecuteDepoPricingController.getActiveCNDPricngDifferential(cndPricngDiffRecdTypId);
            diffType = diffRecod.diffRecordType;
            diffValue = diffRecod.diffRecordValue;
            diffUnit = diffRecod.diffRecordUnit;
            
            // Get all the Branded and Unbranded Base and Derived Products respectively
            RE_CND_ExecuteDepoPricingController.cndDepotPricingRecordWrapper cndAllActiveDepotPricing = new RE_CND_ExecuteDepoPricingController.cndDepotPricingRecordWrapper();            
            cndAllActiveDepotPricing =  RE_CND_ExecuteDepoPricingController.getActiveAllCNDDepotPricing(cndDepotPricingRecdTypId);             
            unbrandedExecutePriceBaseProduct = cndAllActiveDepotPricing.unbrandedExecutePriceBaseProduct;
            unbrandedAndBrandedDerivedProduct = cndAllActiveDepotPricing.unbrandedAndBrandedDerivedProduct;
            
            // Get the previous day's cost price records
            prevDayCostPrice = RE_CND_ExecuteDepoPricingController.getLatestCostPriceRecords(request_Date);
            
            // Get the default unit rate for Price execution Calculation
            for(RE_Default_Unit_Rate_Settings__c dunitRate : RE_Default_Unit_Rate_Settings__c.getall().values())
            {
                if((dunitRate.Country_Name__c == 'Canada') && (dunitRate.Object_Name__c == 'RE_MOA__c')
                   && (dunitRate.Type__c == 'Price Execution') && (dunitRate.Is_Active__c == TRUE))
                {
                    epDefaultUnitRate = dunitRate.Default_Unit_Rate__c;                  
                }
            }            
            
            // Unbranded Execute Pricing for Base Products           
            if(unbrandedExecutePriceBaseProduct.size() > 0)
            {         
                for(RE_Depot_Pricing_Backbone__c unBrndExecteBaseProd : unbrandedExecutePriceBaseProduct)
                {                
                    RE_MY_CostPrice__c currCostPrice = new RE_MY_CostPrice__c();
                    
                    if(unBrndExecteBaseProd.RE_Product_Name__r.RE_Product_Classification_L0__c == 'Gasoline')
                    {                       
                        rackBaseDiff = 0.00;
                        refBaseRack = '';
                        
                        if(refRackNtMveGasoline.containsKey(unBrndExecteBaseProd.RE_CND_Rack__c+' '+unBrndExecteBaseProd.RE_Product_Name__r.RE_Product_Classification_L0__c))
                            rackBaseDiff = refRackNtMveGasoline.get(unBrndExecteBaseProd.RE_CND_Rack__c+' '+unBrndExecteBaseProd.RE_Product_Name__r.RE_Product_Classification_L0__c);
                        
                        if(refRackGasoline.containsKey(unBrndExecteBaseProd.RE_CND_Rack__c+' '+unBrndExecteBaseProd.RE_Product_Name__r.RE_Product_Classification_L0__c))
                            refBaseRack = refRackGasoline.get(unBrndExecteBaseProd.RE_CND_Rack__c+' '+unBrndExecteBaseProd.RE_Product_Name__r.RE_Product_Classification_L0__c);
                        
                        currCostPrice = RE_CND_ExecuteDepoPricingController.calculatePricingLogic(request_Date, unBrndExecteBaseProd, cndActivePricngDiff, prevDayCostPrice,  requestdDate, effectiveFromDate, effectiveToDate, TRUE, 0.00, FALSE, 0.00, currtFxRate, epDefaultUnitRate, null,diffType,diffValue,diffUnit,rackBaseDiff,refBaseRack,updatedMOA);
                    }
                    else
                    {
                        rackBaseDiff = 0.00;
                        refBaseRack = '';
                        
                        if(refRackNtMveDiesel.containsKey(unBrndExecteBaseProd.RE_CND_Rack__c+' '+unBrndExecteBaseProd.RE_Product_Name__r.RE_Product_Classification_L0__c))
                            rackBaseDiff = refRackNtMveDiesel.get(unBrndExecteBaseProd.RE_CND_Rack__c+' '+unBrndExecteBaseProd.RE_Product_Name__r.RE_Product_Classification_L0__c);
                        else if(refRackNtMveDiesel.containsKey(unBrndExecteBaseProd.RE_CND_Rack__c+' '+'Gas Oil'))
                            rackBaseDiff = refRackNtMveDiesel.get(unBrndExecteBaseProd.RE_CND_Rack__c+' '+'Gas Oil');  
                        
                        if(refRackDiesel.containsKey(unBrndExecteBaseProd.RE_CND_Rack__c+' '+unBrndExecteBaseProd.RE_Product_Name__r.RE_Product_Classification_L0__c))
                            refBaseRack = refRackDiesel.get(unBrndExecteBaseProd.RE_CND_Rack__c+' '+unBrndExecteBaseProd.RE_Product_Name__r.RE_Product_Classification_L0__c);
                        else if(refRackDiesel.containsKey(unBrndExecteBaseProd.RE_CND_Rack__c+' '+'Gas Oil'))
                            refBaseRack = refRackDiesel.get(unBrndExecteBaseProd.RE_CND_Rack__c+' '+'Gas Oil'); 
                        
                        currCostPrice = RE_CND_ExecuteDepoPricingController.calculatePricingLogic(request_Date, unBrndExecteBaseProd, cndActivePricngDiff, prevDayCostPrice, requestdDate, effectiveFromDate, effectiveToDate, TRUE, 0.00, FALSE, 0.00, currtFxRate, epDefaultUnitRate, null,diffType,diffValue,diffUnit,rackBaseDiff,refBaseRack,updatedMOA); 
                    }
                    
                    currentCostPriceList.add(currCostPrice); 
                    unBrandedAndBrandedMV.put(unBrndExecteBaseProd.RE_Product_Name__r.RT_Product_Code__c+'-'+unBrndExecteBaseProd.RE_Location_Name__r.RE_Location_Code__c+ '-' + unBrndExecteBaseProd.RE_CND_Group__c, currCostPrice.RE_CND_Market_Move__c);
                    unBrandedAndBrandedProdCostPrice.put(unBrndExecteBaseProd.RE_Product_Name__r.RT_Product_Code__c+'-'+unBrndExecteBaseProd.RE_Location_Name__r.RE_Location_Code__c+ '-' + unBrndExecteBaseProd.RE_CND_Group__c, currCostPrice.RE_CND_New_Base_Value__c);
                    baseProdctUnitRate.put(unBrndExecteBaseProd.RE_Product_Name__r.RT_Product_Code__c+'-'+unBrndExecteBaseProd.RE_Location_Name__r.RE_Location_Code__c+ '-' + unBrndExecteBaseProd.RE_CND_Group__c, currCostPrice.RE_Costprice_Unit__c);
                }
            }
            
            // Unbranded/Branded Pricing for Derived Products 
            if(unbrandedAndBrandedDerivedProduct.size() > 0)
            {                
                for(RE_Depot_Pricing_Backbone__c unBrndBrndDerivedProd : unbrandedAndBrandedDerivedProduct)
                {                   
                    RE_MY_CostPrice__c currCostPrice = new RE_MY_CostPrice__c();
                    
                    if(unBrandedAndBrandedProdCostPrice.containsKey(unBrndBrndDerivedProd.RE_CND_Pricing_Basis__c))
                    {           
                        if(unBrndBrndDerivedProd.RE_Product_Name__r.RE_Product_Classification_L0__c == 'Gasoline')
                        {
                            rackBaseDiff = 0.00;
                            refBaseRack = '';
                            
                            if(refRackNtMveGasoline.containsKey(unBrndBrndDerivedProd.RE_CND_Rack__c+' '+unBrndBrndDerivedProd.RE_Product_Name__r.RE_Product_Classification_L0__c))
                                rackBaseDiff = refRackNtMveGasoline.get(unBrndBrndDerivedProd.RE_CND_Rack__c+' '+unBrndBrndDerivedProd.RE_Product_Name__r.RE_Product_Classification_L0__c);
                            
                            if(refRackGasoline.containsKey(unBrndBrndDerivedProd.RE_CND_Rack__c+' '+unBrndBrndDerivedProd.RE_Product_Name__r.RE_Product_Classification_L0__c))
                                refBaseRack = refRackGasoline.get(unBrndBrndDerivedProd.RE_CND_Rack__c+' '+unBrndBrndDerivedProd.RE_Product_Name__r.RE_Product_Classification_L0__c);
                            
                            currCostPrice = RE_CND_ExecuteDepoPricingController.calculatePricingLogic(request_Date, unBrndBrndDerivedProd, cndActivePricngDiff, prevDayCostPrice, requestdDate, effectiveFromDate, effectiveToDate, FALSE, 
                                                                  unBrandedAndBrandedMV.get(unBrndBrndDerivedProd.RE_CND_Pricing_Basis__c), TRUE, unBrandedAndBrandedProdCostPrice.get(unBrndBrndDerivedProd.RE_CND_Pricing_Basis__c), currtFxRate, epDefaultUnitRate, baseProdctUnitRate.get(unBrndBrndDerivedProd.RE_CND_Pricing_Basis__c),diffType,diffValue,diffUnit,
                                                                  rackBaseDiff,refBaseRack,updatedMOA);                            
                        }
                        else
                        {
                            rackBaseDiff = 0.00;
                            refBaseRack = '';
                            
                            if(refRackNtMveDiesel.containsKey(unBrndBrndDerivedProd.RE_CND_Rack__c+' '+unBrndBrndDerivedProd.RE_Product_Name__r.RE_Product_Classification_L0__c))
                                rackBaseDiff = refRackNtMveDiesel.get(unBrndBrndDerivedProd.RE_CND_Rack__c+' '+unBrndBrndDerivedProd.RE_Product_Name__r.RE_Product_Classification_L0__c);
                            else if(refRackNtMveDiesel.containsKey(unBrndBrndDerivedProd.RE_CND_Rack__c+' '+'Gas Oil'))
                                rackBaseDiff = refRackNtMveDiesel.get(unBrndBrndDerivedProd.RE_CND_Rack__c+' '+'Gas Oil');
                            
                            if(refRackDiesel.containsKey(unBrndBrndDerivedProd.RE_CND_Rack__c+' '+unBrndBrndDerivedProd.RE_Product_Name__r.RE_Product_Classification_L0__c))
                                refBaseRack = refRackDiesel.get(unBrndBrndDerivedProd.RE_CND_Rack__c+' '+unBrndBrndDerivedProd.RE_Product_Name__r.RE_Product_Classification_L0__c);                                            
                            else if(refRackDiesel.containsKey(unBrndBrndDerivedProd.RE_CND_Rack__c+' '+'Gas Oil'))
                                refBaseRack = refRackDiesel.get(unBrndBrndDerivedProd.RE_CND_Rack__c+' '+'Gas Oil');                                            
                            
                            currCostPrice = RE_CND_ExecuteDepoPricingController.calculatePricingLogic(request_Date, unBrndBrndDerivedProd, cndActivePricngDiff, prevDayCostPrice, requestdDate, effectiveFromDate, effectiveToDate, FALSE, 
                                                                  unBrandedAndBrandedMV.get(unBrndBrndDerivedProd.RE_CND_Pricing_Basis__c), TRUE, unBrandedAndBrandedProdCostPrice.get(unBrndBrndDerivedProd.RE_CND_Pricing_Basis__c), currtFxRate, epDefaultUnitRate, baseProdctUnitRate.get(unBrndBrndDerivedProd.RE_CND_Pricing_Basis__c),diffType,diffValue,diffUnit,
                                                                  rackBaseDiff,refBaseRack,updatedMOA);                            
                        }
                        
                        currentCostPriceList.add(currCostPrice);                         
                    }                           
                }
            }
            
            // Insert New Cost Price records
            if(currentCostPriceList.size() > 0)
            {                         
                Database.SaveResult[] cpList = Database.insert(currentCostPriceList, false);
                insertedCostPriceIds = RE_CND_Utility.handleInsert('RE_CND_ExecuteDepoPricingController','startCalculatingDepoPricing-InsertNewCostPrice',cpList,jrAudit);                            
            }
            
            if(excpList.size()>0)
            {                
                RV_ClassException.insertExceptionRecord(excpList); 
                String otherComment = 'Refer RV_Exception__c record for more details with jobAudit :'+jrAudit.Id;
                RE_CND_Utility.updateJobAuditPartialSuccess(jrAudit,'DML Exception while Database.Insert',otherComment);                                
            }            
            
            // Records existing on same day then update the InitialVersion same as Name in CostPrice
            if((insertedCostPriceIds.Size() > 0) && (oldMapCostPrice != null) && (oldMapCostPrice.Size() > 0))            
                initialVersnLst = RE_CND_ExecuteDepoPricingController.updateInitialVersionInOlderCostPrice(insertedCostPriceIds,curDayRecrdWrapper);     
            // If no existing records on same day then update the InitialVersion same as Name in CostPrice
            else if(insertedCostPriceIds.Size() > 0)   
                initialVersnLst = RE_CND_ExecuteDepoPricingController.updateInitialVersionInCostPrice(insertedCostPriceIds);
            
            // Update Cost Price, Price Book
            if(initialVersnLst.Size() > 0)
            {               
                RE_CND_CostPriceBatchUpdate updateCp = New RE_CND_CostPriceBatchUpdate(initialVersnLst, oldPriceBookLst, jrAudit, jrAudit.RE_Job_Status__c, IsSuccessJobAudit);
                Database.executeBatch(updateCp);              
            }
            else if((jrAudit.RE_Job_Status__c == 'Processing') && (IsSuccessJobAudit))
            {
                jrAudit.RE_Job_Status__c = 'Completed';               
                update jrAudit;                   
            }
            else
            {             
                String comments = 'Refer RV_Exception__c record for more details with jobAudit :'+jrAudit.Id;
                RE_CND_Utility.updateJobAuditPartialSuccess(jrAudit,'Issue while generating Canada Depo Pricing Job',comments);                
            }        
        }
        catch(Exception ex)
        {       
            System.debug('startCalculatingDepoPricing-Main-->'+ex.getMessage());
            System.debug('startCalculatingDepoPricing-Main-LN-->'+ex.getLineNumber());
            RV_ClassException.insertExceptionRecord('CalculatingDepoPricing',ex.getMessage()+'-'+ex.getLineNumber(),'RE_CND_ExecuteDepoPricingController','startCalculatingDepoPricing-Main','Exception');            
            RE_CND_Utility.updateJobAudit(jrAudit,'Failed',ex);  
        }        
        
    }
}