force-app/main/default/objects/ATP__c/ATP__c.object-meta.xml
<CustomObject>
    <description>Available to Promise(ATP) quantities will be used by the OBAMs to ensure that they not overselling and creating shortfall of products that could potentially be expensive for Shell to fulfill.</description>
    <label>ATP</label>
    <nameField>
        <displayFormat>ATP-{0000}</displayFormat>
        <label>ATP Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ATP__c/fields/ATP1__c.field-meta.xml
<CustomField>
    <fullName>ATP1__c</fullName>
    <label>D(00-14)(Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/ATP2__c.field-meta.xml
<CustomField>
    <fullName>ATP2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>D(15-28)(Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/ATP2_Live__c.field-meta.xml
<CustomField>
    <fullName>ATP2_Live__c</fullName>
    <label>Live(15-28)(Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/ATP3__c.field-meta.xml
<CustomField>
    <fullName>ATP3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>D(29-61)(Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/ATP3_Live__c.field-meta.xml
<CustomField>
    <fullName>ATP3_Live__c</fullName>
    <label>Live(29-61)(Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/ATP_Live__c.field-meta.xml
<CustomField>
    <fullName>ATP_Live__c</fullName>
    <label>Live(00-14)(Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/ATP_Refresh__c.field-meta.xml
<CustomField>
    <fullName>ATP_Refresh__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this checkbox to refresh the value of Live(00-14)(Tons)</description>
    <label>Reset Live(00-14)(Tons)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Grade_Level2__c.field-meta.xml
<CustomField>
    <fullName>Grade_Level2__c</fullName>
    <label>Product Sub Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AGO B7</fullName>
            </value>
            <value>
                <fullName>IGO Austria</fullName>
            </value>
            <value>
                <fullName>IGO 50ppm</fullName>
            </value>
            <value>
                <fullName>ULG95 E5</fullName>
            </value>
            <value>
                <fullName>AGO-B7</fullName>
                <isActive>false</isActive>
                <label>AGO-B7</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Name</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>ATP</relationshipLabel>
    <relationshipName>ATP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <formula>Location__r.Plant_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plant Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Reset_2__c.field-meta.xml
<CustomField>
    <fullName>Reset_2__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is field is used to reset Live(15-28)(Tons) value</description>
    <label>Reset Live(15-28)(Tons)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Reset_3__c.field-meta.xml
<CustomField>
    <fullName>Reset_3__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Reset Live(29-61)(Tons) values</description>
    <label>Reset Live(29-61)(Tons)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <formula>Plant_Code__c+ &apos;-&apos; +  TEXT(Grade_Level2__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UniqueKey</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Object to store all OU, Region and Location information for Trading and Supply - ATP/AMV/SCHT</description>
    <label>Location</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <description>Plant Number of Depot Code of the particular Plant/Depot</description>
    <label>Plant Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/Revolution_Dashboard__c.object-meta.xml
<CustomObject>
    <description>This object is used to create the dashboard of Revolution.</description>
    <label>Sales Dashboard</label>
    <nameField>
        <displayFormat>RV-{0000}</displayFormat>
        <label>Revolution Dashboard Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Dashboard</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revolution_Dashboard__c/fields/ATP1_Live_AGO__c.field-meta.xml
<CustomField>
    <fullName>ATP1_Live_AGO__c</fullName>
    <label>ATP1 Live (AGO)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/ATP1_Live_IGO__c.field-meta.xml
<CustomField>
    <fullName>ATP1_Live_IGO__c</fullName>
    <label>ATP1 Live (IGO)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/ATP1_Live_MOGAS__c.field-meta.xml
<CustomField>
    <fullName>ATP1_Live_MOGAS__c</fullName>
    <label>ATP1 Live (MOGAS)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/ATP2_Live_AGO__c.field-meta.xml
<CustomField>
    <fullName>ATP2_Live_AGO__c</fullName>
    <label>ATP2 Live (AGO)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/ATP2_Live_IGO__c.field-meta.xml
<CustomField>
    <fullName>ATP2_Live_IGO__c</fullName>
    <label>ATP2 Live (IGO)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/ATP3_Live_AGO__c.field-meta.xml
<CustomField>
    <fullName>ATP3_Live_AGO__c</fullName>
    <label>ATP3 Live (AGO)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/ATP3_Live_IGO__c.field-meta.xml
<CustomField>
    <fullName>ATP3_Live_IGO__c</fullName>
    <label>ATP3 Live (IGO)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/BSP_AGO__c.field-meta.xml
<CustomField>
    <fullName>BSP_AGO__c</fullName>
    <label>BSP (AGO)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/BSP_IGO__c.field-meta.xml
<CustomField>
    <fullName>BSP_IGO__c</fullName>
    <label>BSP (IGO)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/BSP_MOGAS__c.field-meta.xml
<CustomField>
    <fullName>BSP_MOGAS__c</fullName>
    <label>BSP (MOGAS)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/MOT__c.field-meta.xml
<CustomField>
    <fullName>MOT__c</fullName>
    <label>MOT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>Rail</fullName>
            </value>
            <value>
                <fullName>Barge</fullName>
            </value>
            <value>
                <fullName>ITT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/OTM_AGO__c.field-meta.xml
<CustomField>
    <fullName>OTM_AGO__c</fullName>
    <label>OTM (AGO)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/OTM_IGO__c.field-meta.xml
<CustomField>
    <fullName>OTM_IGO__c</fullName>
    <label>OTM (IGO)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/OTM_MOGAS__c.field-meta.xml
<CustomField>
    <fullName>OTM_MOGAS__c</fullName>
    <label>OTM (MOGAS)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <formula>Plant_Name__r.Plant_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plant Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/Plant_Name__c.field-meta.xml
<CustomField>
    <fullName>Plant_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Name</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipName>Revolution_Dashboards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/PSP_AGO__c.field-meta.xml
<CustomField>
    <fullName>PSP_AGO__c</fullName>
    <label>PSP (AGO)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/PSP_IGO__c.field-meta.xml
<CustomField>
    <fullName>PSP_IGO__c</fullName>
    <label>PSP (IGO)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/PSP_MOGAS__c.field-meta.xml
<CustomField>
    <fullName>PSP_MOGAS__c</fullName>
    <label>PSP (MOGAS)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AT01</fullName>
            </value>
            <value>
                <fullName>DE01</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Revolution_Dashboard__c/recordTypes/Dashboard.recordType-meta.xml
<RecordType>
    <fullName>Dashboard</fullName>
    <active>true</active>
    <label>Dashboard</label>
</RecordType>

force-app/main/default/classes/RV_ATPTriggerHelperTest.cls
@isTest
public class RV_ATPTriggerHelperTest {
    static testMethod void atpTriggerHelperMethd(){
        //Insert Location
        Location__c insertLoc = new Location__c();
        insertLoc = RV_TestHelper.insertLocation(insertLoc);
        insert insertLoc;
        
        
        
        
        //Insert dashbaord
        String revdashboardRT = Schema.SObjectType.Revolution_Dashboard__c.getRecordTypeInfosByName().get('Dashboard').getRecordTypeId();
		Revolution_Dashboard__c revDashboard = new Revolution_Dashboard__c();
        revDashboard.Plant_Name__c = insertLoc.Id;
        revDashboard.RecordTypeId = revdashboardRT;
        revDashboard.Sales_Channel__c = 'DE01';
        revDashboard.UniqueKey__c = 'DE01'+revDashboard.Plant_Name__c+'10';
        revDashboard.MOT__c = 'Truck';
        revDashboard.BSP_IGO__c = 34;
        revDashboard.PSP_IGO__c = 45;
        revDashboard.OTM_IGO__c = 55;
        revDashboard.ATP1_Live_IGO__c = 1000;
        revDashboard.ATP2_Live_IGO__c = 1000;
        revDashboard.ATP3_Live_IGO__c = 1000;
        
        revDashboard.BSP_AGO__c = 40;
        revDashboard.PSP_AGO__c = 43;
        revDashboard.OTM_AGO__c = 58;
        revDashboard.ATP1_Live_AGO__c = 1003;
        revDashboard.ATP2_Live_AGO__c = 1000;
        revDashboard.ATP3_Live_AGO__c = 1000;
        
        revDashboard.BSP_MOGAS__c = 37;
        revDashboard.PSP_MOGAS__c = 49;
        revDashboard.OTM_MOGAS__c = 56;
         
        revDashboard.ATP1_Live_MOGAS__c = 1004;
        revDashboard.ATP2_Live_AGO__c = 1000;
        revDashboard.ATP3_Live_AGO__c = 1000;
        insert revDashboard;   
        
        //Insert ATP
        RV_ATPTriggerHelper.recursiveDashboard=true;
        List<ATP__c> atpList = new List<ATP__c>(); // added by Dharmendra
        ATP__c atpInsert = new ATP__c();
        atpInsert  = RV_TestHelper.insertATPRecord(atpInsert,insertLoc);
        atpList.add(atpInsert);

        ATP__c atpInsert2 = new ATP__c();
        atpInsert2  = RV_TestHelper.insertATPRecord(atpInsert2,insertLoc);
        atpInsert2.ATP_Refresh__c = true;
        atpList.add(atpInsert2);

        ATP__c atpInsert3 = new ATP__c();
        atpInsert3  = RV_TestHelper.insertATPRecord(atpInsert3,insertLoc);
        atpInsert3.ATP_Refresh__c = true;
        atpList.add(atpInsert3);

        ATP__c atpInsert4 = new ATP__c();
        atpInsert4  = RV_TestHelper.insertATPRecord(atpInsert4,insertLoc);
        atpInsert4.ATP_Refresh__c = true;
        atpList.add(atpInsert4);

        ATP__c atpInsert5   = new ATP__c();
        atpInsert5          = RV_TestHelper.insertATPRecord(atpInsert5,insertLoc);
        atpInsert5.ATP_Refresh__c = true;
        atpList.add(atpInsert5);
        
        ATP__c atpInsertIgo = new ATP__c();
        atpInsertIgo  = RV_TestHelper.insertATPRecord(atpInsertIgo,insertLoc);
        atpInsertIgo.Grade_Level2__c='IGO 50ppm';
        atpList.add(atpInsertIgo); // added by Dharmendra
        
        //insert atpInsert;
        ATP__c atpInsertUlg = new ATP__c();
        atpInsertUlg=RV_TestHelper.insertATPRecordULG(atpInsertUlg,insertLoc);
        atpList.add(atpInsertUlg);

        atpList[2].ATP2_Live__c = null;
        atpList[2].ATP2__c = null;
        atpList[2].Reset_2__c = true;
        atpList[2].Reset_3__c = true;

        atpList[4].ATP_Refresh__c = true;
        atpList[4].ATP2_Live__c = null;
        atpList[4].ATP2__c = null;
        atpList[4].ATP3_Live__c = null;
        atpList[4].ATP3__c      = null;
        atpList[4].Reset_2__c = true;
        atpList[4].Reset_3__c = true;

        insert atpList;

        atpList[3].ATP2_Live__c = null;
        atpList[3].ATP2__c      = null;
        atpList[3].ATP3_Live__c = null;
        atpList[3].ATP3__c      = null;
        atpList[3].ATP_Refresh__c = true;
        atpList[3].Reset_2__c   = true;
        atpList[3].Reset_3__c   = true;

        update atpList;
       /*
        insert atpInsert;
        insert atpInsertUlg;
        insert atpInsertIgo;
        */

        //AdditionalTestCoverage_12Jun2019_Soumyajit starts 
        Location__c insertLocNull = new Location__c();
        insertLocNull = RV_TestHelper.insertLocation(insertLocNull);
        insertLocNull.name='Test Loc Null';
        insertLocNull.Plant_Code__c = 'D9999';
        insert insertLocNull;
        
        ATP__c atpInsertNull = new ATP__c();
        atpInsertNull=RV_TestHelper.insertATPRecordULG(atpInsertNull,insertLocNull);
        atpInsertNull.ATP_Live__c = 100;
        atpInsertNull.ATP2_Live__c = 100;
        atpInsertNull.ATP3_Live__c = 100;
        insert atpInsertNull;
        
        Revolution_Dashboard__c revDashboardNull = new Revolution_Dashboard__c();
        revDashboardNull.Plant_Name__c = insertLocNull.Id;
        revDashboardNull.RecordTypeId = revdashboardRT;
        revDashboardNull.Sales_Channel__c = 'DE01';
        revDashboardNull.UniqueKey__c = 'DE01'+revDashboardNull.Plant_Name__c+'10';
        revDashboardNull.MOT__c = 'Truck';
        insert revDashboardNull;
        
        //AdditionalTestCoverage_12Jun2019_Soumyajit ends 
        
        test.startTest();
        
        atpInsert.ATP_Live__c = 1100;
        atpInsert.ATP2_Live__c = 1200;
        atpInsert.ATP3_Live__c = 1300;
        
        atpInsertUlg.ATP_Live__c = 1100;
        atpInsertUlg.ATP2_Live__c = 1200;
        atpInsertUlg.ATP3_Live__c = 1300;
        
        atpInsertIgo.ATP_Live__c = 1100;
        atpInsertIgo.ATP2_Live__c = 1200;
        atpInsertIgo.ATP3_Live__c = 1300;
        
        update atpInsert;
        update atpInsertIgo;
        update atpInsertUlg;
        atpInsertIgo.ATP1__c = 1200;
        update atpInsertIgo;
        test.stopTest();
        
        
    }

}