force-app/main/default/objects/ATP__c/ATP__c.object-meta.xml
<CustomObject>
    <description>Available to Promise(ATP) quantities will be used by the OBAMs to ensure that they not overselling and creating shortfall of products that could potentially be expensive for Shell to fulfill.</description>
    <label>ATP</label>
    <nameField>
        <displayFormat>ATP-{0000}</displayFormat>
        <label>ATP Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ATP__c/fields/ATP1__c.field-meta.xml
<CustomField>
    <fullName>ATP1__c</fullName>
    <label>D(00-14)(Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/ATP_Auto_Refresh__c.field-meta.xml
<CustomField>
    <fullName>ATP_Auto_Refresh__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is used by a batch class to refresh ATP value.</description>
    <label>Batch ATP (00-14)(Tons)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/ATP_Live__c.field-meta.xml
<CustomField>
    <fullName>ATP_Live__c</fullName>
    <label>Live(00-14)(Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/ATP_Refresh__c.field-meta.xml
<CustomField>
    <fullName>ATP_Refresh__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this checkbox to refresh the value of Live(00-14)(Tons)</description>
    <label>Reset Live(00-14)(Tons)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Name</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>ATP</relationshipLabel>
    <relationshipName>ATP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Minimum_ATP1__c.field-meta.xml
<CustomField>
    <fullName>Minimum_ATP1__c</fullName>
    <label>Batch ATP (00-14)(Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Sales_8_30_17_30__c.field-meta.xml
<CustomField>
    <fullName>Sales_8_30_17_30__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sales(00-14)(Tons)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Object to store all OU, Region and Location information for Trading and Supply - ATP/AMV/SCHT</description>
    <label>Location</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Minimum_ATP1__c.field-meta.xml
<CustomField>
    <fullName>Minimum_ATP1__c</fullName>
    <label>Minimum ATP1</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RV_ATPAutoRefreshBatch.cls
/*****************************************************************************
@Name:  RV_ATPAutoRefreshBatch      
@=========================================================================
@Purpose: Batch will execute  to calculate ATP auto Refresh                                                                                        
@=========================================================================
@History                                                            
@---------                                                            
@VERSION AUTHOR                            DATE                DETAIL                                 
@1.0 - Dhriti Krishna Ghosh Moulick      10/18/2017         INITIAL DEVELOPMENT

******************************************************************************/
global  class RV_ATPAutoRefreshBatch implements Database.Batchable<sObject> {
   global Database.QueryLocator start(Database.BatchableContext BC){
      String query = 'SELECT id,ATP_Refresh__c,ATP_Auto_Refresh__c,ATP_Live__c,Minimum ATP1 ,Location__r.Minimum_ATP1__c,Location__c from ATP__c where ATP_Auto_Refresh__c = true';
      return Database.getQueryLocator(query);
   } 

   global void execute(Database.BatchableContext BC, List<ATP__c> scope){
    
         List<ATP__c> finalupdateATPRecord = new List<ATP__c>();
         for(ATP__c atpRecords : scope){
             if(atpRecords.ATP_Live__c <> null){
                if(atpRecords.Minimum_ATP1__c == null)atpRecords.Minimum_ATP1__c=0.0;
                atpRecords.ATP1__c = atpRecords.Minimum_ATP1__c;
                atpRecords.ATP_Live__c = atpRecords.ATP1__c;
                atpRecords.Sales_8_30_17_30__c = 0;
                //atpRecords.ATP_Refresh__c = false;
                finalupdateATPRecord.add(atpRecords);
            }
         }
         try{
             update finalupdateATPRecord;
         }catch(Exception e){
                System.debug('%%%%%%%%%%%%%%%'+e);
         }
    }

   global void finish(Database.BatchableContext BC){
   }
}