force-app/main/default/objects/ATP__c/ATP__c.object-meta.xml
<CustomObject>
    <description>Available to Promise(ATP) quantities will be used by the OBAMs to ensure that they not overselling and creating shortfall of products that could potentially be expensive for Shell to fulfill.</description>
    <label>ATP</label>
    <nameField>
        <displayFormat>ATP-{0000}</displayFormat>
        <label>ATP Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ATP__c/fields/ATP1__c.field-meta.xml
<CustomField>
    <fullName>ATP1__c</fullName>
    <label>D(00-14)(Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/ATP2__c.field-meta.xml
<CustomField>
    <fullName>ATP2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>D(15-28)(Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/ATP2_Live__c.field-meta.xml
<CustomField>
    <fullName>ATP2_Live__c</fullName>
    <label>Live(15-28)(Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/ATP3__c.field-meta.xml
<CustomField>
    <fullName>ATP3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>D(29-61)(Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/ATP3_Live__c.field-meta.xml
<CustomField>
    <fullName>ATP3_Live__c</fullName>
    <label>Live(29-61)(Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/ATP_Auto_Refresh__c.field-meta.xml
<CustomField>
    <fullName>ATP_Auto_Refresh__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is used by a batch class to refresh ATP value.</description>
    <label>Batch ATP (00-14)(Tons)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/ATP_Live__c.field-meta.xml
<CustomField>
    <fullName>ATP_Live__c</fullName>
    <label>Live(00-14)(Tons)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Comment_Forward2_Sales__c.field-meta.xml
<CustomField>
    <fullName>Comment_Forward2_Sales__c</fullName>
    <label>Comment Forward2 Sales</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Comment_Forward_Sales__c.field-meta.xml
<CustomField>
    <fullName>Comment_Forward_Sales__c</fullName>
    <label>Comment Forward Sales</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Comment_Prompt_Sales__c.field-meta.xml
<CustomField>
    <fullName>Comment_Prompt_Sales__c</fullName>
    <label>Comment Prompt Sales</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <formula>TEXT( Location__r.Company_Code__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Grade_Level2__c.field-meta.xml
<CustomField>
    <fullName>Grade_Level2__c</fullName>
    <label>Product Sub Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AGO B7</fullName>
            </value>
            <value>
                <fullName>IGO Austria</fullName>
            </value>
            <value>
                <fullName>IGO 50ppm</fullName>
            </value>
            <value>
                <fullName>ULG95 E5</fullName>
            </value>
            <value>
                <fullName>AGO-B7</fullName>
                <isActive>false</isActive>
                <label>AGO-B7</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Lifting_Validity_From1__c.field-meta.xml
<CustomField>
    <fullName>Lifting_Validity_From1__c</fullName>
    <label>Lifting Day1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Lifting_Validity_From2__c.field-meta.xml
<CustomField>
    <fullName>Lifting_Validity_From2__c</fullName>
    <label>Lifting Day2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Lifting_Validity_From3__c.field-meta.xml
<CustomField>
    <fullName>Lifting_Validity_From3__c</fullName>
    <label>Lifting Day3</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Name</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>ATP</relationshipLabel>
    <relationshipName>ATP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <formula>Location__r.Plant_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plant Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Sales_15_28__c.field-meta.xml
<CustomField>
    <fullName>Sales_15_28__c</fullName>
    <label>Sales(15-28)(Tons)</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Sales_29_61__c.field-meta.xml
<CustomField>
    <fullName>Sales_29_61__c</fullName>
    <label>Sales(29-61)(Tons)</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Sales_8_30_17_30__c.field-meta.xml
<CustomField>
    <fullName>Sales_8_30_17_30__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sales(00-14)(Tons)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Object to store all OU, Region and Location information for Trading and Supply - ATP/AMV/SCHT</description>
    <label>Location</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE01</fullName>
            </value>
            <value>
                <fullName>AT01</fullName>
            </value>
            <value>
                <fullName>CH01</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <description>Plant Number of Depot Code of the particular Plant/Depot</description>
    <label>Plant Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Location__c/fields/Source_Location__c.field-meta.xml
<CustomField>
    <fullName>Source_Location__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Source Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/My_AT_Locations__c.field-meta.xml
<CustomField>
    <fullName>My_AT_Locations__c</fullName>
    <label>My AT Locations</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/User/fields/My_DE_Locations__c.field-meta.xml
<CustomField>
    <fullName>My_DE_Locations__c</fullName>
    <label>My DE Locations</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/LiveAtpPspControllerTest.cls
@isTest
public class LiveAtpPspControllerTest {
    @testSetup 
    static void setup() {
        List<ATP__c> atplst = new List<ATP__c>();
        Location__c loc = new Location__c();
        loc.Name = 'Ludwigshafen depot';
        loc.Plant_Code__c = 'D004';
        loc.Source_Location__c = true;
        loc.Company_Code__c = 'DE01';
        insert loc;
        //AdditionalTestCoverage_12Jun2019_Lakshmi_starts
        /* PBI_166252_DataCleanup_Lakshmi_1stOct2019 == Commented PSP Object Related fields
        List<PSP__c> PspList = new List<PSP__c>();
        
		 PSP__c PspDataInsertAGO = new PSP__c();
         PspDataInsertAGO.Plant_Name__c = loc.Id;
         PspDataInsertAGO.Grade__c= Label.AGO_B7;
         PspDataInsertAGO.Product_Category__c=Label.AGO_B7;
         PspDataInsertAGO.AMV__c = 1000.78;
         PspDataInsertAGO.HCV__c = 1000.78;
         PspDataInsertAGO.Manual_Adjustment1__c=100.56;
         PspDataInsertAGO.Apply_Throughput__c='Yes';
         PspDataInsertAGO.Throughputcost__c=1000.78;
         PspList.add(PspDataInsertAGO);
         insert PspList;
		*/
        //AdditionalTestCoverage_12Jun2019_Lakshmi_Ends
        
        ATP__c atpDataInsertAGO = new ATP__c();
        atpDataInsertAGO.Location__c = loc.Id;
        atpDataInsertAGO.Grade_Level2__c = Label.AGO_B7;
        atpDataInsertAGO.ATP1__c = 1000;
        atpDataInsertAGO.ATP2__c = 1000;
        atpDataInsertAGO.ATP3__c = 1000;
        atpDataInsertAGO.ATP_Live__c = 1000;
        atpDataInsertAGO.ATP2_Live__c  = 1000;
        atpDataInsertAGO.ATP3_Live__c  = 1000;   
        atpDataInsertAGO.Sales_8_30_17_30__c = 0;
        atpDataInsertAGO.Sales_15_28__c = 0;
        atpDataInsertAGO.Sales_29_61__c = 0;
        //AdditionalTestCoverage_12Jun2019_Lakshmi_starts
        //atpDataInsertAGO.Lifting_Validity_From1__c = Date.Today();
        atpDataInsertAGO.Lifting_Validity_From1__c=system.today();
       	atpDataInsertAGO.Lifting_Validity_From2__c=system.today();
        atpDataInsertAGO.Lifting_Validity_From3__c=system.today();
        atpDataInsertAGO.Comment_Forward_Sales__c='test';
        atpDataInsertAGO.Comment_Prompt_Sales__c='test1';
        atpDataInsertAGO.Comment_Forward2_Sales__c='test2';
        //AdditionalTestCoverage_12Jun2019_Lakshmi_Ends
        atpDataInsertAGO.ATP_Auto_Refresh__c = true;
        atplst.add(atpDataInsertAGO);
        
        
        ATP__c atpDataInsertIGO = new ATP__c();
        atpDataInsertIGO.Location__c = loc.Id;
        atpDataInsertIGO.Grade_Level2__c = Label.IGO_50ppm;
        atpDataInsertIGO.ATP1__c = 1000;
        atpDataInsertIGO.ATP2__c = 1000;
        atpDataInsertIGO.ATP3__c = 1000;
        atpDataInsertIGO.ATP_Live__c = 1000;
        atpDataInsertIGO.ATP2_Live__c  = 1000;
        atpDataInsertIGO.ATP3_Live__c  = 1000;   
        atpDataInsertIGO.Sales_8_30_17_30__c = 0;
        atpDataInsertIGO.Sales_15_28__c = 0;
        atpDataInsertIGO.Sales_29_61__c = 0;
        //AdditionalTestCoverage_12Jun2019_Lakshmi_Starts
        //atpDataInsertIGO.Lifting_Validity_From2__c = Date.Today();
        atpDataInsertIGO.Lifting_Validity_From2__c = system.today();
        atpDataInsertIGO.Lifting_Validity_From2__c=system.today();
        atpDataInsertIGO.Lifting_Validity_From3__c=system.today();
        atpDataInsertIGO.Comment_Forward_Sales__c='test';
        atpDataInsertIGO.Comment_Prompt_Sales__c='test1';
        atpDataInsertIGO.Comment_Forward2_Sales__c='test2';
        //AdditionalTestCoverage_12Jun2019_Lakshmi_Ends
        atpDataInsertIGO.ATP_Auto_Refresh__c = true;
        atplst.add(atpDataInsertIGO);    
        
        ATP__c atpDataInsertULG = new ATP__c();
        atpDataInsertULG.Location__c = loc.Id;
        atpDataInsertULG.Grade_Level2__c =  'ULG95 E5';
        atpDataInsertULG.ATP1__c = 1000;
        atpDataInsertULG.ATP2__c = 1000;
        atpDataInsertULG.ATP3__c = 1000;
        atpDataInsertULG.ATP_Live__c = 1000;
        atpDataInsertULG.ATP2_Live__c  = 1000;
        atpDataInsertULG.ATP3_Live__c  = 1000;   
        atpDataInsertULG.Sales_8_30_17_30__c = 0;
        atpDataInsertULG.Sales_15_28__c = 0;
        atpDataInsertULG.Sales_29_61__c = 0;
        //AdditionalTestCoverage_12Jun2019_Lakshmi_Starts
        //atpDataInsertULG.Lifting_Validity_From1__c = Date.Today();
         atpDataInsertULG.Lifting_Validity_From1__c =system.today();
         atpDataInsertULG.Lifting_Validity_From2__c=system.today();
        atpDataInsertULG.Lifting_Validity_From3__c=system.today();
        atpDataInsertULG.Comment_Forward_Sales__c='test';
        atpDataInsertULG.Comment_Prompt_Sales__c='test1';
        atpDataInsertULG.Comment_Forward2_Sales__c='test2';
        //AdditionalTestCoverage_12Jun2019_Lakshmi_Ends
        atpDataInsertULG.ATP_Auto_Refresh__c = true;
        atplst.add(atpDataInsertULG);
        insert atplst;
    }
    public static testMethod void testLiveAtpPspController() {
        PageReference pageRef = new PageReference('');
        Test.setCurrentPage(pageRef);
      
        // To insert user and it's property and do run as user 
        Profile objProfile = [Select Id, Name from Profile where Name =: 'System Administrator' limit 1];
        User objUser = [Select Id, ProfileId from User where Id=: UserInfo.getUserId()];
        objUser.My_DE_Locations__c = 'D004';
        objUser.My_AT_Locations__c ='';
        ApexPages.currentPage().getParameters().put('qp', 'yyyy');
        String[] companyCodes = new String[]{'AT01','DE01'};
        String[] companyCode = new String[]{'DE01'};
        String option = 'My';
        String wndw = 'ATP1';
        
        List<LiveATPPSPDemoController.ATPWrap> wrapList = new List<LiveATPPSPDemoController.ATPWrap>(); 
        //LiveATPPSPDemoController.ATPWrap = new LiveATPPSPDemoController.ATPWrap();
        system.runAs(objUser){
            LiveAtpPspController controller = new LiveAtpPspController(); 
            controller.option = option;
            controller.wndw = wndw;
            controller.companyCodes=companyCodes;
            controller.atpWrapper = wrapList;
            controller.setRefreshedTime('5');
            controller.setOption('All');
            controller.setWndw('ATP1');
            controller.SetCompanyCodes(companyCodes);
            controller.selectedCompanyCodes();
            controller.selectedWindows();
            
            controller.getItems();
            controller.getOption();
            controller.getRefreshedTime();
            controller.getTranche();
            controller.getChannels();
            
            controller.selectedPreference();
            controller.refreshPage();
            
            LiveAtpPspController controller2 = new LiveAtpPspController(); 
            controller2.option = option;
            controller2.wndw = wndw;
            controller2.companyCodes=companyCodes;
            controller2.atpWrapper = wrapList;
            controller2.setRefreshedTime('5');
            controller2.setOption('All');
            controller2.setWndw('ATP2');
            controller2.SetCompanyCodes(companyCodes);
            wrapList = LiveATPPSPDemoController.getAllATPList(companyCodes,'ATP1','All');
            LiveATPPSPDemoController.getAllATPList(companyCodes,'ATP2','All');
            LiveATPPSPDemoController.getAllATPList(companyCodes,'ATP3','All');
            LiveATPPSPDemoController.saveLocationPref(JSON.serialize(wrapList),companyCodes);
            LiveATPPSPDemoController.saveLocationPref(JSON.serialize(wrapList),companyCode);
            //Added by Dharmendra on 12/11/2020 for RV_LocaleHelper Start
            RV_LocaleHelper.formattedDecimal(11.11);
            //Added by Dharmendra for RV_LocaleHelper End
        }
    }
}