force-app/main/default/objects/Customer_Specific_Pricing__c/Customer_Specific_Pricing__c.object-meta.xml
<CustomObject>
    <label>Customer Specific Pricing</label>
    <nameField>
        <displayFormat>CSP-{0000}</displayFormat>
        <label>Customer Specific Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Specific Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Specific_Pricing__c/fields/CSP_Eur_100L__c.field-meta.xml
<CustomField>
    <fullName>CSP_Eur_100L__c</fullName>
    <label>CSP (Eur/100L)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Specific_Pricing__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AGO B7</fullName>
            </value>
            <value>
                <fullName>IGO 50ppm</fullName>
            </value>
            <value>
                <fullName>ULG95 E5</fullName>
            </value>
            <value>
                <fullName>GTL B0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Specific_Pricing__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Customer Specific Pricing</relationshipLabel>
    <relationshipName>Customer_Specific_Pricing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Specific_Pricing__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE01</fullName>
            </value>
            <value>
                <fullName>AT01</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Specific_Pricing__c/fields/Tranche__c.field-meta.xml
<CustomField>
    <fullName>Tranche__c</fullName>
    <label>Lifting Window/Tranche</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ATP1</fullName>
                <default>true</default>
                <label>Tranche1</label>
            </value>
            <value>
                <fullName>ATP2</fullName>
                <label>Tranche2</label>
            </value>
            <value>
                <fullName>ATP3</fullName>
                <label>Tranche3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Margin__c/Margin__c.object-meta.xml
<CustomObject>
    <label>Margin</label>
    <nameField>
        <displayFormat>MR-{0000}</displayFormat>
        <label>Margin Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Margins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Margin__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Margins</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/Sales_Mgn_AGO_B7__c.field-meta.xml
<CustomField>
    <fullName>Sales_Mgn_AGO_B7__c</fullName>
    <label>Sales Mgn AGO B7(Euro/100L)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/Sales_Mgn_IGO_50ppm__c.field-meta.xml
<CustomField>
    <fullName>Sales_Mgn_IGO_50ppm__c</fullName>
    <label>Sales Mgn IGO 50ppm(Euro/100L)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/Sales_Mgn_ULG95_E5__c.field-meta.xml
<CustomField>
    <fullName>Sales_Mgn_ULG95_E5__c</fullName>
    <label>Sales Mgn ULG95 E5(Euro/100L)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Margin__c/fields/Tranche__c.field-meta.xml
<CustomField>
    <fullName>Tranche__c</fullName>
    <inlineHelpText>Tranche for which margin will be applied.</inlineHelpText>
    <label>Tranche</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ATP1</fullName>
                <label>Tranche1</label>
            </value>
            <value>
                <fullName>ATP2</fullName>
                <label>Tranche2</label>
            </value>
            <value>
                <fullName>ATP3</fullName>
                <label>Tranche3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Margin__c/recordTypes/Truck_ITT.recordType-meta.xml
<RecordType>
    <fullName>Truck_ITT</fullName>
    <active>true</active>
    <label>Truck/ITT</label>
</RecordType>

force-app/main/default/classes/RV_CspTriggerHelper.cls
public with sharing class RV_CspTriggerHelper {
/*****************************************************************************
@Name:  RV_CspTriggerHelper     
@=========================================================================
@Purpose: Helper class for RV_CspTrigger.trg
@=========================================================================
@History                                                            
@---------                                                            
@VERSION AUTHOR                            DATE                DETAIL                                 
@1.0 - Rahul Sharma     ```````````````    12-Feb-2020         INITIAL DEVELOPMENT

******************************************************************************/  

    //On before insert
    public static void onBeforeInsert(List<Customer_Specific_Pricing__c> cspListNew){
        validateCsp(cspListNew);
    }

    //On before update
    public static void onBeforeUpdate(List<Customer_Specific_Pricing__c> cspListOld, List<Customer_Specific_Pricing__c> cspListNew, 
                                      Map<Id, Customer_Specific_Pricing__c> cspOldMap, Map<Id, Customer_Specific_Pricing__c> cspNewMap){
        validateCsp(cspListNew);
    }

    //On before delete
    public static void onBeforeDelete(List<Customer_Specific_Pricing__c> cspListOld, Map<Id, Customer_Specific_Pricing__c> cspOldMap){

    }
    
    //on after insert
    public static void onAfterInsert(List<Customer_Specific_Pricing__c> cspListNew, Map<Id, Customer_Specific_Pricing__c> cspNewMap){

    }
    
    //on after update
    public static void onAfterUpdate(List<Customer_Specific_Pricing__c> cspListOld, List<Customer_Specific_Pricing__c> cspListNew,
                                     Map<Id, Customer_Specific_Pricing__c> cspOldMap, Map<Id, Customer_Specific_Pricing__c> cspNewMap){

    }


    public static void validateCsp(List<Customer_Specific_Pricing__c> cspList){
        Set<Id> locationIdSet = new Set<Id>();
        Set<String> salesOrgSet = new Set<String>();
        Id marginRecordTypeId = Schema.SObjectType.Margin__c.getRecordTypeInfosByDeveloperName().get('Truck_ITT').getRecordTypeId();

        for(Customer_Specific_Pricing__c csp : cspList){
            locationIdSet.add(csp.Plant__c);
            salesOrgSet.add(csp.Sales_Org__c);
        }
        if(!locationIdSet.isEmpty() && !salesOrgSet.isEmpty()){
        //START - Rahul Sharma | Date: 02-Nov-20 : Updated logic to include margins for all tranches.
            List<Margin__c> marginList = [SELECT Id,
                                                 Sales_Org__c,
                                                 Plant__c,
                                                 Sales_Mgn_AGO_B7__c,
                                                 Sales_Mgn_IGO_50ppm__c,
                                          		 Tranche__c,
                                                 Sales_Mgn_ULG95_E5__c FROM Margin__c WHERE Sales_Org__c IN : salesOrgSet AND 
                                                                                            Plant__c IN : locationIdSet AND 
                                                                                            RecordTypeId =: marginRecordTypeId];
            System.debug('RV_CspTriggerHelper >> validateCsp >> marginList: '+marginList);
            if(!marginList.isEmpty()){
                for(Customer_Specific_Pricing__c csp : cspList){
                    for(Margin__c margin : marginList){
                        if(margin.Sales_Org__c == csp.Sales_Org__c && margin.Plant__c == csp.Plant__c && margin.Tranche__c == csp.Tranche__c){
        //END - Rahul Sharma | Date: 02-Nov-20 : Updated logic to include margins for all tranches.
                            //START - Rahul Sharma | Date: 20-Janv-21 : Fixed null pointer exception.
                            Decimal cspPrice = 0;
                            if(csp.CSP_Eur_100L__c != null)
                                cspPrice = csp.CSP_Eur_100L__c;
                            if(margin.Sales_Mgn_AGO_B7__c == null)
                                margin.Sales_Mgn_AGO_B7__c = 0;
                            if(margin.Sales_Mgn_IGO_50ppm__c == null)
                                margin.Sales_Mgn_IGO_50ppm__c = 0;
                            if(margin.Sales_Mgn_ULG95_E5__c == null)
                                margin.Sales_Mgn_ULG95_E5__c = 0;
                            //END - Rahul Sharma | Date: 20-Janv-21 : Fixed null pointer exception.
                            System.debug('RV_CspTriggerHelper >> validateCsp >> cspPrice: '+cspPrice+' csp.Grade__c: '+csp.Grade__c);
                            System.debug('RV_CspTriggerHelper >> validateCsp >> margin.Sales_Mgn_AGO_B7__c: '+margin.Sales_Mgn_AGO_B7__c+' margin.Sales_Mgn_IGO_50ppm__c: '+margin.Sales_Mgn_IGO_50ppm__c+' margin.Sales_Mgn_ULG95_E5__c'+margin.Sales_Mgn_ULG95_E5__c);
                            if(csp.Grade__c == 'AGO B7' && (csp.CSP_Eur_100L__c + margin.Sales_Mgn_AGO_B7__c) < 0){
                                csp.addError('Invalid input. Addition of Sales Margin and Customer Specific Pricing cannot be less than zero.');
                            }
                            else if(csp.Grade__c == 'IGO 50ppm' && (csp.CSP_Eur_100L__c + margin.Sales_Mgn_IGO_50ppm__c) < 0){
                                csp.addError('Invalid input. Addition of Sales Margin and Customer Specific Pricing cannot be less than zero.');
                            }
                            else if(csp.Grade__c == 'ULG95 E5' && (csp.CSP_Eur_100L__c + margin.Sales_Mgn_ULG95_E5__c) < 0){
                                csp.addError('Invalid input. Addition of Sales Margin and Customer Specific Pricing cannot be less than zero.');
                            }
                        }
                    }
                }
            }
        }
    }

}