force-app/main/default/objects/Order/fields/GSAP_Status__c.field-meta.xml
<CustomField>
    <fullName>GSAP_Status__c</fullName>
    <label>GSAP Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Queue</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed to Process</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Resent</fullName>
            </value>
            <value>
                <fullName>No GSAP Response</fullName>
            </value>
            <value>
                <fullName>Stuck in Queue</fullName>
            </value>
            <value>
                <fullName>Sent Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/TCP_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>TCP_Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Approved (M)</fullName>
            </value>
            <value>
                <fullName>Approved (C)</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TCP_OrderStatusAlertSchedulerTest.cls
@isTest
public class TCP_OrderStatusAlertSchedulerTest {
	@TestSetup
    static void createTestData() {       
    	List<Account> accList = TCP_TestDataUtilities.createAccounts(1, true);
        TCP_TestDataUtilities.createOrders(4, accList[0]);
       
    }
    
    @isTest
    static  void testScheduledJob() {
        List<Order> ordList = [Select id from Order];
        ordList[0].TCP_Order_Status__c = 'Approved';
        ordList[0].GSAP_Status__c = 'No GSAP Response';
        update ordList;
        
        String cronExp = '0 0 * * * ?';
        Test.startTest();      
        System.schedule('Order Status Alert job 1 Test',cronExp,new TCP_OrderStatusAlertScheduler());        
        Test.stopTest();
        System.assert(true);
    }
}