force-app/main/default/objects/Order/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Sold To)</relationshipLabel>
    <relationshipName>Sold_To_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/TCP_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>TCP_Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Approved (M)</fullName>
            </value>
            <value>
                <fullName>Approved (C)</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TCP_OrderLineItem__c/TCP_OrderLineItem__c.object-meta.xml
<CustomObject>
    <description>This object hold the line item details</description>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/TCP_OrderSearchControllerTest.cls
@isTest
public class TCP_OrderSearchControllerTest{

    @TestSetup
    public static void createTestData() {
        List<Account> testAccounts=TCP_TestDataUtilities.createAccounts(1,false);
        for(Account testAccount:testAccounts){
            List<contact> testContact=TCP_TestDataUtilities.createContacts(1,testAccount);
            List<Order> testOrders=TCP_TestDataUtilities.createOrders(1,testAccount);
                for(Order testOrder:testOrders){
                    List<TCP_OrderLineItem__c> testOrderLineItem=TCP_TestDataUtilities.createOrderLineItems(1,testOrder);
                }
        }
    }
    @isTest
    public static void testGetOrderDetailsBySearchKey(){
        List<Order> testOrderRec=new List<Order>([select id,ordernumber,Name,Sold_To__c,TCP_Order_Status__c,Accountid from order where TCP_Order_Status__c ='Submitted' limit 1]);
        Test.startTest();
        List<TCP_OrderWrapper> resp = TCP_OrderSearchController.getOrderDetailsBySearchKey(testOrderRec[0].Sold_To__c,testOrderRec[0].Name,'Draft;Submitted','Comm Ops User','Previous Orders');
        List<TCP_OrderWrapper> resp2 = TCP_OrderSearchController.getOrderDetailsBySearchKey(testOrderRec[0].Sold_To__c,testOrderRec[0].Name,'Submitted','End User','Previous Orders');
        Test.stopTest();
        System.Assert(resp.size()>0);
        System.Assert(resp2.size()>0);
    }
}