force-app/main/default/objects/RE_Field_Value_Mappings__c/RE_Field_Value_Mappings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used for Field Value mappings in Revolution</description>
    <label>RE Field Value Mappings</label>
</CustomObject>

force-app/main/default/objects/RE_Job_Run_Audit__c/RE_Job_Run_Audit__c.object-meta.xml
<CustomObject>
    <label>Job Run Audit</label>
    <nameField>
        <displayFormat>JR-{00000000}</displayFormat>
        <label>Job Run Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Run Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_JobControls__c/RE_JobControls__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting to enable/disable functions in classes</description>
    <label>RE Job Controls</label>
</CustomObject>

force-app/main/default/objects/RE_Market_Quotes__c/RE_Market_Quotes__c.object-meta.xml
<CustomObject>
    <label>RE Market Quotes</label>
    <nameField>
        <displayFormat>MarketQuote-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Market Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_CND_Daily_Racks_Raw_Date__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_Daily_Racks_Raw_Date__c</fullName>
    <label>Daily Racks Raw Date</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_CND_Rack__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_Rack__c</fullName>
    <label>Rack</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Price__c.field-meta.xml
<CustomField>
    <fullName>RE_Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Quote_Source__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Source__c</fullName>
    <label>Quote Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OPIS</fullName>
            </value>
            <value>
                <fullName>ZEMA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Type__c</fullName>
    <label>Quote Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Market Premium</fullName>
            </value>
            <value>
                <fullName>Assessed Premium</fullName>
            </value>
            <value>
                <fullName>Midday</fullName>
            </value>
            <value>
                <fullName>Forward Swap</fullName>
            </value>
            <value>
                <fullName>Spot</fullName>
            </value>
            <value>
                <fullName>Freight</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/recordTypes/Canada_Competitor.recordType-meta.xml
<RecordType>
    <fullName>Canada_Competitor</fullName>
    <active>true</active>
    <description>Record type for Uploaded Revolution Canada Competitor Data</description>
    <label>Canada Competitor</label>
</RecordType>

force-app/main/default/objects/RE_Market_Quotes__c/recordTypes/Canada_OPIS_Spot_Ticker.recordType-meta.xml
<RecordType>
    <fullName>Canada_OPIS_Spot_Ticker</fullName>
    <active>true</active>
    <description>Record type for Uploaded Revolution Canada Live OPIS Spot Ticker</description>
    <label>Canada OPIS Spot Ticker</label>
</RecordType>

force-app/main/default/objects/RE_MY_CostPrice__c/RE_MY_CostPrice__c.object-meta.xml
<CustomObject>
    <label>Cost Price</label>
    <nameField>
        <displayFormat>RE-MY-C{000000}</displayFormat>
        <label>Costing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Price</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_MY_CostPrice__c/fields/RE_CND_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_Product_Group__c</fullName>
    <label>Product Group</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/fields/RE_CND_Supplier2_Price__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_Supplier2_Price__c</fullName>
    <description>Revolution Canada Competitor Suncor Price</description>
    <label>Suncor</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/fields/RE_CND_Supplier3_Price__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_Supplier3_Price__c</fullName>
    <description>Revolution Canada Competitor Valero Price</description>
    <label>Valero</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/fields/RE_CND_Supplier4_Price__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_Supplier4_Price__c</fullName>
    <label>Parkland</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/recordTypes/Canada.recordType-meta.xml
<RecordType>
    <fullName>Canada</fullName>
    <active>true</active>
    <label>Canada</label>
</RecordType>

force-app/main/default/objects/RE_Pricing_Input_STG__c/RE_Pricing_Input_STG__c.object-meta.xml
<CustomObject>
    <label>RE Pricing Input STG</label>
    <nameField>
        <displayFormat>RPI-{0000000000}</displayFormat>
        <label>Pricing Input STG Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Pricing Input STG</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Pricing_Input_STG__c/fields/RE_CND_Brand_Indicator__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_Brand_Indicator__c</fullName>
    <label>Brand Indicator</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Pricing_Input_STG__c/fields/RE_CND_City_Code__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_City_Code__c</fullName>
    <label>City Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Pricing_Input_STG__c/fields/RE_CND_City_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_City_Name__c</fullName>
    <label>City Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Pricing_Input_STG__c/fields/RE_CND_Move_Value__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_Move_Value__c</fullName>
    <label>Move Value</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Pricing_Input_STG__c/fields/RE_CND_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_Product_Group__c</fullName>
    <label>Product Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Pricing_Input_STG__c/fields/RE_CND_Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_Quote_Name__c</fullName>
    <label>Quote Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Pricing_Input_STG__c/fields/RE_CND_Supplier_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_CND_Supplier_Name__c</fullName>
    <label>Supplier Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Pricing_Input_STG__c/fields/RE_Default_Currency__c.field-meta.xml
<CustomField>
    <fullName>RE_Default_Currency__c</fullName>
    <label>Default Currency</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Pricing_Input_STG__c/fields/RE_Pricing_Date__c.field-meta.xml
<CustomField>
    <fullName>RE_Pricing_Date__c</fullName>
    <label>Pricing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_Pricing_Input_STG__c/fields/RE_Quote_Source__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Source__c</fullName>
    <label>Quote Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Pricing_Input_STG__c/fields/RE_Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Type__c</fullName>
    <label>Quote Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Pricing_Input_STG__c/fields/RE_Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>RE_Unit_of_Measure__c</fullName>
    <label>Unit of Measure</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Pricing_Input_STG__c/fields/RE_Validity_Month__c.field-meta.xml
<CustomField>
    <fullName>RE_Validity_Month__c</fullName>
    <label>Validity Month</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Pricing_Input_STG__c/recordTypes/Canada_Competitor.recordType-meta.xml
<RecordType>
    <fullName>Canada_Competitor</fullName>
    <active>true</active>
    <description>Record type for Revolution Canada Daily Racks Raw Early Upload</description>
    <label>Canada Competitor</label>
</RecordType>

force-app/main/default/objects/RE_Pricing_Input_STG__c/recordTypes/Canada_OPIS_Spot_Ticker.recordType-meta.xml
<RecordType>
    <fullName>Canada_OPIS_Spot_Ticker</fullName>
    <active>true</active>
    <description>Record type for Revolution Canada OPIS Spot Ticker Upload</description>
    <label>Canada OPIS Spot Ticker</label>
</RecordType>

force-app/main/default/classes/RE_PricingInputSTGTriggerHelper_Test.cls
/**************************************************************************************************
* Name: RE_PricingInputSTGTriggerHelper_Test
* Object: RE_Market_Quotes__c
* Purpose: Pricing Input Staging for Revolution Test Class
* Author: Abhilash KT (abhilash.kt@shell.com)
* Create Date: 2021-09-01
* Modify History: 
* 2021-09-01		Abhilash		Created
**************************************************************************************************/
@isTest
public class RE_PricingInputSTGTriggerHelper_Test {
    
    
    @testSetup static void setup() { 
      
    }
    
    @isTest
    static void procingPricingInputStgData_Competitor_Test()
    {
        Test.startTest();
        
        RE_JobControls__c jobControl =  RE_CND_TestDataFactory.createJobControlSetting('JC1','RE_CND_PricingInputStaging','processCompetitorData','Canada',true); 
        RE_Job_Run_Audit__c jra = RE_CND_TestDataFactory.createJobRunAudit('Manual','Canada Competitor Data Processing','CA'); 
        RE_Field_Value_Mappings__c fmvPg =  RE_CND_TestDataFactory.createFieldValueMappings('fmvPg','Canada','Competitor Data Import','RE_MY_CostPrice__c','RE_CND_Product_Group__c','Pre','Premium',True);
        RE_Field_Value_Mappings__c fmvPg1 =  RE_CND_TestDataFactory.createFieldValueMappings('fmvPg1','Canada','Competitor Data Import','RE_MY_CostPrice__c','RE_CND_Product_Group__c','Unl','RUG',True); 
        RE_Field_Value_Mappings__c fmvRk =  RE_CND_TestDataFactory.createFieldValueMappings('fmvRk','Canada','Competitor Data Import','RE_MY_CostPrice__c','RE_CND_Rack__c','EDMONTON','Edmonton',True);
        RE_Field_Value_Mappings__c fmvRk1 =  RE_CND_TestDataFactory.createFieldValueMappings('fmvRk1','Canada','Competitor Data Import','RE_MY_CostPrice__c','RE_CND_Rack__c','CALGARY','Calgary',True);      
        RE_Field_Value_Mappings__c fmvSupp1 =  RE_CND_TestDataFactory.createFieldValueMappings('fmvSupp1','Canada','Competitor Data Import','RE_MY_CostPrice__c','RE_CND_Supplier1_Price__c','Supplier1','Esso Canada',True);
        RE_Field_Value_Mappings__c fmvSupp2 =  RE_CND_TestDataFactory.createFieldValueMappings('fmvSupp2','Canada','Competitor Data Import','RE_MY_CostPrice__c','RE_CND_Supplier2_Price__c','Supplier2','Suncor',True);
        RE_Field_Value_Mappings__c fmvSupp3 =  RE_CND_TestDataFactory.createFieldValueMappings('fmvSupp3','Canada','Competitor Data Import','RE_MY_CostPrice__c','RE_CND_Supplier3_Price__c','Supplier3','Valero',True);
        RE_Field_Value_Mappings__c fmvSupp4 =  RE_CND_TestDataFactory.createFieldValueMappings('fmvSupp4','Canada','Competitor Data Import','RE_MY_CostPrice__c','RE_CND_Supplier4_Price__c','Supplier4','Parkland',True);

        Id competitorRecordTypeId = Schema.SObjectType.RE_Pricing_Input_STG__c.getRecordTypeInfosByDeveloperName().get('Canada_Competitor').getRecordTypeId();
        List<RE_MY_CostPrice__c> newCostPriceDataList = RE_CND_TestDataFactory.createCostPriceData(); 
        List<RE_Pricing_Input_STG__c> newCompetitorDataList = RE_CND_TestDataFactory.createCompetitorData(); 
        
        List<RE_Pricing_Input_STG__c> newCompeDataList = [Select RE_CND_Daily_Racks_Raw_Date__c,RE_CND_City_Code__c, RE_CND_City_Name__c,RE_CND_Supplier_Name__c,RE_CND_Brand_Indicator__c,
                                                          RE_CND_Product_Group__c,RE_Price__c, RE_CND_Move_Value__c,RE_Pricing_Date__c,RE_Default_Currency__c,RE_Unit_of_Measure__c from RE_Pricing_Input_STG__c
                                                          where RecordTypeId =: competitorRecordTypeId];
        
        RE_CND_PricingInputStaging.processCompetitorData(newCompeDataList);
        
        Test.stopTest();
    }   
    
    @isTest
    static void processingLiveOPISSpotTicker_Test()
    {
        Test.startTest();
        Id opisRecordTypeId = Schema.SObjectType.RE_Pricing_Input_STG__c.getRecordTypeInfosByDeveloperName().get('Canada_OPIS_Spot_Ticker').getRecordTypeId(); 
        RE_JobControls__c jobControl1 =  RE_CND_TestDataFactory.createJobControlSetting('JC2','RE_CND_PricingInputStaging','processingLiveOPISSpotTicker','Canada',true); 
        RE_Job_Run_Audit__c jra1 = RE_CND_TestDataFactory.createJobRunAudit('Manual','Canada Live OPIS Spot Ticker Processing','CA'); 
        List<RE_Pricing_Input_STG__c> newCompetitorDataList = RE_CND_TestDataFactory.createOPISspotTickerData();       
        
        List<RE_Pricing_Input_STG__c> newOPISDataList = [Select RE_CND_Quote_Name__c,RE_Price__c,RE_Validity_Month__c,RE_Pricing_Date__c,
                                                         RE_Default_Currency__c,RE_Unit_of_Measure__c,RE_Quote_Type__c,RE_Quote_Source__c
                                                         from RE_Pricing_Input_STG__c where RecordTypeId =: opisRecordTypeId]; 
        
        RE_CND_PricingInputStaging.processingLiveOPISSpotTicker(newOPISDataList);        
        
        Test.stopTest(); 
    }  
    
}