force-app/main/default/objects/BET_BDD_Address__c/BET_BDD_Address__c.object-meta.xml
<CustomObject>
    <label>BDD Address</label>
    <nameField>
        <displayFormat>BA-{0000}</displayFormat>
        <label>BET Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDD Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BET_BDD_Address__c/fields/AddLine1__c.field-meta.xml
<CustomField>
    <fullName>AddLine1__c</fullName>
    <label>* Address Line 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BET_BDD_Address__c/fields/Address_Type__c.field-meta.xml
<CustomField>
    <fullName>Address_Type__c</fullName>
    <inlineHelpText>**Required Address Types** GoldTier: All Regions = Legal and Operating | MDN: WONA = Registered | SENA = Legal | STUSCO = Invoice</inlineHelpText>
    <label>* Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>***WONA***</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Trading</fullName>
            </value>
            <value>
                <fullName>***SENA***</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>***STUSCO***</fullName>
            </value>
            <value>
                <fullName>Main</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>**WONA &amp; STUSCO**</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>**STUSCO &amp; SENA**</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>**All Regions**</fullName>
            </value>
            <value>
                <fullName>Contracts</fullName>
            </value>
            <value>
                <fullName>Operating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BET_BDD_Address__c/fields/BDD_Form__c.field-meta.xml
<CustomField>
    <fullName>BDD_Form__c</fullName>
    <label>BDD Form</label>
    <referenceTo>BET_BDD_Form__c</referenceTo>
    <relationshipLabel>BDD Address List</relationshipLabel>
    <relationshipName>BDD_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BET_BDD_Address__c/fields/BusLine__c.field-meta.xml
<CustomField>
    <fullName>BusLine__c</fullName>
    <label>* Business Line (WONA &amp; SENA Only)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>COAL</fullName>
            </value>
            <value>
                <fullName>CREDIT PARENT LINE</fullName>
            </value>
            <value>
                <fullName>Crude (Derivatives)</fullName>
            </value>
            <value>
                <fullName>Crude (Physical)</fullName>
            </value>
            <value>
                <fullName>Crude Freight</fullName>
            </value>
            <value>
                <fullName>EMISSIONS</fullName>
            </value>
            <value>
                <fullName>FINANCIAL LNG</fullName>
            </value>
            <value>
                <fullName>GAS &amp; POWER</fullName>
            </value>
            <value>
                <fullName>GAS &amp; POWER DERIVATIVES</fullName>
            </value>
            <value>
                <fullName>GENERAL &amp; ADMINISTRATIVE VENDOR</fullName>
            </value>
            <value>
                <fullName>LNG Freight</fullName>
            </value>
            <value>
                <fullName>LNG SHIPPING</fullName>
            </value>
            <value>
                <fullName>OIL DERIVATIVES - Do Not Use</fullName>
            </value>
            <value>
                <fullName>OIL SHIPPING</fullName>
            </value>
            <value>
                <fullName>PHYSICAL LNG</fullName>
            </value>
            <value>
                <fullName>PHYSICAL OIL - Do Not Use</fullName>
            </value>
            <value>
                <fullName>Products (Derivatives)</fullName>
            </value>
            <value>
                <fullName>Products (Physical)</fullName>
            </value>
            <value>
                <fullName>Products Freight</fullName>
            </value>
            <value>
                <fullName>NA Credit System</fullName>
            </value>
            <value>
                <fullName>NA Emissions Carbon</fullName>
            </value>
            <value>
                <fullName>NA Emissions Non-Carbon</fullName>
            </value>
            <value>
                <fullName>NA G&amp;A</fullName>
            </value>
            <value>
                <fullName>NA Gas</fullName>
            </value>
            <value>
                <fullName>NA Power</fullName>
            </value>
            <value>
                <fullName>NA Risk Gas</fullName>
            </value>
            <value>
                <fullName>NA Risk Others</fullName>
            </value>
            <value>
                <fullName>NA Risk Power</fullName>
            </value>
            <value>
                <fullName>NA Scheduling Only</fullName>
            </value>
            <value>
                <fullName>North America LNG</fullName>
            </value>
            <value>
                <fullName>Crude</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BET_BDD_Address__c/fields/Same_TR_AND_REGAdd__c.field-meta.xml
<CustomField>
    <fullName>Same_TR_AND_REGAdd__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is Trading Address and Registered Address are same?</inlineHelpText>
    <label>Same as Registered/Trading Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BET_BDD_Address__c/fields/SameAs_LegAdd__c.field-meta.xml
<CustomField>
    <fullName>SameAs_LegAdd__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Same as Legal/Operating Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BET_BDD_Address__c/recordTypes/GOLDTIER.recordType-meta.xml
<RecordType>
    <fullName>GOLDTIER</fullName>
    <active>true</active>
    <label>GOLDTIER</label>
</RecordType>

force-app/main/default/objects/BET_BDD_Address__c/recordTypes/MDN.recordType-meta.xml
<RecordType>
    <fullName>MDN</fullName>
    <active>true</active>
    <label>MDN</label>
</RecordType>

force-app/main/default/objects/BET_BDD_Form__c/BET_BDD_Form__c.object-meta.xml
<CustomObject>
    <label>BDD Form</label>
    <nameField>
        <displayFormat>BD-{000}</displayFormat>
        <label>BDD Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDD Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BET_BDD_Form__c/fields/MDN_OI_Business_Roles__c.field-meta.xml
<CustomField>
    <fullName>MDN_OI_Business_Roles__c</fullName>
    <label>* Business Roles</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aggregators</fullName>
            </value>
            <value>
                <fullName>BANK</fullName>
            </value>
            <value>
                <fullName>BROKER</fullName>
            </value>
            <value>
                <fullName>Bunker Fuel End User</fullName>
            </value>
            <value>
                <fullName>BUNKERS BROKER</fullName>
            </value>
            <value>
                <fullName>C&amp;I</fullName>
            </value>
            <value>
                <fullName>CARGO INSPECTOR</fullName>
            </value>
            <value>
                <fullName>CASH MARGINING</fullName>
            </value>
            <value>
                <fullName>CEM</fullName>
            </value>
            <value>
                <fullName>CHARTERER</fullName>
            </value>
            <value>
                <fullName>CLEARHOUSE</fullName>
            </value>
            <value>
                <fullName>COSTS (DEX &amp; SAP)</fullName>
            </value>
            <value>
                <fullName>DIRECT CONSULTANTS</fullName>
            </value>
            <value>
                <fullName>DISP OFC</fullName>
            </value>
            <value>
                <fullName>DISTRIBTR</fullName>
            </value>
            <value>
                <fullName>END USER</fullName>
            </value>
            <value>
                <fullName>ESP</fullName>
            </value>
            <value>
                <fullName>EXCHANGE</fullName>
            </value>
            <value>
                <fullName>FED GOVT</fullName>
            </value>
            <value>
                <fullName>FED PWR MK</fullName>
            </value>
            <value>
                <fullName>G&amp;A VENDOR</fullName>
            </value>
            <value>
                <fullName>G&amp;T</fullName>
            </value>
            <value>
                <fullName>GENERAL SHIPPING SERVICE</fullName>
            </value>
            <value>
                <fullName>Generator</fullName>
            </value>
            <value>
                <fullName>GOVERNMENT ENTITY</fullName>
            </value>
            <value>
                <fullName>GOVERNMENT INTERMEDIARIES</fullName>
            </value>
            <value>
                <fullName>GUARANTOR / PARENT ACCOUNT ONLY</fullName>
            </value>
            <value>
                <fullName>IBT</fullName>
            </value>
            <value>
                <fullName>INDIRECT CONSULTANTS</fullName>
            </value>
            <value>
                <fullName>INDUSTRIAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BET_BDDAddressTriggerHelperTest.cls
@isTest
public class BET_BDDAddressTriggerHelperTest {
    static testmethod void testsameAsLegalAddressUpdate(){
        recordtype rc1 = [SELECT Id,Name FROM RecordType WHERE SObjectType = 'BET_BDD_Address__c' and developername = 'GOLDTIER' limit 1];
        recordtype rc2 = [SELECT Id,Name FROM RecordType WHERE SObjectType = 'BET_BDD_Address__c' and developername = 'MDN' limit 1];
          Id docRecTypeIdSena = Schema.SObjectType.BET_BDD_Form__c.getRecordTypeInfosByDeveloperName().get('WONA_NEW_CPTBNK').getRecordTypeId();
        BET_BDD_Form__c bddForm=BET_BDD_SearchController_TestDataFactory.createBDDForm('WONA','Bank','New Onboard');
       bddForm.RecordTypeId = docRecTypeIdSena;
       bddForm.MDN_OI_Business_Roles__c ='BANK';
        insert bddForm;
        BET_BDD_Address__c addRec = new BET_BDD_Address__c(BDD_Form__c = bddForm.Id,Address_Type__c = 'Registered',Same_TR_AND_REGAdd__c = True,RecordTypeId=rc2.id);
        try{
            insert addRec;}
        catch(Exception e){
            System.debug(e);}
        BET_BDD_Address__c addRec1 = new BET_BDD_Address__c(BDD_Form__c = bddForm.Id,Address_Type__c = 'Legal',SameAs_LegAdd__c = True,RecordTypeId=rc1.id);
        insert addRec1;
        BET_BDD_Address__c addRec2 = new BET_BDD_Address__c(BDD_Form__c = bddForm.Id,Address_Type__c = 'Billing',SameAs_LegAdd__c = True,RecordTypeId=rc2.id,Same_TR_AND_REGAdd__c = True);
        try{
            insert addRec2;}
        catch(Exception e){
            System.debug(e);}
        BET_BDD_Address__c addRec3 = new BET_BDD_Address__c(BDD_Form__c = bddForm.Id,Address_Type__c = 'Invoice',SameAs_LegAdd__c = True,RecordTypeId=rc2.id);
        try{
            insert addRec3;}
        catch(Exception e){
            System.debug(e);}
        BET_BDD_Address__c addRec4 = new BET_BDD_Address__c(BDD_Form__c = bddForm.Id,Address_Type__c = 'Invoice',Same_TR_AND_REGAdd__c = True,RecordTypeId=rc2.id);
        try{
            insert addRec4;}
        catch(Exception e){
            System.debug(e);}
        bddForm.RecordTypeId = Schema.SObjectType.BET_BDD_Form__c.getRecordTypeInfosByName().get('WONA NEW CPT/BANK FORM').getRecordTypeId();
        try{
            update bddForm;}
        catch(Exception e){
            System.debug(e);}
        BET_BDD_Address__c addRec5 = new BET_BDD_Address__c(BDD_Form__c = bddForm.Id,Address_Type__c = 'Registered',BusLine__c = 'Crude',RecordTypeId=rc2.id);
        try{
            insert addRec5;
            addRec5.AddLine1__c = 'test';
            update addRec5;}
        catch(Exception e){
            System.debug(e);} 
    }
    
}