force-app/main/default/objects/RE_Bio_Quotes__c/RE_Bio_Quotes__c.object-meta.xml
<CustomObject>
    <label>RE Bio Quotes</label>
    <nameField>
        <displayFormat>BioQuote-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Bio Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Bio_Quotes__c/fields/RE_Bio_Quotes_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Bio_Quotes_Name__c</fullName>
    <label>Bio Quotes Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Bio_Quotes__c/fields/RE_Bio_RateUnit__c.field-meta.xml
<CustomField>
    <fullName>RE_Bio_RateUnit__c</fullName>
    <label>Rate Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RE_Rate_Unit_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Bio_Quotes__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipName>Bio_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Bio_Quotes__c/fields/RE_Price__c.field-meta.xml
<CustomField>
    <fullName>RE_Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Bio_Quotes__c/fields/RE_Pricing_Date__c.field-meta.xml
<CustomField>
    <fullName>RE_Pricing_Date__c</fullName>
    <label>Pricing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_Bio_Quotes__c/recordTypes/Malaysia.recordType-meta.xml
<RecordType>
    <fullName>Malaysia</fullName>
    <active>true</active>
    <label>Malaysia</label>
</RecordType>

force-app/main/default/objects/RE_Bio_Quotes__c/recordTypes/Thailand.recordType-meta.xml
<RecordType>
    <fullName>Thailand</fullName>
    <active>true</active>
    <label>Thailand</label>
</RecordType>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/RE_Depot_Pricing_Backbone__c.object-meta.xml
<CustomObject>
    <label>Depot Pricing Backbone</label>
    <nameField>
        <displayFormat>DPB-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depot Pricing Backbone</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Depot_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Depot_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Depot Name</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Final_Price_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Final_Price_Unit__c</fullName>
    <label>Final Price Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RE_Rate_Unit_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/recordTypes/Malaysia.recordType-meta.xml
<RecordType>
    <fullName>Malaysia</fullName>
    <active>true</active>
    <label>Malaysia</label>
</RecordType>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/recordTypes/Thailand.recordType-meta.xml
<RecordType>
    <fullName>Thailand</fullName>
    <active>true</active>
    <description>Use for Thailand CBU calculation</description>
    <label>Thailand</label>
</RecordType>

force-app/main/default/objects/RE_Job_Run_Audit__c/RE_Job_Run_Audit__c.object-meta.xml
<CustomObject>
    <label>Job Run Audit</label>
    <nameField>
        <displayFormat>JR-{00000000}</displayFormat>
        <label>Job Run Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Run Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Country_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Country_Name__c</fullName>
    <label>Country Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RT_Revolution_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Exception__c.field-meta.xml
<CustomField>
    <fullName>RE_Exception__c</fullName>
    <label>Exception</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_IsSuccess__c.field-meta.xml
<CustomField>
    <fullName>RE_IsSuccess__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSuccess</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Job_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Malaysia Output</fullName>
            </value>
            <value>
                <fullName>Singapore Output</fullName>
            </value>
            <value>
                <fullName>SG Midday Output</fullName>
            </value>
            <value>
                <fullName>Malaysia AMV Output</fullName>
            </value>
            <value>
                <fullName>Thailand Output</fullName>
            </value>
            <value>
                <fullName>CustomerOps Output</fullName>
            </value>
            <value>
                <fullName>New Contract Pricing Output</fullName>
            </value>
            <value>
                <fullName>Thailand AMV Output</fullName>
            </value>
            <value>
                <fullName>MY Export Report</fullName>
            </value>
            <value>
                <fullName>MY Customer Opps CBU</fullName>
            </value>
            <value>
                <fullName>Philippines Output</fullName>
            </value>
            <value>
                <fullName>Canada Daily Reuters Quote Move</fullName>
            </value>
            <value>
                <fullName>Canada Execute Depo Pricing</fullName>
            </value>
            <value>
                <fullName>Canada Pricing Recalculation</fullName>
            </value>
            <value>
                <fullName>Canada SFJ Record Creation</fullName>
            </value>
            <value>
                <fullName>Canada Live OPIS Spot Ticker Processing</fullName>
            </value>
            <value>
                <fullName>Canada Market Move Calculation</fullName>
            </value>
            <value>
                <fullName>Canada Competitor Data Processing</fullName>
            </value>
            <value>
                <fullName>Canada GSAP Upload</fullName>
            </value>
            <value>
                <fullName>Canada Email Output</fullName>
            </value>
            <value>
                <fullName>MY Data Analysis Report</fullName>
            </value>
            <value>
                <fullName>PH Customer Opps CBU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/RE_Market_Quotes__c.object-meta.xml
<CustomObject>
    <label>RE Market Quotes</label>
    <nameField>
        <displayFormat>MarketQuote-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Market Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipName>Market_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Price__c.field-meta.xml
<CustomField>
    <fullName>RE_Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Name__c</fullName>
    <label>Quote Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Rate_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Rate_Unit__c</fullName>
    <label>Rate Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RE_Rate_Unit_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/RE_MY_CostPrice__c.object-meta.xml
<CustomObject>
    <label>Cost Price</label>
    <nameField>
        <displayFormat>RE-MY-C{000000}</displayFormat>
        <label>Costing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Price</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_MY_CostPrice__c/fields/RE_Additive_Cost__c.field-meta.xml
<CustomField>
    <fullName>RE_Additive_Cost__c</fullName>
    <label>Additive Cost</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/fields/RE_Costprice_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Costprice_Unit__c</fullName>
    <label>Cost Price Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RE_Rate_Unit_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipName>Costing_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/fields/RE_Depot_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Depot_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Depot Name</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipName>Costing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/fields/RE_Job_Run_Count__c.field-meta.xml
<CustomField>
    <fullName>RE_Job_Run_Count__c</fullName>
    <label>Job Run Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/fields/RE_Oil_Loss__c.field-meta.xml
<CustomField>
    <fullName>RE_Oil_Loss__c</fullName>
    <label>Oil Loss</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/fields/RE_Primary_Transport_Cost__c.field-meta.xml
<CustomField>
    <fullName>RE_Primary_Transport_Cost__c</fullName>
    <label>Primary Transport Cost</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/fields/RE_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipName>Costing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/fields/RE_Storage_Handling_Cost__c.field-meta.xml
<CustomField>
    <fullName>RE_Storage_Handling_Cost__c</fullName>
    <label>Storage &amp; Handling Cost</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/recordTypes/Malaysia.recordType-meta.xml
<RecordType>
    <fullName>Malaysia</fullName>
    <active>true</active>
    <label>Malaysia</label>
</RecordType>

force-app/main/default/objects/RE_MY_CostPrice__c/recordTypes/Thailand.recordType-meta.xml
<RecordType>
    <fullName>Thailand</fullName>
    <active>true</active>
    <label>Thailand</label>
</RecordType>

force-app/main/default/objects/RE_Product__c/RE_Product__c.object-meta.xml
<CustomObject>
    <label>RE Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Product__c/fields/RE_Additive_Cost__c.field-meta.xml
<CustomField>
    <fullName>RE_Additive_Cost__c</fullName>
    <label>Additive Cost</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipName>Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_Country_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Country_Name__c</fullName>
    <label>Country Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RT_Revolution_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Product__c/recordTypes/Malaysia.recordType-meta.xml
<RecordType>
    <fullName>Malaysia</fullName>
    <active>true</active>
    <label>Malaysia</label>
</RecordType>

force-app/main/default/objects/RE_Product__c/recordTypes/Thailand.recordType-meta.xml
<RecordType>
    <fullName>Thailand</fullName>
    <active>true</active>
    <label>Thailand</label>
</RecordType>

force-app/main/default/globalValueSets/RE_Rate_Unit_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MYR CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/TON</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>USD/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>USD/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>USD/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>BBL</fullName>
    </customValue>
    <customValue>
        <fullName>LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR</fullName>
    </customValue>
    <customValue>
        <fullName>THB/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>STG/LTR</fullName>
    </customValue>
    <description>Rate Units to be used in  Revolution East Applicaion</description>
    <masterLabel>RE_Rate_Unit_Set</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/RT_Revolution_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TU</fullName>
        <label>Turkey</label>
    </customValue>
    <customValue>
        <fullName>MY</fullName>
        <label>Malaysia</label>
    </customValue>
    <customValue>
        <fullName>TH</fullName>
        <label>Thailand</label>
    </customValue>
    <customValue>
        <fullName>PH</fullName>
        <label>Philippines</label>
    </customValue>
    <customValue>
        <fullName>SG</fullName>
        <label>Singapore</label>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
        <label>Canada</label>
    </customValue>
    <masterLabel>Revolution Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RE_TH_CostCalculation.cls
public class RE_TH_CostCalculation { 
    RE_SOQLController soqldata = new RE_SOQLController();
    //Get latest Depot pricing data
    public List<RE_Depot_Pricing_Backbone__c> thailandCCList = soqldata.fetchTHDepoPricingData();
    //Get Market Quotes Data
    public List<RE_Market_Quotes__c> latestmarketquotes = soqldata.fetchMarketQuotesTHData();
    //Get (HDGO,GTL,POME,ETHANOL) Quotes Data for Malaysia
    public List<RE_Bio_Quotes__c> latestbioquotes = soqldata.fetchThailandQuotesData('Thailand');
    //Get Malaysia product data
    public List<RE_Product__c> prodlist = RE_SOQLController.fetchThailandprodData('Thailand');
    //Get Latest Fx Data
    public Map<String,Double> curConvMap = soqldata.fetchLatestMidFxData();
    public List<RE_MY_FormulaFetchController.formulaWrapper> formWrapList = new List<RE_MY_FormulaFetchController.formulaWrapper>();

    public List<RE_MY_FormulaFetchController.formulaWrapperTH> formWrapListTH = new List<RE_MY_FormulaFetchController.formulaWrapperTH>();
	
    public RE_UtilitywrapperController.lineitemwraapper finalhcval;
   // public RE_UtilitywrapperController.lineitemwraapper finalbioval;
   // public RE_UtilitywrapperController.lineitemwraapper finaltppval;
   // public RE_UtilitywrapperController.lineitemwraapper finalmpval;
   // public RE_UtilitywrapperController.lineitemwraapper finalbbpval;
    public RE_UtilitywrapperController.lineitemwraapper finalrstval;		//sales tax
    public RE_UtilitywrapperController.lineitemwraapper finalsahval;
   // public RE_UtilitywrapperController.lineitemwraapper finalmasval;
   // public RE_UtilitywrapperController.lineitemwraapper finalslpval;
    public RE_UtilitywrapperController.lineitemwraapper finalolval;
    public RE_UtilitywrapperController.lineitemwraapper finalptval;
   // public RE_UtilitywrapperController.lineitemwraapper finalmrfval;
   // public RE_UtilitywrapperController.lineitemwraapper finalbolval;
   // public RE_UtilitywrapperController.lineitemwraapper finalpcval;  // port charges
    public RE_UtilitywrapperController.lineitemwraapper finalacval;		//aditive cost
    public Map<Id, Double> finalmccval = new Map<Id, Double>();
    public Map<Id,Double> laiddownCostMap = new Map<Id,Double>();
    public Map<Id,Double> marginalCostMap = new Map<Id,Double>();
    Map<String, String> quoteMapes = new  Map<String, String> ();
    public String errormessage = '';

    public Boolean lineItemsCalculation(RE_Job_Run_Audit__c jra){//RE_Job_Run_Audit__c jra
        if(Test.isRunningTest()){
            curConvMap.put('THB-USD',4.3720);
            curConvMap.put('BBL-USD',4.3720);
            curConvMap.put('STG-THB',4.3720);
        }
        if(!thailandCCList.isEmpty()){ 
            
            for(RE_Bio_Quotes__c rbq : latestbioquotes){
                latestmarketquotes.add(new RE_Market_Quotes__c(RE_Price__c=rbq.RE_Price__c,RE_Pricing_Date__c=rbq.RE_Pricing_Date__c,RE_Rate_Unit__c=rbq.RE_Bio_RateUnit__c,RE_Quote_Name__c=rbq.RE_Bio_Quotes_Name__c,RE_Country_Name__c = 'SG;PH;TH;MY'));
            	quoteMapes.put(rbq.RE_Bio_Quotes_Name__c,rbq.RE_Bio_Quotes_Name__c);
            }
            //fatch data from RE_Depot_Pricing_Backbone__c for TH wrt Product,Depot
            RE_MY_FormulaFetchController ffcntrlr = new RE_MY_FormulaFetchController();
            formWrapListTH = ffcntrlr.formulaforDepotDataTH(thailandCCList);
            //HCV calculation
            RE_TH_HCVController hcvcal = new RE_TH_HCVController();
            finalhcval =  hcvcal.hcfDataPreparation(formWrapListTH,curConvMap,latestmarketquotes,prodlist,quoteMapes);
            System.debug(finalhcval);
            errormessage = errormessage + finalhcval.errorMessage;
            RE_MY_AdditiveCostController acval = new RE_MY_AdditiveCostController();
            finalacval = acval.additivecostCalculation(thailandCCList,prodlist,curConvMap);
            System.debug(finalacval);
            errormessage = errormessage + finalacval.errorMessage;
            
            RE_MY_StorageAndHandlingTariffController sahval = new RE_MY_StorageAndHandlingTariffController();
            finalsahval = sahval.shtPreparation(thailandCCList,curConvMap);
            errormessage = errormessage + finalsahval.errorMessage;
            System.debug(finalsahval);

            RE_MY_PrimaryTransportCostController ptcval = new RE_MY_PrimaryTransportCostController();
            finalptval = ptcval.primaryTransportCostpreparation(thailandCCList,curConvMap);
            errormessage = errormessage + finalptval.errorMessage;
            System.debug(finalptval);

            //List<RE_MY_FormulaFetchController.formulaWrapperTH> olformList,Map<Id, Double> finalhcval,Map<Id, Double> finalmpval,List<RE_Product__c> prodlist
            /*RE_TH_OilLossController olval = new RE_TH_OilLossController();//finalmpval.finalval
            finalolval = olval.olDataPreparation(formWrapListTH,finalhcval.finalval,prodlist);
            errormessage = errormessage + finalolval.errorMessage;
            System.debug(finalolval);*/
			
			RE_MY_RecoverySalesTaxController rcst	= new RE_MY_RecoverySalesTaxController();
			finalrstval	=	rcst.recoverySalesTaxTHPreparation(thailandCCList,curConvMap,prodlist);
			errormessage = errormessage + finalrstval.errorMessage;
            System.debug(finalrstval);
			
            marginallaidDownCostCalculation();
            finalCostingData(jra);
        }
        return false;
    }
    
    public void marginallaidDownCostCalculation(){
        //finalbbpval,finalmasval,finalslpval,finalmrfval,finalbolval,finalpcval
		
        for(RE_Depot_Pricing_Backbone__c dpbdata : thailandCCList){
            Double marginalCost = 0;
            Double laidDownCost = 0;
            if(finalhcval.finalval.containsKey(dpbdata.Id))
                marginalCost = marginalCost + finalhcval.finalval.get(dpbdata.Id);
			
            
            
            if(finalsahval.finalval.containsKey(dpbdata.Id))
                marginalCost = marginalCost + finalsahval.finalval.get(dpbdata.Id);
            if(finalptval.finalval.containsKey(dpbdata.Id))
                marginalCost = marginalCost + finalptval.finalval.get(dpbdata.Id);
			
            if(finalacval.finalval.containsKey(dpbdata.Id))
                marginalCost = marginalCost + finalacval.finalval.get(dpbdata.Id);
			/*
            if(finalolval.finalval.containsKey(dpbdata.Id))
                marginalCost = marginalCost + finalolval.finalval.get(dpbdata.Id);*/
			
			if(finalrstval.finalval.containsKey(dpbdata.Id))
                marginalCost = marginalCost + finalrstval.finalval.get(dpbdata.Id);
			
            marginalCostMap.put(dpbdata.Id, marginalCost);

            //if(finalmccval.containsKey(dpbdata.Id))
                laidDownCost = marginalCost ;//+ finalmccval.get(dpbdata.Id);
            /*if(finalmasval.finalval.containsKey(dpbdata.Id))
                laidDownCost = laidDownCost + finalmasval.finalval.get(dpbdata.Id);*/
            laiddownCostMap.put(dpbdata.Id,laidDownCost);
        }
    }
	public void finalCostingData(RE_Job_Run_Audit__c jra){
        Boolean Issuccess;
		Integer jobCount = 0;
        System.debug(String.isEmpty(errormessage)+'    '+errormessage);
        
        if(String.isEmpty(errormessage)){           
        
            List<RE_MY_CostPrice__c>costingList = new List<RE_MY_CostPrice__c>();
            List<RE_MY_CostPrice__c> updateLatestData = new List<RE_MY_CostPrice__c>();
            Id rectypeId = Schema.SObjectType.RE_MY_CostPrice__c.getRecordTypeInfosByName().get('Thailand').getRecordTypeId() ;
                List<RE_MY_CostPrice__c> costDataLatest = [SELECT RE_IsLatest__c FROM RE_MY_CostPrice__c WHERE recordtypeId = : rectypeId AND RE_IsLatest__c = True];
                if(!costDataLatest.isEmpty()){
                    for(RE_MY_CostPrice__c costMY : costDataLatest){
                        costMY.RE_IsLatest__c = False;
                        updateLatestData.add(costMY);
                    }
                }
            List<RE_Job_Run_Audit__c> costDataToday = [SELECT RE_Job_Run_Count__c FROM RE_Job_Run_Audit__c
                WHERE createddate = Today AND RE_Job_Type__c = 'Thailand Output' ORDER BY RE_Job_Run_Count__c DESC LIMIT 1];
            if(!costDataToday.isEmpty())
                    jobCount = Integer.valueOf(costDataToday[0].RE_Job_Run_Count__c);
            for(RE_Depot_Pricing_Backbone__c dpbdata : thailandCCList){
                
                RE_MY_CostPrice__c costData = new RE_MY_CostPrice__c();
                
                costData.recordtypeId=Schema.SObjectType.RE_MY_CostPrice__c.getRecordTypeInfosByName().get('Thailand').getRecordTypeId() ;//'0120C00000077tO';
                costData.RE_Job_Run_Count__c = jobCount;
                costData.RE_IsLatest__c = True;
                costData.RE_Country__c = dpbdata.RE_Country__c;
                costData.RE_Depot_Name__c = dpbdata.RE_Depot_Name__c;
                costData.RE_Product_Name__c = dpbdata.RE_Product_Name__c;
                costData.RE_Costprice_Unit__c = dpbdata.RE_Final_Price_Unit__c;
                costData.RE_Pricing_Date__c = System.today();
                if(finalhcval.finalval.containsKey(dpbdata.Id))
                    costData.RE_Hydrocarbon_Value__c = finalhcval.finalval.get(dpbdata.Id);
                /*if(finalolval.finalval.containsKey(dpbdata.Id))
                        costData.RE_Oil_Loss__c = finalolval.finalval.get(dpbdata.Id);*/
                if(finalsahval.finalval.containsKey(dpbdata.Id))
                    costData.RE_Storage_Handling_Cost__c = finalsahval.finalval.get(dpbdata.Id);
                if(finalptval.finalval.containsKey(dpbdata.Id))
                        costData.RE_Primary_Transport_Cost__c = finalptval.finalval.get(dpbdata.Id);
                if(finalacval.finalval.containsKey(dpbdata.Id))
                    costData.RE_Additive_Cost__c = finalacval.finalval.get(dpbdata.Id);
                if(laiddownCostMap.containsKey(dpbdata.Id))
                    costData.RE_Costprice_Laid_Down_Cost__c = laiddownCostMap.get(dpbdata.Id);
                if(finalrstval.finalval.containsKey(dpbdata.Id))
                    costData.RE_Recovery_Sales_Tax__c = finalrstval.finalval.get(dpbdata.Id);
                    
                //if(marginalCostMap.containsKey(dpbdata.Id))
                  //      costData.RE_Costprice_Marginal_Cost__c = marginalCostMap.get(dpbdata.Id);
                costingList.add(costData);
            }
            if(!costingList.isEmpty()){
                    try{
                        if(!updateLatestData.isEmpty())
                            update updateLatestData;
                        insert costingList;
                        Issuccess = True;
                    }
                    catch(Exception e){
                        Issuccess = False;
                    }
                }
        }else{
            Issuccess = False;
        }
         try{
            jra.RE_IsSuccess__c = Issuccess;
            jra.RE_Exception__c = errormessage;
            update jra;
        }
        catch(Exception e){

        }
		
	}
}