force-app/main/default/objects/OLF_EmailTemplate__mdt/OLF_EmailTemplate__mdt.object-meta.xml
<CustomObject>
    <label>OLF Email Template</label>
    <pluralLabel>OLF Email Templates</pluralLabel>
</CustomObject>

force-app/main/default/objects/OLF_EmailTemplate__mdt/fields/EMAIL_CC__c.field-meta.xml
<CustomField>
    <fullName>EMAIL_CC__c</fullName>
    <description>Enter emails to be sent as CC in semicolon (;) separated, e.g. abc@test.com; efz@test.com;</description>
    <inlineHelpText>Enter emails to be sent as CC in semicolon (;) separated, e.g. abc@test.com; efz@test.com;</inlineHelpText>
    <label>EMAIL CC</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OLF_EmailTemplate__mdt/fields/EMAIL_SUBJECT__c.field-meta.xml
<CustomField>
    <fullName>EMAIL_SUBJECT__c</fullName>
    <label>EMAIL SUBJECT</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OLF_EmailTemplate__mdt/fields/EMAIL_TO__c.field-meta.xml
<CustomField>
    <fullName>EMAIL_TO__c</fullName>
    <label>EMAIL TO</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/RV_MetadataCoverageTest.cls
/**************************************************************************************************
* Name: RV_MetadataCoverageTest
* Purpose: Test Class of Custom MetaData coverage
* Create Date: 2022-10-20
**************************************************************************************************/
@isTest
public class RV_MetadataCoverageTest {
    static testmethod void testMetadataCoverageMethod(){
        List<SObject> metadataCoverageRecords;
        Test.startTest();
                 metadataCoverageRecords = new RV_MetadataCoverage().getMetadataCoverageRecords('SELECT EMAIL_CC__c,EMAIL_TO__c,EMAIL_SUBJECT__c FROM OLF_EmailTemplate__mdt'); 
        Test.stopTest();

        
    }
    public static void setMetadata(String query, List<SObject> records){
        RV_MetadataCoverage.MetadataCoverageRecordsMap.put(query, records);
    }
}