force-app/main/default/objects/Freight_Rate__c/Freight_Rate__c.object-meta.xml
<CustomObject>
    <label>Backbone AMV/Freight Rate</label>
    <nameField>
        <displayFormat>BA-{0}</displayFormat>
        <label>Backbone Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backbone AMV/Freight Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Freight_Rate__c/fields/Freight_Quotation__c.field-meta.xml
<CustomField>
    <fullName>Freight_Quotation__c</fullName>
    <label>Freight Quotation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rv_Freight_quotation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freight_Rate__c/fields/Marker__c.field-meta.xml
<CustomField>
    <fullName>Marker__c</fullName>
    <label>Marker Value(€/mt)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Object to store all OU, Region and Location information for Trading and Supply - ATP/AMV/SCHT</description>
    <label>Location</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Abbreviated_Name__c.field-meta.xml
<CustomField>
    <fullName>Abbreviated_Name__c</fullName>
    <label>Abbreviated Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Source_Location__c.field-meta.xml
<CustomField>
    <fullName>Source_Location__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Source Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Price__c/Price__c.object-meta.xml
<CustomObject>
    <label>Price</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}-{00}</displayFormat>
        <label>Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reuters_Quotes__c/Reuters_Quotes__c.object-meta.xml
<CustomObject>
    <label>Reuters Quotes</label>
    <nameField>
        <displayFormat>RQ-{00000}</displayFormat>
        <label>Reuters Quotes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ReutersQuotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reuters_Quotes__c/fields/Quote_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Quote_Display_Name__c</fullName>
    <label>Quote Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Rv_Freight_quotation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoil ARA-BasleSFR</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoil ARA-Cologne</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoil ARA-Dortmund</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoil ARA-Duisburg</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoil ARA-Frankfurt</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoil ARA-Karlsruhe</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoline ARA-BasleSFR</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoline ARA-Cologne</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoline ARA-Dortmund</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoline ARA-Duisburg</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoline ARA-Frankfurt</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoline ARA-Karlsruhe</fullName>
    </customValue>
    <masterLabel>Rv_Freight quotation</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RV_FreightRateTriggerHelperTest.cls
@isTest
public class RV_FreightRateTriggerHelperTest {
        static testmethod void testFreightRate(){
             Location__c locinsert = new Location__c();
             locinsert = RV_TestHelperPhase2.insertLocationLudwigshafen(locinsert);
             locinsert.Abbreviated_Name__c = 'Ludwigshafen';
             locinsert.Source_Location__c = true;
             insert locinsert;
            
             Location__c locinsert1 = new Location__c();
             locinsert1 = RV_TestHelperPhase2.insertLocationKarlsruhe(locinsert1);
             locinsert1.Abbreviated_Name__c = 'Karlsruhe';
             locinsert1.Source_Location__c = true;
             insert locinsert1;
            
             Reuters_Quotes__c reuterQuoteInsert1 = new Reuters_Quotes__c();
             reuterQuoteInsert1.Price__c = 749.7500;
             reuterQuoteInsert1.Pricing_Date__c = System.today();
             reuterQuoteInsert1.CurrencyCode__c = 'EUR';
             reuterQuoteInsert1.Unit_Of_Measure__c = 't';
             reuterQuoteInsert1.Quote_Name__c = 'GELT_Freight_Mogas_Rdam_Karlsruhe_M (Daily Spot)[EUR/t]';
             reuterQuoteInsert1.Quote_Display_Name__c = 'Reuters (PJK) Rhine Freight Gasoline ARA-Karlsruhe';
             insert reuterQuoteInsert1;
            
             Reuters_Quotes__c reuterQuoteInsert2 = new Reuters_Quotes__c();
             reuterQuoteInsert2.Price__c = 550.4500;
             reuterQuoteInsert2.Pricing_Date__c = System.today();
             reuterQuoteInsert2.CurrencyCode__c = 'EUR';
             reuterQuoteInsert2.Unit_Of_Measure__c = 't';
             reuterQuoteInsert2.Quote_Name__c = 'GELT_Freight_Mogas_Rdam_Frankfurt_M (Daily Spot)[EUR/t]';
             reuterQuoteInsert2.Quote_Display_Name__c = 'Reuters (PJK) Rhine Freight Gasoline ARA-Frankfurt';
             insert reuterQuoteInsert2;
            
             Freight_Rate__c freightRateInsert = new Freight_Rate__c();
             freightRateInsert = RV_TestHelperPhase2.insertFreightRate(freightRateInsert, locinsert1, locinsert);
             freightRateInsert.Freight_Quotation__c = 'Reuters (PJK) Rhine Freight Gasoline ARA-Karlsruhe';
             insert freightRateInsert;
            //added by swarna to cover queuable class
             freightRateInsert.Valid_To__c = System.today().addDays(7);
             freightRateInsert.Marker__c = 23.56;
             freightRateInsert.Freight_Quotation__c = 'Reuters (PJK) Rhine Freight Gasoline ARA-Frankfurt';
             update freightRateInsert;
        }
    
}