force-app/main/default/objects/Freight_Rate__c/Freight_Rate__c.object-meta.xml
<CustomObject>
    <label>Backbone AMV/Freight Rate</label>
    <nameField>
        <displayFormat>BA-{0}</displayFormat>
        <label>Backbone Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backbone AMV/Freight Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Freight_Rate__c/fields/Backbone_Route_Name__c.field-meta.xml
<CustomField>
    <fullName>Backbone_Route_Name__c</fullName>
    <formula>CASE(TEXT( SubGrade_3P__c ),
 &apos;ULG98&apos;, &apos;MOGAS-98&apos;,
 &apos;ULG98 E0&apos;, &apos;MOGAS-98-E0&apos;,
 &apos;ULG95 E0&apos;, &apos;MOGAS-E0&apos;,
 &apos;ULG95 E10&apos;, &apos;MOGAS-E10&apos;,
 &apos;ULG95 E5&apos;, &apos;MOGAS-E5&apos;,
 &apos;ULG95_BOB_E10&apos;, &apos;MOGAS-BOB_E10&apos;,
 &apos;ULG95_BOB_E5&apos;, &apos;MOGAS-BOB_E5&apos;,
 &apos;ULG100 VP&apos;, &apos;MOGAS-100-VP&apos;,
 &apos;IGO 50ppm&apos;,&apos;IGO-50&apos;,
 &apos;IGO 1000ppm&apos;,&apos;IGO-1000&apos;,
 &apos;IGO 10ppm&apos;,&apos;IGO-10&apos;,
 &apos;GTL B7&apos;,&apos;AGO-GTL.B7&apos;,
 &apos;GTL B0&apos;,&apos;AGO-GTL.B0&apos;,
 &apos;AGO B0 CH&apos;,&apos;AGO-CH&apos;,
 &apos;AGO B7&apos;,&apos;AGO-B7&apos;,
 &apos;AGO B0&apos;,&apos;AGO-B0&apos;,
 &apos;AGO VPD&apos;,&apos;AGO-VPD&apos;,
 TEXT(SubGrade_3P__c)) &amp;&quot;_&quot;&amp; TEXT( Supplier__c )&amp;&quot;_&quot;&amp;  Source__r.Abbreviated_Name__c  &amp;&quot;_&quot;&amp;TEXT( Mode_Of_Transport__c )&amp;&quot;_&quot;&amp;  Destination__r.Abbreviated_Name__c</formula>
    <label>Route Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Freight_Rate__c/fields/Freight_Quotation__c.field-meta.xml
<CustomField>
    <fullName>Freight_Quotation__c</fullName>
    <label>Freight Quotation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rv_Freight_quotation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freight_Rate__c/fields/Freight_rate_EUR_mt__c.field-meta.xml
<CustomField>
    <fullName>Freight_rate_EUR_mt__c</fullName>
    <formula>IF(ISPICKVAL( Freight_Cost__c ,&apos;Variable&apos;) ,Freight_Percentage__c *Marker__c + Freight_diff_EUR_mt__c,Freight_diff_EUR_mt__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Freight rate [EUR/mt]</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Freight_Rate__c/fields/Marker__c.field-meta.xml
<CustomField>
    <fullName>Marker__c</fullName>
    <label>Marker Value(€/mt)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Freight_Rate__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipName>Freight_Rates1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Freight_Rate__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>Supplier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gunvor</fullName>
            </value>
            <value>
                <fullName>Shell</fullName>
            </value>
            <value>
                <fullName>Total</fullName>
            </value>
            <value>
                <fullName>BP</fullName>
            </value>
            <value>
                <fullName>Varo</fullName>
            </value>
            <value>
                <fullName>OMV</fullName>
            </value>
            <value>
                <fullName>ENI</fullName>
            </value>
            <value>
                <fullName>Q8</fullName>
            </value>
            <value>
                <fullName>HGM</fullName>
            </value>
            <value>
                <fullName>Klesch</fullName>
            </value>
            <value>
                <fullName>MOL</fullName>
            </value>
            <value>
                <fullName>STR</fullName>
            </value>
            <value>
                <fullName>DS</fullName>
            </value>
            <value>
                <fullName>Holborn</fullName>
            </value>
            <value>
                <fullName>ESSO</fullName>
            </value>
            <value>
                <fullName>Leitner</fullName>
            </value>
            <value>
                <fullName>Alcmene</fullName>
            </value>
            <value>
                <fullName>Rosneft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Steer__c/Location_Steer__c.object-meta.xml
<CustomObject>
    <label>Location Steer</label>
    <nameField>
        <displayFormat>LS-{0000}</displayFormat>
        <label>Location Steer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Steer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Steer__c/fields/Origination_Steer_Type__c.field-meta.xml
<CustomField>
    <fullName>Origination_Steer_Type__c</fullName>
    <label>Origination Steer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ARA AGO Steer</fullName>
            </value>
            <value>
                <fullName>ARA IGO Steer</fullName>
            </value>
            <value>
                <fullName>ARA MOGAS Steer</fullName>
            </value>
            <value>
                <fullName>Harburg AGO steer</fullName>
            </value>
            <value>
                <fullName>Harburg IGO steer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Steer__c/fields/Product_Sub_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Group__c</fullName>
    <label>Product Sub Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AGO B7</fullName>
            </value>
            <value>
                <fullName>IGO 50ppm</fullName>
            </value>
            <value>
                <fullName>ULG95 E5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Steer__c/fields/productPlantScenarioKey__c.field-meta.xml
<CustomField>
    <fullName>productPlantScenarioKey__c</fullName>
    <formula>IF(ISPICKVAL( Product_Sub_Group__c,&apos;IGO 50ppm&apos;),&apos;IGO&apos;,
   IF(ISPICKVAL( Product_Sub_Group__c,&apos;AGO B7&apos;),&apos;AGO&apos;,
   IF(ISPICKVAL( Product_Sub_Group__c ,&apos;ULG95 E5&apos;),&apos;MOGAS&apos;,&apos;&apos;))) +&apos;-&apos; +   Plant__r.Abbreviated_Name__c + &apos;-&apos; +  TEXT(Scenario__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>productPlantScenarioKey</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Steer__c/fields/Scenario__c.field-meta.xml
<CustomField>
    <fullName>Scenario__c</fullName>
    <label>Scenario</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Import</fullName>
            </value>
            <value>
                <fullName>Export</fullName>
            </value>
            <value>
                <fullName>Balanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Steer__c/fields/Scenario_Value__c.field-meta.xml
<CustomField>
    <fullName>Scenario_Value__c</fullName>
    <label>Scenario Value(€/mt)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location_Steer__c/fields/Source_Location__c.field-meta.xml
<CustomField>
    <fullName>Source_Location__c</fullName>
    <formula>Plant__r.Source_Location__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source Location</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Location_Steer_Metadata__mdt/Location_Steer_Metadata__mdt.object-meta.xml
<CustomObject>
    <label>Location Steer</label>
    <pluralLabel>Location Steers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Location_Steer_Metadata__mdt/fields/Differential_Value_1__c.field-meta.xml
<CustomField>
    <fullName>Differential_Value_1__c</fullName>
    <label>Differential Value 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Steer_Metadata__mdt/fields/Factor_Route_1__c.field-meta.xml
<CustomField>
    <fullName>Factor_Route_1__c</fullName>
    <label>Factor Route 1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location_Steer_Metadata__mdt/fields/Factor_Route_2__c.field-meta.xml
<CustomField>
    <fullName>Factor_Route_2__c</fullName>
    <label>Factor Route 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location_Steer_Metadata__mdt/fields/Origination_Steer_Type__c.field-meta.xml
<CustomField>
    <fullName>Origination_Steer_Type__c</fullName>
    <label>Origination Steer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Harburg IGO steer</fullName>
            </value>
            <value>
                <fullName>Harburg AGO steer</fullName>
            </value>
            <value>
                <fullName>ARA AGO Steer</fullName>
            </value>
            <value>
                <fullName>ARA IGO Steer</fullName>
            </value>
            <value>
                <fullName>ARA MOGAS Steer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Steer_Metadata__mdt/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <label>Plant Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>D003</fullName>
            </value>
            <value>
                <fullName>D004</fullName>
            </value>
            <value>
                <fullName>D023</fullName>
            </value>
            <value>
                <fullName>D024</fullName>
                <default>true</default>
                <label>D024</label>
            </value>
            <value>
                <fullName>D025</fullName>
            </value>
            <value>
                <fullName>D028</fullName>
            </value>
            <value>
                <fullName>D029</fullName>
            </value>
            <value>
                <fullName>D127</fullName>
            </value>
            <value>
                <fullName>D322</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Steer_Metadata__mdt/fields/Product_Sub_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Group__c</fullName>
    <label>Product Sub Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AGO</fullName>
                <default>true</default>
                <label>AGO</label>
            </value>
            <value>
                <fullName>IGO</fullName>
            </value>
            <value>
                <fullName>MOGAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Steer_Metadata__mdt/fields/Route_1__c.field-meta.xml
<CustomField>
    <fullName>Route_1__c</fullName>
    <label>Route 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Steer_Metadata__mdt/fields/Route_2__c.field-meta.xml
<CustomField>
    <fullName>Route_2__c</fullName>
    <label>Route 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location_Steer_Metadata__mdt/fields/Scenario__c.field-meta.xml
<CustomField>
    <fullName>Scenario__c</fullName>
    <label>Scenario</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Import</fullName>
                <default>true</default>
                <label>Import</label>
            </value>
            <value>
                <fullName>Export</fullName>
            </value>
            <value>
                <fullName>Balanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Steer_Metadata__mdt/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ARA</fullName>
            </value>
            <value>
                <fullName>Flörsheim</fullName>
            </value>
            <value>
                <fullName>Godorf</fullName>
            </value>
            <value>
                <fullName>Harburg</fullName>
            </value>
            <value>
                <fullName>Karlsruhe</fullName>
            </value>
            <value>
                <fullName>Ludwigshafen</fullName>
            </value>
            <value>
                <fullName>Schwedt-PCK</fullName>
            </value>
            <value>
                <fullName>Wesseling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Rv_Freight_quotation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoil ARA-BasleSFR</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoil ARA-Cologne</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoil ARA-Dortmund</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoil ARA-Duisburg</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoil ARA-Frankfurt</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoil ARA-Karlsruhe</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoline ARA-BasleSFR</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoline ARA-Cologne</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoline ARA-Dortmund</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoline ARA-Duisburg</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoline ARA-Frankfurt</fullName>
    </customValue>
    <customValue>
        <fullName>Reuters (PJK) Rhine Freight Gasoline ARA-Karlsruhe</fullName>
    </customValue>
    <masterLabel>Rv_Freight quotation</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RV_FreightRateTriggerHelper.cls
public class RV_FreightRateTriggerHelper {
    public static Boolean staticVal = true;
    public static void onBeforeInsertHelper(List<Freight_Rate__c> onBeforeUpdateNew , 
                                            list<Freight_Rate__c> onBeforeUpdateOld){
                                                
            Map<String,Freight_Rate__c> freightRateMap = new Map<String,Freight_Rate__c>();                                  
           // Map<String,Freight_Rate__c> markerValueMap = new Map<String,Freight_Rate__c>();
             Set<String> FreightQuoteSet = new  Set<String>();                                        
            for(Freight_Rate__c freightRate : onBeforeUpdateNew){
                //Added By Dhriti
                /*PBI-437456-Lakshmi_04162020_starts
                List<String> split = freightRate.Name.split('_');
                if(String.isNotBlank(split[1])){
                	freightRate.supplier__c = split[1];
                }
                PBI-437456-Lakshmi_04162020_Ends*/
                if(freightRate.Freight_rate_EUR_mt__c <> 0){
                    //freightRateMap.put(freightRate.Name,freightRate);//Fix_493485_Lakshmi_27Apr2020
                    freightRateMap.put(freightRate.Backbone_Route_Name__c,freightRate);
                    System.debug('freightRateMap'+freightRateMap);
                }
                if(freightRate.Freight_Quotation__c <> null){
                    FreightQuoteSet.add(freightRate.Freight_Quotation__c);
                    
                }
            }
            
            if(FreightQuoteSet.size()>0){                                        
           		Map<String,Reuters_Quotes__c> reuterMap = getReuterQuoteVal(FreightQuoteSet);
                for(Freight_Rate__c fr : onBeforeUpdateNew){
                   if(reuterMap.containskey(fr.Freight_Quotation__c)){
                   		fr.Marker__c = reuterMap.get(fr.Freight_Quotation__c).Price__c;
                   }
                }                                  
            }
            
            if(!freightRateMap.isEmpty()){
                
                   Map<String,Location_Steer_Metadata__mdt> mapOfSteerMetadata = mapOfLocationSteerMetadata(freightRateMap.keyset());
                   System.debug('%%%%%%mapOfSteerMetadata%%%%%'+mapOfSteerMetadata);  
                    
                   List<Location_Steer__c> fetchLocationSteerLst = [select id,Scenario_Value__c,productPlantScenarioKey__c
                                                                     from Location_Steer__c where productPlantScenarioKey__c in:mapOfSteerMetadata.keyset() ];//AND Source_Location__c = true
                   System.debug('%%%%%%fetchLocationSteerLst%%%%%'+fetchLocationSteerLst);
                   try{
                        update fetchLocationSteerLst;
                   }catch(Exception e){
                        System.debug('-------Exception--------'+e);
                   }
            }
                                                
           
                                                
    }
    public static void onAfterInsertHelper(List<Freight_Rate__c> onAfterInsertNew , 
                                            list<Freight_Rate__c> onAfterInsertOld){
                  List<String> freighRateIdLst = new List<String>();
                  for(Freight_Rate__c freightRate : onAfterInsertNew){
                      freighRateIdLst.add(freightRate.Id);
                  }
                  insertGroupMembersToGroup(freighRateIdLst);               
    }
    public static void onBeforeUpdateHelper(Map<Id,Freight_Rate__c> onBeforeUpdateNewMap , 
                                            Map<Id,Freight_Rate__c> onBeforeUpdateOldMap){
        //if(staticVal == true){
            
            //staticVal = false;
        
			     
            Set<String> FreightQuoteSet = new  Set<String>();
            for(Freight_Rate__c freightRate : onBeforeUpdateNewMap.values()){
               //Added By Dhriti
               /*PBI-437456-Lakshmi_04162020_starts
               List<String> split = freightRate.Name.split('_');
               if(String.isNotBlank(split[1])){
                	freightRate.supplier__c = split[1];
               }
                PBI-437456-Lakshmi_04162020_Ends*/
               if((onBeforeUpdateNewMap.get(freightRate.Id).Freight_Quotation__c <> onBeforeUpdateOldMap.get(freightRate.ID).Freight_Quotation__c ) ){
                  //  markerValueMap.put(freightRate.Freight_Quotation__c,freightRate);
                    FreightQuoteSet.add(freightRate.Freight_Quotation__c);
               }
                
            }
           
			
             if(FreightQuoteSet.size()>0){                                        
           		Map<String,Reuters_Quotes__c> reuterMap = getReuterQuoteVal(FreightQuoteSet);
                for(Freight_Rate__c fr : onBeforeUpdateNewMap.values()){
                   if(reuterMap.containskey(fr.Freight_Quotation__c)){
                   		fr.Marker__c = reuterMap.get(fr.Freight_Quotation__c).Price__c;
                        
                   }
                }                                  
            }
            
       // }
    }
    
     public static void onAfterUpdateHelper(Map<Id,Freight_Rate__c> onBeforeUpdateNewMap , 
                                            Map<Id,Freight_Rate__c> onBeforeUpdateOldMap){
        if(staticVal == true){
            
            staticVal = false;
        
            Map<String,Freight_Rate__c> freightRateMap = new Map<String,Freight_Rate__c>();
			 List<String> freighRateIdLst = new List<String>();
            for(Freight_Rate__c freightRate : onBeforeUpdateNewMap.values()){
                freighRateIdLst.add(freightRate.Id);
                if((onBeforeUpdateNewMap.get(freightRate.Id).Freight_rate_EUR_mt__c <> onBeforeUpdateOldMap.get(freightRate.ID).Freight_rate_EUR_mt__c ) ){
                   // freightRateMap.put(freightRate.Name,freightRate);
                    freightRateMap.put(freightRate.Backbone_Route_Name__c,freightRate);//Fix_493485_Lakshmi_27Apr2020
                    System.debug('freightRateMap'+freightRateMap.keyset());
                }
                
            }
             insertGroupMembersToGroup(freighRateIdLst); 
            
            if(!freightRateMap.isEmpty()){
                
                   Map<String,Location_Steer_Metadata__mdt> mapOfSteerMetadata = mapOfLocationSteerMetadata(freightRateMap.keyset());
                    System.debug('%%%%%%mapOfSteerMetadata%%%%%'+mapOfSteerMetadata);  
                    
                    List<Location_Steer__c> fetchLocationSteerLst = [select id,Scenario_Value__c,productPlantScenarioKey__c
                                                                     from Location_Steer__c where productPlantScenarioKey__c in:mapOfSteerMetadata.keyset() ];//AND Source_Location__c = true
                    System.debug('%%%%%%fetchLocationSteerLst%%%%%'+fetchLocationSteerLst);
                    try{
                        update fetchLocationSteerLst;
                    }catch(Exception e){
                        System.debug('-------Exception--------'+e);
                    }
            }
            
        }
    }
    
     // Creating Map of Key and Location steer Meta data
    // Key - Product sub Group + Plant Code + Scenario
    // Example - IGO 50ppm + D024 + Import
    public static Map<String,Location_Steer_Metadata__mdt> mapOfLocationSteerMetadata(Set<String> freightRateName){
        
        List<Location_Steer_Metadata__mdt> locationSteerLst = [select id,MasterLabel,DeveloperName,Factor_Route_1__c,Factor_Route_2__c,Origination_Steer_Type__c,
                                                               Plant_Code__c,Product_Sub_Group__c,Route_1__c,Route_2__c,Scenario__c,Source__c,Differential_Value_1__c ,
                                                               Differential_Value_2__c  from Location_Steer_Metadata__mdt ];
        
        Map<String,Location_Steer_Metadata__mdt> locationSteerMap = new Map<String,Location_Steer_Metadata__mdt>();
        
        if(!locationSteerLst.isEmpty()){
            for(Location_Steer_Metadata__mdt locationSteerMeta : locationSteerLst){
                if(freightRateName.contains(locationSteerMeta.Route_1__c) || freightRateName.contains(locationSteerMeta.Route_2__c) ||
                  freightRateName.contains(locationSteerMeta.Differential_Value_1__c) || freightRateName.contains(locationSteerMeta.Differential_Value_2__c)){
                	locationSteerMap.put(locationSteerMeta.Product_Sub_Group__c + '-' + locationSteerMeta.Source__c + '-' + locationSteerMeta.Scenario__c , locationSteerMeta);
                }
            }
        }
        return locationSteerMap;
    }
    
   
    public static Map<String,Reuters_Quotes__c> getReuterQuoteVal(Set<String> freightRateQuote){
        System.debug('----------freightRateMap.keyset()-------'+freightRateQuote);
        List<Reuters_Quotes__c> mapOfReutersQuote = new List<Reuters_Quotes__c>();
        mapOfReutersQuote = [SELECT id,Name,Quote_Display_Name__c,Price__c from Reuters_Quotes__c where Quote_Display_Name__c
                             in:freightRateQuote order by LastModifiedDate DESC ];
        System.debug('----------mapOfReutersQuote-------'+mapOfReutersQuote);
        Map<String,Reuters_Quotes__c> mapOfReuter = new Map<String,Reuters_Quotes__c>();
        if(!mapOfReutersQuote.isEmpty()){
            for(Reuters_Quotes__c reuter : mapOfReutersQuote){
                if(!mapOfReuter.containskey(reuter.Quote_Display_Name__c)){
                    //reuter.Price__c = freightRateMap.get(reuter.Quote_Display_Name__c).Marker__c;
                    mapOfReuter.put(reuter.Quote_Display_Name__c,reuter);
                 
                }
            }
        }
        System.debug('%%%%%mapOfReuter%%%%%'+mapOfReuter);
		return mapOfReuter;
    }
    @future
    public static void insertGroupMembersToGroup(List<String> freighRateIdLst){
        List<Freight_Rate__c> freighRate = [SELECT id,Valid_To_Fomula__c,LastModifiedById from Freight_Rate__c where 
                                            Id in:freighRateIdLst AND Valid_To_Fomula__c = TODAY]; 
        List<Group> groupLst = [SELECT Id,DeveloperName FROM Group where DeveloperName = 'RV_LastModifiedByUserId'];
        List<GroupMember> addlistGroupMember =new List<GroupMember>(); 
        if(!freighRate.isEmpty()){
            for(Freight_Rate__c freightRate : freighRate){
                 GroupMember gm= new GroupMember(); 
                 gm.GroupId = groupLst.get(0).Id;
                 gm.UserOrGroupId = freightRate.LastModifiedById;
                 addlistGroupMember.add(gm);
            }
            if(!addlistGroupMember.isEmpty()){
                try{
                     insert addlistGroupMember;
                }catch(Exception e){
                        System.debug('-------Exception--------'+e);
                }       
            }
        }
    }
}