force-app/main/default/objects/Freight_Rate__c/Freight_Rate__c.object-meta.xml
<CustomObject>
    <label>Backbone AMV/Freight Rate</label>
    <nameField>
        <displayFormat>BA-{0}</displayFormat>
        <label>Backbone Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backbone AMV/Freight Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Freight_Rate__c/fields/Valid_To_Fomula__c.field-meta.xml
<CustomField>
    <fullName>Valid_To_Fomula__c</fullName>
    <formula>CASE(WEEKDAY( Valid_To__c ),
2, Valid_To__c - 7, 
3, Valid_To__c - 7, 
4, Valid_To__c - 7,
5, Valid_To__c - 7,
6, Valid_To__c - 7,
7, Valid_To__c - 6,
1, Valid_To__c - 7,
null)</formula>
    <label>Valid To Fomula</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/RV_RoutesInvalidEmailBatch.cls
global class RV_RoutesInvalidEmailBatch implements Database.Batchable<sObject> {
	global Database.QueryLocator start(Database.BatchableContext BC){
      String query = 'SELECT id,Valid_To_Fomula__c,LastModifiedById from Freight_Rate__c where Valid_To_Fomula__c = TODAY';
      return Database.getQueryLocator(query);
   } 

   global void execute(Database.BatchableContext BC, List<Freight_Rate__c> scope){
         List<Group> groupLst = [SELECT Id,DeveloperName FROM Group where DeveloperName = 'RV_LastModifiedByUserId'];
         delete [SELECT Id, GroupId, UserOrGroupId FROM GroupMember where GroupId =: groupLst.get(0).Id];
         List<GroupMember> addlistGroupMember =new List<GroupMember>();  
         for(Freight_Rate__c freightRate : scope){
             GroupMember gm= new GroupMember(); 
             gm.GroupId = groupLst.get(0).Id;
             gm.UserOrGroupId = freightRate.LastModifiedById;
             addlistGroupMember.add(gm);
         }
         try{
             insert addlistGroupMember;
         }catch(Exception e){
                System.debug('-------Exception--------'+e);
         }
    }

   global void finish(Database.BatchableContext BC){
   }
}