force-app/main/default/objects/TCP_Controls__mdt/TCP_Controls__mdt.object-meta.xml
<CustomObject>
    <description>Used to maintain flags for triggers or any specific operations</description>
    <label>TCP Controls</label>
    <pluralLabel>TCP Controls</pluralLabel>
</CustomObject>

force-app/main/default/objects/User/fields/CIPM_Access__c.field-meta.xml
<CustomField>
    <fullName>CIPM_Access__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CIPM Access?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TCP_UserHandler.cls
/************************************************************************************************
Description    :    This is trigger handler class for user object for TCP project
************************************************************************************************/

public with sharing class TCP_UserHandler{

    public static void handleAfterInsert(list<user> userlist){
        if(!userlist.isEmpty()){
            TCP_Controls__mdt isTriggerActive = TCP_Controls__mdt.getInstance('TCP_UserTigger');
            TCP_Controls__mdt isCIPMRegActive = TCP_Controls__mdt.getInstance('TCP_CIPMRegister');

            //check if trigger operations are active and CIPM register is active
            if(isTriggerActive.isactive__c && isCIPMRegActive.isActive__c){
            
                for(user u : userlist){
                    if(u.CIPM_Access__c)
                    TCP_CIPM_PreRegisterHandler.manageCIPMRegister(u.id);
                }
            }
        }
    }
}