force-app/main/default/objects/Account/recordTypes/TCP_Account.recordType-meta.xml
<RecordType>
    <fullName>TCP_Account</fullName>
    <active>true</active>
    <label>TCP Account</label>
</RecordType>

force-app/main/default/objects/TCP_DistributionEmailList__c/TCP_DistributionEmailList__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To capture distribution list of each region.</description>
    <label>TCP Distribution Email List</label>
</CustomObject>

force-app/main/default/objects/TCP_DistributionEmailList__c/fields/TCP_Commops_Delivery_Lists__c.field-meta.xml
<CustomField>
    <fullName>TCP_Commops_Delivery_Lists__c</fullName>
    <description>To capture multiple DL&apos;s that should be placed in TCP related emails CC address. Please separate email address with semicolon ;</description>
    <inlineHelpText>To capture multiple DL&apos;s that should be placed in TCP related emails CC address. Please separate email address with semicolon ;</inlineHelpText>
    <label>TCP Commops Delivery Lists</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_DistributionEmailList__c/fields/TCP_Region__c.field-meta.xml
<CustomField>
    <fullName>TCP_Region__c</fullName>
    <description>Enter values in similar format as Sales Area&apos;s Sales Org</description>
    <inlineHelpText>Enter values in similar format as Sales Area&apos;s Sales Org</inlineHelpText>
    <label>TCP Region</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TCP_OrderLineItem__c/TCP_OrderLineItem__c.object-meta.xml
<CustomObject>
    <description>This object hold the line item details</description>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/TCP_EmailServiceTest.cls
@isTest
private class TCP_EmailServiceTest {

    @isTest
    static void testSendEmail()
    {	
        List<contact> testContact= new List<contact>();
        List<Order> testOrders=new List<Order>();
        List<TCP_OrderLineItem__c> testOrderLineItem= new  List<TCP_OrderLineItem__c>();   
        TCP_TestDataUtilities.createAccounts(1,true);
       string tcpAccountRecTypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('TCP_Account').getRecordTypeId();
        Account acc=[select id,name,recordtype.id,Active__c from account where name='SampleAccount0' limit 1];
        acc.recordtypeId=tcpAccountRecTypeid;
        update acc;
            testContact=TCP_TestDataUtilities.createContacts(1,acc);
            testOrders=TCP_TestDataUtilities.createOrders(1,acc);
                for(Order testOrder:testOrders){
                     testOrderLineItem=TCP_TestDataUtilities.createOrderLineItems(1,testOrder);
                }
        
        insert new TCP_DistributionEmailList__c(TCP_Commops_Delivery_Lists__c ='ishaque.mohammad@shell.com',TCP_Region__c='SETO',Name='SETO');
        Test.StartTest();
        TCP_EmailService.sendEmail(testOrders[0].id,testContact[0].id,acc.id,null,'TCP_Order_acknowledgement_EN_US',true);
        TCP_EmailService.sendEmail(testOrders[0].id,null,acc.id,userinfo.getUserId(),'TCP_Order_acknowledgement_EN_US',true);
        Integer invocations = Limits.getEmailInvocations();
        Test.stopTest();
 		System.assertEquals(2, invocations);
    }
}