force-app/main/default/objects/RE_FX_Rates__c/RE_FX_Rates__c.object-meta.xml
<CustomObject>
    <label>RE FX Rates</label>
    <nameField>
        <displayFormat>FXR-{000000}</displayFormat>
        <label>FX_Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE FX Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Conversion_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Conversion_Unit__c</fullName>
    <label>Conversion Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Is_MTDWTD__c.field-meta.xml
<CustomField>
    <fullName>RE_Is_MTDWTD__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is MTDWTD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Name__c</fullName>
    <description>quote display name is stored</description>
    <label>Quote Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Tracker__c.field-meta.xml
<CustomField>
    <fullName>RE_Tracker__c</fullName>
    <label>Tracker</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>D-1</fullName>
            </value>
            <value>
                <fullName>D-2</fullName>
            </value>
            <value>
                <fullName>D+1</fullName>
            </value>
            <value>
                <fullName>MTD</fullName>
            </value>
            <value>
                <fullName>WTD</fullName>
            </value>
            <value>
                <fullName>W-1</fullName>
            </value>
            <value>
                <fullName>W-2</fullName>
            </value>
            <value>
                <fullName>M-1</fullName>
            </value>
            <value>
                <fullName>M-2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/RE_Job_Run_Audit__c.object-meta.xml
<CustomObject>
    <label>Job Run Audit</label>
    <nameField>
        <displayFormat>JR-{00000000}</displayFormat>
        <label>Job Run Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Run Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Country_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Country_Name__c</fullName>
    <label>Country Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RT_Revolution_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Job_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Malaysia Output</fullName>
            </value>
            <value>
                <fullName>Singapore Output</fullName>
            </value>
            <value>
                <fullName>SG Midday Output</fullName>
            </value>
            <value>
                <fullName>Malaysia AMV Output</fullName>
            </value>
            <value>
                <fullName>Thailand Output</fullName>
            </value>
            <value>
                <fullName>CustomerOps Output</fullName>
            </value>
            <value>
                <fullName>New Contract Pricing Output</fullName>
            </value>
            <value>
                <fullName>Thailand AMV Output</fullName>
            </value>
            <value>
                <fullName>MY Export Report</fullName>
            </value>
            <value>
                <fullName>MY Customer Opps CBU</fullName>
            </value>
            <value>
                <fullName>Philippines Output</fullName>
            </value>
            <value>
                <fullName>Canada Daily Reuters Quote Move</fullName>
            </value>
            <value>
                <fullName>Canada Execute Depo Pricing</fullName>
            </value>
            <value>
                <fullName>Canada Pricing Recalculation</fullName>
            </value>
            <value>
                <fullName>Canada SFJ Record Creation</fullName>
            </value>
            <value>
                <fullName>Canada Live OPIS Spot Ticker Processing</fullName>
            </value>
            <value>
                <fullName>Canada Market Move Calculation</fullName>
            </value>
            <value>
                <fullName>Canada Competitor Data Processing</fullName>
            </value>
            <value>
                <fullName>Canada GSAP Upload</fullName>
            </value>
            <value>
                <fullName>Canada Email Output</fullName>
            </value>
            <value>
                <fullName>MY Data Analysis Report</fullName>
            </value>
            <value>
                <fullName>PH Customer Opps CBU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/RE_Market_Quotes__c.object-meta.xml
<CustomObject>
    <label>RE Market Quotes</label>
    <nameField>
        <displayFormat>MarketQuote-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Market Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Name__c</fullName>
    <label>Quote Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Type__c</fullName>
    <label>Quote Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Market Premium</fullName>
            </value>
            <value>
                <fullName>Assessed Premium</fullName>
            </value>
            <value>
                <fullName>Midday</fullName>
            </value>
            <value>
                <fullName>Forward Swap</fullName>
            </value>
            <value>
                <fullName>Spot</fullName>
            </value>
            <value>
                <fullName>Freight</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Tracker__c.field-meta.xml
<CustomField>
    <fullName>RE_Tracker__c</fullName>
    <label>Tracker</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>D-1</fullName>
            </value>
            <value>
                <fullName>MTD</fullName>
            </value>
            <value>
                <fullName>WTD</fullName>
            </value>
            <value>
                <fullName>W-1</fullName>
            </value>
            <value>
                <fullName>W-2</fullName>
            </value>
            <value>
                <fullName>M-1</fullName>
            </value>
            <value>
                <fullName>M-2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/RT_Revolution_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TU</fullName>
        <label>Turkey</label>
    </customValue>
    <customValue>
        <fullName>MY</fullName>
        <label>Malaysia</label>
    </customValue>
    <customValue>
        <fullName>TH</fullName>
        <label>Thailand</label>
    </customValue>
    <customValue>
        <fullName>PH</fullName>
        <label>Philippines</label>
    </customValue>
    <customValue>
        <fullName>SG</fullName>
        <label>Singapore</label>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
        <label>Canada</label>
    </customValue>
    <masterLabel>Revolution Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RE_ControlDashboardTest.cls
@isTest
public class RE_ControlDashboardTest {

    @isTest
    public static void RE_ControlDashboardTestMethod(){
       
        RE_ControlDashboard.getAutomatedJobs();
        RE_ControlDashboard.getData();
        RE_ControlDashboard.getJobsMetaData();
    }
    
   @testSetup
    public static void getDataTest(){
        
        RE_Job_Run_Audit__c jobType = new RE_Job_Run_Audit__c();
        jobType.RE_Job_Type__c = 'Malaysia Output';
        insert jobType;
        
       List<RE_Market_Quotes__c> marketQuoteList =  new List<RE_Market_Quotes__c>();
        
        RE_Market_Quotes__c marketQuote = new RE_Market_Quotes__c();
        marketQuote.RE_Quote_Name__c = 'Kero Premium';
        marketQuote.RE_Quote_Type__c = 'Market Premium';
        marketQuote.RE_Tracker__c = 'D';
        marketQuote.RE_Is_MTDWTD__c = false;
        marketQuote.RE_Country_Name__c = 'SG';
        marketQuoteList.add(marketQuote); 
        
        RE_Market_Quotes__c marketQuote2 = new RE_Market_Quotes__c();
        marketQuote2.RE_Quote_Name__c = 'Kero Premium';
        marketQuote2.RE_Quote_Type__c = 'Settlement';
        marketQuote2.RE_Tracker__c = 'D';
        marketQuote2.RE_Is_MTDWTD__c = false;
        marketQuote2.RE_Country_Name__c = 'SG';
		marketQuoteList.add(marketQuote2); 
        
        RE_Market_Quotes__c marketQuote3 = new RE_Market_Quotes__c();
        marketQuote3.RE_Quote_Name__c = 'MID RON PREMIUM';
        marketQuote3.RE_Quote_Type__c = 'Assessed Premium';
        marketQuote3.RE_Tracker__c = 'D';
        marketQuote3.RE_Is_MTDWTD__c = false;
        marketQuote3.RE_Country_Name__c = 'SG';
		marketQuoteList.add(marketQuote3); 
        
        RE_Market_Quotes__c marketQuote4 = new RE_Market_Quotes__c();
        marketQuote4.RE_Quote_Name__c = 'Kero Premium';
        marketQuote4.RE_Quote_Type__c = 'Midday';
        marketQuote4.RE_Tracker__c = 'D';
        marketQuote4.RE_Is_MTDWTD__c = false;
        marketQuote4.RE_Country_Name__c = 'SG';
		marketQuoteList.add(marketQuote4); 
        
        RE_Market_Quotes__c marketQuote5 = new RE_Market_Quotes__c();
        marketQuote5.RE_Quote_Name__c = 'MKT PREMIA MPI08';
        marketQuote5.RE_Quote_Type__c = 'Market Premium';
        marketQuote5.RE_Tracker__c = 'D';
        marketQuote5.RE_Is_MTDWTD__c = false;
        marketQuote5.RE_Country_Name__c = 'SG';
		marketQuoteList.add(marketQuote5); 
        
        RE_Market_Quotes__c marketQuote6 = new RE_Market_Quotes__c();
        marketQuote6.RE_Quote_Name__c = 'FuelSave98 Premium';
        marketQuote6.RE_Quote_Type__c = 'Assessed Premium';
        marketQuote6.RE_Tracker__c = 'D';
        marketQuote6.RE_Is_MTDWTD__c = false;
        marketQuote6.RE_Country_Name__c = 'SG';
		marketQuoteList.add(marketQuote6); 
        
        RE_Market_Quotes__c marketQuote7 = new RE_Market_Quotes__c();
        marketQuote7.RE_Quote_Name__c = 'CME Discount';
        marketQuote7.RE_Quote_Type__c = 'Freight';
        marketQuote7.RE_Tracker__c = 'D';
        marketQuote7.RE_Is_MTDWTD__c = false;
        marketQuote7.RE_Country_Name__c = 'SG';
		marketQuoteList.add(marketQuote7); 
        
        RE_Market_Quotes__c marketQuote8 = new RE_Market_Quotes__c();
        marketQuote8.RE_Quote_Name__c = 'Breakbulk Premium';
        marketQuote8.RE_Quote_Type__c = 'Assessed Premium';
        marketQuote8.RE_Tracker__c = 'D';
        marketQuote8.RE_Is_MTDWTD__c = false;
        marketQuote8.RE_Country_Name__c = 'SG';
		marketQuoteList.add(marketQuote8); 
        
        RE_Market_Quotes__c marketQuote9 = new RE_Market_Quotes__c();
        marketQuote9.RE_Quote_Name__c = 'CME Discount';
        marketQuote9.RE_Quote_Type__c = 'Forward Swap';
        marketQuote9.RE_Tracker__c = 'D';
        marketQuote9.RE_Is_MTDWTD__c = false;
        marketQuote9.RE_Country_Name__c = 'SG';
		marketQuoteList.add(marketQuote9); 
        
        RE_Market_Quotes__c marketQuote10 = new RE_Market_Quotes__c();
        marketQuote10.RE_Quote_Name__c = 'UCAP RBD CNO';
        marketQuote10.RE_Quote_Type__c = 'Forward Swap';
        marketQuote10.RE_Tracker__c = 'D';
        marketQuote10.RE_Is_MTDWTD__c = false;
        marketQuote10.RE_Country_Name__c = 'SG';
		marketQuoteList.add(marketQuote10); 
        
        RE_Market_Quotes__c marketQuote11 = new RE_Market_Quotes__c();
        marketQuote11.RE_Quote_Name__c = 'Ethanol';
        marketQuote11.RE_Quote_Type__c = 'Forward Swap';
        marketQuote11.RE_Tracker__c = 'D';
        marketQuote11.RE_Is_MTDWTD__c = false;
        marketQuote11.RE_Country_Name__c = 'SG';
		marketQuoteList.add(marketQuote11); 
        
        insert marketQuoteList;
        
        List<String> conversionUnit = new List<String>{'PHP','MYR','SGD'};
        List<RE_FX_Rates__c> fxRateList = new List<RE_FX_Rates__c>(); 
        for(String item : conversionUnit)
        {
            RE_FX_Rates__c fxRate = new RE_FX_Rates__c();
            fxRate.RE_Conversion_Unit__c = item;
            fxRate.RE_Is_MTDWTD__c = false;
            fxRateList.add(fxRate);
        }
        insert fxRateList;
    }
}