force-app/main/default/objects/RE_FX_Rates__c/RE_FX_Rates__c.object-meta.xml
<CustomObject>
    <label>RE FX Rates</label>
    <nameField>
        <displayFormat>FXR-{000000}</displayFormat>
        <label>FX_Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE FX Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Market_Quotes__c/RE_Market_Quotes__c.object-meta.xml
<CustomObject>
    <label>RE Market Quotes</label>
    <nameField>
        <displayFormat>MarketQuote-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Market Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_MY_Output__c/RE_MY_Output__c.object-meta.xml
<CustomObject>
    <label>MY Output</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Costing Output Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MY Output</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_Job_Run_Count__c.field-meta.xml
<CustomField>
    <fullName>RE_Job_Run_Count__c</fullName>
    <label>Job Run Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_Region__c.field-meta.xml
<CustomField>
    <fullName>RE_Region__c</fullName>
    <label>Region</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_TH_AWD_DIFF__c.field-meta.xml
<CustomField>
    <fullName>RE_TH_AWD_DIFF__c</fullName>
    <label>AWD DIFF</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_TH_AWD_LDC__c.field-meta.xml
<CustomField>
    <fullName>RE_TH_AWD_LDC__c</fullName>
    <label>AWD LDC</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/recordTypes/Thailand.recordType-meta.xml
<RecordType>
    <fullName>Thailand</fullName>
    <active>true</active>
    <label>Thailand</label>
</RecordType>

force-app/main/default/classes/RE_ThailandOutputControllrTest.cls
@isTest
public class RE_ThailandOutputControllrTest {
  public static testmethod void testUtility()
  {
        RE_Market_Quotes__c createMQ1  = RE_UtilityClass.getMarketQuotes(23.6560,'USD','BBL','MID RON PREMIUM');
        RE_Market_Quotes__c createMQ2  = RE_UtilityClass.getMarketQuotes(57.4658,'USD','BBL','Gasoil 0.05% S');
        RE_UtilityClass.getCountryCode('Thailand');
        RE_FX_Rates__c FXrate3 = RE_UtilityClass.createFXRecords('THB/USD',4.3520,'USD','THB','Thailand');
        List<RE_MY_Output__c> ls = new List<RE_MY_Output__c>();
        ls.add(new RE_MY_Output__c(RE_TH_AWD_DIFF__c=56.78,RE_TH_AWD_LDC__c = 231.21,RE_Region__c='Thailand',RE_Job_Run_Count__c=0));
        insert ls;
  }
}