force-app/main/default/objects/RE_FX_Rates__c/RE_FX_Rates__c.object-meta.xml
<CustomObject>
    <label>RE FX Rates</label>
    <nameField>
        <displayFormat>FXR-{000000}</displayFormat>
        <label>FX_Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE FX Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Base_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Base_Unit__c</fullName>
    <label>Base Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Conversion_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Conversion_Unit__c</fullName>
    <label>Conversion Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Is_MTDWTD__c.field-meta.xml
<CustomField>
    <fullName>RE_Is_MTDWTD__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is MTDWTD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Pricing_Date__c.field-meta.xml
<CustomField>
    <fullName>RE_Pricing_Date__c</fullName>
    <label>Published Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RE_Holiday_Calendar__c/RE_Holiday_Calendar__c.object-meta.xml
<CustomObject>
    <label>Holiday Calendar</label>
    <nameField>
        <displayFormat>CAL-{00000}</displayFormat>
        <label>Calendar Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holiday Calendars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Job_Run_Audit__c/RE_Job_Run_Audit__c.object-meta.xml
<CustomObject>
    <label>Job Run Audit</label>
    <nameField>
        <displayFormat>JR-{00000000}</displayFormat>
        <label>Job Run Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Run Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Country_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Country_Name__c</fullName>
    <label>Country Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RT_Revolution_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Job_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Malaysia Output</fullName>
            </value>
            <value>
                <fullName>Singapore Output</fullName>
            </value>
            <value>
                <fullName>SG Midday Output</fullName>
            </value>
            <value>
                <fullName>Malaysia AMV Output</fullName>
            </value>
            <value>
                <fullName>Thailand Output</fullName>
            </value>
            <value>
                <fullName>CustomerOps Output</fullName>
            </value>
            <value>
                <fullName>New Contract Pricing Output</fullName>
            </value>
            <value>
                <fullName>Thailand AMV Output</fullName>
            </value>
            <value>
                <fullName>MY Export Report</fullName>
            </value>
            <value>
                <fullName>MY Customer Opps CBU</fullName>
            </value>
            <value>
                <fullName>Philippines Output</fullName>
            </value>
            <value>
                <fullName>Canada Daily Reuters Quote Move</fullName>
            </value>
            <value>
                <fullName>Canada Execute Depo Pricing</fullName>
            </value>
            <value>
                <fullName>Canada Pricing Recalculation</fullName>
            </value>
            <value>
                <fullName>Canada SFJ Record Creation</fullName>
            </value>
            <value>
                <fullName>Canada Live OPIS Spot Ticker Processing</fullName>
            </value>
            <value>
                <fullName>Canada Market Move Calculation</fullName>
            </value>
            <value>
                <fullName>Canada Competitor Data Processing</fullName>
            </value>
            <value>
                <fullName>Canada GSAP Upload</fullName>
            </value>
            <value>
                <fullName>Canada Email Output</fullName>
            </value>
            <value>
                <fullName>MY Data Analysis Report</fullName>
            </value>
            <value>
                <fullName>PH Customer Opps CBU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Run_Time__c.field-meta.xml
<CustomField>
    <fullName>RE_Run_Time__c</fullName>
    <label>Run Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Run_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Run_Type__c</fullName>
    <label>Run Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automate</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_User__c.field-meta.xml
<CustomField>
    <fullName>RE_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Job_Run_Audit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/RE_Market_Quotes__c.object-meta.xml
<CustomObject>
    <label>RE Market Quotes</label>
    <nameField>
        <displayFormat>MarketQuote-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Market Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Type__c</fullName>
    <label>Quote Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Market Premium</fullName>
            </value>
            <value>
                <fullName>Assessed Premium</fullName>
            </value>
            <value>
                <fullName>Midday</fullName>
            </value>
            <value>
                <fullName>Forward Swap</fullName>
            </value>
            <value>
                <fullName>Spot</fullName>
            </value>
            <value>
                <fullName>Freight</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/RT_Revolution_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TU</fullName>
        <label>Turkey</label>
    </customValue>
    <customValue>
        <fullName>MY</fullName>
        <label>Malaysia</label>
    </customValue>
    <customValue>
        <fullName>TH</fullName>
        <label>Thailand</label>
    </customValue>
    <customValue>
        <fullName>PH</fullName>
        <label>Philippines</label>
    </customValue>
    <customValue>
        <fullName>SG</fullName>
        <label>Singapore</label>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
        <label>Canada</label>
    </customValue>
    <masterLabel>Revolution Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RE_PH_ExecuteAutomateJob.cls
global class RE_PH_ExecuteAutomateJob implements Schedulable {
	public void execute(SchedulableContext ctx) {
        Boolean isSettlement = False;
        Boolean isMarkPrem = False;
        Boolean isFreight = False;
        Boolean isPHFx = False;
        Datetime dt = (DateTime)System.today();
        String dayOfWeek = dt.format('EEEE');
        Map<String, RE_Holiday_Calendar__c> holidayMap = RE_SOQLController.fetchPHHolidayData();
        for(RE_Market_Quotes__c LatestmopsList : [Select RE_Pricing_Date__c,RE_Quote_Type__c from RE_Market_Quotes__c where createddate = Today AND RE_Country_Name__c INCLUDES ('SG','PH','TH','MY') AND RE_Is_MTDWTD__c = false AND RE_Quote_Type__c != 'Midday']){
            if(LatestmopsList.RE_Quote_Type__c == 'Settlement') isSettlement = True;             
            if(LatestmopsList.RE_Quote_Type__c == 'Market Premium') isMarkPrem = True; 
            if(LatestmopsList.RE_Quote_Type__c == 'Freight') isFreight = True;             
        }
        for(RE_FX_Rates__c LatestFxRate : [SELECT RE_Conversion_Unit__c,RE_Base_Unit__c FROM RE_FX_Rates__c WHERE createddate = Today  AND RE_Is_MTDWTD__c = false]){
            if(LatestFxRate.RE_Conversion_Unit__c == 'PHP') isPHFx = True; 
        }
        if(holidayMap.containsKey(String.valueOf(System.today().addDays(-1))))
        	isPHFx = True;
        
        if(isSettlement && isMarkPrem && isFreight && isPHFx){
            RE_MarketQuotesTriggerHelper.temperaturegaincalculation();
            List<RE_Job_Run_Audit__c> jraList = new List<RE_Job_Run_Audit__c>();
            Boolean mopsRun = RE_ExternalTriggerHelper.mopsDataTracker();
            Boolean fxRun = RE_ExternalTriggerHelper.fxDataTracker();
            
            if(mopsRun == True && fxRun == True){
                try{                                                         
                    RE_Job_Run_Audit__c jrAuditTH = new RE_Job_Run_Audit__c();
                    jrAuditTH.RE_Run_Time__c = System.now();
                    jrAuditTH.RE_Run_Type__c = 'Automate';
                    jrAuditTH.RE_Job_Type__c = 'Philippines Output';
                    jrAuditTH.RE_User__c = UserInfo.getUserId();
                    jrAuditTH.RE_Job_Run_Count__c = 0;
                    jraList.add(jrAuditTH);                     
                    if(!jraList.isEmpty())
                        insert jraList;
                }
                catch(Exception e){
					System.debug(e.getCause());
                }
            }
        }
        else{
			sendnotification();
        }
    }
    
    public static void sendnotification(){
        List<String> tomail = System.label.RE_TH_Mail_Recipient.split(';');
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setToAddresses(tomail);
            email.setSubject('TH CBU Output not generated for - '+System.Today());
            email.setHtmlBody('Hello, <br/><br/>Since we have not received today`s data from BOT we are not generating PH CBU output. <br/><br/>Regards,<br/> Dev Team');
        	try{
                if(![SELECT Id, isSandbox FROM Organization LIMIT 1].isSandbox)
                    Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });
        	}catch(exception e){
            	apexpages.addmessage(new apexpages.message(apexpages.severity.error,e.getMessage()));
        	}
    }
}