force-app/main/default/objects/RE_FX_Rates__c/RE_FX_Rates__c.object-meta.xml
<CustomObject>
    <label>RE FX Rates</label>
    <nameField>
        <displayFormat>FXR-{000000}</displayFormat>
        <label>FX_Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE FX Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Base_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Base_Unit__c</fullName>
    <label>Base Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Conversion_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Conversion_Unit__c</fullName>
    <label>Conversion Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Forex_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Forex_Name__c</fullName>
    <label>Forex Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Forex_Rate__c.field-meta.xml
<CustomField>
    <fullName>RE_Forex_Rate__c</fullName>
    <label>Forex Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Pricing_Date__c.field-meta.xml
<CustomField>
    <fullName>RE_Pricing_Date__c</fullName>
    <label>Published Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Tracker__c.field-meta.xml
<CustomField>
    <fullName>RE_Tracker__c</fullName>
    <label>Tracker</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>D-1</fullName>
            </value>
            <value>
                <fullName>D-2</fullName>
            </value>
            <value>
                <fullName>D+1</fullName>
            </value>
            <value>
                <fullName>MTD</fullName>
            </value>
            <value>
                <fullName>WTD</fullName>
            </value>
            <value>
                <fullName>W-1</fullName>
            </value>
            <value>
                <fullName>W-2</fullName>
            </value>
            <value>
                <fullName>M-1</fullName>
            </value>
            <value>
                <fullName>M-2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Trade_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Trade_Type__c</fullName>
    <label>Trade Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
            <value>
                <fullName>Exchange Rate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Gain_Loss_Audit__c/RE_Gain_Loss_Audit__c.object-meta.xml
<CustomObject>
    <label>Gain Loss Audit</label>
    <nameField>
        <displayFormat>GLA-{0000000}</displayFormat>
        <label>Gain Loss Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gain Loss Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Gain_Loss_Audit__c/fields/RE_Month__c.field-meta.xml
<CustomField>
    <fullName>RE_Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Jan</fullName>
            </value>
            <value>
                <fullName>Feb</fullName>
            </value>
            <value>
                <fullName>Mar</fullName>
            </value>
            <value>
                <fullName>Apr</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>Jun</fullName>
            </value>
            <value>
                <fullName>Jul</fullName>
            </value>
            <value>
                <fullName>Aug</fullName>
            </value>
            <value>
                <fullName>Sep</fullName>
            </value>
            <value>
                <fullName>Oct</fullName>
            </value>
            <value>
                <fullName>Nov</fullName>
            </value>
            <value>
                <fullName>Dec</fullName>
            </value>
            <value>
                <fullName>July</fullName>
                <isActive>false</isActive>
                <label>July</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Gain_Loss_Audit__c/fields/RE_MonthlyAverage__c.field-meta.xml
<CustomField>
    <fullName>RE_MonthlyAverage__c</fullName>
    <label>M-1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Gain_Loss_Audit__c/fields/RE_Months_Avg__c.field-meta.xml
<CustomField>
    <fullName>RE_Months_Avg__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Months</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Gain_Loss_Audit__c/fields/RE_MOPS_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_MOPS_Name__c</fullName>
    <label>MOPS Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Gain_Loss_Audit__c/fields/RE_Published_Date__c.field-meta.xml
<CustomField>
    <fullName>RE_Published_Date__c</fullName>
    <label>Published Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_Gain_Loss_Audit__c/fields/RE_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>W-1</fullName>
            </value>
            <value>
                <fullName>M-1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Gain_Loss_Audit__c/fields/RE_Week_Number__c.field-meta.xml
<CustomField>
    <fullName>RE_Week_Number__c</fullName>
    <label>Week Number</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Week 1</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Week 2</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Week 3</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Week 4</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Week 5</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Week 6</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Gain_Loss_Audit__c/fields/RE_WeekAverage__c.field-meta.xml
<CustomField>
    <fullName>RE_WeekAverage__c</fullName>
    <label>W-1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Gain_Loss_Audit__c/fields/RE_Weeks_AVG__c.field-meta.xml
<CustomField>
    <fullName>RE_Weeks_AVG__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Weeks</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Gain_Loss_Audit__c/fields/RE_Year__c.field-meta.xml
<CustomField>
    <fullName>RE_Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Gain_Loss_Audit__c/recordTypes/Malaysia.recordType-meta.xml
<RecordType>
    <fullName>Malaysia</fullName>
    <active>true</active>
    <label>Malaysia</label>
</RecordType>

force-app/main/default/objects/RE_Gain_Loss_Audit__c/recordTypes/Thailand.recordType-meta.xml
<RecordType>
    <fullName>Thailand</fullName>
    <active>true</active>
    <label>Thailand</label>
</RecordType>

force-app/main/default/objects/RE_Market_Quotes__c/RE_Market_Quotes__c.object-meta.xml
<CustomObject>
    <label>RE Market Quotes</label>
    <nameField>
        <displayFormat>MarketQuote-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Market Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Price__c.field-meta.xml
<CustomField>
    <fullName>RE_Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Type__c</fullName>
    <label>Quote Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Market Premium</fullName>
            </value>
            <value>
                <fullName>Assessed Premium</fullName>
            </value>
            <value>
                <fullName>Midday</fullName>
            </value>
            <value>
                <fullName>Forward Swap</fullName>
            </value>
            <value>
                <fullName>Spot</fullName>
            </value>
            <value>
                <fullName>Freight</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Tracker__c.field-meta.xml
<CustomField>
    <fullName>RE_Tracker__c</fullName>
    <label>Tracker</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>D-1</fullName>
            </value>
            <value>
                <fullName>MTD</fullName>
            </value>
            <value>
                <fullName>WTD</fullName>
            </value>
            <value>
                <fullName>W-1</fullName>
            </value>
            <value>
                <fullName>W-2</fullName>
            </value>
            <value>
                <fullName>M-1</fullName>
            </value>
            <value>
                <fullName>M-2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Weekly_Data__c/RE_Weekly_Data__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>RE_Weekly_Data</label>
</CustomObject>

force-app/main/default/objects/RE_Weekly_Data__c/fields/RE_Month__c.field-meta.xml
<CustomField>
    <fullName>RE_Month__c</fullName>
    <label>Month</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Weekly_Data__c/fields/RE_Valid_From__c.field-meta.xml
<CustomField>
    <fullName>RE_Valid_From__c</fullName>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_Weekly_Data__c/fields/RE_Valid_To__c.field-meta.xml
<CustomField>
    <fullName>RE_Valid_To__c</fullName>
    <label>Valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_Weekly_Data__c/fields/RE_Week_End_Date__c.field-meta.xml
<CustomField>
    <fullName>RE_Week_End_Date__c</fullName>
    <label>Week End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_Weekly_Data__c/fields/RE_Week_Number__c.field-meta.xml
<CustomField>
    <fullName>RE_Week_Number__c</fullName>
    <label>Week Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Weekly_Data__c/fields/RE_Week_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>RE_Week_Start_Date__c</fullName>
    <label>Week Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_Weekly_Data__c/fields/RE_Year__c.field-meta.xml
<CustomField>
    <fullName>RE_Year__c</fullName>
    <label>Year</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RE_GainLossControllerTest.cls
/*******************************************************************************************************************************************************-*********
@ Class:          RE_GainLossControllerTest
@ Version:        1.0
@ Author:         Sunidhi Pandey
@ Purpose:        Test classes for RE_GainLossController. 
------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
@isTest
    public class RE_GainLossControllerTest {
    
    public static testmethod void InitialTestDetails(){
        
        Country__c createCtry1 = RE_UtilityClass.getCountryCode('Malaysia');
        Country__c createCtry2 = RE_UtilityClass.getCountryCode('Thailand');
        
         //Fetch Custom Setting Data For Rate
        RE_UtilityClass.fetchRateUnitData();
        
        //Fetch Custom Setting Data For Volume
        RE_UtilityClass.fetchVolumeConversionData();
        
     //Creating Latest Market Quotes data
        RE_Market_Quotes__c createMQ1  = RE_UtilityClass.getMarketQuotes(23.6560,'USD/BBL','BBL','MID RON PREMIUM','D');
        RE_Market_Quotes__c createMQ2  = RE_UtilityClass.getMarketQuotes(57.4658,'USD/BBL','BBL','Gasoil 0.05% S','D');
        RE_Market_Quotes__c createMQ3  = RE_UtilityClass.getMarketQuotes(33.6560,'USD/BBL','BBL','Gasoil 0.001% S','D');
        RE_Market_Quotes__c createMQ4  = RE_UtilityClass.getMarketQuotes(27.4658,'USD/BBL','BBL','Gasoil 0.25% S','D');
        RE_Market_Quotes__c createMQ5  = RE_UtilityClass.getMarketQuotes(27.4658,'USD/BBL','BBL','Gasoil 0.001% Premium','D');
        RE_Market_Quotes__c createMQ6  = RE_UtilityClass.getMarketQuotes(17.4658,'USD/BBL','BBL','Kero','D');
        RE_Market_Quotes__c createMQ7  = RE_UtilityClass.getMarketQuotes(27.4658,'USD/BBL','BBL','MOGAS 97','D');
        RE_Market_Quotes__c createMQ8  = RE_UtilityClass.getMarketQuotes(27.4658,'USD/BBL','BBL','MOGAS 95','D');
        RE_Market_Quotes__c createMQ9  = RE_UtilityClass.getMarketQuotes(17.4658,'USD/BBL','BBL','Kero Premium','D');
        RE_Market_Quotes__c createMQ10  = RE_UtilityClass.getMarketQuotes(17.4658,'USD/BBL','BBL','Distillation Discount','D');
        
        createMQ2.RE_Quote_Type__c='Settlement';
        update createMQ2;
        RE_FX_Rates__c sFXRates= new RE_FX_Rates__c(RE_Forex_Name__c='MYR CTS/USD',
                                                    RE_Forex_Rate__c=135.235,
                                                    RE_Base_Unit__c='USD',
                                                    RE_Conversion_Unit__c='MYR CTS',
                                                    RE_Pricing_Date__c=System.now()+1,
                                                    RE_Trade_Type__c = 'Sell',
                                                    RE_Tracker__c = 'D+1');
        insert sFXRates;
        RE_FX_Rates__c sFXRates1= new RE_FX_Rates__c(RE_Forex_Name__c='MYR CTS/USD',
                                                    RE_Forex_Rate__c=135.235,
                                                    RE_Base_Unit__c='USD',
                                                    RE_Conversion_Unit__c='MYR CTS',
                                                    RE_Pricing_Date__c=System.now()-5,
                                                    RE_Trade_Type__c = 'Sell',
                                                    RE_Tracker__c = 'D');
        insert sFXRates1;
        RE_FX_Rates__c sFXRates2= new RE_FX_Rates__c(RE_Forex_Name__c='THB/USD',
                                                    RE_Forex_Rate__c=135.235,
                                                    RE_Base_Unit__c='USD',
                                                    RE_Conversion_Unit__c='THB',
                                                    RE_Pricing_Date__c=System.now()-5,
                                                    RE_Trade_Type__c = 'Sell',
                                                    RE_Tracker__c = 'D');
        insert sFXRates2;
               
		RE_FX_Rates__c fX1 = RE_UtilityClass.createFXRecords('MYR CTS/USD',136.2900,'USD','MYR CTS','Malaysia','D'); 
      	RE_FX_Rates__c fX2 = RE_UtilityClass.createFXRecords('MYR/USD',1.3629,'USD','MYR','Malaysia','D');
      	RE_FX_Rates__c fX3 = RE_UtilityClass.createFXRecords('THB/USD',1.3629,'USD','THB','Thailand','D');
        
    //Creating Custom setting data
        RE_Weekly_Data__c weeklyData1 = new RE_Weekly_Data__c();
        weeklyData1.Name ='WD-0001';
        weeklyData1.RE_Month__c ='Apr';
        weeklyData1.RE_Valid_From__c = System.Today()-31;
        weeklyData1.RE_Valid_To__c = System.Today()+31;
        weeklyData1.RE_Week_End_Date__c = System.Today();
        weeklyData1.RE_Week_Number__c = '1';
        weeklyData1.RE_Week_Start_Date__c =System.Today();
        weeklyData1.RE_Year__c ='2020';
        insert weeklyData1;
       
       RE_Gain_Loss_Audit__c glaudit = new RE_Gain_Loss_Audit__c (RE_WeekAverage__c=2.22,
                                                                  RE_MOPS_Name__c = 'Gasoil 0.001% S',
                                                                  RE_MonthlyAverage__c = 2.33,
                                                                  RE_Published_Date__c = System.today(),
                                                                  RE_Type__c = 'W-1',
                                                                  RE_Weeks_AVG__c = 2.22,
                                                                  RE_Months_AVG__c = 3.23,
                                                                  RE_Week_Number__c ='1',
                                                                  RE_Year__c = '2020',
                                                                  RE_Month__c = 'Apr',
                                                                  RE_Price__c  = 170.66,
                                                                  recordtypeId	=	Schema.SObjectType.RE_Gain_Loss_Audit__c.getRecordTypeInfosByName().get('Malaysia').getRecordTypeId(),
                                                                 RE_Quote_Name__c=createMQ1.Id);
        RE_Gain_Loss_Audit__c glaudit2 = new RE_Gain_Loss_Audit__c (RE_WeekAverage__c=2.22,
                                                                  RE_MOPS_Name__c = 'Gasoil 0.001% S',
                                                                  RE_MonthlyAverage__c = 2.33,
                                                                  RE_Published_Date__c = System.today(),
                                                                  RE_Type__c = 'M-1',
                                                                  RE_Weeks_AVG__c = 2.22,
                                                                  RE_Months_AVG__c = 3.23,
                                                                  RE_Week_Number__c ='1',
                                                                  RE_Year__c = '2020',
                                                                  RE_Month__c = 'Apr',
                                                                  RE_Price__c  = 170.66,
                                                                  recordtypeId	=	Schema.SObjectType.RE_Gain_Loss_Audit__c.getRecordTypeInfosByName().get('Malaysia').getRecordTypeId(),
                                                                  RE_Quote_Name__c=createMQ2.Id);
        insert glaudit;
        insert glaudit2;        
        
        Test.startTest();
        RE_GainLossController.OptionWrapper optionWrap = new RE_GainLossController.OptionWrapper('Kero','Kero');
        RE_GainLossController.getMopsProducts();
        RE_GainLossController.GainLossWrapper gainLossWrappr = new RE_GainLossController.GainLossWrapper();
        gainLossWrappr.liftingDate = 'test';
        gainLossWrappr.Differences=2.22;
        gainLossWrappr.monthAverage = 7.87;
        gainLossWrappr.Position = 'test';
        gainLossWrappr.week_1 = 8.66;
        gainLossWrappr.weeks = 'week1';
        RE_GainLossController.gainLossDetails('Gasoil 0.001% S','Malaysia');
        RE_GainLossController.glWrap gainWrap = new RE_GainLossController.glWrap();
        gainWrap.monthlydifference = 3.33;
        gainWrap.mopsdata = 'Gasoil 0.001% S';
        gainWrap.weeklydifference = 4.45;
        RE_Gain_Loss_Audit__c glaudit1 = new RE_Gain_Loss_Audit__c (RE_WeekAverage__c=2.22,
                                                                  RE_MOPS_Name__c = 'Gasoil 0.001% S',
                                                                 RE_MonthlyAverage__c = 2.33,
                                                                 RE_Published_Date__c = System.today(),
                                                                 RE_Type__c = 'D',
                                                                 RE_Price__c  = 170.66,
                                                                 recordtypeId	=	Schema.SObjectType.RE_Gain_Loss_Audit__c.getRecordTypeInfosByName().get('Malaysia').getRecordTypeId(),
                                                                 RE_Quote_Name__c=createMQ2.Id);
        insert glaudit1;
        RE_GainLossController.fetchGainLossData('Gasoil 0.001% S','Malaysia');
        RE_UtilityClass.getCountryCode('Singapore');
        RE_UtilityClass.getProduct('IGO 10ppm','Singapore','SGD CTS/LTR');
        list<RE_Product__c>  prodlist = RE_GainLossClass.fetchMC0Data();
        RE_GainLossClass.updateRecords(prodlist);
        RE_ExternalTriggerHelper.CreateLagAuditData();
       	RE_ExternalTriggerHelper.createweeklyLagData('MYR CTS','MYR CTS/LTR','Malaysia');
        RE_ExternalTriggerHelper.createmonthlyLagData('MYR CTS','MYR CTS/LTR','Malaysia');
        RE_CreateLagAuditDataScheduler ob= new RE_CreateLagAuditDataScheduler();
        ob.execute(null);
        RE_ExternalTriggerHelper.createDailyLagAuditData('MYR CTS/LTR','Malaysia');
        
        Test.stopTest();
     	
    }

}