force-app/main/default/objects/RE_FX_Rates__c/RE_FX_Rates__c.object-meta.xml
<CustomObject>
    <label>RE FX Rates</label>
    <nameField>
        <displayFormat>FXR-{000000}</displayFormat>
        <label>FX_Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE FX Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Base_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Base_Unit__c</fullName>
    <label>Base Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Conversion_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Conversion_Unit__c</fullName>
    <label>Conversion Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Forex_Rate__c.field-meta.xml
<CustomField>
    <fullName>RE_Forex_Rate__c</fullName>
    <label>Forex Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Is_MTDWTD__c.field-meta.xml
<CustomField>
    <fullName>RE_Is_MTDWTD__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is MTDWTD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Pricing_Date__c.field-meta.xml
<CustomField>
    <fullName>RE_Pricing_Date__c</fullName>
    <label>Published Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Tracker__c.field-meta.xml
<CustomField>
    <fullName>RE_Tracker__c</fullName>
    <label>Tracker</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>D-1</fullName>
            </value>
            <value>
                <fullName>D-2</fullName>
            </value>
            <value>
                <fullName>D+1</fullName>
            </value>
            <value>
                <fullName>MTD</fullName>
            </value>
            <value>
                <fullName>WTD</fullName>
            </value>
            <value>
                <fullName>W-1</fullName>
            </value>
            <value>
                <fullName>W-2</fullName>
            </value>
            <value>
                <fullName>M-1</fullName>
            </value>
            <value>
                <fullName>M-2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Trade_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Trade_Type__c</fullName>
    <label>Trade Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
            <value>
                <fullName>Exchange Rate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/RE_Job_Run_Audit__c.object-meta.xml
<CustomObject>
    <label>Job Run Audit</label>
    <nameField>
        <displayFormat>JR-{00000000}</displayFormat>
        <label>Job Run Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Run Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Job_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Malaysia Output</fullName>
            </value>
            <value>
                <fullName>Singapore Output</fullName>
            </value>
            <value>
                <fullName>SG Midday Output</fullName>
            </value>
            <value>
                <fullName>Malaysia AMV Output</fullName>
            </value>
            <value>
                <fullName>Thailand Output</fullName>
            </value>
            <value>
                <fullName>CustomerOps Output</fullName>
            </value>
            <value>
                <fullName>New Contract Pricing Output</fullName>
            </value>
            <value>
                <fullName>Thailand AMV Output</fullName>
            </value>
            <value>
                <fullName>MY Export Report</fullName>
            </value>
            <value>
                <fullName>MY Customer Opps CBU</fullName>
            </value>
            <value>
                <fullName>Philippines Output</fullName>
            </value>
            <value>
                <fullName>Canada Daily Reuters Quote Move</fullName>
            </value>
            <value>
                <fullName>Canada Execute Depo Pricing</fullName>
            </value>
            <value>
                <fullName>Canada Pricing Recalculation</fullName>
            </value>
            <value>
                <fullName>Canada SFJ Record Creation</fullName>
            </value>
            <value>
                <fullName>Canada Live OPIS Spot Ticker Processing</fullName>
            </value>
            <value>
                <fullName>Canada Market Move Calculation</fullName>
            </value>
            <value>
                <fullName>Canada Competitor Data Processing</fullName>
            </value>
            <value>
                <fullName>Canada GSAP Upload</fullName>
            </value>
            <value>
                <fullName>Canada Email Output</fullName>
            </value>
            <value>
                <fullName>MY Data Analysis Report</fullName>
            </value>
            <value>
                <fullName>PH Customer Opps CBU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Run_Time__c.field-meta.xml
<CustomField>
    <fullName>RE_Run_Time__c</fullName>
    <label>Run Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Run_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Run_Type__c</fullName>
    <label>Run Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automate</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_User__c.field-meta.xml
<CustomField>
    <fullName>RE_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Job_Run_Audit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RE_FxRatesTriggerHelper.cls
public class RE_FxRatesTriggerHelper {
	//Remove duplicate data from system
    public static void onBeforeTriggerHelper(List<RE_FX_Rates__c> newFxLst
                                             ,Map<ID,RE_FX_Rates__c> oldFxMap
                                             ,Map<ID,RE_FX_Rates__c> newFxMap)
    {
        list<RE_FX_Rates__c> oldFxlist = new list<RE_FX_Rates__c>();
        //Revolution is receiving future exchange rates from ADF. To run the below logic to remove duplicate records, where clause has been changed from RE_Pricing_Date__c to createddate
        for(RE_FX_Rates__c oldFxData : [
            SELECT RE_Conversion_Unit__c,RE_Base_Unit__c,RE_Forex_Rate__c,RE_Pricing_Date__c,RE_Trade_Type__c , RE_Tracker__c
            FROM RE_FX_Rates__c WHERE createddate = LAST_N_DAYS:7 AND Id NOT IN : newFxLst ORDER BY RE_Pricing_Date__c DESC
        ]){
            for(RE_FX_Rates__c newdata : newFxLst){
                if(newdata.RE_Pricing_Date__c == oldFxData.RE_Pricing_Date__c 
                   	&& newdata.RE_Base_Unit__c == oldFxData.RE_Base_Unit__c
                  	&& newdata.RE_Conversion_Unit__c == oldFxData.RE_Conversion_Unit__c 
                   	&& newdata.RE_Trade_Type__c == oldFxData.RE_Trade_Type__c
                    && newdata.RE_Is_MTDWTD__c == False){
					oldFxlist.add(oldFxData);
                    newdata.RE_Tracker__c = oldFxData.RE_Tracker__c;
				}
                if(newdata.RE_Pricing_Date__c == oldFxData.RE_Pricing_Date__c 
                   	&& newdata.RE_Base_Unit__c == oldFxData.RE_Base_Unit__c
                  	&& newdata.RE_Conversion_Unit__c == oldFxData.RE_Conversion_Unit__c 
                   	&& newdata.RE_Trade_Type__c == oldFxData.RE_Trade_Type__c
                    && newdata.RE_Is_MTDWTD__c == True
                  	&& newdata.RE_Tracker__c == oldFxData.RE_Tracker__c){
					oldFxlist.add(oldFxData);
				}
            }                                 
        }
        
        if(!oldFxlist.isEmpty())
        {
            try{delete oldFxlist;}
            catch(Exception e)
            {System.debug('Failed while delete to Fx Rates -- '+e.getMessage());}
        }
    }
    public static void onAfterTriggerHelper(List<RE_FX_Rates__c> newFxLst ,Map<ID,RE_FX_Rates__c> oldFxMap ,Map<ID,RE_FX_Rates__c> newFxMap){
        List<RE_Job_Run_Audit__c> jraList = new List<RE_Job_Run_Audit__c>();
        List<String> typelist = new List<String>();
        for(RE_FX_Rates__c quotes : newFxLst){
            if(quotes.RE_Tracker__c != null && !typelist.contains(quotes.RE_Tracker__c)){
                typelist.add(quotes.RE_Tracker__c);
            }            
        }
        if(typelist.contains('W-1')){
            System.debug('inside fX trigger for W1');
            RE_Job_Run_Audit__c jrAuditW1 = new RE_Job_Run_Audit__c();
            jrAuditW1.RE_Run_Time__c = System.now();
            jrAuditW1.RE_Run_Type__c = 'Automate';
            jrAuditW1.RE_Job_Type__c = 'Philippines W-1 Output';
            jrAuditW1.RE_User__c = UserInfo.getUserId();
            jrAuditW1.RE_Job_Run_Count__c = 0;
            jraList.add(jrAuditW1);
        }
        if(typelist.contains('M-1')){
        	RE_Job_Run_Audit__c jrAuditM1 = new RE_Job_Run_Audit__c();
            jrAuditM1.RE_Run_Time__c = System.now();
            jrAuditM1.RE_Run_Type__c = 'Automate';
            jrAuditM1.RE_Job_Type__c = 'Philippines M-1 Output';
            jrAuditM1.RE_User__c = UserInfo.getUserId();
            jrAuditM1.RE_Job_Run_Count__c = 0;
            jraList.add(jrAuditM1);
        }
        if(!jraList.isEmpty()){
            try{insert jraList;}
            catch(Exception ex){system.debug(ex.getCause());}
        }
    }
    
}