force-app/main/default/objects/Account/fields/Billing_Block__c.field-meta.xml
<CustomField>
    <fullName>Billing_Block__c</fullName>
    <description>Billing Block</description>
    <label>Billing Block</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Calculation Missing</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Compl Confirm Missng</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Prices Incomplete</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Check Terms of Paymt</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Check Terms of Dlv</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Check Credit Memo</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Check Debit Memo</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Entered in error</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sold To</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Delivery_Block__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Block__c</fullName>
    <description>Delivery Block</description>
    <label>Delivery Block</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Credit limit</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Political reasons</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Bottleneck material</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Export papers missng</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Check free of ch.dlv</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>No printing</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Quantity Change</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Kanban Delivery</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Incoterms1__c.field-meta.xml
<CustomField>
    <fullName>Incoterms1__c</fullName>
    <description>Incoterms</description>
    <label>Incoterms1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>FCA</fullName>
            </value>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>CFR</fullName>
            </value>
            <value>
                <fullName>FIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Incoterms2__c.field-meta.xml
<CustomField>
    <fullName>Incoterms2__c</fullName>
    <description>Incoterms</description>
    <label>Incoterms2</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mode_of_Transport__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Transport__c</fullName>
    <description>Mode of Transport</description>
    <label>Mode of Transport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Rail</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Road Tank Truck</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Bulk tanker</label>
            </value>
            <value>
                <fullName>36</fullName>
                <label>Road IM Portable Tnk</label>
            </value>
            <value>
                <fullName>1J</fullName>
                <label>Bulk Cont. road/sea</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Rail Tank Car</label>
            </value>
            <value>
                <fullName>37</fullName>
                <label>Road (Bulk)  / Rail</label>
            </value>
            <value>
                <fullName>39</fullName>
                <label>Road(Bulk)/Short Sea</label>
            </value>
            <value>
                <fullName>80</fullName>
                <label>Inland water-transpt</label>
            </value>
            <value>
                <fullName>3A</fullName>
                <label>Road(Pack)/Short Sea</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>Air-transport</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>Pipeline-transport</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Order_Block__c.field-meta.xml
<CustomField>
    <fullName>Order_Block__c</fullName>
    <description>Order Block</description>
    <label>Order Block</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Overall block</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>All free of charge</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Test block</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Counter__c.field-meta.xml
<CustomField>
    <fullName>Partner_Counter__c</fullName>
    <label>Partner Counter</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Function__c.field-meta.xml
<CustomField>
    <fullName>Partner_Function__c</fullName>
    <label>Partner Function</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Area__c.field-meta.xml
<CustomField>
    <fullName>Sales_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Area</label>
    <referenceTo>TCP_Sales_Area__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/TCP_P94_Partner_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>TCP_P94_Partner_Account_Number__c</fullName>
    <label>TCP P94 Partner Account Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TCP_Sales_Area_text__c.field-meta.xml
<CustomField>
    <fullName>TCP_Sales_Area_text__c</fullName>
    <label>Sales Area text</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/TCP_Account.recordType-meta.xml
<RecordType>
    <fullName>TCP_Account</fullName>
    <active>true</active>
    <label>TCP Account</label>
</RecordType>

force-app/main/default/objects/TCP_P94_Staging_object__c/TCP_P94_Staging_object__c.object-meta.xml
<CustomObject>
    <description>TCP P94 Staging Object</description>
    <label>TCP P94 Staging object</label>
    <nameField>
        <label>TCP P94 Staging object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TCP P94 Staging object</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TCP_P94_Staging_object__c/fields/Billing_Block__c.field-meta.xml
<CustomField>
    <fullName>Billing_Block__c</fullName>
    <label>Billing Block</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_P94_Staging_object__c/fields/Cust_No_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Cust_No_External_Id__c</fullName>
    <description>SPCustomerNo +Sales Org + DC +Divison + SPCustomerNo + Partner Function
SPCustomerNo +Sales Org + DC +Divison + SHCustomerNo + Partner Function
SPCustomerNo +Sales Org + DC +Divison + PYCustomerNo + Partner Function
SPCustomerNo +Sales Org + DC +Divison + BPCustomerNo + Partner Function</description>
    <label>Customer No ExternalID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_P94_Staging_object__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <description>&apos;CUST&apos; for Customer Master Data, &apos;MATR&apos; for Material Master Data and &apos;CMIR&apos; for CMIR Data</description>
    <label>Data Type</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_P94_Staging_object__c/fields/Delivery_Block__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Block__c</fullName>
    <label>Delivery Block</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_P94_Staging_object__c/fields/Incoterms1__c.field-meta.xml
<CustomField>
    <fullName>Incoterms1__c</fullName>
    <label>Incoterms1</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_P94_Staging_object__c/fields/Incoterms2__c.field-meta.xml
<CustomField>
    <fullName>Incoterms2__c</fullName>
    <label>Incoterms2</label>
    <length>28</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_P94_Staging_object__c/fields/Is_Cust_Processed__c.field-meta.xml
<CustomField>
    <fullName>Is_Cust_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>by default False, if the record is successfully inserted then mark it as True</description>
    <label>Is Customer Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TCP_P94_Staging_object__c/fields/Order_Block__c.field-meta.xml
<CustomField>
    <fullName>Order_Block__c</fullName>
    <label>Order Block</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_P94_Staging_object__c/fields/Partner_Counter__c.field-meta.xml
<CustomField>
    <fullName>Partner_Counter__c</fullName>
    <label>Partner Counter</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_P94_Staging_object__c/fields/Partner_Number__c.field-meta.xml
<CustomField>
    <fullName>Partner_Number__c</fullName>
    <label>Partner Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_P94_Staging_object__c/fields/Sales_Area_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Sales_Area_External_Id__c</fullName>
    <description>Sales Org + Distribution Channel +Division</description>
    <label>Sales Area ExternalID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_P94_Staging_object__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_Sales_Area__c/TCP_Sales_Area__c.object-meta.xml
<CustomObject>
    <label>Sales Area</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Sales Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Area</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TCP_Sales_Area__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <label>Distribution Channel</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_Sales_Area__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_Sales_Area__c/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_Sales_Area__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TCP_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TCP_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EAST</fullName>
    </customValue>
    <customValue>
        <fullName>EUROPE</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>Singapore</fullName>
        <isActive>false</isActive>
        <label>Singapore</label>
    </customValue>
    <masterLabel>TCP Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TCP_P94_AccountSyncBatchHelper.cls
/* Description - Batch Helper Class which will run every 4 hours for P94 Account Staging Records. This Staging Records will be a dump from GSAP system 
 * via DDF/Biztalk system as part of P94.
 * Date - 02-05-2023
 * Created By - Madhu Javvaji
 */

 /* Handler Class to process all the account staging records in a batch to create/update the relevent Account records as part of
  * P94 Customer master data Intgeration */
public class TCP_P94_AccountSyncBatchHelper {
    
    //Constants
    static final String SelectString = 'SELECT';
    
    public static string tcpAccountRecTypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('TCP_Account').getRecordTypeId();
    
    /* Method to fetch all the Account staging records to be processed in the start method of the batch */
    public Static String getQuery(){
        Set<String> SobjectFields = Schema.getGlobalDescribe().get('TCP_P94_Staging_object__c').getDescribe().fields.getMap().keySet();
		String P94DataTypeVal = 'CUST';        
        String query = SelectString + ' ' + String.join(new List<String>(SobjectFields), ',') + 
            	   	   ' FROM TCP_P94_Staging_object__c WHERE Is_Cust_Processed__c=false AND Data_Type__c = \'CUST\' AND  Cust_No_External_Id__c != NULL AND Sales_Area_External_ID__c != NULL Order By CreatedDate';
                
        //include the filter "AND Data_Type__c = 'CUST'"AND Data_Type__c = \'CUST\'
        return query;        
    }
    
    /* Method to upsert Account records based on P94 Account staging records */
    public static void upsertAccounts(List<TCP_P94_Staging_object__c> stagingRecords){ 
    	Map<String,TCP_P94_Staging_object__c> stagingMap = new Map<String,TCP_P94_Staging_object__c>();
        List<TCP_P94_Staging_object__c> stagingProcessedRecords = new List<TCP_P94_Staging_object__c>();
        List<Account> accountParentIdUpdatedRecords = new List<account>();
		//filter staging records
        for(TCP_P94_Staging_object__c stagingRec : stagingRecords){
            if(stagingMap != Null && stagingMap.containsKey(stagingRec.Cust_No_External_Id__c)){
                TCP_P94_Staging_object__c s = stagingMap.get(stagingRec.Cust_No_External_Id__c);
                s.Is_Cust_Processed__c = true;
                stagingProcessedRecords.add(s);
                stagingMap.put(stagingRec.Cust_No_External_Id__c,stagingRec);                
            }
            else{
            	stagingMap.put(stagingRec.Cust_No_External_Id__c,stagingRec);
            }
        }  
        
        //upsert accounts
        
        List<TCP_Sales_Area__c> salesAreaData = new List<TCP_Sales_Area__c>();
        List<Account> accountParentId = new List<Account>();
        Map<String,TCP_Sales_Area__c> salesAreaMap = new Map<String,TCP_Sales_Area__c>();
        Map<String, Account> accMap = new Map<String, Account>();
        
        List<Account> accountsToUpsert = new List<Account>();
        List<Account> accountsParentIdUpdateList = new List<Account>();
        List<TCP_P94_Staging_object__c> stagingRecsList = new List<TCP_P94_Staging_object__c>();
        list<Account> finalUpsertAccountList =  new list<Account>();
        
        salesAreaData = [SELECT Id, Sales_Org__c, Distribution_Channel__c, Division__c, Name, Sales_Region__c FROM TCP_Sales_Area__c];
                    
        if (salesAreaData != null){
        	for(TCP_Sales_Area__c sArea : salesAreaData){
            	String key = sArea.Sales_Org__c + sArea.Distribution_Channel__c + sArea.Division__c;                
                salesAreaMap.put(key,sArea);
            }    
        } 
        
        for(TCP_P94_Staging_object__c stagingRec : stagingMap.values()){
            
            string salesAreaKey = stagingRec.Sales_Org__c + stagingRec.Distribution_Channel__c + stagingRec.Division__c;             
            TCP_Sales_Area__c salesArea =  salesAreaMap.get(salesAreaKey);
                        
        	Account a = new Account();
            a.Name = stagingRec.Name;           	
           	a.AccountNumber = stagingRec.Partner_Number__c;
            a.Sales_Area__c = salesArea.Id;
            a.TCP_Sales_Area_text__c = salesArea.Sales_Region__c;			
			a.TCP_P94_Partner_Account_Number__c = stagingRec.Partner_Number__c;
			a.Partner_Function__c = stagingRec.Partner_Function__c;
            if(stagingRec.Partner_Function__c == 'SP'){
            	a.Customer_Type__c = 'Sold To';    
            }else if (stagingRec.Partner_Function__c == 'SH'){
                a.Customer_Type__c = 'Ship To';    
            }else if (stagingRec.Partner_Function__c == 'BP'){
                a.Customer_Type__c = 'Bill To';    
            }else if (stagingRec.Partner_Function__c == 'PY'){
                a.Customer_Type__c = 'Payer';    
            }			
			a.Partner_Counter__c = stagingRec.Partner_Counter__c;
			a.ShippingStreet = stagingRec.Street__c;
			a.ShippingCity = stagingRec.City__c;
            a.ShippingState = stagingRec.State__c;
			a.ShippingCountry = stagingRec.Country__c;
            a.ShippingPostalCode = stagingRec.Postal_Code__c;
			a.Billing_Block__c = stagingRec.Billing_Block__c;
			a.Delivery_Block__c = stagingRec.Delivery_Block__c;
			a.Order_Block__c = stagingRec.Order_Block__c;            
			a.Incoterms1__c = stagingRec.Incoterms1__c;
			a.Incoterms2__c = stagingRec.Incoterms2__c;
			a.Mode_of_Transport__c = stagingRec.Shipping_Conditions__c;
            a.TCP_Payment_Terms__c = stagingRec.Payment_Terms__c;			
			a.VAT_Reg_No__c = stagingRec.VAT_Reg_No__c;
            a.TCP_P94_Cust_ExternalID__c = stagingRec.Cust_No_External_Id__c;
            a.RecordTypeId =  tcpAccountRecTypeid;
            a.Active__c = !(stagingRec.Deletion_flag__c);
            a.TCP_P94_Sold_To_Account_Group__c = stagingRec.Sold_To_Account_Group__c;
            a.TCP_P94_Partner_Account_Group__c = stagingRec.Partner_Account_Group__c;
			accountsToUpsert.add(a); 
            stagingRecsList.add(stagingRec);
        }
        Schema.SObjectField ftoken = Account.Fields.TCP_P94_Cust_ExternalID__c;
          
        //Processing Result
        Database.UpsertResult[] results = Database.upsert(accountsToUpsert,ftoken,false);
        accountParentId = [SELECT Id, Name, AccountNumber,Customer_Type__c,ParentId,TCP_P94_Cust_ExternalID__c FROM Account where Customer_Type__c = 'Sold To' AND TCP_P94_Cust_ExternalID__c != null];
        if(accountParentId != null){
        	for(Account acc : accountParentId){
            	accMap.put(acc.TCP_P94_Cust_ExternalID__c, acc); 
            }    
        }
        for(Integer i=0; i<results.size();i++){
            if(results[i].isSuccess()){                
                string soldToExternalId = stagingRecsList[i].Sold_To__c + stagingRecsList[i].Sales_Org__c + stagingRecsList[i].Distribution_Channel__c + stagingRecsList[i].Division__c + stagingRecsList[i].Sold_To__c + 'SP';
            	Account accSoldToExtId = accMap.get(soldToExternalId);
                                
                Account accParentId = new Account();
                accParentId.Id = results[i].Id;
                If(stagingRecsList[i].Partner_Function__c != 'SP'){
                	accParentId.ParentId = accSoldToExtId.Id;    
                }
                
                accountParentIdUpdatedRecords.add(accParentId);                
                
                TCP_P94_Staging_object__c s = new TCP_P94_Staging_object__c();
                s.Id = stagingRecsList[i].Id;
                s.Is_Cust_Processed__c = true;
                stagingProcessedRecords.add(s);               
            }
            else if(!results[i].isSuccess()){                
                for(Database.Error e : results[i].getErrors()) {                    
                    TCP_ExceptionLogClass.insertExceptionRecord('Upsert the Accounts from P94 staging object',e.getMessage(),'TCP_P94_AccountSyncBatchHelper','upsertAccounts','Exception');            
                   
                }
            }
        }
        Database.update(stagingProcessedRecords);  
        Database.update(accountParentIdUpdatedRecords);
    }    

}