force-app/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sold To</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Area__c.field-meta.xml
<CustomField>
    <fullName>Sales_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Area</label>
    <referenceTo>TCP_Sales_Area__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/TCP_STNSAP_ExternalId1__c.field-meta.xml
<CustomField>
    <fullName>TCP_STNSAP_ExternalId1__c</fullName>
    <description>this is the unique and external Id reference field consider for the 1st Service STNSAP SoldTo</description>
    <externalId>true</externalId>
    <label>STNSAP ExternalId1</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/TCP_STNSAP_ExternalId2__c.field-meta.xml
<CustomField>
    <fullName>TCP_STNSAP_ExternalId2__c</fullName>
    <description>this is the unique and external Id reference field consider for the 2nd Service STNSAP Shipto, billto</description>
    <externalId>true</externalId>
    <label>STNSAP ExternalId2</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TCP_STNSAPProductCMIRSchedulerTest.cls
@isTest
public class TCP_STNSAPProductCMIRSchedulerTest {
  
    
    @TestSetup
    static void createTestData() {       
    	 
         List<Account> testAccountsList=TCP_TestDataUtilities.createParentAccountsBulk(50);
    }
    
    @isTest
    static  void testScheduledJob() {
        List<Account> acc=[SELECT id, Active__c , AccountNumber, Customer_Type__c, Sales_Area__c, TCP_STNSAP_ExternalId1__c , TCP_STNSAP_ExternalId2__c  FROM Account];
        System.debug('Checking account '+acc);
        String CRON_EXP = '0 0 14 * * ?';
        Test.startTest();      
        String jobId = System.schedule('Account Updates',CRON_EXP,new TCP_STNSAPProductCMIRScheduler());        
        Test.stopTest();
        System.assert(true);
    }
    
 
}