force-app/main/default/objects/Account/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <description>Customer volume, Total demand units/year</description>
    <inlineHelpText>Total Customer volume for their fuel purchases-  Total demand tonnes year</inlineHelpText>
    <label>Total Customer demand</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rv_Credit_Available__c.field-meta.xml
<CustomField>
    <fullName>Rv_Credit_Available__c</fullName>
    <label>Current Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Event_Manager__mdt/Deal_Event_Manager__mdt.object-meta.xml
<CustomObject>
    <label>Deal Event Manager</label>
    <pluralLabel>Deal Event Manager</pluralLabel>
</CustomObject>

force-app/main/default/objects/Deal_Event_Manager__mdt/fields/Shipping_Condition__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Condition__c</fullName>
    <label>Shipping Condition</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Object to store all OU, Region and Location information for Trading and Supply - ATP/AMV/SCHT</description>
    <label>Location</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <description>Plant Number of Depot Code of the particular Plant/Depot</description>
    <label>Plant Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MRC__c/MRC__c.object-meta.xml
<CustomObject>
    <label>MRC</label>
    <nameField>
        <label>MRC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MRC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MRC__c/fields/Material_Description__c.field-meta.xml
<CustomField>
    <fullName>Material_Description__c</fullName>
    <formula>TEXT(Product__r.Commodity_Grade_L2__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Material Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MRC__c/fields/MRC_Number__c.field-meta.xml
<CustomField>
    <fullName>MRC_Number__c</fullName>
    <formula>IF(NOT(OR(BEGINS(Name, &apos;0Barge&apos;), (BEGINS(Name, &apos;0Truck&apos;)))), MID( Name , 0, 10), Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MRC Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MRC__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>MRC</relationshipLabel>
    <relationshipName>MRC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRC__c/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold-To Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected customer is not a valid customer. Please select a valid customer type.</errorMessage>
        <filterItems>
            <field>Account.Customer_Type__c</field>
            <operation>equals</operation>
            <value>Sold To</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MRC</relationshipLabel>
    <relationshipName>MRC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Sold To)</relationshipLabel>
    <relationshipName>Sold_To_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Catalogue__c/Product_Catalogue__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <label>Material Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Catalogue__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipName>Product_Catalogues_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Catalogue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Name_Mapping__mdt/Product_Name_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Product Name Mapping</label>
    <pluralLabel>Product Name Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Product_Name_Mapping__mdt/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AGO B7</fullName>
                <default>true</default>
                <label>AGO B7</label>
            </value>
            <value>
                <fullName>IGO 50ppm</fullName>
            </value>
            <value>
                <fullName>ULG95 E5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Condition_Mapping__mdt/Shipping_Condition_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Shipping Condition Mapping</label>
    <pluralLabel>Shipping Condition Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/Shipping_Condition_Mapping__mdt/fields/MOT__c.field-meta.xml
<CustomField>
    <fullName>MOT__c</fullName>
    <label>MOT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Truck</fullName>
                <default>true</default>
                <label>Truck</label>
            </value>
            <value>
                <fullName>ITT</fullName>
            </value>
            <value>
                <fullName>Rail</fullName>
            </value>
            <value>
                <fullName>Barge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Condition_Mapping__mdt/fields/Shipping_Condition__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Condition__c</fullName>
    <label>Shipping Condition</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SHT__c/SHT__c.object-meta.xml
<CustomObject>
    <label>SHT</label>
    <nameField>
        <displayFormat>SHT - {0}</displayFormat>
        <label>SHT Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SHT</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SHT__c/fields/BSP__c.field-meta.xml
<CustomField>
    <fullName>BSP__c</fullName>
    <label>BSP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Contract_Start__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start__c</fullName>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Revolution</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SHT</relationshipLabel>
    <relationshipName>SHT</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/isOlfDeal__c.field-meta.xml
<CustomField>
    <fullName>isOlfDeal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isOlfDeal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>SHTS</relationshipLabel>
    <relationshipName>SHTS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/MRC__c.field-meta.xml
<CustomField>
    <fullName>MRC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MRC</label>
    <referenceTo>MRC__c</referenceTo>
    <relationshipLabel>SHT</relationshipLabel>
    <relationshipName>SHT</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/MRC_Number__c.field-meta.xml
<CustomField>
    <fullName>MRC_Number__c</fullName>
    <label>MRC Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/MSP__c.field-meta.xml
<CustomField>
    <fullName>MSP__c</fullName>
    <defaultValue>0</defaultValue>
    <label>MSP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/OTM__c.field-meta.xml
<CustomField>
    <fullName>OTM__c</fullName>
    <defaultValue>0</defaultValue>
    <label>OTM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RV_Product_Catalogues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Sales_Type__c.field-meta.xml
<CustomField>
    <fullName>Sales_Type__c</fullName>
    <label>Sales Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internet Sales</fullName>
            </value>
            <value>
                <fullName>Obam Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Select__c.field-meta.xml
<CustomField>
    <fullName>Select__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Select</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/SP_100L__c.field-meta.xml
<CustomField>
    <fullName>SP_100L__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SP €/100L</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Auto-Completed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Tranche__c.field-meta.xml
<CustomField>
    <fullName>Tranche__c</fullName>
    <label>Tranche</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ATP1</fullName>
            </value>
            <value>
                <fullName>ATP2</fullName>
            </value>
            <value>
                <fullName>ATP3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Volume_CBM__c.field-meta.xml
<CustomField>
    <fullName>Volume_CBM__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Volume CBM</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/RV_Product_Catalogues.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AGO B0</fullName>
    </customValue>
    <customValue>
        <fullName>AGO B0 CH</fullName>
    </customValue>
    <customValue>
        <fullName>AGO B7</fullName>
    </customValue>
    <customValue>
        <fullName>AGO VPD</fullName>
    </customValue>
    <customValue>
        <fullName>GTL B0</fullName>
    </customValue>
    <customValue>
        <fullName>GTL B7</fullName>
    </customValue>
    <customValue>
        <fullName>IGO 1000ppm</fullName>
    </customValue>
    <customValue>
        <fullName>IGO 10ppm</fullName>
    </customValue>
    <customValue>
        <fullName>IGO 50ppm</fullName>
    </customValue>
    <customValue>
        <fullName>ULG100 VP</fullName>
    </customValue>
    <customValue>
        <fullName>ULG95_BOB_E10</fullName>
    </customValue>
    <customValue>
        <fullName>ULG95_BOB_E5</fullName>
    </customValue>
    <customValue>
        <fullName>ULG95 E0</fullName>
    </customValue>
    <customValue>
        <fullName>ULG95 E10</fullName>
    </customValue>
    <customValue>
        <fullName>ULG95 E5</fullName>
    </customValue>
    <customValue>
        <fullName>ULG98</fullName>
    </customValue>
    <masterLabel>RV_Product Catalogues</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/OLF_CreateDeal.cls
@RestResource(urlMapping='/createDeal/*')
global class OLF_CreateDeal {
    @HttpPost 
    global static void createOlfDeals(){ 
        RestRequest req = RestContext.request;
        if(OLF_Utility.connectionAllowed()){	//292153_OLFConnectionTime_11Jul2019_Soumyajit
            Map<String, String> headerMap=req.headers;
            OLF_Utility.auditOlfApiLogin(headerMap,'createDeal',system.now());
            Blob body = req.requestBody;
            String requestString = body.toString();
            List<OLFWrapper.MrcPriceWrap> mrcWrpLst=new List<OLFWrapper.MrcPriceWrap>();
            mrcWrpLst=(List<OLFWrapper.MrcPriceWrap>)JSON.deserialize(requestString,List<OLFWrapper.MrcPriceWrap>.class);
            string dealCreationResult=insertOlfDealInSht(mrcWrpLst);
            system.debug('dealCreationResult.message==>'+dealCreationResult);
            //Return Response
            RestContext.response.addHeader('Content-Type', 'application/json');
            RestContext.response.responseBody = Blob.valueOf(dealCreationResult); 
            
        //292153_OLFConnectionTime_11Jul2019_Soumyajit starts
        }
        else
        {
            System.debug('Connection Not Allowed');
            RestContext.response.addHeader('Content-Type', 'application/json');
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(OLF_Utility.connectionErrMsg));
            RestContext.response.statusCode = 500;
        }
        //292153_OLFConnectionTime_11Jul2019_Soumyajit ends
    }
    public static string insertOlfDealInSht(List<OLFWrapper.MrcPriceWrap> olfDealWrap){ 
        //Set<String> mrcNumSet= new Set<String>();
        //string contractStartDat;
        //string contractEndDate;
        String contactEmail;
        List<OLFWrapper.MrcPriceWrap> olfResponse;
        Set<String> mrcNumSet = new Set<String>(); 
        Map<String, Set<String>> startDateVsMrcNoSetMap = new Map<String, Set<String>>();
        Map<String, List<OLFWrapper.MrcPriceWrap>> startDateVsDealWrapLstMap = new Map<String, List<OLFWrapper.MrcPriceWrap>>();
        for(OLFWrapper.MrcPriceWrap mpw:olfDealWrap){
            mrcNumSet.add(mpw.MRCNumber);
            if(!startDateVsDealWrapLstMap.isEmpty() && startDateVsDealWrapLstMap.containsKey(mpw.StartDate)){
                List<OLFWrapper.MrcPriceWrap> mrcPriceWrapList = startDateVsDealWrapLstMap.get(mpw.StartDate);
                mrcPriceWrapList.add(mpw);
                startDateVsDealWrapLstMap.put(mpw.StartDate, mrcPriceWrapList);
            }
            else{
                startDateVsDealWrapLstMap.put(mpw.StartDate, new List<OLFWrapper.MrcPriceWrap>{mpw});
            }
            if(!startDateVsMrcNoSetMap.isEmpty() && startDateVsMrcNoSetMap.containsKey(mpw.StartDate)){
                Set<String> mrcNoSet = startDateVsMrcNoSetMap.get(mpw.StartDate);
                mrcNoSet.add(mpw.MRCNumber);
                startDateVsMrcNoSetMap.put(mpw.StartDate, mrcNoSet);
            }
            else{
                startDateVsMrcNoSetMap.put(mpw.StartDate, new Set<String>{mpw.MRCNumber});
            }
            //contractStartDat=mpw.StartDate;
            //contractEndDate=mpw.EndDate;
            contactEmail=mpw.contactEmail;
        }
        //String dealCreationResult;
        if(!startDateVsDealWrapLstMap.isEmpty() && !startDateVsMrcNoSetMap.isEmpty())
            olfResponse = getPrice(startDateVsDealWrapLstMap, startDateVsMrcNoSetMap, mrcNumSet, contactEmail);         
        /*if(mrcNumSet.size()>0){
            olfResponse=getPrice(olfDealWrap,mrcNumSet,contractStartDat,contractEndDate,contactEmail);         
        }*/
        return JSON.serialize(olfResponse);
    }

    //public static List<OLFWrapper.MrcPriceWrap> getPrice(List<OLFWrapper.MrcPriceWrap> olfDealToBeCreated,Set<String> mrcNoSet,string contractStartDate,string contractEndDate,String contactEmail){
    public static List<OLFWrapper.MrcPriceWrap> getPrice(Map<String, List<OLFWrapper.MrcPriceWrap>> startDateVsDealWrapLstMap, Map<String, Set<String>> startDateVsMrcNoSetMap, Set<String> mrcNoSet, String contactEmail){
        //String tranche;
        //RV_SPCalculationController.salesPriceCalAndAuditWrap salesPrcWrp = new RV_SPCalculationController.salesPriceCalAndAuditWrap();
        Map<String, String> startDateVsTrancheMap = new Map<String, String>();
        //List<RV_SPCalculationController.salesPriceWrap> toBeInsertedDealSpWrp = new List<RV_SPCalculationController.salesPriceWrap>();
        Map<String, List<RV_SPCalculationController.salesPriceWrap>> startDateVsDealWrpMap = new Map<String, List<RV_SPCalculationController.salesPriceWrap>>();
        List<RV_SPCalculationController.priceAuditWrap> salesPriceAuditInsertLst= new List<RV_SPCalculationController.priceAuditWrap>();
        Map<String, List<RV_SPCalculationController.priceAuditWrap>> startDateVsPriceAuditMap= new Map<String, List<RV_SPCalculationController.priceAuditWrap>>();
        List<Sht__c> shtLst = new List<Sht__c>();
        List<Mrc__c> mrcLst= new List<Mrc__c>();
        List<Date> startDateList;
        Map<String, List<MRC__c>> startDateVsMrcLstMap = new Map<String, List<MRC__c>>(); 
        Map<String,Mrc__c> mrcNoPoTypHandTypMap= new Map<String,Mrc__c>();
        Map<String,RV_SPCalculationController.salesPriceWrap> mrcNoRecentCalculatedSpMap = new Map<String,RV_SPCalculationController.salesPriceWrap>();
        Set<String> plantCodeSet= new Set<String>();
        List<Product_Name_Mapping__mdt> pdtNameMapLst=[Select Id,Product_Name__c,MasterLabel from Product_Name_Mapping__mdt];
        Map<String,String> gradeMap= new Map<String,String>();
        List<OLFWrapper.MrcPriceWrap> mrcPriceWrapList = new List<OLFWrapper.MrcPriceWrap>();
        for(Product_Name_Mapping__mdt pnm :pdtNameMapLst){
            gradeMap.put(pnm.MasterLabel,pnm.Product_Name__c);
        }
        if(mrcNoSet.size()>0){
            mrcLst=getMrcRecords(mrcNoSet);
        }
        Id accountId;
        Map<String,String> mrcPlantGrdMap= new Map<String,String>();
        String olfContactName;
        RV_SPCalculationController.isOlfDeal = true;
        if(mrcLst.size()>0){
            startDateList = new List<Date>();
            for(Mrc__c mr : mrcLst){
                mrcPlantGrdMap.put(mr.name,mr.Plant_Code__c+gradeMap.get(mr.Material_Description__c));
                mrcNoPoTypHandTypMap.put(mr.Name,mr);
                accountId=mr.Sold_To__c;
                plantCodeSet.add(mr.Plant_Code__c);
                for(String startDate : startDateVsMrcNoSetMap.keySet()){
                    startDateList.add(Date.valueOf(startDate));
                    Set<String> mrcNumSet = startDateVsMrcNoSetMap.get(startDate);
                    if(mrcNumSet.contains(mr.Name)){
                        if(!startDateVsMrcLstMap.isEmpty() && startDateVsMrcLstMap.containsKey(startDate)){
                            List<MRC__c> mrcList = startDateVsMrcLstMap.get(startDate);
                            mrcList.add(mr);
                            startDateVsMrcLstMap.put(startDate, mrcList);
                        }
                        else{
                            startDateVsMrcLstMap.put(startDate, new List<MRC__c>{mr});
                        }
                    }
                }
            }
            startDateVsTrancheMap = OLF_Utility.getOnilineTranche(startDateList);
            for(String startDate : startDateVsDealWrapLstMap.keySet()){
                String tranche = startDateVsTrancheMap.get(startDate);
                if(tranche == 'ATP4'){
                    tranche = 'ATP3';
                    startDateVsTrancheMap.put(startDate, tranche);
                }
                RV_SPCalculationController.tranche = tranche;
                RV_SPCalculationController.salesPriceCalAndAuditWrap salesPrcWrp = new RV_SPCalculationController.salesPriceCalAndAuditWrap();
                String endDate = startDateVsDealWrapLstMap.get(startDate)[0].EndDate;
                List<MRC__c> mrcList = startDateVsMrcLstMap.get(startDate);
                salesPrcWrp = RV_SPCalculationController.getCalulatedSp(mrcList, Date.valueOf(startDate), Date.valueOf(endDate)); 
                startDateVsDealWrpMap.put(startDate, salesPrcWrp.salesPriceWrpLst);
                startDateVsPriceAuditMap.put(startDate, salesPrcWrp.auditWrpLst);
                //toBeInsertedDealSpWrp.addAll(salesPrcWrp.salesPriceWrpLst);
                //salesPriceAuditInsertLst.addAll(salesPrcWrp.auditWrpLst);
                //toBeInsertedDealSpWrp = salesPrcWrp.salesPriceWrpLst; 
                //salesPriceAuditInsertLst = salesPrcWrp.auditWrpLst; 
            }
        }
        List<Account> actLst=OLF_Utility.queryForCustomerDetail(contactEmail);
        //START | Rahul Sharma | Date - 18-Mar-2020 : Updated input paramenter to send ParentId of Sold-to account from Ship-to accounts
        //START | Rahul Sharma | Date - 06-Nov-2020 : Added tranche parameter to get tranche specific ATP.
        Map<String ,Decimal> atpLocMap = OLF_FetchMrcFinalPrice.getAtpforPlant(plantCodeSet, actLst[0].ParentId, new List<String>(new Set<String>(startDateVsTrancheMap.values()))); 
        //END | Rahul Sharma | Date - 06-Nov-2020 : Added tranche parameter to get tranche specific ATP.
        //END | Rahul Sharma | Date - 18-Mar-2020 : Updated input paramenter to send ParentId of Sold-to account from Ship-to accounts
        /*if(toBeInsertedDealSpWrp.size()>0){
            for(RV_SPCalculationController.salesPriceWrap spw :toBeInsertedDealSpWrp){
                mrcNoRecentCalculatedSpMap.put(spw.mrcNo + spw.tranche, spw);
            }
        }*/
        if(!startDateVsDealWrpMap.isEmpty()){
            for(String startDate : startDateVsDealWrpMap.keySet()){
                for(RV_SPCalculationController.salesPriceWrap spw : startDateVsDealWrpMap.get(startDate)){
                    mrcNoRecentCalculatedSpMap.put(spw.mrcNo + startDate, spw);
                }
            }
        }
        //Shipping Condition Map
        Map<Integer,String> ShipCondNoNameMap= new Map<Integer,String>();
        List<Shipping_Condition_Mapping__mdt> shipCdnMetDatLst= [Select id,Mot__c,Shipping_Condition__c
                                                                from Shipping_Condition_Mapping__mdt];
        for(Shipping_Condition_Mapping__mdt shp:shipCdnMetDatLst){
            ShipCondNoNameMap.put(Integer.valueOf(shp.Shipping_Condition__c),shp.Mot__c);
        }
        //Deal Event Manager metadata
        Map<String,Deal_Event_Manager__mdt> poTypeHandlingDealMdtMap=RV_SHT_CreateController.getDealEventMetdataMap(); 
        //Map<String,Integer> plantGradeVolumeInDealMap= new Map<String,Integer>();
        Map<String,String> plantIdCodeMap=new Map<String,String>();
        decimal volumeCheckforAllDeals= 0;
        decimal creditAvailable=0;
        decimal creditTobeDeducted=0;
        String volCheckPlantGrade=''; 
        //boolean deductCredit=false;
        Account acc=actLst[0];
        if(acc.Parent.Rv_Credit_Available__c != null){
            creditAvailable=acc.Parent.Rv_Credit_Available__c; 
        } 
        for(String startDate : startDateVsDealWrapLstMap.keySet()){
            Boolean deductCredit = false;
            String tranche = startDateVsTrancheMap.get(startDate);
            List<OLFWrapper.MrcPriceWrap> olfDealToBeCreated = startDateVsDealWrapLstMap.get(startDate);
            Map<String,Integer> plantGradeVolumeInDealMap= new Map<String,Integer>();
            for(OLFWrapper.MrcPriceWrap mpw : olfDealToBeCreated){
                if(contactEmail != null && contactEmail != '' 
                   && mpw.inputVolume != null && mpw.inputVolume != '' &&
                   mpw.PricePerUnit != null && mpw.PricePerUnit != ''){ 
                    Sht__c sh = new Sht__c();
                    Mrc__c mr= new Mrc__c();
                    mr=mrcNoPoTypHandTypMap.get(mpw.MRCNumber);
                    System.debug('Inside for '+mpw.inputVolume);
                    //Available Volume Check
                    if(Integer.valueOf(mpw.inputVolume) <= atpLocMap.get(mr.Plant_Code__c+mpw.grade+tranche)){
                        plantIdCodeMap.put(mr.Plant__c,mr.Plant_Code__c);
                        sh.MRC__c = mr.Id;
                        sh.MRC_Number__c = mpw.MRCNumber;
                        sh.Customer__c = mr.Sold_To__c;
                        sh.Tranche__c = tranche; //Rahul Sharma | Date - 06-Nov-2020 : Removed hardcoded ATP value.
                        if(mrcNoRecentCalculatedSpMap.containsKey(mpw.MRCNumber + startDate)){
                            sh.BSP__c=(mrcNoRecentCalculatedSpMap.get(mpw.MRCNumber + startDate)).BSP;
                            sh.MSP__c=(mrcNoRecentCalculatedSpMap.get(mpw.MRCNumber + startDate)).MSP;
                            sh.OTM__c=(mrcNoRecentCalculatedSpMap.get(mpw.MRCNumber + startDate)).OTM;
                        }
                        if(mpw.PricePerUnit!=null & mpw.PricePerUnit!='')
                            sh.SP_100L__c=Decimal.valueOf(mpw.PricePerUnit);
                        sh.Status__c='Completed';
                        sh.Sales_Type__c='Internet Sales';
                        sh.Product_Category__c=mpw.grade;
                        sh.Select__c=true;
                        sh.Contract_Start__c=Date.valueOf(mpw.StartDate);
                        sh.Contract_End_Date__c=Date.valueOf(mpw.EndDate);
                        if(mpw.inputVolume!=null & mpw.inputVolume!=''){
                            if(plantGradeVolumeInDealMap.containsKey(mr.Plant_Code__c + mpw.grade)){
                                Integer volumeInDeal = plantGradeVolumeInDealMap.get(mr.Plant_Code__c + mpw.grade) + Integer.valueOf(mpw.inputVolume);
                                if(volumeInDeal <= atpLocMap.get(mr.Plant_Code__c+mpw.grade+tranche)){
                                    sh.Volume_CBM__c = Decimal.valueOf(mpw.inputVolume);
                                    deductCredit = true;
                                }
                                else{
                                    deductCredit = false;
                                    volCheckPlantGrade = volCheckPlantGrade+mpw.Location+' and ' +mpw.MaterialName+' ;'; 
                                    volumeCheckforAllDeals++;
                                }
                                plantGradeVolumeInDealMap.put(mr.Plant_Code__c + mpw.grade, volumeInDeal);   
                            }
                            else{
                                sh.Volume_CBM__c=Decimal.valueOf(mpw.inputVolume);
                                deductCredit=true;
                                plantGradeVolumeInDealMap.put(mr.Plant_Code__c+mpw.grade,Integer.valueOf(mpw.inputVolume));
                            }  
                        }     
                        sh.isOlfDeal__c=true;
                        sh.Location__c=mr.Plant__c;
                        sh.Contact_Email__c=contactEmail;
                        sh.Contact_Name__c=olfContactName;
                        //Deal Event Manager Attributes for Pricing ,Vol deduction & Hedging
                        sh.Price_Condition__c='YP24';
                        sh.IsATPVolumeReduced__c=false;
                        sh.IsGsapDealCancelOn__c=false;
                        sh.IsGsapDealCreateOn__c=false;
                        sh.IsPricingTaxed__c=false;
                        sh.IsVolumeHedged__c=false;
                        sh.IsZeroPriceDeal__c=false;
                        
                        string key=mr.PO_Type__c + mr.Handling_Type__c;
                        String otherKey=mr.PO_Type__c + 'Others';
                        string finalKey; 
                        Deal_Event_Manager__mdt dealEvent;
                        if(poTypeHandlingDealMdtMap.containsKey(key)){
                            dealEvent = poTypeHandlingDealMdtMap.get(key);
                        }
                        else if(poTypeHandlingDealMdtMap.containsKey(otherKey)){
                            dealEvent=poTypeHandlingDealMdtMap.get(otherKey);
                        }
                        system.debug('dealEvent==>'+dealEvent);
                        if(dealEvent != null){
                            sh.IsPricingTaxed__c=dealEvent.IsPricingTaxed__c;
                            sh.Price_Condition__c=dealEvent.Pricing_Condition__c;
                            sh.IsATPVolumeReduced__c=dealEvent.IsATPVolumeReduced__c;
                            sh.IsVolumeHedged__c=dealEvent.IsVolumeHedged__c;
                            sh.IsZeroPriceDeal__c=dealEvent.IsZeroPriceDeal__c; 
                            if(dealEvent.Shipping_Condition__c.contains(ShipCondNoNameMap.get(Integer.valueOf(mr.Shipping_Condition__c)))){
                                sh.IsGsapDealCreateOn__c=dealEvent.IsGsapDealCreateOn__c;
                                sh.IsGsapDealCancelOn__c=dealEvent.IsGsapDealCancelOn__c;
                            }
                            //Retro Volume Deals not required here   
                        } 
                        if(poTypeHandlingDealMdtMap.containsKey(key)){
                            sh.Price_Condition__c=poTypeHandlingDealMdtMap.get(key).Pricing_Condition__c;
                            sh.IsATPVolumeReduced__c=poTypeHandlingDealMdtMap.get(key).IsATPVolumeReduced__c;
                            sh.IsGsapDealCancelOn__c=poTypeHandlingDealMdtMap.get(key).IsGsapDealCancelOn__c;
                            sh.IsGsapDealCreateOn__c=poTypeHandlingDealMdtMap.get(key).IsGsapDealCreateOn__c;
                            sh.IsPricingTaxed__c=poTypeHandlingDealMdtMap.get(key).IsPricingTaxed__c;
                            sh.IsVolumeHedged__c=poTypeHandlingDealMdtMap.get(key).IsVolumeHedged__c;
                            sh.IsPricingTaxed__c=poTypeHandlingDealMdtMap.get(key).IsPricingTaxed__c;
                            sh.IsZeroPriceDeal__c=poTypeHandlingDealMdtMap.get(key).IsZeroPriceDeal__c;
                        } 
                        else if(poTypeHandlingDealMdtMap.containsKey(otherKey)){
                            sh.Price_Condition__c=poTypeHandlingDealMdtMap.get(otherKey).Pricing_Condition__c;
                            sh.IsATPVolumeReduced__c=poTypeHandlingDealMdtMap.get(otherKey).IsATPVolumeReduced__c;
                            sh.IsGsapDealCancelOn__c=poTypeHandlingDealMdtMap.get(otherKey).IsGsapDealCancelOn__c;
                            sh.IsGsapDealCreateOn__c=poTypeHandlingDealMdtMap.get(otherKey).IsGsapDealCreateOn__c;
                            sh.IsPricingTaxed__c=poTypeHandlingDealMdtMap.get(otherKey).IsPricingTaxed__c;
                            sh.IsVolumeHedged__c=poTypeHandlingDealMdtMap.get(otherKey).IsVolumeHedged__c;
                            sh.IsPricingTaxed__c=poTypeHandlingDealMdtMap.get(otherKey).IsPricingTaxed__c;
                            sh.IsZeroPriceDeal__c=poTypeHandlingDealMdtMap.get(otherKey).IsZeroPriceDeal__c;
                        }
                        else{
                            sh.Price_Condition__c='YP24';
                            sh.IsATPVolumeReduced__c=false;
                            sh.IsGsapDealCancelOn__c=false;
                            sh.IsGsapDealCreateOn__c=false;
                            sh.IsPricingTaxed__c=false;
                            sh.IsVolumeHedged__c=false;
                            sh.IsPricingTaxed__c=false;
                            sh.IsZeroPriceDeal__c=false;
                        }
                        if(deductCredit){
                            creditTobeDeducted = creditTobeDeducted + (sh.SP_100L__c*sh.Volume_CBM__c*10);  
                        }
                        shtLst.add(sh);   
                    }
                    else{
                        volCheckPlantGrade=volCheckPlantGrade+mpw.Location+' and ' +mpw.MaterialName+' ;'; 
                        volumeCheckforAllDeals++; 
                    } 
                }   
            }
        }
        List<String> insertedIds=new List<String>();
        //Available Volume & Credit Check
        if(volumeCheckforAllDeals == 0  && creditAvailable >= creditTobeDeducted){
            if(shtLst.size()>0){
                try{ 
                    //Inserting Deals
                    RV_SHTTriggerHelper.isOlfDeal = true; //166747_OLF_OnlineATPsplit_24Jun2019_Soumyajit
                    RV_SHTTriggerHelper.accountAlreadyUpdated = true; //OLFCustomerCreditChk_01Aug2019_Soumyajit
                    
                    List<Database.SaveResult> srList= database.insert(shtLst);
                    for(database.SaveResult sr:srList){
                        if(sr.isSuccess()){
                            insertedIds.add(sr.getId());
                        }
                    }
                    //updating credit for the customer
                    OLF_Utility.updateCreditForCustomer(acc,creditTobeDeducted);
                    //Inserting/Updating sales of Customer for Plant Grade and Customer Combination
                    //START | Rahul Sharma | Date - 18-March-2020 : Updated input parameter for send parent account (Sold-to Account) Id.
                    OLF_Utility.makeEntryInCustomerSalesManagement(shtLst, acc.ParentId, gradeMap, plantIdCodeMap);
                    //END | Rahul Sharma | Date - 18-March-2020 : Updated input parameter for send parent account (Sold-to Account) Id.
                }
                catch(Exception e){ 
                    System.debug('OLF_CreateDeal >> getPrice() >> Exception: ' + e.getMessage() + ' Line number: ' + e.getLineNumber()); 
                }
            }
        }
        
        Map<string,String> mrcNoSHTNoMap= new Map<string,String>();
        //List<OLFWrapper.MrcPriceWrap> olfCompDealEmailWrpLst = new List<OLFWrapper.MrcPriceWrap>();
        //Map<String,Decimal> mrcAtpMap= new Map<String,Decimal>();
        Map<String,Decimal> plantGrdAtpMap= new Map<String,Decimal>();
      
       
        //Inserting Audit Record for deals Created
        if(insertedIds.size()>0){
            List<Sht__c> createdOlfDeals= new List<Sht__c>();
            createdOlfDeals = [SELECT Id,
                                      Name,
                                      MRC__r.Name,
                                      Contract_Start__c,
                                      Tranche__c FROM SHT__c WHERE Id IN :insertedIds];
            system.debug('createdOlfDeals shtIds===>'+createdOlfDeals);
            Map<String,String> mrcNoShtIdMap= new Map<String,String>();
            for(Sht__c sh : createdOlfDeals){
                mrcNoShtIdMap.put(sh.MRC__r.Name + String.valueOf(sh.Contract_Start__c), sh.Id);
                mrcNoSHTNoMap.put(sh.MRC__r.Name + String.valueOf(sh.Contract_Start__c), sh.Name);
            }
            /*for(RV_SPCalculationController.priceAuditWrap adtWrp : salesPriceAuditInsertLst){
                adtWrp.shtId = mrcNoShtIdMap.get(adtWrp.mrcNo + adtWrp.tranche);
            }*/
            for(String startDate : startDateVsPriceAuditMap.keySet()){
                for(RV_SPCalculationController.priceAuditWrap adtWrp : startDateVsPriceAuditMap.get(startDate)){
                    adtWrp.shtId = mrcNoShtIdMap.get(adtWrp.mrcNo + startDate);
                    salesPriceAuditInsertLst.add(adtWrp);
                }
            }
            if(salesPriceAuditInsertLst.size()>0){
                Rv_PriceAuditController.insertPriceAuditWrap(salesPriceAuditInsertLst);
            }
            for(String startDate : startDateVsDealWrapLstMap.keySet()){
                //String tranche = startDateVsTrancheMap.get(startDate);
                List<OLFWrapper.MrcPriceWrap> olfDealToBeCreated = startDateVsDealWrapLstMap.get(startDate);
                for(OLFWrapper.MrcPriceWrap mpw :olfDealToBeCreated){
                    if(mpw.inputVolume != null && mpw.inputVolume != '' && mpw.PricePerUnit != null && mpw.PricePerUnit != ''){
                        if(mrcNoSHTNoMap.containsKey(mpw.MRCNumber + startDate)){
                            mpw.sfdcDealNumber=mrcNoSHTNoMap.get(mpw.MRCNumber + startDate); 
                            mpw.dealMessage='Deal Created Successfully.';
                            //olfCompDealEmailWrpLst.add(mpw);
                            mrcPriceWrapList.add(mpw);
                        }  
                    }
                }
            }     
        }
        /*if(olfCompDealEmailWrpLst.size()>0){
            OLF_SendEmail.sendEmailtoCustomer(olfCompDealEmailWrpLst);
        }*/
        if(mrcPriceWrapList.size()>0){
            OLF_SendEmail.sendEmailtoCustomer(mrcPriceWrapList);
        }
        
        if(volumeCheckforAllDeals > 0){
            //On Insufficient Volume Available for any Combnation of plant and Grade
            Set<String> plantGrdSet=new Set<String>();
            plantGrdSet.addAll(mrcPlantGrdMap.values());
            //START | Rahul Sharma | Date - 18-Mar-2020 : Updated input paramenter to send ParentId of Sold-to account from Ship-to accounts
            //START | Rahul Sharma | Date - 06-Nov-2020 : Added tranche parameter to get tranche specific ATP.
            plantGrdAtpMap = OLF_FetchMrcFinalPrice.getAtpforPlant(plantCodeSet,acc.ParentId, new List<String>(new Set<String>(startDateVsTrancheMap.values()))); 
            //END | Rahul Sharma | Date - 06-Nov-2020 : Added tranche parameter to get tranche specific ATP.
            //END | Rahul Sharma | Date - 18-Mar-2020 : Updated input paramenter to send ParentId of Sold-to account from Ship-to accounts
            for(String startDate : startDateVsDealWrapLstMap.keySet()){
                String tranche = startDateVsTrancheMap.get(startDate);
                List<OLFWrapper.MrcPriceWrap> olfDealToBeCreated = startDateVsDealWrapLstMap.get(startDate);
                for(OLFWrapper.MrcPriceWrap mpw :olfDealToBeCreated){
                    mpw.dealMessage='Insufficent Volume for Plant Grade Combination of '+ volCheckPlantGrade;
                    if(plantGrdAtpMap.get(mrcPlantGrdMap.get(mpw.MRCNumber) + tranche) <1){
                        mpw.availableVolume='0';
                    }
                    else{
                        mpw.availableVolume = String.valueOf(plantGrdAtpMap.get(mrcPlantGrdMap.get(mpw.MRCNumber) + tranche));
                    }
                    mrcPriceWrapList.add(mpw);  
                }
            }
            //return olfDealToBeCreated;
        }
        else if(creditAvailable < creditTobeDeducted){
            //On Insufficient Credit Limit Available
            for(String startDate : startDateVsDealWrapLstMap.keySet()){
                String tranche = startDateVsTrancheMap.get(startDate);
                List<OLFWrapper.MrcPriceWrap> olfDealToBeCreated = startDateVsDealWrapLstMap.get(startDate);
                for(OLFWrapper.MrcPriceWrap mpw :olfDealToBeCreated){
                    mpw.dealMessage='Insufficient Credit';
                    mrcPriceWrapList.add(mpw);
                }
            }
            //return olfDealToBeCreated;
        } 
        /*else{
            //On Successful Deal Creation
           return olfDealToBeCreated;
        }*/
        return mrcPriceWrapList;
    }

    public static List<Mrc__c> getMrcRecords(Set<string> mrcNos){
        List<Mrc__c> mrcList= new List<Mrc__c>();
        if(mrcNos.size()>0){
            mrcList = [select id,name,Plant__c,Plant__r.Name,Po_Type__c,
                      Supply_Type__c,Product__c,Plant_code__c,Product__r.Name,Material_Description__c,Product__r.Commodity_Grade_L2__c,Product__r.BEHG_Value_100l__c,
                       Product__r.Current_BEHG_valid_from_date__c,Product__r.Current_BEHG_valid_to_date__c,Product__r.Future_BEHG_value_in_100l__c,Product__r.Future_BEHG_valid_from_date__c,Product__r.Future_BEHG_valid_to_date__c,
                       Sold_To__c,Sold_To__r.Name,Sales_Organization__c,Handling_Type__c,MRC_Number__c,Ship_to_Number__c,
                       Ship_to_Name__c, Valid_From_Date__c,Valid_To_Date__c,Shipping_Condition__c from MRC__c 
                       where Name IN :mrcNos and Valid_To_Date__c >= TODAY order by Name,Plant_code__c ASC];
        }
        return mrcList;
    }   
}