force-app/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sold To</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rv_Olf_Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Rv_Olf_Customer_Email__c</fullName>
    <label>Online Integration EmailID</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ship_to_Number__c.field-meta.xml
<CustomField>
    <fullName>Ship_to_Number__c</fullName>
    <label>Ship To Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sold_To_Number__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Number__c</fullName>
    <label>Sold To Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Revolution_Ship_To.recordType-meta.xml
<RecordType>
    <fullName>Revolution_Ship_To</fullName>
    <active>true</active>
    <label>Revolution Ship-To Account</label>
</RecordType>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Object to store all OU, Region and Location information for Trading and Supply - ATP/AMV/SCHT</description>
    <label>Location</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <description>Plant Number of Depot Code of the particular Plant/Depot</description>
    <label>Plant Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product_Catalogue__c/Product_Catalogue__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <label>Material Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Catalogue__c/fields/Commodity_Grade_L2__c.field-meta.xml
<CustomField>
    <fullName>Commodity_Grade_L2__c</fullName>
    <label>Grade(L2)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Additive</fullName>
                <isActive>false</isActive>
                <label>Additive</label>
            </value>
            <value>
                <fullName>AGO B0</fullName>
            </value>
            <value>
                <fullName>AGO B0 CH</fullName>
            </value>
            <value>
                <fullName>AGO B7</fullName>
            </value>
            <value>
                <fullName>AGO B7 CH</fullName>
                <isActive>false</isActive>
                <label>AGO B7 CH</label>
            </value>
            <value>
                <fullName>AGO VPD</fullName>
            </value>
            <value>
                <fullName>Alkalyte</fullName>
                <isActive>false</isActive>
                <label>Alkalyte</label>
            </value>
            <value>
                <fullName>AVGAS</fullName>
                <isActive>false</isActive>
                <label>AVGAS</label>
            </value>
            <value>
                <fullName>Cokerfeed</fullName>
                <isActive>false</isActive>
                <label>Cokerfeed</label>
            </value>
            <value>
                <fullName>EBV- Crude-Mix</fullName>
                <isActive>false</isActive>
                <label>EBV- Crude-Mix</label>
            </value>
            <value>
                <fullName>ETHANOL</fullName>
                <isActive>false</isActive>
                <label>ETHANOL</label>
            </value>
            <value>
                <fullName>FAME</fullName>
                <isActive>false</isActive>
                <label>FAME</label>
            </value>
            <value>
                <fullName>FO</fullName>
                <isActive>false</isActive>
                <label>FO</label>
            </value>
            <value>
                <fullName>GTL B0</fullName>
            </value>
            <value>
                <fullName>GTL B7</fullName>
            </value>
            <value>
                <fullName>High Sulphur Gasoil</fullName>
                <isActive>false</isActive>
                <label>High Sulphur Gasoil</label>
            </value>
            <value>
                <fullName>IGO 1000ppm</fullName>
            </value>
            <value>
                <fullName>IGO 10ppm</fullName>
            </value>
            <value>
                <fullName>IGO 50ppm</fullName>
            </value>
            <value>
                <fullName>Jet A1</fullName>
                <isActive>false</isActive>
                <label>Jet A1</label>
            </value>
            <value>
                <fullName>Kerosene</fullName>
                <isActive>false</isActive>
                <label>Kerosene</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>ULG100 VP</fullName>
            </value>
            <value>
                <fullName>ULG95_BOB_E10</fullName>
            </value>
            <value>
                <fullName>ULG95_BOB_E5</fullName>
            </value>
            <value>
                <fullName>ULG95 E0</fullName>
            </value>
            <value>
                <fullName>ULG95 E10</fullName>
            </value>
            <value>
                <fullName>ULG95 E5</fullName>
            </value>
            <value>
                <fullName>ULG98</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Catalogue__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipName>Product_Catalogues_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Catalogue__c/fields/Marketing_Cost__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Marketing cost [EUR/100l]</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Catalogue__c/fields/Online_Material_Name_Taxed__c.field-meta.xml
<CustomField>
    <fullName>Online_Material_Name_Taxed__c</fullName>
    <label>Online Material Name [Taxed]</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Catalogue__c/fields/Online_Material_Name_UnTaxed__c.field-meta.xml
<CustomField>
    <fullName>Online_Material_Name_UnTaxed__c</fullName>
    <label>Online Material Name [UnTaxed]</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RV_MRCInsertWebserviceClassTest.cls
/**
 * Created by Dharmendra.Singh2 on 1/5/2021.
 */

@IsTest
private class RV_MRCInsertWebserviceClassTest {
    @IsTest
    static void testMRC() {
        
        Account accInsert = new Account();
        accInsert = RV_TestHelper.insertAccount(accInsert);
        accInsert.Sold_To_Number__c = '11113864';
        accInsert.Customer_Type__c = 'Sold To';
        insert accInsert;
        
        Account accInsert2 = new Account();
        Id recTypeId=Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Revolution_Ship_To').getRecordTypeId();
        accInsert2 = RV_TestHelper.insertAccount(accInsert2);
        accInsert2.Ship_to_Number__c = '11102253';
        accInsert2.Rv_Olf_Customer_Email__c='test@abc.com';
        accInsert2.Customer_Type__c = 'Ship To';
        accInsert2.recordTypeId = recTypeId;
        accInsert2.ParentId = accInsert.Id;
       // insert accInsert2;
        
        Location__c loc=new Location__c();
        loc=RV_TestHelper.insertLocation(loc);
        loc.Plant_Code__c = 'D003';
        insert loc;
        
        Product_Catalogue__c pc=new Product_Catalogue__c();
        pc=RV_TestHelper.insertProductCat(pc);
        pc.Online_Material_Name_Taxed__c='Diesel B7';
        pc.Online_Material_Name_UnTaxed__c='Diesel B7, unversteuert';
        pc.Commodity_Grade_L2__c='AGO B7';
        pc.Marketing_Cost__c = 0.014;
        pc.Name = '400003805';
        insert pc;

        String preq = '{'+
                ' "ActionInd":"C",'+
                ' "MRCNo":"320076190",'+
                ' "SalesDoctype":"ZCM",'+
                ' "ShipToPOtype":"TSFP",'+
                ' "SalesOrg":"DE01",'+
                ' "DistributionChannel":"2",'+
                ' "Division":"2",'+
                ' "ValidFrom":"2021-01-01",'+
                ' "ValidTo":"2022-12-31",'+
                ' "SoldTo":"11113864",'+
                ' "SoldToName":"ADAM OMMERT MINERALOELHANDEL",'+
                ' "ShipTo":"11102253",'+
                ' "ShipToName":"ADAM OMMERT MINERALOELHANDEL",'+
                ' "ShippingCondition":"10",'+
                ' "Description": "",'+
                ' "ShipCondDescription": "",'+
                ' "SoldToDelFlgAllArea":"",'+
                ' "SoldToDelFlgSaleArea":"",'+
                ' "SoldToNatiAccPart":"",'+
                ' "SoldToNatiAccPartName":"",'+
                ' "SoldToPrimSalesRep":"",'+
                ' "SoldToPrimSalesRepName":"",'+
                ' "SoldToSalesGrp":"",'+
                ' "SoldToSalesGrpDescrp":"",'+
                ' "ShipToPrimrySalesRepr":"",'+
                ' "ShipToPrimrySalesReprName":"",'+
                ' "ShipToSalesGrp":"",'+
                ' "ShipToSalesGrpDesc":"",'+
                ' "MRCItemList":[ '+
                '	{ '+
                ' "MRCItemNo":"103003",'+
                ' "MRCNumber":"320076188",'+
                ' "PlantCode":"D003",'+
                ' "PlantName":"Flörsheim Shell Depot",'+
                ' "MaterialNumber":"400003805",'+
                ' "MaterialDescription":"SH ULG95 10ppmS E10 UdyUmk LowDose DE",'+
                ' "HandlingType":"CA",'+
                ' "ReasonforRejectionCode":"",'+
                ' "ReasonforRejectionMessage":"",'+
                ' "ModeofTransport":"1",'+
                ' "ExterMOTDesc" : "",'+
                ' "incoTermsPart1" : "",'+
                ' "incoTermsPart2" : "",'+
                ' "PaymentTerms" : "Z011",'+
                ' "PaymentTermsDescrp" : "",'+
                ' "ValuationType" : "",'+
                ' "CondGroup2" : "",'+
                ' "CondGroup2Desc" : "",'+
                ' "InvoiceDate" : "",'+
                ' "InvoiceDateDesc" : "",'+
                ' "Paymentmethod" : "",'+
                ' "PaymentmethodDesc" : ""'+
                '	},'+
                '	{ '+
                ' "MRCItemNo":"101011",'+
                ' "MRCNumber":"320076188",'+
                ' "PlantCode":"D011",'+
                ' "PlantName":"Raunheim Unitank Depot",'+
                ' "MaterialNumber":"400002410",'+
                ' "MaterialDescription":"BF IGO 50ppmS B0 Dye Mkd Germany",'+
                ' "HandlingType":"EB11111111111",'+
                ' "ReasonforRejectionCode":"",'+
                ' "ReasonforRejectionMessage":"",'+
                ' "ModeofTransport":"1",'+
                ' "ExterMOTDesc" : "",'+
                ' "incoTermsPart1" : "",'+
                ' "incoTermsPart2" : "",'+
                ' "PaymentTerms" : "Z011",'+
                ' "PaymentTermsDescrp" : "",'+
                ' "ValuationType" : "",'+
                ' "CondGroup2" : "",'+
                ' "CondGroup2Desc" : "",'+
                ' "InvoiceDate" : "",'+
                ' "InvoiceDateDesc" : "",'+
                ' "Paymentmethod" : "",'+
                ' "PaymentmethodDesc" : ""'+
                '	}, '+
                '	{ '+
                ' "MRCItemNo":"101012", '+
                ' "MRCNumber":"320076188",'+
                ' "PlantCode":"D011",'+
                ' "PlantName":"Raunheim Unitank Depot",'+
                ' "MaterialNumber":"400002410",'+
                ' "MaterialDescription":"BF IGO 50ppmS B0 Dye Mkd Germany",'+
                ' "HandlingType":"EB",'+
                ' "ReasonforRejectionCode":"",'+
                ' "ReasonforRejectionMessage":"",'+
                ' "ModeofTransport":"1",'+
                ' "ExterMOTDesc" : "",'+
                ' "incoTermsPart1" : "",'+
                ' "incoTermsPart2" : "",'+
                ' "PaymentTerms" : "",'+
                ' "PaymentTermsDescrp" : "",'+
                ' "ValuationType" : "",'+
                ' "CondGroup2" : "",'+
                ' "CondGroup2Desc" : "",'+
                ' "InvoiceDate" : "",'+
                ' "InvoiceDateDesc" : "",'+
                ' "Paymentmethod" : "",'+
                ' "PaymentmethodDesc" : ""'+
                '	} '+

                ' ] '+
                '}';

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/createMRC' ;
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(preq);
        RestContext.request = req;
        RestContext.response= res;
		
        Test.startTest();
        RV_MRCInsertWebserviceClass.createMRCStagings();
        Test.stopTest();

    }
}