force-app/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sold To</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Area__c.field-meta.xml
<CustomField>
    <fullName>Sales_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Area</label>
    <referenceTo>TCP_Sales_Area__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/TCP_STNSAP_ExternalId1__c.field-meta.xml
<CustomField>
    <fullName>TCP_STNSAP_ExternalId1__c</fullName>
    <description>this is the unique and external Id reference field consider for the 1st Service STNSAP SoldTo</description>
    <externalId>true</externalId>
    <label>STNSAP ExternalId1</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/TCP_STNSAP_ExternalId2__c.field-meta.xml
<CustomField>
    <fullName>TCP_STNSAP_ExternalId2__c</fullName>
    <description>this is the unique and external Id reference field consider for the 2nd Service STNSAP Shipto, billto</description>
    <externalId>true</externalId>
    <label>STNSAP ExternalId2</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/TCP_Account.recordType-meta.xml
<RecordType>
    <fullName>TCP_Account</fullName>
    <active>true</active>
    <label>TCP Account</label>
</RecordType>

force-app/main/default/classes/TCP_STNSAPSoldToShipToScheduler.cls
/***** TCP STNSAP SoldTo ShipTo Service 2 Schedular  ***********/
global class TCP_STNSAPSoldToShipToScheduler implements Schedulable {
    public final string tcp_AccRecTypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('TCP_Account').getRecordTypeId();
    global void execute(SchedulableContext ctx) {
        try{
            //get customer details
            //list<Account> tcpCustomersList = database.query('SELECT id, AccountNumber FROM Account WHERE recordtypeid =: tcp_AccRecTypeid AND AccountNumber != null AND TCP_STNSAP_ExternalId1__c != null AND Sales_Area__c != null AND Customer_Type__c =\'' + String.escapeSingleQuotes('Sold To') + '\'');
            list<Account> tcpCustomersList = [SELECT id, Active__c , AccountNumber, Customer_Type__c, Sales_Area__c, TCP_STNSAP_ExternalId1__c , TCP_STNSAP_ExternalId2__c  FROM Account WHERE recordtypeid =: tcp_AccRecTypeid AND AccountNumber != null AND TCP_STNSAP_ExternalId1__c != null AND Sales_Area__c != null AND Customer_Type__c IN ('Sold To')];
            List<list<string>> accountIdInSplits = new List<list<string>>();
            Integer size =tcpCustomersList.size();
            Integer splitSize=45;
            Integer count=0,index=0;
            list<string> tempSet = new list<string>();
            while(index < size) {
                tempSet.add(tcpCustomersList.get(index++).id);
                ++count;
                if(count == splitSize) {
                    accountIdInSplits.add(tempSet);
                    tempSet=new list<string>();
                    count = 0;
                }
            }
            if(!tempSet.isEmpty()) {
                accountIdInSplits.add(tempSet);
            }
            for(Integer i=0;i<accountIdInSplits.size();i++){
                System.enqueueJob(new TCP_STNSAPSoldToShipToQueueable(accountIdInSplits.get(i),i) );
            }
        }
        catch(Exception e){
            system.debug('Exception in TCP_STNSAPSoldToShipToScheduler class : '+e.getMessage()+'line : '+e.getLineNumber());
            TCP_ExceptionLogClass.insertExceptionRecord('STNSAP SoldTo ShipTo Queueable Exception',e.getMessage(),'TCP_STNSAPSoldToShipToScheduler','execute','Exception');          
        }
    } 
}