force-app/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sold To</fullName>
            </value>
            <value>
                <fullName>Ship To</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RT_PaymentTerm__c.field-meta.xml
<CustomField>
    <fullName>RT_PaymentTerm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Terms of Payment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RT_Setting__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Code - Value mapping</value>
        </filterItems>
        <filterItems>
            <field>RT_Setting__c.Type__c</field>
            <operation>equals</operation>
            <value>Payment Term</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>RT_Setting__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Contract__c/RE_Contract__c.object-meta.xml
<CustomObject>
    <label>RE SAP Contract</label>
    <nameField>
        <displayFormat>CN-{0000000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE SAP Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Contract__c/fields/RE_Location_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Location_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location Name</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Contract__c/fields/RE_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Contract__c/fields/RT_Contract_Item__c.field-meta.xml
<CustomField>
    <fullName>RT_Contract_Item__c</fullName>
    <label>Contract Item</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Contract__c/fields/RT_Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>RT_Contract_Number__c</fullName>
    <label>Contract</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Contract__c/fields/RT_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>RT_Product_Code__c</fullName>
    <formula>RE_Product_Name__r.RT_Product_Code__c</formula>
    <label>Material</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Contract__c/fields/RT_Ship_to_Name__c.field-meta.xml
<CustomField>
    <fullName>RT_Ship_to_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship to Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>RE_Contracts_Ship_to</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Contract__c/fields/RT_Sold_To_Name__c.field-meta.xml
<CustomField>
    <fullName>RT_Sold_To_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold to Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>RE_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Contract__c/fields/RT_Terms_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>RT_Terms_of_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Terms of Payment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RT_Setting__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Code - Value mapping</value>
        </filterItems>
        <filterItems>
            <field>RT_Setting__c.Type__c</field>
            <operation>equals</operation>
            <value>Payment Term</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RT_Setting__c</referenceTo>
    <relationshipLabel>RE SAP Contracts</relationshipLabel>
    <relationshipName>RE_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Contract__c/fields/RT_Valid_From__c.field-meta.xml
<CustomField>
    <fullName>RT_Valid_From__c</fullName>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_Contract__c/fields/RT_Valid_To__c.field-meta.xml
<CustomField>
    <fullName>RT_Valid_To__c</fullName>
    <label>Valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_Location__c/RE_Location__c.object-meta.xml
<CustomObject>
    <label>RE Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Location__c/fields/RT_Location_Type__c.field-meta.xml
<CustomField>
    <fullName>RT_Location_Type__c</fullName>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RT_Import_Terminal__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Depot</fullName>
            </value>
            <value>
                <fullName>Refinery</fullName>
            </value>
            <value>
                <fullName>Retail Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Product__c/RE_Product__c.object-meta.xml
<CustomObject>
    <label>RE Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Product__c/fields/RT_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>RT_Product_Code__c</fullName>
    <label>Product Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REV_Contract_Master__c/REV_Contract_Master__c.object-meta.xml
<CustomObject>
    <label>REV Contract Master</label>
    <nameField>
        <displayFormat>REV-{0000000}</displayFormat>
        <label>REV Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REV Contract Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/REV_Contract_Master__c/fields/RT_AMOUNT__c.field-meta.xml
<CustomField>
    <fullName>RT_AMOUNT__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/REV_Contract_Master__c/fields/RT_Condition_Type__c.field-meta.xml
<CustomField>
    <fullName>RT_Condition_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condition Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RT_Setting__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Code - Value mapping</value>
        </filterItems>
        <filterItems>
            <field>RT_Setting__c.Type__c</field>
            <operation>equals</operation>
            <value>Condition Type</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RT_Setting__c</referenceTo>
    <relationshipLabel>REV Contract Master (Condition Type)</relationshipLabel>
    <relationshipName>Aureus_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/REV_Contract_Master__c/fields/RT_Material_Desc__c.field-meta.xml
<CustomField>
    <fullName>RT_Material_Desc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipLabel>REV Contract Master</relationshipLabel>
    <relationshipName>Aureus_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/REV_Contract_Master__c/fields/RT_Plant_Desc__c.field-meta.xml
<CustomField>
    <fullName>RT_Plant_Desc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipLabel>REV Contract Master</relationshipLabel>
    <relationshipName>Aureus_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/REV_Contract_Master__c/fields/RT_Ship_to_Name__c.field-meta.xml
<CustomField>
    <fullName>RT_Ship_to_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship to Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Customer_Type__c</field>
            <operation>equals</operation>
            <value>Ship To</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>REV Contract Master (Ship to Name)</relationshipLabel>
    <relationshipName>Aureus_Data_Ship_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/REV_Contract_Master__c/fields/RT_Sold_to_Name__c.field-meta.xml
<CustomField>
    <fullName>RT_Sold_to_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold to Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>REV Contract Master (Sold to Name)</relationshipLabel>
    <relationshipName>Aureus_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/REV_Contract_Master__c/fields/RT_Valid_From__c.field-meta.xml
<CustomField>
    <fullName>RT_Valid_From__c</fullName>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/REV_Contract_Master__c/fields/SAP_Contract__c.field-meta.xml
<CustomField>
    <fullName>SAP_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SAP Contract</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>No contract item found for the Material.</errorMessage>
        <filterItems>
            <field>RE_Contract__c.RE_Product_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.RT_Material_Desc__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RE_Contract__c</referenceTo>
    <relationshipLabel>REV Contract Master</relationshipLabel>
    <relationshipName>Aureus_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RT_PriceOutput__c/RT_PriceOutput__c.object-meta.xml
<CustomObject>
    <label>Turkey Price Output</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Price Output Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Turkey Price Outputs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RT_Setting__c/RT_Setting__c.object-meta.xml
<CustomObject>
    <label>REV Country Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REV Country Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RT_Setting__c/fields/RE_Location__c.field-meta.xml
<CustomField>
    <fullName>RE_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipLabel>REV Country Settings</relationshipLabel>
    <relationshipName>REV_Country_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RT_Setting__c/fields/RE_Location_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Location_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location Name</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipLabel>REV Country Settings (Location Name)</relationshipLabel>
    <relationshipName>REV_Country_Settings_CND_CS_Location</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RT_Setting__c/fields/RE_Product__c.field-meta.xml
<CustomField>
    <fullName>RE_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>used in List price calculation Malaysia customer Opps</description>
    <label>Product</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipLabel>REV Country Settings</relationshipLabel>
    <relationshipName>REV_Country_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RT_Setting__c/fields/RE_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipLabel>REV Country Settings</relationshipLabel>
    <relationshipName>REV_Country_Settings_CND_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RT_REVContractDataBatchTest.cls
/**
* Created by Dharmendra.Singh2 on 8/1/2020.
*/


@IsTest  (SeeAllData=false)
private class RT_REVContractDataBatchTest {


    @IsTest
    static void setupTestData() {
        
        List<RT_Setting__c> csList = new List<RT_Setting__c>();
        RT_Setting__c payTerm = new RT_Setting__c();
        payTerm.Name = 'Z042';
        payTerm.RecordTypeId = RT_Util.codeSettRecTypeId;
        payTerm.Type__c = 'Payment Term';
        csList.add(payTerm);
        
        RT_Setting__c condType = new RT_Setting__c();
        condType.Name = 'YP04';
        condType.RecordTypeId = RT_Util.codeSettRecTypeId;
        condType.Type__c = 'Condition Type';
        csList.add(condType);
        
        insert csList;
        
        
        List<Account> accList = new List<Account>();
        for(Integer i=0; i< 100; i++){
            Account a = new Account();
            a.Name = 'Test'+i;
            a.AccountNumber = '123456'+i;
            a.RecordTypeId =RT_Util.accRecTypeId;
            a.Customer_Type__c = 'Sold To';
            a.RT_PaymentTerm__c=csList[0].Id;
            accList.add(a);
        }
        insert accList;

        RE_Product__c product = new RE_Product__c();
        product.Name = 'Test Product';
        product.RT_Product_Code__c = '26536354';
        product.RecordTypeId = RT_Util.prodRecTypeId;
        insert product;

        RE_Location__c location = new RE_Location__c();
        location.Name = 'Test Location';
        location.RT_Location_Type__c = RT_Util.depotLocType;
        location.RecordTypeId = RT_Util.locRecTypeId;
        insert location;
        
        List<RE_Contract__c> contractList = new List<RE_Contract__c>();
        for(Integer j=0; j< 100; j++){
            RE_Contract__c c = new RE_Contract__c();
            c.Active__c=true;
            c.RT_Contract_Number__c='321133965'+j;
            c.RE_Product_Name__c = product.Id;
            c.RT_Contract_Item__c = '10';
            c.RT_Valid_From__c = System.today()-30;
            c.RT_Valid_To__c = System.today()+30;
            c.RT_Sold_To_Name__c = accList[j].Id;
            c.RT_Ship_to_Name__c = accList[j].Id;
            c.RE_Location_Name__c = location.Id;
            c.RT_Terms_of_Payment__c = csList[0].Id;
            contractList.add(c);
        }
        insert contractList;

        List<REV_Contract_Master__c> auList = new List<REV_Contract_Master__c>();
        for(Integer k=0; k< 100; k++){
            REV_Contract_Master__c au = new REV_Contract_Master__c();
            au.Active__c = true;
            //au.RT_Sold_to_Name__c=accList[k].Id;
            au.RT_AMOUNT__c = 300;
            //au.RT_Ship_to_Name__c = accList[k].Id;
            au.SAP_Contract__c = contractList[k].Id;
            au.RT_Condition_Type__c = csList[1].Id;
            au.RT_Plant_Desc__c = location.Id;
            au.RT_Material_Desc__c = product.Id;
            au.Country_Name__c = 'TU';
            au.RT_Key_Value__c = 'TR040202032222639600000000040000375'+k;
            auList.add(au);
        }
        insert auList;

        List<REV_Contract_Master__c> RevUpdateList = new List<REV_Contract_Master__c>();
        for(REV_Contract_Master__c revContract : auList){
            revContract.RT_AMOUNT__c = 400;
            RevUpdateList.add(revContract);
        }
        update RevUpdateList;

        String cronExpr = '0 0 0 15 3 ? 2099';
        String jobRunningTime = '2022-03-15 00:00:00';
        
        Test.startTest();
        RT_REVContractDataBatch obj = new RT_REVContractDataBatch();  
        Database.executeBatch( obj );
        String jobId = 
        System.schedule('RT_AureusJobSchedule', cronExpr, new RT_AureusJobSchedule());
        Test.stopTest();  
        
        //List < RT_PriceOutput__c > poList = [ SELECT Id FROM RT_PriceOutput__c ];  
        //system.assertEquals( 100, poList.size() );  
        
    }  
    
}