force-app/main/default/objects/Account/fields/GSAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>GSAP_Account_Number__c</fullName>
    <description>This is the field where the account number from Chemical GSAP will be mapped to account number from P80</description>
    <label>GSAP Account Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mode_of_Transport__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Transport__c</fullName>
    <description>Mode of Transport</description>
    <label>Mode of Transport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Rail</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Road Tank Truck</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Bulk tanker</label>
            </value>
            <value>
                <fullName>36</fullName>
                <label>Road IM Portable Tnk</label>
            </value>
            <value>
                <fullName>1J</fullName>
                <label>Bulk Cont. road/sea</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Rail Tank Car</label>
            </value>
            <value>
                <fullName>37</fullName>
                <label>Road (Bulk)  / Rail</label>
            </value>
            <value>
                <fullName>39</fullName>
                <label>Road(Bulk)/Short Sea</label>
            </value>
            <value>
                <fullName>80</fullName>
                <label>Inland water-transpt</label>
            </value>
            <value>
                <fullName>3A</fullName>
                <label>Road(Pack)/Short Sea</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>Air-transport</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>Pipeline-transport</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <inlineHelpText>Pick list</inlineHelpText>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tonnes</fullName>
                <default>true</default>
                <label>Tonnes</label>
            </value>
            <value>
                <fullName>Liters</fullName>
            </value>
            <value>
                <fullName>Gallons</fullName>
            </value>
            <value>
                <fullName>Barrels</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/TCP_Account.recordType-meta.xml
<RecordType>
    <fullName>TCP_Account</fullName>
    <active>true</active>
    <label>TCP Account</label>
</RecordType>

force-app/main/default/objects/CurrentOrders__x/CurrentOrders__x.object-meta.xml
<CustomObject>
    <description>CurrentOrdersSet</description>
    <externalDataSource>TCP_Get_Current_Orders</externalDataSource>
    <externalName>CurrentOrdersSet</externalName>
    <label>CurrentOrders</label>
    <pluralLabel>CurrentOrdersSet</pluralLabel>
</CustomObject>

force-app/main/default/objects/CurrentOrders__x/fields/Terms__c.field-meta.xml
<CustomField>
    <fullName>Terms__c</fullName>
    <description>Terms</description>
    <externalDeveloperName>Terms</externalDeveloperName>
    <label>Terms</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Delivery_Terms__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Terms__c</fullName>
    <label>Delivery Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FCA</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>CFR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Mode_of_Transport__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Transport__c</fullName>
    <label>Mode of Transport</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bulk tanker</fullName>
            </value>
            <value>
                <fullName>Rail Tank Car</fullName>
            </value>
            <value>
                <fullName>Road Tank Truck</fullName>
            </value>
            <value>
                <fullName>Road IM Portable Tnk</fullName>
            </value>
            <value>
                <fullName>Road (Bulk)  / Rail</fullName>
            </value>
            <value>
                <fullName>Road(Bulk)/Short Sea</fullName>
            </value>
            <value>
                <fullName>Inland water-transpt</fullName>
            </value>
            <value>
                <fullName>Bulk Cont. road/sea</fullName>
            </value>
            <value>
                <fullName>No transport</fullName>
            </value>
            <value>
                <fullName>Pack Cont. road/sea</fullName>
            </value>
            <value>
                <fullName>Rail Hopper Car</fullName>
            </value>
            <value>
                <fullName>Road Hopper Truck</fullName>
            </value>
            <value>
                <fullName>Road Package Truck</fullName>
            </value>
            <value>
                <fullName>Road Package Trk.LTL</fullName>
            </value>
            <value>
                <fullName>Road (Bulk) / Barge</fullName>
            </value>
            <value>
                <fullName>Road(Pack)/Short Sea</fullName>
            </value>
            <value>
                <fullName>Air-transport</fullName>
            </value>
            <value>
                <fullName>Pipeline-transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Other_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Order_Other_Instructions__c</fullName>
    <label>Order Other Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/Payer__c.field-meta.xml
<CustomField>
    <fullName>Payer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Payer)</relationshipLabel>
    <relationshipName>Payer_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sales_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Number__c</fullName>
    <description>track Sales Order Number from Chemical GSAP and 3rd Party</description>
    <label>Sales Order Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Ship To)</relationshipLabel>
    <relationshipName>Ship_To_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Sold To)</relationshipLabel>
    <relationshipName>Sold_To_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/TCP_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>TCP_Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Approved (M)</fullName>
            </value>
            <value>
                <fullName>Approved (C)</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TCP_OrdrManagementProcessorTest.cls
@isTest
public class TCP_OrdrManagementProcessorTest {
@TestSetup
    static void createTestData() {
        
        List<Account> testAccounts=TCP_TestDataUtilities.createAccounts(1,false);
        List<contact> testContact=TCP_TestDataUtilities.createContacts(1,testAccounts[0]);
        List<Order> testOrder=TCP_TestDataUtilities.createOrders(1,testAccounts[0]);
        
    }
     @istest
    static void trackStatusGSAPOrderTest(){
         string tcpAccountRecTypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('TCP_Account').getRecordTypeId();
        Account acc=[select id,name,recordtype.id,GSAP_Account_Number__c,AccountNumber from account where name='SampleAccount0' limit 1];
        acc.recordtype.id=tcpAccountRecTypeid;
        update acc;
        Order ord=[select id,Name,recordtype.id,createddate, AccountId,Sales_Order_Number__c, OrderNumber, Sold_To__c, Ship_To__c,Payer__c,Bill_To__c, EffectiveDate,Ship_To__r.GSAP_Account_Number__c,Sold_To__r.GSAP_Account_Number__c,Bill_To__r.GSAP_Account_Number__c, poNumber, Payer__r.GSAP_Account_Number__c,Order_Other_Instructions__c, Mode_of_Transport__c, Delivery_Terms__c, TCP_Order_Status__c, status,CreatedBy.Name from Order where TCP_Order_Status__c='Submitted' limit 1];
  /**CurrentOrders__x cuOrd=new CurrentOrders__x();
        cuOrd.Soldto__c=ord.Sold_To__r.GSAP_Account_Number__c;
        cuOrd.Weborder__c=ord.Id;
        cuOrd.Unit__c='KG';
         cuOrd.Terms__c='Terms';
        insert cuOrd;**/
        
        List<CurrentOrders__x> cuOrdList=[Select Id,Soldto__c,Weborder__c,Unit__c,Terms__c from CurrentOrders__x where Weborder__c=:ord.Id ];
        TCP_OrderManagementProcessor.trackStatusGSAPOrder(ord.Id,true, false, ord.Sales_Order_Number__c,false);
         TCP_OrderManagementProcessor.trackStatusGSAPOrder(ord.Id,false, true, ord.Sales_Order_Number__c,false);
        TCP_OrderManagementProcessor.trackCurrentOrderFromsGSAP(cuOrdList,ord.Sold_To__r.GSAP_Account_Number__c,acc.AccountNumber);
    }
}