force-app/main/default/objects/Account/fields/GSAP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>GSAP_Account_Number__c</fullName>
    <description>This is the field where the account number from Chemical GSAP will be mapped to account number from P80</description>
    <label>GSAP Account Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Area__c.field-meta.xml
<CustomField>
    <fullName>Sales_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Area</label>
    <referenceTo>TCP_Sales_Area__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/GSAP_Status__c.field-meta.xml
<CustomField>
    <fullName>GSAP_Status__c</fullName>
    <label>GSAP Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Queue</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed to Process</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Resent</fullName>
            </value>
            <value>
                <fullName>No GSAP Response</fullName>
            </value>
            <value>
                <fullName>Stuck in Queue</fullName>
            </value>
            <value>
                <fullName>Sent Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Ship To)</relationshipLabel>
    <relationshipName>Ship_To_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Sold To)</relationshipLabel>
    <relationshipName>Sold_To_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/tcp_email_alert_sent__c.field-meta.xml
<CustomField>
    <fullName>tcp_email_alert_sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email alert sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TCP_DistributionEmailList__c/TCP_DistributionEmailList__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To capture distribution list of each region.</description>
    <label>TCP Distribution Email List</label>
</CustomObject>

force-app/main/default/objects/TCP_DistributionEmailList__c/fields/TCP_Commops_Delivery_Lists__c.field-meta.xml
<CustomField>
    <fullName>TCP_Commops_Delivery_Lists__c</fullName>
    <description>To capture multiple DL&apos;s that should be placed in TCP related emails CC address. Please separate email address with semicolon ;</description>
    <inlineHelpText>To capture multiple DL&apos;s that should be placed in TCP related emails CC address. Please separate email address with semicolon ;</inlineHelpText>
    <label>TCP Commops Delivery Lists</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_Sales_Area__c/TCP_Sales_Area__c.object-meta.xml
<CustomObject>
    <label>Sales Area</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Sales Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Area</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TCP_Sales_Area__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sales area account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Area</relationshipLabel>
    <relationshipName>Sales_Area</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TCP_Sales_Area__c/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TCP_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TCP_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EAST</fullName>
    </customValue>
    <customValue>
        <fullName>EUROPE</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>Singapore</fullName>
        <isActive>false</isActive>
        <label>Singapore</label>
    </customValue>
    <masterLabel>TCP Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TCP_OrderFailedAlertHelper.cls
public with sharing class TCP_OrderFailedAlertHelper {
	public static void processFailedOrderList(List<sObject> scope){
        List<Order> ordList = new List<Order>();
        for(sObject objScope : scope){
                Order ord = (Order)objScope;
                if(ord.GSAP_Status__c == 'No GSAP Response' || ord.GSAP_Status__c == 'Sent Failed'){
                    ord.tcp_email_alert_sent__c = true;
                    ordList.add(ord);
                }
        }
        
        if(ordList.size()>0){
            List<String> ordStrListEast = new List<String>();
            List<String> ordStrListEur = new List<String>();
            List<String> ordStrListNA = new List<String>();
            for(Order ord: ordList){
                datetime ordDate = ord.CreatedDate;
                String ordCreatedDate = ordDate.format('dd MMM yyyy HH:MM:SS').toUpperCase();
                dateTime lastModDt = ord.LastModifiedDate;
                String lastModDate = lastModDt.format('dd MMM yyyy HH:MM:SS').toUpperCase();
                String ordString = 'WEBORDERNUMBER- '+ord.OrderNumber+', SOLDTOID- '+ord.Sold_To__r.GSAP_Account_Number__c+', SHIPTOID- '+ord.Ship_To__r.GSAP_Account_Number__c+', CREATEDBY- '+ord.CreatedBy.Name+', CREATEDDATE- '+ordCreatedDate+', STATUS- '+ord.GSAP_Status__c+', LASTMODIFIED- '+lastModDate;
                if(ord.Sold_To__r.Sales_Area__r.Sales_Region__c == 'EAST'){
                    ordStrListEast.add(ordString);
                }else if(ord.Sold_To__r.Sales_Area__r.Sales_Region__c == 'EUROPE'){
                    ordStrListEur.add(ordString);
                }else if(ord.Sold_To__r.Sales_Area__r.Sales_Region__c == 'NA'){
                    ordStrListNA.add(ordString);
                }
            }
            if(ordStrListEast.size()>0){
                sendEmail(ordStrListEast,'EAST',true);
            }
            if(ordStrListEur.size()>0){
                sendEmail(ordStrListEur,'EUROPE',true);
            }
            if(ordStrListNA.size()>0){
                sendEmail(ordStrListNA,'NA',true);
            }
			update ordList;        
        }
		
    }
    
    public static void sendEmail(List<String> ordStrList,String region, Boolean useOrgAddress) {
        try {
            String msgBody ='<pre><br></br>Failed Order Information:<br></br>';
            for(String ord : ordStrList){
                msgBody += ord+'<br></br>';
            }
            msgBody = msgBody + '</pre>';
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            TCP_DistributionEmailList__c ccListBasedOnRegion = TCP_DistributionEmailList__c.getValues(region);
            if(ccListBasedOnRegion!=null){
             	List<string> toEmailList=ccListBasedOnRegion.TCP_Commops_Delivery_Lists__c.split(';'); 
                mail.setToAddresses(toEmailList);
                mail.setSubject('Order Alert - '+region);
                mail.setHtmlBody(System.label.TCP_BatchJobOrderAlertHeaderText+msgBody);
            }
           
            if(useOrgAddress){
                OrgWideEmailAddress OrgWideEmail = [Select id From OrgWideEmailAddress o where o.DisplayName =:Label.TCP_From_Email_Address Limit 1];
          	  	mail.setOrgWideEmailAddressId(OrgWideEmail.Id);
            }
            List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
		 	mails.add(mail);
            if(!mails.isempty()){
                Messaging.sendEmail(mails);
            }
        }
        catch(Exception excptn) {
            TCP_ExceptionLogClass.insertExceptionRecord('TCP Failed Order Alert',excptn.getMessage(),'TCP_OrderFailedAlertHelper','sendEmail','Exception');
            throw excptn;
        }
    }
}