force-app/main/default/objects/Account/fields/Mode_of_Transport__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Transport__c</fullName>
    <description>Mode of Transport</description>
    <label>Mode of Transport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Rail</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Road Tank Truck</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Bulk tanker</label>
            </value>
            <value>
                <fullName>36</fullName>
                <label>Road IM Portable Tnk</label>
            </value>
            <value>
                <fullName>1J</fullName>
                <label>Bulk Cont. road/sea</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Rail Tank Car</label>
            </value>
            <value>
                <fullName>37</fullName>
                <label>Road (Bulk)  / Rail</label>
            </value>
            <value>
                <fullName>39</fullName>
                <label>Road(Bulk)/Short Sea</label>
            </value>
            <value>
                <fullName>80</fullName>
                <label>Inland water-transpt</label>
            </value>
            <value>
                <fullName>3A</fullName>
                <label>Road(Pack)/Short Sea</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>Air-transport</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>Pipeline-transport</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <inlineHelpText>Pick list</inlineHelpText>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tonnes</fullName>
                <default>true</default>
                <label>Tonnes</label>
            </value>
            <value>
                <fullName>Liters</fullName>
            </value>
            <value>
                <fullName>Gallons</fullName>
            </value>
            <value>
                <fullName>Barrels</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Contact_Relationship__c/Account_Contact_Relationship__c.object-meta.xml
<CustomObject>
    <description>This junction object connects the Account and Contact standard objects in a many-to-many relationship and houses customized user permission indicators which can be enabled per portal user and can be made unique to a given Account-Contact pair.</description>
    <label>Account Contact Relationship</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Account Contact Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contact Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Contact_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Contact Relationship</relationshipLabel>
    <relationshipName>Account_Contact_Relationship</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Contact_Relationship__c/fields/Portal_User_Contact__c.field-meta.xml
<CustomField>
    <fullName>Portal_User_Contact__c</fullName>
    <description>Related Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Related Accounts</relationshipLabel>
    <relationshipName>Account_Contact_Relationship</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Contact/fields/TCP_TandC__c.field-meta.xml
<CustomField>
    <fullName>TCP_TandC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TCP TandC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Delivery_Terms__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Terms__c</fullName>
    <label>Delivery Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FCA</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>CFR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Mode_of_Transport__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Transport__c</fullName>
    <label>Mode of Transport</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bulk tanker</fullName>
            </value>
            <value>
                <fullName>Rail Tank Car</fullName>
            </value>
            <value>
                <fullName>Road Tank Truck</fullName>
            </value>
            <value>
                <fullName>Road IM Portable Tnk</fullName>
            </value>
            <value>
                <fullName>Road (Bulk)  / Rail</fullName>
            </value>
            <value>
                <fullName>Road(Bulk)/Short Sea</fullName>
            </value>
            <value>
                <fullName>Inland water-transpt</fullName>
            </value>
            <value>
                <fullName>Bulk Cont. road/sea</fullName>
            </value>
            <value>
                <fullName>No transport</fullName>
            </value>
            <value>
                <fullName>Pack Cont. road/sea</fullName>
            </value>
            <value>
                <fullName>Rail Hopper Car</fullName>
            </value>
            <value>
                <fullName>Road Hopper Truck</fullName>
            </value>
            <value>
                <fullName>Road Package Truck</fullName>
            </value>
            <value>
                <fullName>Road Package Trk.LTL</fullName>
            </value>
            <value>
                <fullName>Road (Bulk) / Barge</fullName>
            </value>
            <value>
                <fullName>Road(Pack)/Short Sea</fullName>
            </value>
            <value>
                <fullName>Air-transport</fullName>
            </value>
            <value>
                <fullName>Pipeline-transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Other_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Order_Other_Instructions__c</fullName>
    <label>Order Other Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/Ordered_By__c.field-meta.xml
<CustomField>
    <fullName>Ordered_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordered By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Ship To)</relationshipLabel>
    <relationshipName>Ship_To_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Sold To)</relationshipLabel>
    <relationshipName>Sold_To_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/TCP_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>TCP_Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Approved (M)</fullName>
            </value>
            <value>
                <fullName>Approved (C)</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/recordTypes/TCP_Orders.recordType-meta.xml
<RecordType>
    <fullName>TCP_Orders</fullName>
    <active>true</active>
    <description>This record type will be used for Trading customer portal</description>
    <label>TCP Orders</label>
</RecordType>

force-app/main/default/objects/TCP_OrderLineItem__c/TCP_OrderLineItem__c.object-meta.xml
<CustomObject>
    <description>This object hold the line item details</description>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TCP_OrderLineItem__c/fields/Contract_No__c.field-meta.xml
<CustomField>
    <fullName>Contract_No__c</fullName>
    <label>Contract No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_OrderLineItem__c/fields/Delivery_Collection_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Collection_Date__c</fullName>
    <label>Delivery/Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TCP_OrderLineItem__c/fields/Material_Name__c.field-meta.xml
<CustomField>
    <fullName>Material_Name__c</fullName>
    <label>Material Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_OrderLineItem__c/fields/MaterialNumber__c.field-meta.xml
<CustomField>
    <fullName>MaterialNumber__c</fullName>
    <label>MaterialNumber</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_OrderLineItem__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TCP_OrderLineItem__c/fields/Other_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Other_Instruction__c</fullName>
    <label>Other Instruction</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/TCP_OrderLineItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TCP_OrderLineItem__c/fields/Special_Price__c.field-meta.xml
<CustomField>
    <fullName>Special_Price__c</fullName>
    <label>Special Price</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_OrderLineItem__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KG</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TCP_HomePageControllerTest.cls
/*****************************************************************************
 * Purpose: Test class for TCP_HomePageController
 * Verion : 1.0
 * **************************************************************************/
@isTest
public class TCP_HomePageControllerTest {
    
	@TestSetup
    static void createTestData(){
         User us=TCP_TestDataUtilities.createAdminUsers();
        System.runAs(us){
        List<Account> testAccounts=TCP_TestDataUtilities.createAccounts(1,false);
        List<contact> testContact=TCP_TestDataUtilities.createContacts(1,testAccounts[0]);
        List<Account_Contact_Relationship__c> testacr=TCP_TestDataUtilities.createACRRecords(testAccounts[0], testContact[0], 1);
   		List<Order> testOrder=TCP_TestDataUtilities.createOrders(1,testAccounts[0]);
         List<TCP_OrderLineItem__c> ordLine=TCP_TestDataUtilities.createOrderLineItems(1,testOrder[0]);
        }
    }
    
    @isTest
    static void PostiveTestCase(){
        string tcpOrderRecTypeid = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('TCP_Orders').getRecordTypeId();
        List<TCP_OrderLineItemWrapper> lineWrapList=new List<TCP_OrderLineItemWrapper>();
        Account acc=[select id, AccountNumber, ParentId,recordtype.id, name from account where name='SampleAccount0' limit 1];
        acc.recordtype.id=tcpOrderRecTypeid;
        update acc;
        Order ord=[select  id,Name, AccountId, OrderNumber, Sold_To__c, Ship_To__c, EffectiveDate, poNumber, Order_Other_Instructions__c, Mode_of_Transport__c, Delivery_Terms__c, TCP_Order_Status__c, status from order where Sold_To__c=:acc.Id limit 1];
        TCP_OrderLineItem__c ordLine=[Select Id, Order__c, Quantity__c, Unit__c, Delivery_Collection_Date__c, MaterialNumber__c, Material_Name__c, Contract_No__c, Special_Price__c, Other_Instruction__c from TCP_OrderLineItem__c where Order__c=:ord.Id];
        
        List<Account_Contact_Relationship__c>  acrRecList=[select id, account__c,Portal_User_Contact__c from Account_Contact_Relationship__c where account__c=:acc.id limit 1];
        List<contact> testCons=new List<contact> ([select id,TCP_TandC__c, Email, Name from contact limit 1]);
        List<User> listofusers=TCP_TestDataUtilities.createcustomerUsers(1, 'TCPCustomerCommunityPlusUser', testCons[0]);
         TCP_OrderWrapper wrap=new TCP_OrderWrapper();
        wrap.id=ord.Id;
        wrap.name=ord.Name;
        wrap.orderNumber=ord.OrderNumber;
        wrap.poNumber=ord.PoNumber;
        wrap.otherInstructions=ord.Order_Other_Instructions__c;
        wrap.modeOfTransport=ord.Mode_of_Transport__c;
        wrap.deliveryTerms=ord.Delivery_Terms__c;
        wrap.status=ord.Status;
        wrap.soldToId=acc.Id;
        wrap.shipToId = acc.Id;
        wrap.billToId = acc.Id;
        wrap.shipToNumber = acc.AccountNumber;
        wrap.soldToName = acc.Name;
        wrap.billToNumber = acc.AccountNumber;
        wrap.shipToNumber = acc.AccountNumber;
        wrap.payerNumber = acc.AccountNumber;
        wrap.payerId = acc.Id;
        TCP_OrderLineItemWrapper lineWrap=new TCP_OrderLineItemWrapper();
        lineWrap.Id=ordLine.Id;
        lineWrap.shellContractNo = '12345';
        lineWrap.instructions = 'test';
        lineWrap.orderId=ordLine.Order__c;
        lineWrap.quantity=String.valueOf(ordLine.Quantity__c);
        lineWrap.unit=ordLine.Unit__c;
        lineWrap.deliveryCollDate=String.valueOf(ordLine.Delivery_Collection_Date__c);
        lineWrap.materialNumber=ordLine.MaterialNumber__c;
        lineWrap.materialName=ordLine.Material_Name__c;
        lineWrapList.add(lineWrap);
        System.runas(listofusers[0]){
        test.startTest();
        TCP_HomePageController.getAccountDataOfEndUser();
       TCP_HomePageController.getAccountDetails();
        TCP_HomePageController.getAccountDetailsOfComOps(listofusers[0]);
        TCP_HomePageController.loggedInAsTcpUser();
        TCP_HomePageController.getAccountId();
        TCP_HomePageController.getAccDetailsByParentId(acc.Id);
        TCP_HomePageController.getCustomerByAccountId(acc.Id);
        TCP_HomePageController.getProductDetails(acc.ParentId, acc.Id);
        TCP_HomePageController.getProductDetailsBySearchKey('searchKey', acc.ParentId, acc.Id);//Need check for searchKey
        TCP_HomePageController.getPickListValues('Order', 'Mode_of_Transport__c');
        TCP_HomePageController.getCountOfOrders(acc.Id, 'Draft');
        TCP_HomePageController.getCountOfOrdersEU(acc.ParentId);
        TCP_HomePageController.getCountOfOrdersCU(acc.ParentId);
        TCP_HomePageController.saveOrderLineItems(lineWrapList, ord.Id);
        TCP_HomePageController.getOrderedByUserId();
        TCP_HomePageController.getAllProductDetailsBySoldToId(acc.Id);
        TCP_HomePageController.getCustomerBySoldToAndType(acc.ParentId, 'Sold To');
        TCP_HomePageController.getOrderedBySoldToId(acc.ParentId);
        TCP_HomePageController.getOrderNumberOnSave(wrap,lineWrapList,null,false);
        
        Test.stopTest();
        }
       
    }
    
    @isTest
    static void NegativeTestCase(){
        string tcpOrderRecTypeid = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('TCP_Orders').getRecordTypeId();
         List<TCP_OrderLineItemWrapper> lineWrapList=new List<TCP_OrderLineItemWrapper>();
        Account acc=[select id, ParentId,recordtype.id, name from account where name='SampleAccount0' limit 1];
        acc.recordtype.id=tcpOrderRecTypeid;
        update acc;
        Order ord=[select  id,Name, AccountId, OrderNumber, Sold_To__c, Ship_To__c, EffectiveDate, poNumber, Order_Other_Instructions__c, Mode_of_Transport__c, Delivery_Terms__c, TCP_Order_Status__c, status from order where Sold_To__c=:acc.Id limit 1];
        TCP_OrderLineItem__c ordLine=[Select Id, Order__c, Quantity__c, Unit__c, Delivery_Collection_Date__c, MaterialNumber__c, Material_Name__c, Contract_No__c, Special_Price__c, Other_Instruction__c from TCP_OrderLineItem__c where Order__c=:ord.Id];
        
        List<Account_Contact_Relationship__c>  acrRecList=[select id, account__c,Portal_User_Contact__c from Account_Contact_Relationship__c where account__c=:acc.id limit 1];
        List<contact> testCons=new List<contact> ([select id,TCP_TandC__c, Email, Name from contact limit 1]);
        List<User> listofusers=TCP_TestDataUtilities.createcustomerUsers(1, 'TCPCustomerCommunityPlusUser', testCons[0]);
         TCP_OrderWrapper wrap=new TCP_OrderWrapper();
        wrap.id=ord.Id;
        wrap.name=ord.Name;
        wrap.orderNumber=ord.OrderNumber;
        wrap.poNumber=ord.PoNumber;
        wrap.otherInstructions=ord.Order_Other_Instructions__c;
        wrap.modeOfTransport=ord.Mode_of_Transport__c;
        wrap.deliveryTerms=ord.Delivery_Terms__c;
        wrap.status=ord.Status;
        wrap.soldToId=acc.Id;
        TCP_OrderLineItemWrapper lineWrap=new TCP_OrderLineItemWrapper();
        lineWrap.Id=ordLine.Id;
        lineWrap.orderId=ordLine.Order__c;
        lineWrap.quantity=String.valueOf(ordLine.Quantity__c);
        lineWrap.unit=ordLine.Unit__c;
        lineWrap.deliveryCollDate=String.valueOf(ordLine.Delivery_Collection_Date__c);
        lineWrap.materialNumber=ordLine.MaterialNumber__c;
        lineWrap.materialName=ordLine.Material_Name__c;
        lineWrapList.add(lineWrap);
        System.runas(listofusers[0]){
        test.startTest();
        TCP_HomePageController.getAccountDataOfEndUser();
       	TCP_HomePageController.getAccountDetails();
        TCP_HomePageController.getAccountDetailsOfComOps(listofusers[0]);
        TCP_HomePageController.loggedInAsTcpUser();
        TCP_HomePageController.getAccountId();
        TCP_HomePageController.getAccDetailsByParentId('acc.ParentId');
        TCP_HomePageController.getCustomerByAccountId('acc.Id');
        TCP_HomePageController.getProductDetails('acc.ParentId', 'acc.Id');
        TCP_HomePageController.getProductDetailsBySearchKey('searchKey', 'acc.ParentId', 'acc.Id');//Need check for searchKey
        TCP_HomePageController.getPickListValues('Order', 'Mode_of_Transport__c');
        TCP_HomePageController.getCountOfOrders('acc.Id', 'Draft');
        TCP_HomePageController.getCountOfOrdersEU('acc.ParentId');
        TCP_HomePageController.getCountOfOrdersCU('acc.ParentId');
        TCP_HomePageController.saveOrderLineItems(lineWrapList, ord.Id);
        TCP_HomePageController.getOrderedByUserId();
        TCP_HomePageController.getAllProductDetailsBySoldToId('acc.ParentId');
        TCP_HomePageController.getCustomerBySoldToAndType('acc.ParentId', 'Sold To');
        TCP_HomePageController.getOrderedBySoldToId('acc.ParentId');
        TCP_HomePageController.getOrderNumberOnSave(wrap,lineWrapList,null,false);
        
        Test.stopTest();
        }
       
    }
    
    	@isTest
        public static void testGetOrderedBySoldToId(){
            Account acc=[select id, ParentId,recordtype.id, name from account where name='SampleAccount0' limit 1];
            Order ord=[select  id,Name, AccountId, OrderNumber, Ordered_By__c, Sold_To__c, Ship_To__c, EffectiveDate, poNumber, Order_Other_Instructions__c, Mode_of_Transport__c, Delivery_Terms__c, TCP_Order_Status__c, status from order where Sold_To__c=:acc.Id limit 1];
            ord.Ordered_By__c = userInfo.getUserId();
            update ord;
            System.debug('sold to c print:'+ord.Sold_To__c);
            Test.startTest();
            	TCP_HomePageController.getOrderedBySoldToId(acc.Id);
            Test.stopTest();
        }

}