force-app/main/default/objects/Account/fields/Mode_of_Transport__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Transport__c</fullName>
    <description>Mode of Transport</description>
    <label>Mode of Transport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Rail</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Road Tank Truck</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Bulk tanker</label>
            </value>
            <value>
                <fullName>36</fullName>
                <label>Road IM Portable Tnk</label>
            </value>
            <value>
                <fullName>1J</fullName>
                <label>Bulk Cont. road/sea</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Rail Tank Car</label>
            </value>
            <value>
                <fullName>37</fullName>
                <label>Road (Bulk)  / Rail</label>
            </value>
            <value>
                <fullName>39</fullName>
                <label>Road(Bulk)/Short Sea</label>
            </value>
            <value>
                <fullName>80</fullName>
                <label>Inland water-transpt</label>
            </value>
            <value>
                <fullName>3A</fullName>
                <label>Road(Pack)/Short Sea</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>Air-transport</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>Pipeline-transport</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/TCP_Account.recordType-meta.xml
<RecordType>
    <fullName>TCP_Account</fullName>
    <active>true</active>
    <label>TCP Account</label>
</RecordType>

force-app/main/default/objects/Account_Contact_Relationship__c/Account_Contact_Relationship__c.object-meta.xml
<CustomObject>
    <description>This junction object connects the Account and Contact standard objects in a many-to-many relationship and houses customized user permission indicators which can be enabled per portal user and can be made unique to a given Account-Contact pair.</description>
    <label>Account Contact Relationship</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Account Contact Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contact Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Contact_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Contact Relationship</relationshipLabel>
    <relationshipName>Account_Contact_Relationship</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Contact_Relationship__c/fields/Portal_User_Contact__c.field-meta.xml
<CustomField>
    <fullName>Portal_User_Contact__c</fullName>
    <description>Related Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Related Accounts</relationshipLabel>
    <relationshipName>Account_Contact_Relationship</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Order/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/BillToNo__c.field-meta.xml
<CustomField>
    <fullName>BillToNo__c</fullName>
    <label>BillToNo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Delivery_Terms__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Terms__c</fullName>
    <label>Delivery Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FCA</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>CFR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Mode_of_Transport__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Transport__c</fullName>
    <label>Mode of Transport</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bulk tanker</fullName>
            </value>
            <value>
                <fullName>Rail Tank Car</fullName>
            </value>
            <value>
                <fullName>Road Tank Truck</fullName>
            </value>
            <value>
                <fullName>Road IM Portable Tnk</fullName>
            </value>
            <value>
                <fullName>Road (Bulk)  / Rail</fullName>
            </value>
            <value>
                <fullName>Road(Bulk)/Short Sea</fullName>
            </value>
            <value>
                <fullName>Inland water-transpt</fullName>
            </value>
            <value>
                <fullName>Bulk Cont. road/sea</fullName>
            </value>
            <value>
                <fullName>No transport</fullName>
            </value>
            <value>
                <fullName>Pack Cont. road/sea</fullName>
            </value>
            <value>
                <fullName>Rail Hopper Car</fullName>
            </value>
            <value>
                <fullName>Road Hopper Truck</fullName>
            </value>
            <value>
                <fullName>Road Package Truck</fullName>
            </value>
            <value>
                <fullName>Road Package Trk.LTL</fullName>
            </value>
            <value>
                <fullName>Road (Bulk) / Barge</fullName>
            </value>
            <value>
                <fullName>Road(Pack)/Short Sea</fullName>
            </value>
            <value>
                <fullName>Air-transport</fullName>
            </value>
            <value>
                <fullName>Pipeline-transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Other_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Order_Other_Instructions__c</fullName>
    <label>Order Other Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/Ordered_By__c.field-meta.xml
<CustomField>
    <fullName>Ordered_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordered By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Payer__c.field-meta.xml
<CustomField>
    <fullName>Payer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Payer)</relationshipLabel>
    <relationshipName>Payer_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/PayerNo__c.field-meta.xml
<CustomField>
    <fullName>PayerNo__c</fullName>
    <label>PayerNo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Ship To)</relationshipLabel>
    <relationshipName>Ship_To_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ShipToNo__c.field-meta.xml
<CustomField>
    <fullName>ShipToNo__c</fullName>
    <label>ShipToNo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Sold To)</relationshipLabel>
    <relationshipName>Sold_To_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/TCP_Bulk_Order_Requested_by__c.field-meta.xml
<CustomField>
    <fullName>TCP_Bulk_Order_Requested_by__c</fullName>
    <description>To contain the contact id of the user while creating bulk order.</description>
    <label>Bulk Order Requested by</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/TCP_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>TCP_Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Approved (M)</fullName>
            </value>
            <value>
                <fullName>Approved (C)</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/TCP_System_BulkOrderNumber__c.field-meta.xml
<CustomField>
    <fullName>TCP_System_BulkOrderNumber__c</fullName>
    <description>This field is used as part of development to save the bulk orders.</description>
    <label>System Bulk Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/TCP_Orders.recordType-meta.xml
<RecordType>
    <fullName>TCP_Orders</fullName>
    <active>true</active>
    <description>This record type will be used for Trading customer portal</description>
    <label>TCP Orders</label>
</RecordType>

force-app/main/default/objects/TCP_OrderLineItem__c/TCP_OrderLineItem__c.object-meta.xml
<CustomObject>
    <description>This object hold the line item details</description>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TCP_OrderLineItem__c/fields/Contract_No__c.field-meta.xml
<CustomField>
    <fullName>Contract_No__c</fullName>
    <label>Contract No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_OrderLineItem__c/fields/Delivery_Collection_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Collection_Date__c</fullName>
    <label>Delivery/Collection Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TCP_OrderLineItem__c/fields/Material_Name__c.field-meta.xml
<CustomField>
    <fullName>Material_Name__c</fullName>
    <label>Material Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_OrderLineItem__c/fields/MaterialNumber__c.field-meta.xml
<CustomField>
    <fullName>MaterialNumber__c</fullName>
    <label>MaterialNumber</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_OrderLineItem__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TCP_Sales_Area__c/TCP_Sales_Area__c.object-meta.xml
<CustomObject>
    <label>Sales Area</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Sales Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Area</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TCP_Sales_Area__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sales area account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Area</relationshipLabel>
    <relationshipName>Sales_Area</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/TCP_Role__c.field-meta.xml
<CustomField>
    <fullName>TCP_Role__c</fullName>
    <description>To identify the logged in user type in community.</description>
    <inlineHelpText>To identify the logged in user type in community.</inlineHelpText>
    <label>TCP Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>End user</fullName>
            </value>
            <value>
                <fullName>CommOpps user</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TCP_BulkOrderController.cls
public with sharing class TCP_BulkOrderController {
    public static string tcpOrderRecTypeid = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('TCP_Orders').getRecordTypeId();
    public static string tcpAccountRecTypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('TCP_Account').getRecordTypeId();
    @AuraEnabled(cacheable=true)
    public static List<Account_Contact_Relationship__c> getCustomerDetails(){
        List<Account_Contact_Relationship__c> acrList = new List<Account_Contact_Relationship__c>();
        try {
            User userData = TCP_Utilities.getLoggedInUserDetails();
            if(userData.TCP_Role__C == 'CommOpps user'){
                acrList = [SELECT id, Account__r.name, Account__r.Active__c, Account__c,  Account__r.AccountNumber, Account__r.ShippingAddress FROM Account_Contact_Relationship__c WHERE Account__r.recordtypeid =: tcpAccountRecTypeid AND Portal_User_Contact__r.Email =:userData.Email AND Account__r.Active__c = true order by CreatedDate ASC];
                if(acrList.size()>0){
                    return acrList;
                }
            }
            
        } catch (Exception e) {
            TCP_ExceptionLogClass.insertExceptionRecord('Bulk order exception',e.getMessage(),'TCP_BulkOrderController','getCustomerDetails','Exception');
            throw new AuraHandledException(e.getMessage());
        }
        return acrList;
    }

    @AuraEnabled
    public static List<user> getContactsByCustomerId(String soldToId){
        try {
            return [Select Id, Name, ContactId, Contact.Name, IsActive from user where IsActive = true AND Contact.AccountId =: soldToId order by Contact.Name];
            
        } catch (Exception e) {
            TCP_ExceptionLogClass.insertExceptionRecord('Bulk order exception',e.getMessage(),'TCP_BulkOrderController','getContactsByCustomerId','Exception');
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Order> saveBulkOrderDetails(List<TCP_OrderWrapper> ordWrapList){
        List<Order> orderList = new List<Order>();
        List<TCP_OrderLineItem__c> ordLineItemList = new List<TCP_OrderLineItem__c>();
        Map<String,List<TCP_OrderLineItemWrapper>> orderLineMap = new Map<String,List<TCP_OrderLineItemWrapper>>();
        try {
            if(ordWrapList.size()>0){
                List<Id> orderIds = new List<Id>();
                List<Id> requestedByIds = new List<Id>();
                List<Id> accountIds = new List<Id>();
                for(TCP_OrderWrapper orderWrapper: ordWrapList){
                    Order orderObj = new Order();
                    if(String.isNotBlank(orderWrapper.name)){
                        orderObj.Name = orderWrapper.name;
                    }
                    if(String.isNotBlank(orderWrapper.poNumber)){
                        orderObj.PoNumber = orderWrapper.poNumber;
                    }
                    if(String.isNotBlank(orderWrapper.deliveryTerms)){
                        orderObj.Delivery_Terms__c = orderWrapper.deliveryTerms;
                    }
                    if(String.isNotBlank(orderWrapper.modeOfTransport)){
                        orderObj.Mode_of_Transport__c = orderWrapper.modeOfTransport;
                    }
                    if(String.isNotBlank(orderWrapper.otherInstructions)){
                        orderObj.Order_Other_Instructions__c = orderWrapper.otherInstructions;
                    }
                    if(String.isNotBlank(orderWrapper.soldToId)){
                        orderObj.Sold_To__c = orderWrapper.soldToId;
                        orderObj.AccountId = orderWrapper.soldToId;
                        accountIds.add(orderWrapper.soldToId);
                    }
                    if(String.isNotBlank(orderWrapper.shipToId)){
                        orderObj.Ship_To__c = orderWrapper.shipToId;
                    }
                    if(String.isNotBlank(orderWrapper.billToId)){
                        orderObj.Bill_To__c = orderWrapper.billToId;
                    }
                    // if(String.isNotBlank(orderWrapper.soldToNumber)){
                    //     orderObj.AccountNumber = orderWrapper.soldToNumber;
                    // }
                    if(String.isNotBlank(orderWrapper.shipToNumber)){
                        orderObj.ShipToNo__c = orderWrapper.shipToNumber;
                    }
                    if(String.isNotBlank(orderWrapper.soldToName)){
                        orderObj.Customer_Name__c = orderWrapper.soldToName;
                    }
                    if(String.isNotBlank(orderWrapper.billToNumber)){
                        orderObj.BillToNo__c = orderWrapper.billToNumber;
                    }
                    if(String.isNotBlank(orderWrapper.payerId)){
                        orderObj.Payer__c = orderWrapper.payerId;
                    }
                    if(String.isNotBlank(orderWrapper.payerNumber)){
                        orderObj.PayerNo__c = orderWrapper.payerNumber;
                    }
                    if(String.isNotBlank(orderWrapper.status)){
                        orderObj.Status = 'Draft';
                        orderObj.TCP_Order_Status__c = orderWrapper.status;
                    }
                    if(String.isNotBlank(orderWrapper.requestedById)){
                        orderObj.TCP_Bulk_Order_Requested_by__c = orderWrapper.requestedById;
                    }
                    orderObj.EffectiveDate = System.today();
                    orderObj.Ordered_By__c = UserInfo.getUserId();
                    String randomNumber = String.valueOf(Integer.valueof((Math.random() * 100000)));
                    orderObj.TCP_System_BulkOrderNumber__c = randomNumber;
                    orderLineMap.put(randomNumber, orderWrapper.orderLineItemWrapList);
                    orderObj.recordtypeid = tcpOrderRecTypeid;
                    requestedByIds.add(orderWrapper.requestedById);
                    orderList.add(orderObj);
                   
                }
                if(orderList.size()>0){
                    Database.insert(orderList, true);
                }
                for(Order ord : orderList){
                    if(orderLineMap.containsKey(ord.TCP_System_BulkOrderNumber__c)){
                        orderIds.add(ord.Id);
                        ordLineItemList.addAll(saveOrderLineItems(orderLineMap.get(ord.TCP_System_BulkOrderNumber__c), ord.Id));
                    }
                }
                if(ordLineItemList.size()>0){
                    Insert ordLineItemList;
                }
                if(orderIds.size()>0 && orderIds.size()<=10){
                    sendOrderAcknowledgement(orderIds, requestedByIds, accountIds, UserInfo.getUserId());
                }else if(orderIds.size()>10 && orderIds.size()<=20){
                    List<Id> orderIdChunk1 = new List<Id>();
                    List<Id> requestedByIdChunk1  = new List<Id>();
                    List<Id> accountIdChunk1  = new List<Id>();
                    for(Integer i=0;i<10;i++){
                        orderIdChunk1.add(orderIds[i]);
                        requestedByIdChunk1.add(requestedByIds[i]);
                        accountIdChunk1.add(accountIds[i]);
                    }
                    if(orderIdChunk1.size()>0){
                        sendOrderAcknowledgement(orderIdChunk1, requestedByIdChunk1, accountIdChunk1, UserInfo.getUserId());
                    }
                    List<Id> orderIdChunk2 = new List<Id>();
                    List<Id> requestedByIdChunk2  = new List<Id>();
                    List<Id> accountIdChunk2  = new List<Id>();
                    
                    for(Integer i=10;i<orderIds.size();i++){
                        orderIdChunk2.add(orderIds[i]);
                        requestedByIdChunk2.add(requestedByIds[i]);
                        accountIdChunk2.add(accountIds[i]);
                    }
                    if(orderIdChunk2.size()>0){
                        sendOrderAcknowledgement(orderIdChunk2, requestedByIdChunk2, accountIdChunk2, UserInfo.getUserId());
                    }

                }else if(orderIds.size()>20 && orderIds.size()<=30){
                    //chunk 1
                    List<Id> orderIdChunk1 = new List<Id>();
                    List<Id> requestedByIdChunk1  = new List<Id>();
                    List<Id> accountIdChunk1  = new List<Id>();
                    for(Integer i=0;i<10;i++){
                        orderIdChunk1.add(orderIds[i]);
                        requestedByIdChunk1.add(requestedByIds[i]);
                        accountIdChunk1.add(accountIds[i]);
                    }
                    if(orderIdChunk1.size()>0){
                        sendOrderAcknowledgement(orderIdChunk1, requestedByIdChunk1, accountIdChunk1, UserInfo.getUserId());
                    }
                    // chunk 2
                    List<Id> orderIdChunk2 = new List<Id>();
                    List<Id> requestedByIdChunk2  = new List<Id>();
                    List<Id> accountIdChunk2  = new List<Id>();
                    
                    for(Integer i=10;i<20;i++){
                        orderIdChunk2.add(orderIds[i]);
                        requestedByIdChunk2.add(requestedByIds[i]);
                        accountIdChunk2.add(accountIds[i]);
                    }
                    if(orderIdChunk2.size()>0){
                        sendOrderAcknowledgement(orderIdChunk2, requestedByIdChunk2, accountIdChunk2, UserInfo.getUserId());
                    }
                    //chunk 3
                    List<Id> orderIdChunk3 = new List<Id>();
                    List<Id> requestedByIdChunk3  = new List<Id>();
                    List<Id> accountIdChunk3  = new List<Id>();
                    
                    for(Integer i=20;i<orderIds.size();i++){
                        orderIdChunk3.add(orderIds[i]);
                        requestedByIdChunk3.add(requestedByIds[i]);
                        accountIdChunk3.add(accountIds[i]);
                    }
                    if(orderIdChunk3.size()>0){
                        sendOrderAcknowledgement(orderIdChunk3, requestedByIdChunk3, accountIdChunk3, UserInfo.getUserId());
                    }

                }
            }
        } catch (Exception e) {
            TCP_ExceptionLogClass.insertExceptionRecord('Bulk order exception',e.getMessage(),'TCP_BulkOrderController','saveBulkOrderDetails','Exception');
            throw new AuraHandledException(e.getMessage());
        }
        return orderList;
    }

    public static List<TCP_OrderLineItem__c> saveOrderLineItems(List<TCP_OrderLineItemWrapper> orderLineWrapList, String orderId){
        List<TCP_OrderLineItem__c> OrdLineItemList = new List<TCP_OrderLineItem__c>();
        try{ 
            if(orderLineWrapList != null){  
                Integer salesItemNo = 10;
                for(TCP_OrderLineItemWrapper wrap: orderLineWrapList){
                    TCP_OrderLineItem__c objData = new TCP_OrderLineItem__c();
                    objData.Sales_Order_Line_Item_No__c = String.valueOf(salesItemNo).leftPad(6, '0');
                    if(String.isNotBlank(wrap.shellContractNo)){
                        objData.Contract_No__c = wrap.shellContractNo;
                    }
                    if(String.isNotBlank(wrap.deliveryCollDate)){
                        objData.Delivery_Collection_Date__c = Date.valueOf(wrap.deliveryCollDate);
                    }
                    if(String.isNotBlank(wrap.materialName)){
                        objData.Material_Name__c = wrap.materialName;
                    }
                    if(String.isNotBlank(wrap.materialNumber)){
                        objData.MaterialNumber__c = wrap.materialNumber;
                    }
                    
                    if(String.isNotBlank(orderId)){
                        objData.Order__c = orderId;   
                    }
                    if(String.isNotBlank(wrap.productId)){
                        objData.Product__c = wrap.productId;
                    }
                    if(String.isNotBlank(wrap.quantity)){
                        objData.Quantity__c = decimal.valueOf(wrap.quantity);
                    }
                    if(String.isNotBlank(wrap.unit)){
                        objData.Unit__c = wrap.unit;
                    }
                    if(String.isNotBlank(wrap.instructions)){
                        objData.Other_Instruction__c = wrap.instructions;
                    }
                    salesItemNo += 10;
                    OrdLineItemList.add(objData);
                }
            }

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return OrdLineItemList;
    }

    @future
    public static void sendOrderAcknowledgement(List<Id> recordId, List<Id> recipientId, List<Id> accountId, Id recipientUserId){
        try{
            for(Integer i=0; i<recordId.size();i++){
                sendBulkEmail(recordId[i],recipientId[i],accountId[i],recipientUserId,'TCP_Order_acknowledgement_EN_US',true);
            }
        }
        catch(Exception excptn) {
            throw excptn;
        }
    }

    public static void sendBulkEmail(Id recordId, Id recipientId, id accountId, id recipientUserId, String templateName,Boolean useOrgAddress) {
        try {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            
            if(String.isNotEmpty(templateName))
            {
                
                EmailTemplate emailtemplate = [SELECT DeveloperName, Id, TemplateType FROM EmailTemplate WHERE DeveloperName =:templateName];
                mail.setTemplateId(emailtemplate.id);
            }
            if(useOrgAddress)
            {
                
                OrgWideEmailAddress OrgWideEmail = [Select id From OrgWideEmailAddress o where o.DisplayName= :Label.TCP_From_Email_Address];
          	  mail.setOrgWideEmailAddressId(OrgWideEmail.Id);
            }
            if(accountId!=null)
            {
               
                Account accSalesorg = [Select id,sales_area__r.Sales_Region__c from account where id=:accountId and recordtype.id=:tcpAccountRecTypeid and Active__c=true];
          	    String AccountSalesRegion=accSalesorg.sales_area__r.Sales_Region__c;
                System.debug('after accsales::'+AccountSalesRegion);
                if(AccountSalesRegion!=null){
                     System.debug('inside accsales::');
                    TCP_DistributionEmailList__c ccListBasedOnRegion = TCP_DistributionEmailList__c.getValues(AccountSalesRegion);
                    System.debug('inside accsales  adsds::'+ccListBasedOnRegion);
                        if(ccListBasedOnRegion!=null){
                           List<string> ccEmailList=ccListBasedOnRegion.TCP_Commops_Delivery_Lists__c.split(';'); 
                           mail.setCcAddresses(ccEmailList);
                        }
                }
            }
            if(recipientId!=null)
            {
                mail.settargetObjectId(Id.valueof(recipientId));
                mail.setSaveAsActivity(false);
            }
            else
            {
                mail.settargetObjectId(Id.valueof(recipientUserId));
                mail.setSaveAsActivity(false);
            }
            mail.setWhatId(Id.valueof(recordId));
            List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
		 mails.add(mail);
            if(!mails.isempty()){
                if(!Test.isRunningTest()){
                	Messaging.sendEmail(mails);
                }
            }
        }
        catch(Exception excptn) {
            TCP_ExceptionLogClass.insertExceptionRecord('TCP EmailService',excptn.getMessage(),'TCP_EmailService','sendEmail','Exception');
            throw excptn;
        }
    }
}