force-app/main/default/objects/Account/fields/Mode_of_Transport__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Transport__c</fullName>
    <description>Mode of Transport</description>
    <label>Mode of Transport</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Rail</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Road Tank Truck</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Bulk tanker</label>
            </value>
            <value>
                <fullName>36</fullName>
                <label>Road IM Portable Tnk</label>
            </value>
            <value>
                <fullName>1J</fullName>
                <label>Bulk Cont. road/sea</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Rail Tank Car</label>
            </value>
            <value>
                <fullName>37</fullName>
                <label>Road (Bulk)  / Rail</label>
            </value>
            <value>
                <fullName>39</fullName>
                <label>Road(Bulk)/Short Sea</label>
            </value>
            <value>
                <fullName>80</fullName>
                <label>Inland water-transpt</label>
            </value>
            <value>
                <fullName>3A</fullName>
                <label>Road(Pack)/Short Sea</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>Air-transport</label>
            </value>
            <value>
                <fullName>70</fullName>
                <label>Pipeline-transport</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Delivery_Terms__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Terms__c</fullName>
    <label>Delivery Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FCA</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>CFR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Mode_of_Transport__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Transport__c</fullName>
    <label>Mode of Transport</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bulk tanker</fullName>
            </value>
            <value>
                <fullName>Rail Tank Car</fullName>
            </value>
            <value>
                <fullName>Road Tank Truck</fullName>
            </value>
            <value>
                <fullName>Road IM Portable Tnk</fullName>
            </value>
            <value>
                <fullName>Road (Bulk)  / Rail</fullName>
            </value>
            <value>
                <fullName>Road(Bulk)/Short Sea</fullName>
            </value>
            <value>
                <fullName>Inland water-transpt</fullName>
            </value>
            <value>
                <fullName>Bulk Cont. road/sea</fullName>
            </value>
            <value>
                <fullName>No transport</fullName>
            </value>
            <value>
                <fullName>Pack Cont. road/sea</fullName>
            </value>
            <value>
                <fullName>Rail Hopper Car</fullName>
            </value>
            <value>
                <fullName>Road Hopper Truck</fullName>
            </value>
            <value>
                <fullName>Road Package Truck</fullName>
            </value>
            <value>
                <fullName>Road Package Trk.LTL</fullName>
            </value>
            <value>
                <fullName>Road (Bulk) / Barge</fullName>
            </value>
            <value>
                <fullName>Road(Pack)/Short Sea</fullName>
            </value>
            <value>
                <fullName>Air-transport</fullName>
            </value>
            <value>
                <fullName>Pipeline-transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Other_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Order_Other_Instructions__c</fullName>
    <label>Order Other Instructions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Ship To)</relationshipLabel>
    <relationshipName>Ship_To_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Sold To)</relationshipLabel>
    <relationshipName>Sold_To_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/TCP_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>TCP_Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Approved (M)</fullName>
            </value>
            <value>
                <fullName>Approved (C)</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TCP_Change_Cancel_Request__c/TCP_Change_Cancel_Request__c.object-meta.xml
<CustomObject>
    <description>This object will store the change cancel requests.</description>
    <label>Change/Cancel Request</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Change/Cancel Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change/Cancel Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TCP_Change_Cancel_Request__c/fields/Customer_PO__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO__c</fullName>
    <label>Customer PO</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_Change_Cancel_Request__c/fields/Customer_PO_New__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_New__c</fullName>
    <label>Customer PO New</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_Change_Cancel_Request__c/fields/Delivery_Terms__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Terms__c</fullName>
    <label>Delivery Terms</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_Change_Cancel_Request__c/fields/Delivery_Terms_New__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Terms_New__c</fullName>
    <label>Delivery Terms New</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_Change_Cancel_Request__c/fields/Mode_of_Transport__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Transport__c</fullName>
    <label>Mode of Transport</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_Change_Cancel_Request__c/fields/Mode_of_Transport_New__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Transport_New__c</fullName>
    <label>Mode of Transport New</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TCP_Change_Cancel_Request__c/fields/Other_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Other_Instruction__c</fullName>
    <label>Other Instruction</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TCP_Change_Cancel_Request__c/fields/Other_Instruction_New__c.field-meta.xml
<CustomField>
    <fullName>Other_Instruction_New__c</fullName>
    <label>Other Instruction New</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TCP_Change_Cancel_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TCP_Change_Cancel_Request__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Modification</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TCP_Change_Cancel_Request__c/fields/Web_Order__c.field-meta.xml
<CustomField>
    <fullName>Web_Order__c</fullName>
    <label>Web Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Change/Cancel Requests</relationshipLabel>
    <relationshipName>Change_Cancel_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TCP_ChangeCancelOrderEmailControllerTest.cls
/*****************************************************************************
* Purpose: Test class for TCP_ChangeCancelOrderEmailController
* Verion : 1.0
* ***************************************************************************/
@isTest
public class TCP_ChangeCancelOrderEmailControllerTest {
    @TestSetup
    static void createTestData() {
        List<Account> testAccounts=TCP_TestDataUtilities.createAccounts(1,false);
        TCP_TestDataUtilities.createContacts(1,testAccounts[0]);
        List<Order> testOrder=TCP_TestDataUtilities.createOrders(1,testAccounts[0]);
        TCP_TestDataUtilities.createOrderLineItems(1,testOrder[0]);
        List<TCP_Change_Cancel_Request__c> ordIteams=TCP_TestDataUtilities.createChangeOrders(1,testOrder[0]);
        TCP_TestDataUtilities.createChangeOrdersIteams(1,ordIteams[0]);
    }
   /* @isTest 
    static void getOrderNumberOnModify() {
        Order ord=[select id,Name, AccountId, OrderNumber, Sold_To__c, Ship_To__c, EffectiveDate, poNumber, Order_Other_Instructions__c, Mode_of_Transport__c, Delivery_Terms__c, TCP_Order_Status__c, status from Order limit 1];
        TCP_Change_Cancel_Request__c chOrdIteams=[Select Id, Customer_Name__c, Customer_PO__c, Customer_PO_New__c, Delivery_Terms__c, Delivery_Terms_New__c, Mode_of_Transport__c, Mode_of_Transport_New__c, Other_Instruction__c, Other_Instruction_New__c, Status__c, Type__c, Web_Order__c from TCP_Change_Cancel_Request__c where Web_Order__c=:ord.Id];   
        List<TCP_Change_Cancel_Request__c> chOrdList=new list<TCP_Change_Cancel_Request__c>();
        chOrdList.add(chOrdIteams);
        test.startTest();
        TCP_ChangeCancelOrderEmailController classObj=new TCP_ChangeCancelOrderEmailController(); 
        classObj.RecordId=chOrdIteams.Id;
        //classObj.getChangeProdWrapList();
        test.stopTest();
        system.assert(true);
    }*/
}