force-app/main/default/objects/Account/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Customer trades</description>
    <inlineHelpText>What does this customer trade?</inlineHelpText>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AA - Gasoil 0.5 SGP Cargo</fullName>
            </value>
            <value>
                <fullName>AA - High Sulpher FO 180 SGP Cargo</fullName>
            </value>
            <value>
                <fullName>AA - High Sulpher FO 380 SGP Cargo</fullName>
            </value>
            <value>
                <fullName>AA - Jet Kero SGP Cargo</fullName>
            </value>
            <value>
                <fullName>Butane</fullName>
            </value>
            <value>
                <fullName>CR - Dubai</fullName>
            </value>
            <value>
                <fullName>EU - Fuel 1.0 CIF Genoa Cargo</fullName>
            </value>
            <value>
                <fullName>EU - Fuel 1.0 CIF NWE Cargo</fullName>
            </value>
            <value>
                <fullName>EU - Fuel 1.0 FOB NWE Cargo</fullName>
            </value>
            <value>
                <fullName>EU - Fuel 1.0 FOB Rotterdam Barge</fullName>
            </value>
            <value>
                <fullName>EU- Fuel 3.5 CIF Genoa</fullName>
            </value>
            <value>
                <fullName>EU - Fuel 3.5 FOB MED Cargo</fullName>
            </value>
            <value>
                <fullName>EU - Fuel 3.5 FOB Rotterdam Barge</fullName>
            </value>
            <value>
                <fullName>EU - Gasoil 0.2 CIF MED Cargo</fullName>
            </value>
            <value>
                <fullName>EU - Gasoil 0.2 CIF NWE Cargo</fullName>
            </value>
            <value>
                <fullName>EU - Gasoil 0.2 FOB MED Cargo</fullName>
            </value>
            <value>
                <fullName>EU - Gasoil 0.2 FOB NWE Cargo</fullName>
            </value>
            <value>
                <fullName>EU - Gasoil 0.2 FOB Rotterdam Barge</fullName>
            </value>
            <value>
                <fullName>EU - Gasoil EN590 CIF NWE Cargo</fullName>
            </value>
            <value>
                <fullName>EU - Jet Kero CIF NWE Cargo</fullName>
            </value>
            <value>
                <fullName>EU - Jet Kero FOB MED Cargo</fullName>
            </value>
            <value>
                <fullName>EU - Naphta CIF NWE Physical</fullName>
            </value>
            <value>
                <fullName>EU - ULSD 10ppm Fob Rotterdam Barges</fullName>
            </value>
            <value>
                <fullName>IPE - Brent</fullName>
            </value>
            <value>
                <fullName>IPE - Gasoil</fullName>
            </value>
            <value>
                <fullName>LPG</fullName>
            </value>
            <value>
                <fullName>Propane</fullName>
            </value>
            <value>
                <fullName>ARGUS EURO BOB OXY vs PLATTS NPH CC NWE</fullName>
            </value>
            <value>
                <fullName>380 CST SINGAPORE FUEL OIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ship_to_Number__c.field-meta.xml
<CustomField>
    <fullName>Ship_to_Number__c</fullName>
    <label>Ship To Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sold_To_Number__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Number__c</fullName>
    <label>Sold To Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Revolution.recordType-meta.xml
<RecordType>
    <fullName>Revolution</fullName>
    <active>true</active>
    <label>Revolution</label>
</RecordType>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Object to store all OU, Region and Location information for Trading and Supply - ATP/AMV/SCHT</description>
    <label>Location</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <description>Plant Number of Depot Code of the particular Plant/Depot</description>
    <label>Plant Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MRC__c/MRC__c.object-meta.xml
<CustomObject>
    <label>MRC</label>
    <nameField>
        <label>MRC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MRC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MRC__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract No XLS</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MRC__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>MRC</relationshipLabel>
    <relationshipName>MRC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRC__c/fields/Plant_Code_XLS__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code_XLS__c</fullName>
    <label>Plant Code XLS</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MRC__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material Number</label>
    <referenceTo>Product_Catalogue__c</referenceTo>
    <relationshipLabel>MRC</relationshipLabel>
    <relationshipName>MRC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRC__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship-To Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected customer is not a valid customer. Please select a valid customer type.</errorMessage>
        <filterItems>
            <field>Account.Customer_Type__c</field>
            <operation>equals</operation>
            <value>Ship To</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MRC</relationshipLabel>
    <relationshipName>MRC1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRC__c/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold-To Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected customer is not a valid customer. Please select a valid customer type.</errorMessage>
        <filterItems>
            <field>Account.Customer_Type__c</field>
            <operation>equals</operation>
            <value>Sold To</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MRC</relationshipLabel>
    <relationshipName>MRC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MRC__c/fields/Sold_To_Number__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Number__c</fullName>
    <label>Sold-To-Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MRC__c/fields/Sold_To_Number_XLS__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Number_XLS__c</fullName>
    <label>Sold To Number XLS</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MRC__c/recordTypes/MRC.recordType-meta.xml
<RecordType>
    <fullName>MRC</fullName>
    <active>true</active>
    <label>MRC</label>
</RecordType>

force-app/main/default/objects/Product_Catalogue__c/Product_Catalogue__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <label>Material Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Catalogue__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipName>Product_Catalogues_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RV_Exception__c/RV_Exception__c.object-meta.xml
<CustomObject>
    <description>This object is used in revolution app to create exception records</description>
    <label>RV_Exception</label>
    <nameField>
        <displayFormat>Exception{0}</displayFormat>
        <label>RV_Exception Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RV_Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RV_Exception__c/fields/getFields__c.field-meta.xml
<CustomField>
    <fullName>getFields__c</fullName>
    <label>getFields</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RV_Exception__c/fields/getMessage__c.field-meta.xml
<CustomField>
    <fullName>getMessage__c</fullName>
    <label>getMessage</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/RV_MRCDataUploadInsertQueuable.cls
public class RV_MRCDataUploadInsertQueuable implements Queueable{
    public List<MRC__c> mrcList;
    public RV_MRCDataUploadInsertQueuable(List<MRC__c> mrcLists){
        this.mrcList = mrcLists;
    }
    public void execute(QueueableContext queCont){
        System.debug('----mrcList-----'+mrcList);
        List<MRC__c> updatedMRCLst = updateLookupOnInsert(mrcList);
        System.debug('----updatedMRCLst-----'+updatedMRCLst);
        insertMRCList(updatedMRCLst);
        
    }
    public static void insertMRCList(List<MRC__c> updateMRCList){
       
         //system.debug('-------before Insert '+insertList.size());
            try{
            Database.SaveResult[] srList = Database.insert(updateMRCList, false);
            System.debug('------srList----'+srList.size());
            List<RV_Exception__c> rvExceptionList = new List<RV_Exception__c>();
            for (Database.SaveResult sr : srList) {
                if (!sr.isSuccess()) {
                    for(Database.Error err : sr.getErrors()) {
                        RV_Exception__c rvException = new RV_Exception__c();
                        rvException.getFields__c = err.getFields().get(0);
                        rvException.getMessage__c = err.getMessage();
                        rvExceptionList.add(rvException);
                    }
                }
            }
            }catch(Exception e){
                system.debug('--------------'+e);
            }
     }
    public static List<MRC__c> updateLookupOnInsert(List<MRC__c> mrcList){
        //system.debug('---------------------inside updateLookupOnInsert---------------'+mrcList);
        Set<String> shipToSet = new Set<String>();//566937MRC Upload - Fix 
        Set<String> soldToSet = new Set<String>();
        Set<String> locSet = new Set<String>();
        Set<String> plantSet = new Set<String>();
        
        Map<String,String> accSoldToIDMap = new Map<String,String>();
        Map<String,String> accShipToIDMap = new Map<String,String>();
        Map<String,String> locIDMap = new Map<String,String>();
        Map<String,String> materialIDMap = new Map<String,String>();
        if(!mrcList.isEmpty()){
            for(MRC__c mrc : mrcList){
                //System.debug('------------'+mrc);
                if(mrc <> null){
                    if(mrc.Ship_to_Number__c != null){//566937MRC Upload - Fix 
                    	shipToSet.add(mrc.Ship_to_Number__c);
                	} 
                    if(mrc.Sold_To_Number_XLS__c != null){
                        soldToSet.add(mrc.Sold_To_Number_XLS__c);
                    }
                    if(mrc.Plant_Code_XLS__c != null){
                        locSet.add(mrc.Plant_Code_XLS__c);
                    }
                    if(mrc.Material_No_XLS__c != null){
                        plantSet.add(mrc.Material_No_XLS__c);
                    }
                }
            }
        }
        String accrecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Revolution').getRecordTypeId();
        String accShipTorecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Revolution Ship-To Account').getRecordTypeId();
    
        for(Account acc : [Select Id, Sold_To_Number__c from Account where Sold_To_Number__c in : soldToSet AND RecordTypeId =:accrecTypeId]){
            accSoldToIDMap.put(acc.Sold_To_Number__c,acc.id);
        }
        
        for(Account acc : [Select Id, Ship_to_Number__c from Account where Ship_to_Number__c in : shipToSet AND RecordTypeId =:accShipTorecTypeId]){
            accShipToIDMap.put(acc.Ship_to_Number__c,acc.id);//566937MRC Upload - Fix 
        }
        
        for(Location__c loc : [Select Id, Plant_Code__c from Location__c where Plant_Code__c in : locSet]){
            locIDMap.put(loc.Plant_Code__c,loc.id);
        }
        
        for(Product_Catalogue__c prd : [Select Id,Name from Product_Catalogue__c 
                                        where Name in : plantSet]){
            materialIDMap.put(prd.Name,prd.id);
        }
        List<MRC__c> updateMRCList = new List<MRC__c>();
        if(!mrcList.isEmpty()){
            for(MRC__c mrc : mrcList){
                if(mrc <> null){
                if(mrc.Plant_Code_XLS__c != null  && mrc.Sold_To_Number_XLS__c != null 
                   && mrc.Material_No_XLS__c != null ){
                       
                       mrc.name = mrc.Contract__c+'-'+mrc.Item_No_XLS__c;
                       mrc.Sold_To__c = accSoldToIDMap.get(mrc.Sold_To_Number_XLS__c);
                       mrc.Ship_To__c = accShipToIDMap.get(mrc.Ship_to_Number__c);//566937MRC Upload - Fix 
                       mrc.Plant__c = locIDMap.get(mrc.Plant_Code_XLS__c);
                       mrc.Product__c = materialIDMap.get(mrc.Material_No_XLS__c);
                   }
                }
                updateMRCList.add(mrc);
            }
        }
        
         return updateMRCList;
    }
}