force-app/main/default/objects/Account/fields/Rv_Available_for_OLF__c.field-meta.xml
<CustomField>
    <fullName>Rv_Available_for_OLF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available for OLF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rv_Olf_Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Rv_Olf_Customer_Email__c</fullName>
    <label>Online Integration EmailID</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rv_Olf_EmailID__c.field-meta.xml
<CustomField>
    <fullName>Rv_Olf_EmailID__c</fullName>
    <description>Enter Email IDs as semicolon separated. e.g. abc@test.com;efz@test.com;</description>
    <inlineHelpText>Enter Email IDs as semicolon separated. e.g. abc@test.com;efz@test.com;</inlineHelpText>
    <label>EmailID</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ATP__c/ATP__c.object-meta.xml
<CustomObject>
    <description>Available to Promise(ATP) quantities will be used by the OBAMs to ensure that they not overselling and creating shortfall of products that could potentially be expensive for Shell to fulfill.</description>
    <label>ATP</label>
    <nameField>
        <displayFormat>ATP-{0000}</displayFormat>
        <label>ATP Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ATP__c/fields/Grade_Level2__c.field-meta.xml
<CustomField>
    <fullName>Grade_Level2__c</fullName>
    <label>Product Sub Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AGO B7</fullName>
            </value>
            <value>
                <fullName>IGO Austria</fullName>
            </value>
            <value>
                <fullName>IGO 50ppm</fullName>
            </value>
            <value>
                <fullName>ULG95 E5</fullName>
            </value>
            <value>
                <fullName>AGO-B7</fullName>
                <isActive>false</isActive>
                <label>AGO-B7</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Name</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>ATP</relationshipLabel>
    <relationshipName>ATP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <formula>Location__r.Plant_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plant Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Object to store all OU, Region and Location information for Trading and Supply - ATP/AMV/SCHT</description>
    <label>Location</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <description>Plant Number of Depot Code of the particular Plant/Depot</description>
    <label>Plant Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/OLF_SendEmailTest.cls
@isTest
public Class OLF_SendEmailTest{
    static testMethod void test1(){
    
        Account accInsert = new Account();
        accInsert = RV_TestHelper.insertAccount(accInsert);
        accInsert.Rv_Olf_Customer_Email__c = 'test@abc.com';
        accInsert.Rv_Available_for_OLF__c = true;
        accInsert.Rv_Olf_EmailID__c = 'test1@abc.com;test2@abc.com;';
        insert accInsert;
        Location__c loc=new Location__c();
        loc=RV_TestHelper.insertLocation(loc);
        insert loc;
        ATP__c atp1=new ATP__c();
        atp1=RV_TestHelper.insertATPRecord(atp1,loc);
        insert atp1;
        Set<string> plantCode=new Set<String>();
        plantCode.add('D031');
        Set<String> plantCode1=new Set<String>();
        plantCode1.add(atp1.plant_Code__C);
        atp1.Grade_Level2__c='ULG95 E5';
        update atp1;
        
        List<OLFWrapper.MrcPriceWrap> wrapList=new List<OLFWrapper.MrcPriceWrap>();        
        OLFWrapper.MrcPriceWrap testWrap=new OLFWrapper.MrcPriceWrap();
        testWrap.MRCNumber='TP AGO 10ppmS B7 UdUm Low Dose dealer DE';
        testWrap.Location=loc.Name;
        testWrap.MaterialName ='ULG95 E5';
        testWrap.availableVolume='10';
        testWrap.PricePerUnit='2';
        testWrap.StartDate =String.ValueOf(System.Today());
        testWrap.EndDate =String.ValueOf(System.Today()+1);
        testWrap.customerName=accInsert.Name;
        testWrap.contactEmail='test@abc.com';
        wrapList.add(testWrap);
        OLF_SendEmail.sendEmailtoCustomer(wrapList);
    }          

}