force-app/main/default/objects/Account/fields/Rv_Credit_Available__c.field-meta.xml
<CustomField>
    <fullName>Rv_Credit_Available__c</fullName>
    <label>Current Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rv_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Rv_Credit_Limit__c</fullName>
    <inlineHelpText>Credit Limit Last Updated</inlineHelpText>
    <label>Credit Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rv_Credit_Utilized__c.field-meta.xml
<CustomField>
    <fullName>Rv_Credit_Utilized__c</fullName>
    <label>Credit Utilized</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Revolution.recordType-meta.xml
<RecordType>
    <fullName>Revolution</fullName>
    <active>true</active>
    <label>Revolution</label>
</RecordType>

force-app/main/default/objects/ATP__c/ATP__c.object-meta.xml
<CustomObject>
    <description>Available to Promise(ATP) quantities will be used by the OBAMs to ensure that they not overselling and creating shortfall of products that could potentially be expensive for Shell to fulfill.</description>
    <label>ATP</label>
    <nameField>
        <displayFormat>ATP-{0000}</displayFormat>
        <label>ATP Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ATP__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Name</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>ATP</relationshipLabel>
    <relationshipName>ATP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <formula>Location__r.Plant_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plant Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATP__c/fields/Volume_Cap_Customer__c.field-meta.xml
<CustomField>
    <fullName>Volume_Cap_Customer__c</fullName>
    <label>Volume Cap/Customer (Tranche1) TON</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Management__c/Customer_Sales_Management__c.object-meta.xml
<CustomObject>
    <label>Customer Sales Management</label>
    <nameField>
        <displayFormat>CSM-{0000000}</displayFormat>
        <label>CSM Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Sales Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Sales_Management__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Customer Sales Management</relationshipLabel>
    <relationshipName>Customer_Sales_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Management__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <formula>Plant__r.Plant_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plant Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Sales_Management__c/fields/Tranche__c.field-meta.xml
<CustomField>
    <fullName>Tranche__c</fullName>
    <label>Lifting Window (Tranche)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ATP1</fullName>
                <label>Tranche1</label>
            </value>
            <value>
                <fullName>ATP2</fullName>
                <label>Tranche2</label>
            </value>
            <value>
                <fullName>ATP3</fullName>
                <label>Tranche3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Object to store all OU, Region and Location information for Trading and Supply - ATP/AMV/SCHT</description>
    <label>Location</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Plant_Code__c.field-meta.xml
<CustomField>
    <fullName>Plant_Code__c</fullName>
    <description>Plant Number of Depot Code of the particular Plant/Depot</description>
    <label>Plant Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MRC__c/MRC__c.object-meta.xml
<CustomObject>
    <label>MRC</label>
    <nameField>
        <label>MRC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MRC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MRC__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>MRC</relationshipLabel>
    <relationshipName>MRC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Catalogue__c/Product_Catalogue__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <label>Material Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Catalogue__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipName>Product_Catalogues_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Catalogue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Name_Mapping__mdt/Product_Name_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Product Name Mapping</label>
    <pluralLabel>Product Name Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Product_Name_Mapping__mdt/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AGO B7</fullName>
                <default>true</default>
                <label>AGO B7</label>
            </value>
            <value>
                <fullName>IGO 50ppm</fullName>
            </value>
            <value>
                <fullName>ULG95 E5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Revolution_Setting__c/Revolution_Setting__c.object-meta.xml
<CustomObject>
    <label>Revolution Setting</label>
    <nameField>
        <label>Revolution Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revolution Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SHT__c/SHT__c.object-meta.xml
<CustomObject>
    <label>SHT</label>
    <nameField>
        <displayFormat>SHT - {0}</displayFormat>
        <label>SHT Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SHT</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SHT__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>SHTS</relationshipLabel>
    <relationshipName>SHTS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/MRC__c.field-meta.xml
<CustomField>
    <fullName>MRC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MRC</label>
    <referenceTo>MRC__c</referenceTo>
    <relationshipLabel>SHT</relationshipLabel>
    <relationshipName>SHT</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Product_Catalogue__c.field-meta.xml
<CustomField>
    <fullName>Product_Catalogue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Catalogue</label>
    <referenceTo>Product_Catalogue__c</referenceTo>
    <relationshipLabel>SHTS</relationshipLabel>
    <relationshipName>SHTS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Auto-Completed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Tranche__c.field-meta.xml
<CustomField>
    <fullName>Tranche__c</fullName>
    <label>Tranche</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ATP1</fullName>
            </value>
            <value>
                <fullName>ATP2</fullName>
            </value>
            <value>
                <fullName>ATP3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OLF_UtilityTest.cls
@isTest

public Class OLF_UtilityTest{

    @TestSetup
    static void testData(){
        //Create Revolution Setting
        List<Revolution_Setting__c> revSettList = new List<Revolution_Setting__c>();
        Revolution_Setting__c setting1 = RV_TestDataFactory.createRevolutionSetting('OLF Connection Active', 'TRUE', false, null, null);
        Revolution_Setting__c setting2 = RV_TestDataFactory.createRevolutionSetting('Lifting Window 1', 'ATP1', true, 0, 14);
        Revolution_Setting__c setting3 = RV_TestDataFactory.createRevolutionSetting('Lifting Window 2', 'ATP2', true, 15, 28);
        Revolution_Setting__c setting4 = RV_TestDataFactory.createRevolutionSetting('Lifting Window 3', 'ATP3', true, 29, 48);
        Revolution_Setting__c setting5 = RV_TestDataFactory.createRevolutionSetting('Lifting Window 4', 'ATP4', true, 49, 61);
        revSettList.add(setting1);
        revSettList.add(setting2);
        revSettList.add(setting3);
        revSettList.add(setting4);
        revSettList.add(setting5);
        insert revSettList;
    }

    static testMethod void test1(){

        Profile p = [SELECT Id FROM Profile WHERE Name='Integration Profile']; //Fix_513491_lakshmi
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='Europe/Moscow', UserName='revuser@testorg1.com');
        
        Map<String, String> headerMap= new Map<String, String>();
        headerMap.put('CustomerEmail','abc@test.com');
        Test.startTest();
        Account soldToAcc = RV_TestDataFactory.createSoldToCustomer('Test Sold-To Account', '11111111', true, true, true);
        insert soldToAcc;
        Account accInsert = RV_TestDataFactory.createShipToCustomer(soldToAcc, 'Test Ship-To Account', true, true, 'abc@test.com', true, '22222222');
        insert accInsert;
        Location__c loc=new Location__c();
        loc=RV_TestHelper.insertLocation(loc);
        insert loc;
        Customer_Sales_Management__c csm = RV_TestDataFactory.createCSM(soldToAcc, loc, 'IGO 50ppm', 0);
        insert csm;
        ATP__c atp=new ATP__c();
        atp=RV_TestHelper.insertATPRecord(atp,loc);
        atp.Volume_Cap_Customer__c = 100000;	//TestCovearge_340363_Soumyajit_21Oct2019
        insert atp;
        Set<string> plantCode=new Set<String>();
        plantCode.add('D004');
        Map<String,Decimal> atpMap = new Map<String,Decimal>();

        //TestCovearge_340363_Soumyajit_21Oct2019 starts
        Product_Catalogue__c productCat = new Product_Catalogue__c();
        productCat=RV_TestHelper.insertProductCat(productCat);
        insert productCat;
        MRC__c insertmrc = new MRC__c();
        insertmrc=RV_TestDataFactory.createMRC(soldToAcc, accInsert, loc, productCat, 'DE01');
        insert insertmrc;
        SHT__c insertSHTRec = new SHT__c();
        insertSHTRec=RV_TestHelper.insertSHT(insertSHTRec,loc,accInsert,insertmrc);
        insertSHTRec.Status__c = 'Completed';
        insertSHTRec.Tranche__c = 'ATP1';
        insert insertSHTRec;
        List<Product_Name_Mapping__mdt> pdtNameMapLst=[Select Id,Product_Name__c,MasterLabel from Product_Name_Mapping__mdt];
        Map<String,String> gradeMap= new Map<String,String>();
            for(Product_Name_Mapping__mdt pnm :pdtNameMapLst){gradeMap.put(pnm.MasterLabel,pnm.Product_Name__c);}
        Map<String,String> plantIdCodeMap=new Map<String,String>();
            plantIdCodeMap.put(insertmrc.Plant__c,insertmrc.Plant_Code__c);
        list<SHT__c> shtLst = new list<SHT__c>();
        shtLst.add(insertSHTRec);
        Test.stopTest();
        //TestCovearge_340363_Soumyajit_21Oct2019 ends
        
        OLF_Utility.global_overrideChecks = true;
        
        System.runAs(u) {
            OLF_Utility.auditOlfApiLogin(headerMap,'createDeal',system.now());
            OLF_Utility.connectionAllowed();//292153_OLFConnectionTime_11Jul2019_Soumyajit
            OLF_Utility.queryForCustomerDetail(headerMap.get('CustomerEmail'), 'ATP1');	//Rahul Sharma | Date - 13-Nov-2020 : Fix. Added tranche parameter.
            
            //TestCovearge_340363_Soumyajit_21Oct2019 starts
            atpMap = OLF_FetchMrcFinalPrice.getAtpforPlant(plantCode,accInsert.Id, new List<String>{'ATP1'});
            OLF_Utility.makeEntryInCustomerSalesManagement(shtLst,accInsert.id,gradeMap,plantIdCodeMap);
            OLF_Utility.checkOLFConnectionStatus('ATP1');	//Rahul Sharma | Date - 13-Nov-2020 : Fix. Added tranche parameter.
            //TestCovearge_340363_Soumyajit_21Oct2019 ends
        }
    }

    static testMethod void updateCreditForCustomer_Test(){
        Account soldToAcc = RV_TestDataFactory.createSoldToCustomer('Test Sold-To Account', '11111111', true, true, true);
        insert soldToAcc;
        Account shipToAcc = RV_TestDataFactory.createShipToCustomer(soldToAcc, 'Test Ship-To Account', true, true, 'abc@test.com', true, '22222222');
        insert shipToAcc;
        Account thisAcc = [SELECT Id, 
                                  Name, 
                                  Parent.Rv_Credit_Limit__c,
                                  Parent.Rv_Credit_Available__c,
                                  Parent.Rv_Credit_Utilized__c FROM Account WHERE Id =: shipToAcc.Id];
        OLF_Utility.updateCreditForCustomer(thisAcc, 10);
    }
    
    /*Method Name	:	getContractDateWindow_test
    * Date			:	18-Feb-2021
    * Developer		:	Rahul Sharma
    * Description	:	Test method for getContractDateWindow() method*/
    @isTest
    static void getContractDateWindow_test(){
        OLFWrapper.ContractDateWindowWrap dateWrap = OLF_Utility.getContractDateWindow(0, 14);
        System.assertEquals(Date.today(), dateWrap.contractStartDate);
        System.assertEquals(Date.today().addDays(14), dateWrap.contractEndDate);
    }
    
    /*Method Name	:	getOnilineTranche_test
    * Date			:	18-Feb-2021
    * Developer		:	Rahul Sharma
    * Description	:	Test method for getOnilineTranche() method*/
    @isTest
    static void getOnilineTranche_test(){
        Map<String, String> atpWindowList = OLF_Utility.getOnilineTranche(new List<Date>{Date.today()});
    }
    
    /*Method Name	:	queryForCustomerDetail_test
    * Date			:	18-Feb-2021
    * Developer		:	Rahul Sharma
    * Description	:	Test method for queryForCustomerDetail() method*/
    @isTest
    static void fsf(){
        Account soldToAcc = RV_TestDataFactory.createSoldToCustomer('Test Sold-To Account', '11111111', true, true, true);
        insert soldToAcc;
        Account accInsert = RV_TestDataFactory.createShipToCustomer(soldToAcc, 'Test Ship-To Account', true, true, 'abc@test.com', true, '22222222');
        insert accInsert;
		List<Account> accList = OLF_Utility.queryForCustomerDetail('abc@test.com');   
    }
}