force-app/main/default/objects/RE_Location__c/RE_Location__c.object-meta.xml
<CustomObject>
    <label>RE Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Location__c/fields/RE_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Region_Name__c</fullName>
    <label>Region Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Midday_Pricing__c/RE_Midday_Pricing__c.object-meta.xml
<CustomObject>
    <label>RE Midday Pricing</label>
    <nameField>
        <displayFormat>MDP-{000000000}</displayFormat>
        <label>RE Midday Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Midday Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Midday_Pricing__c/fields/RE_Depot_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Depot_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Depot Name</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipLabel>RE Midday Pricing</relationshipLabel>
    <relationshipName>RE_Midday_Pricing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Midday_Pricing__c/fields/RE_Product__c.field-meta.xml
<CustomField>
    <fullName>RE_Product__c</fullName>
    <label>Product</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Midday_Pricing__c/fields/RE_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipLabel>RE Midday Pricing</relationshipLabel>
    <relationshipName>RE_Midday_Pricing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Midday_Pricing__c/fields/RE_Shell_Price__c.field-meta.xml
<CustomField>
    <fullName>RE_Shell_Price__c</fullName>
    <label>Shell Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MOA__c/RE_MOA__c.object-meta.xml
<CustomObject>
    <label>MOA</label>
    <nameField>
        <displayFormat>MOA-{000000000}</displayFormat>
        <label>MOA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MOA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_MOA__c/fields/RE_Depot_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Depot_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Depot Name</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipLabel>MOA</relationshipLabel>
    <relationshipName>MOA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_MOA__c/fields/RE_IsLatest__c.field-meta.xml
<CustomField>
    <fullName>RE_IsLatest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsLatest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RE_MOA__c/fields/RE_Mid_Day_price_out__c.field-meta.xml
<CustomField>
    <fullName>RE_Mid_Day_price_out__c</fullName>
    <label>Mid Day price out</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MOA__c/fields/RE_Product__c.field-meta.xml
<CustomField>
    <fullName>RE_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipLabel>MOA</relationshipLabel>
    <relationshipName>MOA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_MOA__c/fields/RE_Remark__c.field-meta.xml
<CustomField>
    <fullName>RE_Remark__c</fullName>
    <label>Remark</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RE_MOA__c/fields/RE_Today_s_BSP__c.field-meta.xml
<CustomField>
    <fullName>RE_Today_s_BSP__c</fullName>
    <label>Today&apos;s BSP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/RE_Product__c.object-meta.xml
<CustomObject>
    <label>RE Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Product__c/fields/RE_Material__c.field-meta.xml
<CustomField>
    <fullName>RE_Material__c</fullName>
    <label>Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RE_Midday_Pricing_TriggerHelper.cls
public class RE_Midday_Pricing_TriggerHelper { 
    public static void onAfterShellPriceHelper(List<RE_Midday_Pricing__c> midDayPriceList, Map<Id,RE_Midday_Pricing__c> midDayPriceNewMap)
    {
        System.debug('inside trigger :'+midDayPriceNewMap);
		Map<String,RE_Midday_Pricing__c> midDayPricingMap = new Map<String,RE_Midday_Pricing__c>();	
        Map<String,RE_Midday_Pricing__c> U97midDayPricingMap = new Map<String,RE_Midday_Pricing__c>();	
		List<RE_MOA__c> moaOldList = new List<RE_MOA__c>();            						        
        
        for(RE_Midday_Pricing__c midDayvalue : [
			SELECT RE_Depot_Name__r.Name, RE_Product_Name__r.Name,RE_Product_Name__r.Re_material__c,RE_Shell_Price__c,CreatedDate,RE_IsLatest__c
			FROM RE_Midday_Pricing__c 
			WHERE ID IN: midDayPriceNewMap.KeySet()]){                 
            if(midDayvalue.RE_IsLatest__c == True && midDayvalue.RE_Shell_Price__c != null){
                if(midDayvalue.RE_Product_Name__r.Re_material__c == '400008265')
                    U97midDayPricingMap.put(midDayvalue.RE_Product_Name__r.Name,midDayvalue);
                else
					midDayPricingMap.put(middayValue.RE_Depot_Name__r.Name+'_'+middayValue.RE_Product_Name__r.Name,midDayvalue);
			}                            
        }
        system.debug('U97midDayPricingMap'+U97midDayPricingMap);
        if(!midDayPricingMap.values().isEmpty()){
			for(RE_MOA__c moaValue: [
				SELECT Id,RE_Depot_Name__r.Name,RE_Depot_Name__r.RE_Region_Name__c, RE_Product__r.Name, RE_Product__r.Re_material__c,RE_Today_s_BSP__c,RE_Remark__c, RE_Final_PSP__c, RE_Mid_Day_price_out__c
				FROM RE_MOA__c WHERE RE_IsLatest__c = True]){
                if(moaValue.RE_Product__r.Re_material__c == '400008265' && moaValue.RE_Depot_Name__r.RE_Region_Name__c == 'Peninsular' && U97midDayPricingMap.containskey(moaValue.RE_Product__r.Name)){
                	moaValue.RE_Final_PSP__c = 	U97midDayPricingMap.get(moaValue.RE_Product__r.Name).RE_Shell_Price__c; 
                    moaValue.RE_Mid_Day_price_out__c = U97midDayPricingMap.get(moaValue.RE_Product__r.Name).RE_Shell_Price__c;
                    moaOldList.add(moaValue);
                }
				else if(midDayPricingMap.containskey(moaValue.RE_Depot_Name__r.Name+'_'+moaValue.RE_Product__r.Name)) {
					moaValue.RE_Final_PSP__c = midDayPricingMap.get(moaValue.RE_Depot_Name__r.Name+'_'+moaValue.RE_Product__r.Name).RE_Shell_Price__c;	
                    moaValue.RE_Mid_Day_price_out__c = midDayPricingMap.get(moaValue.RE_Depot_Name__r.Name+'_'+moaValue.RE_Product__r.Name).RE_Shell_Price__c;	
                    moaOldList.add(moaValue);
				} 
			}
		}
        
        if(!moaOldList.isEmpty()){
        	try{          
                update moaOldList;
        	}
            catch(Exception ex) {
                System.debug('Error on updating record in RE_MOA__c');
            }  
        }        	        
	}
}