force-app/main/default/objects/RE_Location__c/RE_Location__c.object-meta.xml
<CustomObject>
    <label>RE Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Location__c/recordTypes/Philippines.recordType-meta.xml
<RecordType>
    <fullName>Philippines</fullName>
    <active>true</active>
    <label>Philippines</label>
</RecordType>

force-app/main/default/objects/RE_MY_CostPrice__c/RE_MY_CostPrice__c.object-meta.xml
<CustomObject>
    <label>Cost Price</label>
    <nameField>
        <displayFormat>RE-MY-C{000000}</displayFormat>
        <label>Costing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Price</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_MY_CostPrice__c/fields/RE_Data__c.field-meta.xml
<CustomField>
    <fullName>RE_Data__c</fullName>
    <label>Data</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/fields/RE_Depot_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Depot_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Depot Name</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipName>Costing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/fields/RE_PH_Is_Blend__c.field-meta.xml
<CustomField>
    <fullName>RE_PH_Is_Blend__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Blend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/fields/RE_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipName>Costing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/fields/RE_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>D-1</fullName>
            </value>
            <value>
                <fullName>D-2</fullName>
            </value>
            <value>
                <fullName>MTD</fullName>
            </value>
            <value>
                <fullName>WTD</fullName>
            </value>
            <value>
                <fullName>W-1</fullName>
            </value>
            <value>
                <fullName>W-2</fullName>
            </value>
            <value>
                <fullName>M-1</fullName>
            </value>
            <value>
                <fullName>M-2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_MY_CostPrice__c/recordTypes/Philippines.recordType-meta.xml
<RecordType>
    <fullName>Philippines</fullName>
    <active>true</active>
    <label>Philippines</label>
</RecordType>

force-app/main/default/objects/RE_MY_Output__c/RE_MY_Output__c.object-meta.xml
<CustomObject>
    <label>MY Output</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Costing Output Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MY Output</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_Depot_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Depot_Name__c</fullName>
    <label>Depot Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_PH_D1Data__c.field-meta.xml
<CustomField>
    <fullName>RE_PH_D1Data__c</fullName>
    <label>PH D1Data</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_PH_D2Data__c.field-meta.xml
<CustomField>
    <fullName>RE_PH_D2Data__c</fullName>
    <label>PH D2Data</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_PH_M1Data__c.field-meta.xml
<CustomField>
    <fullName>RE_PH_M1Data__c</fullName>
    <label>PH M1Data</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_PH_M2Data__c.field-meta.xml
<CustomField>
    <fullName>RE_PH_M2Data__c</fullName>
    <label>PH M2Data</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_PH_MTDData__c.field-meta.xml
<CustomField>
    <fullName>RE_PH_MTDData__c</fullName>
    <label>PH MTDData</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_PH_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>RE_PH_Product_Code__c</fullName>
    <label>PH Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_PH_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_PH_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipLabel>MY Output</relationshipLabel>
    <relationshipName>MY_Output</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_PH_W1Data__c.field-meta.xml
<CustomField>
    <fullName>RE_PH_W1Data__c</fullName>
    <label>PH W1Data</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_PH_W2Data__c.field-meta.xml
<CustomField>
    <fullName>RE_PH_W2Data__c</fullName>
    <label>PH W2Data</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_PH_WTDData__c.field-meta.xml
<CustomField>
    <fullName>RE_PH_WTDData__c</fullName>
    <label>PH WTDData</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Name__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Malaysia Output</fullName>
            </value>
            <value>
                <fullName>Singapore Output</fullName>
            </value>
            <value>
                <fullName>MTD Position</fullName>
            </value>
            <value>
                <fullName>SG Temp Gain</fullName>
            </value>
            <value>
                <fullName>SG Midday Output</fullName>
            </value>
            <value>
                <fullName>PH Output</fullName>
            </value>
            <value>
                <fullName>Canada Output</fullName>
            </value>
            <value>
                <fullName>MY Temp Gain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/recordTypes/Philippines.recordType-meta.xml
<RecordType>
    <fullName>Philippines</fullName>
    <active>true</active>
    <label>Philippines</label>
</RecordType>

force-app/main/default/objects/RE_Product__c/RE_Product__c.object-meta.xml
<CustomObject>
    <label>RE Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Product__c/fields/RE_Material__c.field-meta.xml
<CustomField>
    <fullName>RE_Material__c</fullName>
    <label>Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_PH_Index__c.field-meta.xml
<CustomField>
    <fullName>RE_PH_Index__c</fullName>
    <label>PH Index</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/recordTypes/Philippines.recordType-meta.xml
<RecordType>
    <fullName>Philippines</fullName>
    <active>true</active>
    <label>Philippines</label>
</RecordType>

force-app/main/default/classes/RE_PHOutputScheduler.cls
public class RE_PHOutputScheduler implements schedulable{
    public Static Map<String ,RE_MY_Output__c> outputdataList = new Map<String ,RE_MY_Output__c>();
    public Id rectypeId = Schema.SObjectType.RE_MY_Output__c.getRecordTypeInfosByName().get('Philippines').getRecordTypeId() ;
    //  Data Creation in MY_Output table
    public void execute(System.SchedulableContext sc){
        List<RE_MY_Output__c> updateolddata = new List<RE_MY_Output__c>();
        List<RE_MY_Output__c> LatestDataToday = [SELECT RE_IsLatest__c FROM RE_MY_Output__c WHERE RE_IsLatest__c = True AND RE_Type__c ='PH Output'];
        if(!LatestDataToday.isEmpty()){
            for(RE_MY_Output__c outputdata : LatestDataToday){
                outputdata.RE_IsLatest__c = False;
                updateolddata.add(outputdata);
            }
        }
        for(RE_MY_CostPrice__c costdata : [
                SELECT RE_Product_Name__r.RE_Material__c, RE_Product_Name__r.Name,RE_Product_Name__r.RE_PH_Index__c,RE_Costprice_Laid_Down_Cost__c,
                        id, RE_Type__c,RE_Data__c, RE_Effective_Date__c, RE_Costprice_Marginal_Cost__c,RE_Depot_Name__r.Name
                FROM RE_MY_CostPrice__c
                WHERE RE_IsLatest__c = True AND RecordType.Name = 'Philippines' AND RE_PH_Is_Blend__c = False AND  RE_Depot_Name__c != null AND RE_Type__c IN ('D-1','D-2','M-1','M-2','W-1','W-2','WTD','MTD')
                ORDER By RE_Product_Name__c	DESC]){
            String keyProDepo = costdata.RE_Product_Name__r.Name + '_' + costdata.RE_Depot_Name__r.Name;
            if(!outputdataList.containsKey(keyProDepo)){
                RE_MY_Output__c outputdata = new RE_MY_Output__c();
                outputdata.RE_PH_Product_Name__c = costdata.RE_Product_Name__c;
                outputdata.RE_Depot_Name__c = costdata.RE_Depot_Name__r.Name;
                outputdata.RE_PH_Product_Code__c = costdata.RE_Product_Name__r.RE_Material__c;
                outputdata.RE_Type__c ='PH Output';
                outputdata.RE_IsLatest__c = True;
                outputdata.recordtypeId = rectypeId;
                if(costdata.RE_Type__c == 'D-1'){
                    outputdata.RE_PH_D1Data__c = costdata.RE_Costprice_Laid_Down_Cost__c ;
                }
                if(costdata.RE_Type__c == 'D-2')
                {
                    outputdata.RE_PH_D2Data__c= costdata.RE_Costprice_Laid_Down_Cost__c;
                }
                if(costdata.RE_Type__c == 'M-1'){
                    outputdata.RE_PH_M1Data__c= costdata.RE_Costprice_Laid_Down_Cost__c;
                }
                if(costdata.RE_Type__c == 'M-2')
                {
                    outputdata.RE_PH_M2Data__c= costdata.RE_Costprice_Laid_Down_Cost__c;
                }
                if(costdata.RE_Type__c == 'W-1'){
                    outputdata.RE_PH_W1Data__c= costdata.RE_Costprice_Laid_Down_Cost__c;
                }
                if(costdata.RE_Type__c == 'W-2')
                {
                    outputdata.RE_PH_W2Data__c= costdata.RE_Costprice_Laid_Down_Cost__c;
                }
                if(costdata.RE_Type__c == 'MTD'){
                    outputdata.RE_PH_MTDData__c= costdata.RE_Costprice_Laid_Down_Cost__c;
                }
                if(costdata.RE_Type__c == 'WTD')
                {
                    outputdata.RE_PH_WTDData__c= costdata.RE_Costprice_Laid_Down_Cost__c;
                }
                outputdataList.put(keyProDepo,outputdata);
            }
            else
            {
                if(costdata.RE_Type__c == 'D-1'){
                    outputdataList.get(keyProDepo).RE_PH_D1Data__c = costdata.RE_Costprice_Laid_Down_Cost__c;
                }
                if(costdata.RE_Type__c == 'D-2')
                {
                    outputdataList.get(keyProDepo).RE_PH_D2Data__c = costdata.RE_Costprice_Laid_Down_Cost__c;
                }
                if(costdata.RE_Type__c == 'M-1'){
                    outputdataList.get(keyProDepo).RE_PH_M1Data__c = costdata.RE_Costprice_Laid_Down_Cost__c;
                }
                if(costdata.RE_Type__c == 'M-2')
                {
                    outputdataList.get(keyProDepo).RE_PH_M2Data__c = costdata.RE_Costprice_Laid_Down_Cost__c;
                }
                if(costdata.RE_Type__c == 'W-1'){
                    outputdataList.get(keyProDepo).RE_PH_W1Data__c = costdata.RE_Costprice_Laid_Down_Cost__c;
                }
                if(costdata.RE_Type__c == 'W-2')
                {
                    outputdataList.get(keyProDepo).RE_PH_W2Data__c = costdata.RE_Costprice_Laid_Down_Cost__c;
                }
                if(costdata.RE_Type__c == 'MTD'){
                    outputdataList.get(keyProDepo).RE_PH_MTDData__c = costdata.RE_Costprice_Laid_Down_Cost__c;
                }
                if(costdata.RE_Type__c == 'WTD')
                {
                    outputdataList.get(keyProDepo).RE_PH_WTDData__c = costdata.RE_Costprice_Laid_Down_Cost__c;
                }
            }
        }
        if(!updateolddata.isEmpty()){
            try{update updateolddata;}
            catch(Exception ex){system.debug(ex.getCause());}
        }

        if(!outputdataList.values().isEmpty()){
            try{insert outputdataList.values();}
            catch(Exception ex){system.debug(ex.getCause());}
        }



    }
}