force-app/main/default/objects/Bio_AMVs__c/Bio_AMVs__c.object-meta.xml
<CustomObject>
    <label>Bio AMV</label>
    <nameField>
        <displayFormat>BIO-{0}</displayFormat>
        <label>Bio AMV Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bio AMVs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bio_AMVs__c/fields/Future_Valid_From__c.field-meta.xml
<CustomField>
    <fullName>Future_Valid_From__c</fullName>
    <description>First day for M+2</description>
    <label>Future Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bio_AMVs__c/fields/Future_Valid_To__c.field-meta.xml
<CustomField>
    <fullName>Future_Valid_To__c</fullName>
    <description>Last day for M+14</description>
    <label>Future Valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bio_AMVs__c/fields/Override_Date__c.field-meta.xml
<CustomField>
    <fullName>Override_Date__c</fullName>
    <label>Override Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bio_AMVs__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Plant</description>
    <label>Plant</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Bio AMVs</relationshipLabel>
    <relationshipName>Bio_AMVs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bio_AMVs__c/fields/Prompt_Valid_From__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Valid_From__c</fullName>
    <description>Today</description>
    <label>Prompt Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bio_AMVs__c/fields/Prompt_valid_To__c.field-meta.xml
<CustomField>
    <fullName>Prompt_valid_To__c</fullName>
    <description>Last day of M+1</description>
    <label>Prompt valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>Object to store all OU, Region and Location information for Trading and Supply - ATP/AMV/SCHT</description>
    <label>Location</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RV_BIOAMVsTriggerHelperTest.cls
/*****************************************************************************
@Name:  RV_BIOAMVsTriggerHelperTest     
@=========================================================================
@Purpose: Test class for BIO AMV functionality
@=========================================================================
@History                                                            
@---------                                                            
@VERSION AUTHOR                            DATE                DETAIL                                 
@1.0 - Dhriti Krishna Ghosh Moulick      12/04/2018         INITIAL DEVELOPMENT

******************************************************************************/
@isTest
private class RV_BIOAMVsTriggerHelperTest {

    @testSetup static void setup() {
        // Create common test BIO AMVs
        List<Bio_AMVs__c> testAccts = new List<Bio_AMVs__c>();
        Location__c location = new Location__c();
        location = RV_TestHelper.insertLocation(location);
        
        for(Integer i=0;i<2;i++) {
            testAccts.add(new Bio_AMVs__c(Plant__c = location.Id));
        }
        insert testAccts;        
    }
    
    //Test method for Batch
    @isTest static void testMethodBIOAMVBatch() {
         List<Bio_AMVs__c> bioAMV = [SELECT Id,Plant__c,Prompt_Valid_From__c,Prompt_valid_To__c,Future_Valid_From__c,
                                     Future_Valid_To__c,Override_Date__c FROM Bio_AMVs__c ];
         RV_BIOAMVDailyBatch bioAMVBatch = new RV_BIOAMVDailyBatch();
         System.enqueueJob(new RV_BIOAMVDailyBatch());
         //database.executeBatch(bioAMVBatch);
    }
    
	//Test method for Triggers
    @isTest static void testMethodTrigger() {
        //Fix_PBI-513549_12Jun2020_Lakshmi_Starts
        Bio_AMVs__c bioAMV = [SELECT Id,Plant__c,Prompt_Valid_From__c,Prompt_valid_To__c,Override_Date__c,Future_Valid_From__c,Future_Valid_To__c FROM Bio_AMVs__c LIMIT 1];
        bioAMV.Prompt_Valid_From__c= System.Today();
        bioAMV.Override_Date__c=System.Today().addDays(-1);
        //Fix_PBI-513549_12Jun2020_Lakshmi_Starts
        update bioAMV;
        
    }
    //Fix_PBI-513549_12Jun2020_Lakshmi_Starts
    //Test method for Triggers
    @isTest static void testMethod1Trigger() {
        
        Bio_AMVs__c bioAMV = [SELECT Id,Plant__c,Prompt_Valid_From__c,Prompt_valid_To__c,Override_Date__c,Future_Valid_From__c,Future_Valid_To__c FROM Bio_AMVs__c LIMIT 1];
        bioAMV.Prompt_Valid_From__c= System.Today();
        bioAMV.Override_Date__c=System.Today().addDays(1);
        update bioAMV;
        
    }
    //Fix_PBI-513549_12Jun2020_Lakshmi_Ends
    
    //Test method for Scheduler
    @isTest static void testMethodScheduler() {
        //Fix_PBI-513549_12Jun2020_Lakshmi_Starts
        //List<Bio_AMVs__c> bioAMV = [SELECT Id,Plant__c,Prompt_Valid_From__c,Prompt_valid_To__c,Future_Valid_From__c,
          //                           Future_Valid_To__c FROM Bio_AMVs__c ];
        Bio_AMVs__c bioAMV = [SELECT Id,Plant__c,Prompt_Valid_From__c,Override_Date__c,Prompt_valid_To__c,Future_Valid_From__c,
                                    Future_Valid_To__c FROM Bio_AMVs__c limit 1];
        bioAMV.Prompt_Valid_From__c= System.Today();
        bioAMV.Override_Date__c=System.Today().addDays(1);
        update bioAMV;
        //Fix_PBI-513549_12Jun2020_Lakshmi_Ends
        Test.StartTest();

        RV_BIOAMVScheduler bioScheduler = new RV_BIOAMVScheduler();
        String sch = '0 0 23 * * ?'; 
        system.schedule('Bio AMV', sch, bioScheduler); 
        System.enqueueJob(new RV_BIOAMVDailyBatch());
        Test.stopTest();
    
    }
    
    
}