force-app/main/default/objects/Deal_Event_Manager__mdt/Deal_Event_Manager__mdt.object-meta.xml
<CustomObject>
    <label>Deal Event Manager</label>
    <pluralLabel>Deal Event Manager</pluralLabel>
</CustomObject>

force-app/main/default/objects/Deal_Event_Manager__mdt/fields/Handling_Type__c.field-meta.xml
<CustomField>
    <fullName>Handling_Type__c</fullName>
    <label>Handling Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EB</fullName>
                <default>true</default>
                <label>EB</label>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Event_Manager__mdt/fields/IsGsapDealCancelOn__c.field-meta.xml
<CustomField>
    <fullName>IsGsapDealCancelOn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsGsapDealCancelOn</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Event_Manager__mdt/fields/IsGsapDealCreateOn__c.field-meta.xml
<CustomField>
    <fullName>IsGsapDealCreateOn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsGsapDealCreateOn</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Event_Manager__mdt/fields/PO_Type__c.field-meta.xml
<CustomField>
    <fullName>PO_Type__c</fullName>
    <label>PO Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Event_Manager__mdt/fields/Pricing_Indicator__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Indicator__c</fullName>
    <label>Pricing Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>F</fullName>
                <default>true</default>
                <label>F</label>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/SAP_Staging__c.object-meta.xml
<CustomObject>
    <label>SAP Staging</label>
    <nameField>
        <displayFormat>D-{0}</displayFormat>
        <label>SAP Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAP Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAP_Staging__c/fields/CondPUnt__c.field-meta.xml
<CustomField>
    <fullName>CondPUnt__c</fullName>
    <label>CondPUnt</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/CondType__c.field-meta.xml
<CustomField>
    <fullName>CondType__c</fullName>
    <label>CondType</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/CondUnit__c.field-meta.xml
<CustomField>
    <fullName>CondUnit__c</fullName>
    <label>CondUnit</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/ContEndDate__c.field-meta.xml
<CustomField>
    <fullName>ContEndDate__c</fullName>
    <label>ContEndDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/ContStartDate__c.field-meta.xml
<CustomField>
    <fullName>ContStartDate__c</fullName>
    <label>ContStartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/CreationInd__c.field-meta.xml
<CustomField>
    <fullName>CreationInd__c</fullName>
    <label>CreationInd</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/Deal_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Deal_Created_Date__c</fullName>
    <label>Deal Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/Handling_Type__c.field-meta.xml
<CustomField>
    <fullName>Handling_Type__c</fullName>
    <label>Handling Type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/Instance_URL__c.field-meta.xml
<CustomField>
    <fullName>Instance_URL__c</fullName>
    <label>Instance URL</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/MaterialNo__c.field-meta.xml
<CustomField>
    <fullName>MaterialNo__c</fullName>
    <label>MaterialNo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/MrcItemNo__c.field-meta.xml
<CustomField>
    <fullName>MrcItemNo__c</fullName>
    <description>320938943-102095 format....</description>
    <label>MrcItemNo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/PO_Type__c.field-meta.xml
<CustomField>
    <fullName>PO_Type__c</fullName>
    <label>PO Type</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/PriceInd__c.field-meta.xml
<CustomField>
    <fullName>PriceInd__c</fullName>
    <label>PriceInd</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/Processing_Indicator__c.field-meta.xml
<CustomField>
    <fullName>Processing_Indicator__c</fullName>
    <label>Processing Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>New</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Processed</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Error</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/QuantityUom__c.field-meta.xml
<CustomField>
    <fullName>QuantityUom__c</fullName>
    <label>QuantityUom</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Reason__c</fullName>
    <label>Rejection Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z4</fullName>
            </value>
            <value>
                <fullName>Z5</fullName>
            </value>
            <value>
                <fullName>Z6</fullName>
            </value>
            <value>
                <fullName>Z9</fullName>
            </value>
            <value>
                <fullName>ZB</fullName>
            </value>
            <value>
                <fullName>ZD</fullName>
            </value>
            <value>
                <fullName>ZE</fullName>
            </value>
            <value>
                <fullName>ZF</fullName>
            </value>
            <value>
                <fullName>ZG</fullName>
            </value>
            <value>
                <fullName>ZH</fullName>
            </value>
            <value>
                <fullName>ZI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/SalesOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesOrg__c</fullName>
    <label>SalesOrg</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/SapMrcNo__c.field-meta.xml
<CustomField>
    <fullName>SapMrcNo__c</fullName>
    <label>SapMrcNo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/SapSalesContNo__c.field-meta.xml
<CustomField>
    <fullName>SapSalesContNo__c</fullName>
    <label>SapSalesContNo</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/Ship_TO_Name__c.field-meta.xml
<CustomField>
    <fullName>Ship_TO_Name__c</fullName>
    <label>Ship TO Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/SHT_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>SHT_Transaction_Id__c</fullName>
    <label>SHT Transaction Id</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Staging__c/fields/SoldToName__c.field-meta.xml
<CustomField>
    <fullName>SoldToName__c</fullName>
    <label>SoldToName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SHT__c/SHT__c.object-meta.xml
<CustomObject>
    <label>SHT</label>
    <nameField>
        <displayFormat>SHT - {0}</displayFormat>
        <label>SHT Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SHT</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SHT__c/fields/Contract_Start__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start__c</fullName>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Handling_Type__c.field-meta.xml
<CustomField>
    <fullName>Handling_Type__c</fullName>
    <formula>MRC__r.Handling_Type__c</formula>
    <label>Handling Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/IsGsapDealCancelOn__c.field-meta.xml
<CustomField>
    <fullName>IsGsapDealCancelOn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsGsapDealCancelOn</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/IsGsapDealCreateOn__c.field-meta.xml
<CustomField>
    <fullName>IsGsapDealCreateOn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsGsapDealCreateOn</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/isOlfDeal__c.field-meta.xml
<CustomField>
    <fullName>isOlfDeal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isOlfDeal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Material_No__c.field-meta.xml
<CustomField>
    <fullName>Material_No__c</fullName>
    <formula>MRC__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Material Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/MRC_Number__c.field-meta.xml
<CustomField>
    <fullName>MRC_Number__c</fullName>
    <label>MRC Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/MRCNumber__c.field-meta.xml
<CustomField>
    <fullName>MRCNumber__c</fullName>
    <formula>MRC__r.MRC_Number__c</formula>
    <label>MRCNumber</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/PO_Type__c.field-meta.xml
<CustomField>
    <fullName>PO_Type__c</fullName>
    <formula>TEXT(MRC__r.PO_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PO Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Price_Condition__c.field-meta.xml
<CustomField>
    <fullName>Price_Condition__c</fullName>
    <label>Price Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>YP23</fullName>
            </value>
            <value>
                <fullName>YP24</fullName>
            </value>
            <value>
                <fullName>YP03</fullName>
            </value>
            <value>
                <fullName>YP04</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <formula>MRC__r.Sales_Organization__c</formula>
    <label>Sales Organization</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/SAP_Contract_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Contract_Number__c</fullName>
    <label>SAP Contract Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Ship_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Name__c</fullName>
    <formula>MRC__r.Ship_To__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ship To Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Sold_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Name__c</fullName>
    <formula>MRC__r.Sold_To__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sold To Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/SP_100L__c.field-meta.xml
<CustomField>
    <fullName>SP_100L__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SP €/100L</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Auto-Completed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <description>This transaction Id is sent to GSAP via SAP Staging object which is used to allot SAP contract number.</description>
    <label>Transaction Id</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Volume_CBM__c.field-meta.xml
<CustomField>
    <fullName>Volume_CBM__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Volume CBM</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RV_CreateSHTSAP.cls
public class RV_CreateSHTSAP {
    
    public static void processStagingRecord(List<SHT__c> shtRecords,Map<ID,SHT__c> oldRecordMap){   
        Set<SHT__c> shtrecordsNew=new Set<SHT__c>();
        List<SHT__c> rejectshtrecords=new List<SHT__c>();
        List<SHT__c> updateshtrecords=new List<SHT__c>();
        List<String> updateSHTRecordLst = new List<String>(); 
        for(SHT__c shtRecord:shtRecords){
            if(oldRecordMap != null){
            SHT__c oldRecord=oldRecordMap.get(shtRecord.id);
            if((((shtRecord.Status__c == 'Completed' && oldRecord.Status__c!='Completed') || (shtRecord.Status__c == 'Auto-Completed' && oldRecord.Status__c!='Auto-Completed'))) && (shtRecord.IsGsapDealCreateOn__c!=null && shtRecord.IsGsapDealCreateOn__c ==true ))
            {
                shtrecordsNew.add(shtRecord);
            } 
            //OLFChanges_20Apr2019_Soumyajit starts
            else if((shtRecord.isOlfDeal__c) && (shtRecord.Status__c == 'Completed' && oldRecord.name==null) && (shtRecord.IsGsapDealCreateOn__c!=null && shtRecord.IsGsapDealCreateOn__c ==true ))
            {
                //System.debug('Creating Staging for OLF');
                shtrecordsNew.add(shtRecord);
            }
            else{}
            //OLFChanges_20Apr2019_Soumyajit ends
            if(shtRecord.Status__c == 'Cancelled' && oldRecord.Status__c!='Cancelled' && (shtRecord.IsGsapDealCancelOn__c!=null && shtRecord.IsGsapDealCancelOn__c == true))
            {
                rejectshtrecords.add(shtRecord);
            }
            //Added for Deal Interface update operation 13th Jan 2021_Dhriti
            /*if((shtRecord.Volume_CBM__c <> oldRecord.Volume_CBM__c || shtRecord.SP_100L__c <> oldRecord.SP_100L__c) && shtRecord.SAP_Contract_Number__c != null){
                updateSHTRecordLst.add(shtRecord.Id);
                updateshtrecords.add(shtRecord);
            }*/
            }else{
                system.debug('status::'+shtRecord.Status__c );
                if(shtRecord.Status__c == 'Completed'  && shtRecord.IsGsapDealCreateOn__c!=null && shtRecord.IsGsapDealCreateOn__c ==true )
                {
                    shtrecordsNew.add(shtRecord);
                    
                } 
            
            }
        }
        if(shtrecordsNew.size()>0){
            createStagingRecord(shtrecordsNew);
        }
        //Added for Deal Interface update operation 13th Jan 2021_Dhriti
        /*if(updateshtrecords.size()>0){
            List<String> sapStagingId = updateStagingRecord(updateshtrecords);
            if(updateSHTRecordLst.size()>0){
            	RV_UpdateSHTContractHelper.updateDealinGSAPInterface(sapStagingId);
        	}
        }*/
        
        if(rejectshtRecords.size()>0){
            rejectStagingRecord(rejectshtRecords);
        }
        
    }
    
    public static void createStagingRecord(Set<SHT__c> shtRecords){
        List<SAP_Staging__c> stagingRecords=new List<SAP_Staging__c>();
        List<String> insertedIds=new List<String>();
        for(SHT__c shtRecord:shtRecords){
            SAP_Staging__c stagingRecord=new SAP_Staging__c();
            stagingRecord.ContEndDate__c=shtRecord.Contract_End_Date__c;
            stagingRecord.ContStartDate__c=shtRecord.Contract_Start__c;
            stagingRecord.Deal_Created_Date__c=shtRecord.CreatedDate;
            stagingRecord.CreationInd__c='C';
            stagingRecord.CurrencyKey__c='EUR';
            stagingRecord.MaterialNo__c=shtRecord.Material_No__c;
            if(!String.isBlank(shtRecord.MRC_Number__c)){
                stagingRecord.MrcItemNo__c=shtRecord.MRC_Number__c.SubStringAfter('-');
            }
            stagingRecord.Ship_TO_Name__c = shtRecord.Ship_To_Name__c;//Added By Dhriti
            stagingRecord.SoldToName__c = shtRecord.Sold_To_Name__c;//Added By Dhriti
            stagingRecord.Quantity__c=shtRecord.Volume_CBM__c;
            stagingRecord.QuantityUom__c='CBM';
            stagingRecord.SalesOrg__c=shtRecord.Sales_Organization__c;
            stagingRecord.SalesPrice__c=shtRecord.SP_100L__c;
            stagingRecord.SapMrcNo__c=shtRecord.MRCNumber__c;
            stagingRecord.CondType__c=shtRecord.Price_Condition__c;
            stagingRecord.SfItemShtNo__c=shtRecord.Name;
            stagingRecord.Processing_Indicator__c='01';
            stagingRecord.CondPUnt__c='100';
            stagingRecord.CondUnit__c='L15';
            stagingRecord.PO_Type__c =shtRecord.PO_Type__c ;
            stagingRecord.SHTId__c=shtRecord.Id;
            stagingRecord.Handling_Type__c = shtRecord.Handling_Type__c; //Rahul Sharma | Date - 11-Feb-2021 | Bug-732764 : Adding handling type field in SAP Staging.
            Boolean runningInASandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
			System.debug('----runningInASandbox-----'+runningInASandbox);
            if(runningInASandbox == true){
                stagingRecord.Instance_URL__c = 'T';
            }else{
                stagingRecord.Instance_URL__c = 'P';
            }
            
            Map<String,Deal_Event_Manager__mdt> poTypeHandlingDealMdtMap = RV_SHT_CreateController.getDealEventMetdataMap();    //Rahul Sharma | Date - 11-Feb-2021 | Bug-732764 : Adding Deal Event Manager metadata records.
            String dealEventKey = stagingRecord.PO_Type__c + stagingRecord.Handling_Type__c;
            String dealEventOtherKey = stagingRecord.PO_Type__c + 'Others';
            if(!poTypeHandlingDealMdtMap.isEmpty() && poTypeHandlingDealMdtMap.containsKey(dealEventKey) && !String.isEmpty(poTypeHandlingDealMdtMap.get(dealEventKey).Pricing_Indicator__c)){
                stagingRecord.PriceInd__c = poTypeHandlingDealMdtMap.get(dealEventKey).Pricing_Indicator__c;
            }
            else if(!poTypeHandlingDealMdtMap.isEmpty() && poTypeHandlingDealMdtMap.containsKey(dealEventOtherKey) && !String.isEmpty(poTypeHandlingDealMdtMap.get(dealEventOtherKey).Pricing_Indicator__c)){
                stagingRecord.PriceInd__c = poTypeHandlingDealMdtMap.get(dealEventOtherKey).Pricing_Indicator__c;
            }
            else
                stagingRecord.PriceInd__c = '';
            stagingRecord.SHT_Transaction_Id__c = shtRecord.Transaction_Id__c;  //Rahul Sharma | Date - 02-Mar-2021 : Updating transaction id from SHT to SAP Staging.
            stagingRecords.add(stagingRecord);
        }
        if(stagingRecords.size()>0){
            List<Database.SaveResult> srList= database.insert(stagingRecords);
            for(database.SaveResult sr:srList){
                if(sr.isSuccess()){
                    insertedIds.add(sr.getId());
                }
            }
        }
        if(insertedIds.size()>0){
            clubDeals(insertedIds);
        }   
    }
    
    public static void rejectStagingRecord(List<SHT__c> shtRecords){
        List<SAP_Staging__c> stagingRecords=new List<SAP_Staging__c>();
        for(SHT__c shtRecord:shtRecords){
            SAP_Staging__c stagingRecord=new SAP_Staging__c();
            stagingRecord.ContEndDate__c=shtRecord.Contract_End_Date__c;
            stagingRecord.ContStartDate__c=shtRecord.Contract_Start__c;
            stagingRecord.Deal_Created_Date__c=shtRecord.CreatedDate;
            stagingRecord.CreationInd__c='D';
            stagingRecord.CurrencyKey__c='EUR';
            stagingRecord.MaterialNo__c=shtRecord.Material_No__c;
            stagingRecord.MrcItemNo__c=shtRecord.MRC_Number__c.SubStringAfter('-');
            stagingRecord.Quantity__c=shtRecord.Volume_CBM__c;
            stagingRecord.Ship_TO_Name__c = shtRecord.Ship_To_Name__c;//Added By Dhriti
            stagingRecord.SoldToName__c = shtRecord.Sold_To_Name__c;//Added By Dhriti
            stagingRecord.QuantityUom__c='CBM';
            stagingRecord.SalesOrg__c=shtRecord.Sales_Organization__c;
            stagingRecord.SalesPrice__c=shtRecord.SP_100L__c;
            stagingRecord.SapMrcNo__c=shtRecord.MRCNumber__c;
            stagingRecord.CondType__c=shtRecord.Price_Condition__c;
            stagingRecord.SapSalesContNo__c=shtRecord.SAP_Contract_Number__c;
            stagingRecord.SfItemShtNo__c=shtRecord.Name;
            stagingRecord.Processing_Indicator__c='01';
            //Added for Cancellation Reason
           stagingRecord.Rejection_Reason__c= shtRecord.Cancellation_Reason__c;
            stagingRecord.CondPUnt__c='100';
            stagingRecord.CondUnit__c='L15';
            stagingRecord.PO_Type__c =shtRecord.PO_Type__c ;
            stagingRecord.SHTId__c=shtRecord.Id;
            stagingRecord.Handling_Type__c = shtRecord.Handling_Type__c; //Rahul Sharma | Date - 11-Feb-2021 | Bug-732764 : Adding handling type field in SAP Staging.
            Boolean runningInASandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
			System.debug('----runningInASandbox-----'+runningInASandbox);
            if(runningInASandbox == true){
                stagingRecord.Instance_URL__c = 'T';
            }else{
                stagingRecord.Instance_URL__c = 'P';
            }
            
            Map<String,Deal_Event_Manager__mdt> poTypeHandlingDealMdtMap = RV_SHT_CreateController.getDealEventMetdataMap();    //Rahul Sharma | Date - 11-Feb-2021 | Bug-732764 : Adding Deal Event Manager metadata records.
            String dealEventKey = stagingRecord.PO_Type__c + stagingRecord.Handling_Type__c;
            String dealEventOtherKey = stagingRecord.PO_Type__c + 'Others';
            if(!poTypeHandlingDealMdtMap.isEmpty() && poTypeHandlingDealMdtMap.containsKey(dealEventKey) && !String.isEmpty(poTypeHandlingDealMdtMap.get(dealEventKey).Pricing_Indicator__c)){
                stagingRecord.PriceInd__c = poTypeHandlingDealMdtMap.get(dealEventKey).Pricing_Indicator__c;
            }
            else if(!poTypeHandlingDealMdtMap.isEmpty() && poTypeHandlingDealMdtMap.containsKey(dealEventOtherKey) && !String.isEmpty(poTypeHandlingDealMdtMap.get(dealEventOtherKey).Pricing_Indicator__c)){
                stagingRecord.PriceInd__c = poTypeHandlingDealMdtMap.get(dealEventOtherKey).Pricing_Indicator__c;
            }
            else
                stagingRecord.PriceInd__c = '';
            stagingRecord.SHT_Transaction_Id__c = shtRecord.Transaction_Id__c;  //Rahul Sharma | Date - 02-Mar-2021 : Updating transaction id from SHT to SAP Staging.
            stagingRecords.add(stagingRecord);
        }
        if(stagingRecords.size()>0){
            insert stagingRecords;
        }
    }
    
    //Added for Deal Interface update operation 13th Jan 2021_Dhriti
    /*public static List<String> updateStagingRecord(List<SHT__c> shtRecords){
        List<SAP_Staging__c> stagingRecords=new List<SAP_Staging__c>();
        for(SHT__c shtRecord:shtRecords){
            SAP_Staging__c stagingRecord=new SAP_Staging__c();
            stagingRecord.ContEndDate__c=shtRecord.Contract_End_Date__c;
            stagingRecord.ContStartDate__c=shtRecord.Contract_Start__c;
            stagingRecord.Deal_Created_Date__c=shtRecord.CreatedDate;
            stagingRecord.CreationInd__c='U';
            stagingRecord.CurrencyKey__c='EUR';
            stagingRecord.MaterialNo__c=shtRecord.Material_No__c;
            stagingRecord.MrcItemNo__c=shtRecord.MRC_Number__c.SubStringAfter('-');
            stagingRecord.Quantity__c=shtRecord.Volume_CBM__c;
            stagingRecord.Ship_TO_Name__c = shtRecord.Ship_To_Name__c;//Added By Dhriti
            stagingRecord.SoldToName__c = shtRecord.Sold_To_Name__c;//Added By Dhriti
            stagingRecord.QuantityUom__c='CBM';
            stagingRecord.SalesOrg__c=shtRecord.Sales_Organization__c;
            stagingRecord.SalesPrice__c=shtRecord.SP_100L__c;
            stagingRecord.SapMrcNo__c=shtRecord.MRCNumber__c;
            stagingRecord.CondType__c=shtRecord.Price_Condition__c;
            stagingRecord.SapSalesContNo__c=shtRecord.SAP_Contract_Number__c;
            stagingRecord.SfItemShtNo__c=shtRecord.Name;
            stagingRecord.Processing_Indicator__c='01';
            
           stagingRecord.Rejection_Reason__c= shtRecord.Cancellation_Reason__c;//Added for Cancellation Reason
            stagingRecord.CondPUnt__c='100';
            stagingRecord.CondUnit__c='L15';
            stagingRecord.PO_Type__c =shtRecord.PO_Type__c ;
            stagingRecord.SHTId__c=shtRecord.Id;
            stagingRecord.Handling_Type__c = shtRecord.Handling_Type__c; //Rahul Sharma | Date - 11-Feb-2021 | Bug-732764 : Adding handling type field in SAP Staging.
            Boolean runningInASandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
			System.debug('----runningInASandbox-----'+runningInASandbox);
            if(runningInASandbox == true){
                stagingRecord.Instance_URL__c = 'T';
            }else{
                stagingRecord.Instance_URL__c = 'P';
            }
            
            Map<String,Deal_Event_Manager__mdt> poTypeHandlingDealMdtMap = RV_SHT_CreateController.getDealEventMetdataMap();    //Rahul Sharma | Date - 11-Feb-2021 | Bug-732764 : Adding Deal Event Manager metadata records.
            String dealEventKey = stagingRecord.PO_Type__c + stagingRecord.Handling_Type__c;
            String dealEventOtherKey = stagingRecord.PO_Type__c + 'Others';
            if(!poTypeHandlingDealMdtMap.isEmpty() && poTypeHandlingDealMdtMap.containsKey(dealEventKey) && !String.isEmpty(poTypeHandlingDealMdtMap.get(dealEventKey).Pricing_Indicator__c)){
                stagingRecord.PriceInd__c = poTypeHandlingDealMdtMap.get(dealEventKey).Pricing_Indicator__c;
            }
            else if(!poTypeHandlingDealMdtMap.isEmpty() && poTypeHandlingDealMdtMap.containsKey(dealEventOtherKey) && !String.isEmpty(poTypeHandlingDealMdtMap.get(dealEventOtherKey).Pricing_Indicator__c)){
                stagingRecord.PriceInd__c = poTypeHandlingDealMdtMap.get(dealEventOtherKey).Pricing_Indicator__c;
            }
            else
                stagingRecord.PriceInd__c = '';
            stagingRecord.SHT_Transaction_Id__c = shtRecord.Transaction_Id__c;  //Rahul Sharma | Date - 02-Mar-2021 : Updating transaction id from SHT to SAP Staging.
            stagingRecords.add(stagingRecord);
        }
        if(stagingRecords.size()>0){
            insert stagingRecords;
        }
        List<String> sapStagingId = new List<String>();
        for(SAP_Staging__c sapStaging : stagingRecords){
            sapStagingId.add(sapStaging.Id);
        }
        return sapStagingId;
    }*/
    
    public static void clubDeals(List<Id> stagingRecordIds){
        Integer counter=0;
        Integer total=0;
        Set<String> uniqueIds=new Set<String>();
        List<SAP_Staging__c> allStagingRecords=new List<SAP_Staging__c>();
        //START - Rahul Sharma | Date - 02-Mar-21 : Replaced SfHeaderShtNo__c with SHT_Transaction_Id__c.
        allStagingRecords=[SELECT SapSalesContNo__c,
                                  SfItemShtNo__c,
                                  Counter__c,
                                  CreationInd__c,
                                  Processing_Indicator__c,
                                  SHT_Transaction_Id__c FROM SAP_Staging__c WHERE Id IN :stagingRecordIds];
        Map<String,Integer> totalCount=new Map<String,Integer>();
        List<SAP_Staging__c> updateRecords=new List<SAP_Staging__c>();
        for(SAP_Staging__c s:allStagingRecords){
            if(s.Counter__c==NULL && s.CreationInd__c!='D' && (s.Processing_Indicator__c!='02' || s.Processing_Indicator__c!='03') ){
                //uniqueIds.add(s.SfHeaderShtNo__c);
                uniqueIds.add(s.SHT_Transaction_Id__c);
        //END - Rahul Sharma | Date - 02-Mar-21 : Replaced SfHeaderShtNo__c with SHT_Transaction_Id__c.
            } 
        }
        for(String Uniqueid:uniqueIds){  
            counter=0;
            for(SAP_Staging__c s:allStagingRecords){  
                //if(s.SfHeaderShtNo__c==Uniqueid){
                if(s.SHT_Transaction_Id__c==Uniqueid){
                    counter++;
                }
            }
            totalCount.put(Uniqueid,counter);
        }
        for(String str:totalCount.keySet()){
            integer count=totalCount.get(str);
            for(SAP_Staging__c s:allStagingRecords){  
                //if(s.SfHeaderShtNo__c==str && s.SfHeaderShtNo__c!=NULL){
                //END - Rahul Sharma | Date - 02-Mar-21 : Replaced SfHeaderShtNo__c with SHT_Transaction_Id__c.
                if(s.SHT_Transaction_Id__c==str && s.SHT_Transaction_Id__c!=NULL){
                    s.Counter__c=totalCount.get(str);
                    s.Count__c =String.valueOf(count);
                    count--;
                    updateRecords.add(s); 
                }
            }
        }
        if(updateRecords.size()>0){
            update  updateRecords;
        }         
    }
}