force-app/main/default/objects/SHT__c/SHT__c.object-meta.xml
<CustomObject>
    <label>SHT</label>
    <nameField>
        <displayFormat>SHT - {0}</displayFormat>
        <label>SHT Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SHT</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SHT__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved Deal</fullName>
            </value>
            <value>
                <fullName>Z4</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
                <isActive>false</isActive>
                <label>Others</label>
            </value>
            <value>
                <fullName>Wrong Price</fullName>
                <isActive>false</isActive>
                <label>Wrong Price</label>
            </value>
            <value>
                <fullName>Wrong Volume</fullName>
                <isActive>false</isActive>
                <label>Wrong Volume</label>
            </value>
            <value>
                <fullName>Z5</fullName>
                <isActive>false</isActive>
                <label>Z5</label>
            </value>
            <value>
                <fullName>Z6</fullName>
                <isActive>false</isActive>
                <label>Z6</label>
            </value>
            <value>
                <fullName>Z9</fullName>
                <isActive>false</isActive>
                <label>Z9</label>
            </value>
            <value>
                <fullName>ZB</fullName>
                <isActive>false</isActive>
                <label>ZB</label>
            </value>
            <value>
                <fullName>ZD</fullName>
                <isActive>false</isActive>
                <label>ZD</label>
            </value>
            <value>
                <fullName>ZE</fullName>
                <isActive>false</isActive>
                <label>ZE</label>
            </value>
            <value>
                <fullName>ZF</fullName>
                <isActive>false</isActive>
                <label>ZF</label>
            </value>
            <value>
                <fullName>ZG</fullName>
                <isActive>false</isActive>
                <label>ZG</label>
            </value>
            <value>
                <fullName>ZH</fullName>
                <isActive>false</isActive>
                <label>ZH</label>
            </value>
            <value>
                <fullName>ZI</fullName>
                <isActive>false</isActive>
                <label>ZI</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SHT__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Auto-Completed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RV_SHTDailyUpdateQueueable.cls
global class RV_SHTDailyUpdateQueueable implements Queueable {
    /*
	Version : 0.0
	Author	: Soumyajit
	Date	: 26-Nov-2019
	Details	: SHT Daily Update batch - PBI:199964
	*/
    global void execute(QueueableContext q)
    {
        String shtQry = 'select id, Status__c, Cancellation_Reason__c '
            			+ ' from sht__c'
            			+ ' where Status__c = \'Saved\'';
        try{
            List<sht__c> shtLst = Database.query(shtQry);
            if(shtLst.size()>0)
            {
                for(sht__c s : shtLst)
                {
                    s.Status__c = 'Expired';
                	s.Cancellation_Reason__c='Saved Deal';
                }
                
                update shtLst;
            }
            
        }
        Catch (Exception e)
        {
            System.debug('Error in RV_SHTDailyUpdateQueueable' + e.getMessage());
        }
    }
}