force-app/main/default/objects/BET_BDD_Document__c/BET_BDD_Document__c.object-meta.xml
<CustomObject>
    <label>BDD Document</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDD Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BET_BDD_Document__c/fields/BET_BDD_Form__c.field-meta.xml
<CustomField>
    <fullName>BET_BDD_Form__c</fullName>
    <label>BDD Form</label>
    <referenceTo>BET_BDD_Form__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>BDD_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BET_BDD_Document__c/fields/BET_Document__c.field-meta.xml
<CustomField>
    <fullName>BET_Document__c</fullName>
    <label>Document</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Report</fullName>
            </value>
            <value>
                <fullName>Financial Statement</fullName>
            </value>
            <value>
                <fullName>Tax ID Verify</fullName>
            </value>
            <value>
                <fullName>Tax ID Wavier</fullName>
            </value>
            <value>
                <fullName>Bilingual</fullName>
            </value>
            <value>
                <fullName>Tax ID</fullName>
            </value>
            <value>
                <fullName>Credit Boost Approval</fullName>
            </value>
            <value>
                <fullName>Vessel Report</fullName>
            </value>
            <value>
                <fullName>OFAC IMO Check</fullName>
            </value>
            <value>
                <fullName>Banking Details</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BET_BDD_Document__c/fields/BET_Document_Type__c.field-meta.xml
<CustomField>
    <fullName>BET_Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BET_Document__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>W-8</fullName>
            </value>
            <value>
                <fullName>W-9</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>VAT Sign Off</fullName>
            </value>
            <value>
                <fullName>Exemption Certificates</fullName>
            </value>
            <value>
                <fullName>Vessel Report</fullName>
            </value>
            <value>
                <fullName>Other Screening Document</fullName>
            </value>
            <value>
                <fullName>3rd Party Report</fullName>
            </value>
            <value>
                <fullName>Banking Details</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BET_BDD_Document__c/fields/BET_Manual_Upload__c.field-meta.xml
<CustomField>
    <fullName>BET_Manual_Upload__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual Upload</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BET_BDD_Document__c/fields/BET_Retry__c.field-meta.xml
<CustomField>
    <fullName>BET_Retry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BET_BDD_Document__c/fields/BET_Section__c.field-meta.xml
<CustomField>
    <fullName>BET_Section__c</fullName>
    <label>Section</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GT</fullName>
                <color>#FFCC66</color>
                <label>GoldTier</label>
            </value>
            <value>
                <fullName>MDN</fullName>
                <color>#3366FF</color>
                <label>Master Data Navigator</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BET_BDD_Document__c/fields/BET_SharePoint_Fld_Name__c.field-meta.xml
<CustomField>
    <fullName>BET_SharePoint_Fld_Name__c</fullName>
    <label>SharePoint Folder Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BET_BDD_Document__c/fields/BET_Source__c.field-meta.xml
<CustomField>
    <fullName>BET_Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Orbis</fullName>
            </value>
            <value>
                <fullName>Bankers Almanac</fullName>
            </value>
            <value>
                <fullName>VIES</fullName>
            </value>
            <value>
                <fullName>IRS</fullName>
            </value>
            <value>
                <fullName>OFAC</fullName>
            </value>
            <value>
                <fullName>LexisNexis</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <default>true</default>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BET_BDD_Document__c/fields/BET_Upload_Status__c.field-meta.xml
<CustomField>
    <fullName>BET_Upload_Status__c</fullName>
    <label>Upload Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BET_BDD_Document__c/recordTypes/WONA.recordType-meta.xml
<RecordType>
    <fullName>WONA</fullName>
    <active>true</active>
    <label>WONA</label>
</RecordType>

force-app/main/default/objects/BET_BDD_Form__c/BET_BDD_Form__c.object-meta.xml
<CustomObject>
    <label>BDD Form</label>
    <nameField>
        <displayFormat>BD-{000}</displayFormat>
        <label>BDD Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDD Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BET_BDD_Form__c/fields/BDD_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>BDD_Entity_Type__c</fullName>
    <label>* BDD Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BDD_Line_of_Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Counterparty</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Vessel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BET_BDD_Form__c/fields/BDD_Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>BDD_Line_of_Business__c</fullName>
    <label>* BDD  Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WONA</fullName>
            </value>
            <value>
                <fullName>STUSCO</fullName>
            </value>
            <value>
                <fullName>SENA</fullName>
            </value>
            <value>
                <fullName>GLOBAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BET_BDD_Form__c/fields/BDD_Onboard_Type__c.field-meta.xml
<CustomField>
    <fullName>BDD_Onboard_Type__c</fullName>
    <label>* BDD Onboard Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Onboard</fullName>
            </value>
            <value>
                <fullName>Remediation Update</fullName>
            </value>
            <value>
                <fullName>Related Party Update</fullName>
            </value>
            <value>
                <fullName>Mass Upload - New Onboard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BET_BDD_Form__c/fields/BET_Status__c.field-meta.xml
<CustomField>
    <fullName>BET_Status__c</fullName>
    <label>* BET Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Ready for BDD Approver</fullName>
            </value>
            <value>
                <fullName>Review with BDD Approver</fullName>
            </value>
            <value>
                <fullName>Ready for COF</fullName>
            </value>
            <value>
                <fullName>Review with COF</fullName>
            </value>
            <value>
                <fullName>Ready to Onboard</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BET_BDD_Form__c/fields/MDN_PC_Type__c.field-meta.xml
<CustomField>
    <fullName>MDN_PC_Type__c</fullName>
    <label>* Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Main</fullName>
            </value>
            <value>
                <fullName>SDS Safety Contact Data</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BET_fileuplaodToSharepoint_Test.cls
@isTest
public class BET_fileuplaodToSharepoint_Test {
    
    public static Id test_GTMIApi() {
      
        BET_BDD_Form__c bddform = new BET_BDD_Form__c();
        bddform.BDD_Entity_Type__c = 'Bank';
        bddform.BDD_Line_of_Business__c = 'WONA';
        bddform.BDD_Onboard_Type__c = 'New Onboard';
        bddform.MDN_PC_Type__c = 'Main';
        bddform.BET_Status__c = 'Draft';
        
        insert bddform;
        Id docRecTypeId = Schema.SObjectType.BET_BDD_Document__c.getRecordTypeInfosByDeveloperName().get('WONA').getRecordTypeId();
        BET_BDD_Document__c bddDoc1 = new BET_BDD_Document__c(BET_Manual_Upload__c=true,BET_Source__c = 'Orbis',BET_Document__c = '3rd Party Report',BET_Retry__c = false,BET_Upload_Status__c = 'In Progress',BET_BDD_Form__c=bddform.Id,BET_Section__c = 'GT',BET_Document_Type__c='3rd Party Report',BET_SharePoint_Fld_Name__c='HSBC Bank USA National Association - Bank - 09172020',RecordTypeId=docRecTypeId);
        
        insert bddDoc1;
        
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true);
        
            insert contentVersion;  
        
        Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:contentVersion.Id].ContentDocumentId;
        
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = bddDoc1.id;
        cdl.ContentDocumentId = conDoc;
        cdl.shareType = 'V';
        insert cdl;
        
        return bdddoc1.Id;
      
    }
    
     static testmethod void test_UploadTest() {
         
            Id DocId;
            Profile prof = [select id from profile where name = 'System Administrator'];
            User user = new User(Alias = 'batman',
            Email='testtermsconditions1234423@kaplan.com',
            EmailEncodingKey='UTF-8',
            Firstname='Bruce',
            Lastname='Wayne',
            profileId=prof.Id,
            LocaleSidKey='en_US',
            LanguageLocaleKey='en_US',
            Username = 'Tst@kiran.com',
            TimeZoneSidKey='America/Chicago');
            system.runAs(user){
       
           DocId = test_GTMIApi();
}	
         User u=[SELECT Id from User where id=:userinfo.getUserId()];
         System.runas(u){
         Test.StartTest();
       // BET_fileuplaodToSharepoint.indicateExternalSystem(bddDoc1);
       Test.setMock(HttpCalloutMock.class, new BET_BDD_MockHttpResp_Orbis()); 
        BET_fileuplaodToSharepoint.indicateExternalSystem(DocId);
             Test.StopTest();}
         

         
     }
}