force-app/main/default/objects/RE_External_Market_Quotes__c/RE_External_Market_Quotes__c.object-meta.xml
<CustomObject>
    <label>RE External Market Quotes</label>
    <nameField>
        <displayFormat>RMQ-{0000000}</displayFormat>
        <label>RE External Market Quotes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE External Market Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_External_Market_Quotes__c/fields/RE_Default_Currency__c.field-meta.xml
<CustomField>
    <fullName>RE_Default_Currency__c</fullName>
    <label>Default Currency</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_External_Market_Quotes__c/fields/RE_Default_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Default_Per_Unit__c</fullName>
    <label>Default Per Unit</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_External_Market_Quotes__c/fields/RE_Gross_Net_Indicator__c.field-meta.xml
<CustomField>
    <fullName>RE_Gross_Net_Indicator__c</fullName>
    <label>Gross Net Indicator</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_External_Market_Quotes__c/fields/RE_No_Quote_Indicator__c.field-meta.xml
<CustomField>
    <fullName>RE_No_Quote_Indicator__c</fullName>
    <label>No Quote Indicator</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_External_Market_Quotes__c/fields/RE_Quote_Date__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Date__c</fullName>
    <label>Quote Date</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_External_Market_Quotes__c/fields/RE_Quote_No__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_No__c</fullName>
    <label>Quote No</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_External_Market_Quotes__c/fields/RE_Quote_Price__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Price__c</fullName>
    <label>Quote Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_External_Market_Quotes__c/fields/RE_Quote_Source__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Source__c</fullName>
    <label>Quote Source</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_External_Market_Quotes__c/fields/RE_Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Type__c</fullName>
    <label>Quote Type</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_External_Market_Quotes__c/fields/RE_Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>RE_Unit_of_Measure__c</fullName>
    <label>Unit of Measure</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RE_MarketQuotesController.cls
@RestResource(urlMapping='/Mops/*')
global class RE_MarketQuotesController {
	@HttpPost
    global static void createMops() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        List<jsonWrap> jsonWrapList = (List<jsonWrap>)JSON.deserialize(req.requestbody.tostring(),List<jsonWrap>.class);
        List<RE_External_Market_Quotes__c> mopsdatalist = new List<RE_External_Market_Quotes__c>();
        for(jsonWrap jsondata : jsonWrapList){
            if(jsondata.quoteNo != null && jsondata.quoteSource != null && jsondata.quoteType != null && jsondata.quoteDate != null){
                RE_External_Market_Quotes__c marketdata = new RE_External_Market_Quotes__c();
                marketdata.RE_Quote_Source__c = jsondata.quoteSource;
                marketdata.RE_Quote_Type__c = jsondata.quoteType;
                marketdata.RE_Quote_No__c = jsondata.quoteNo;
                marketdata.RE_Quote_Date__c = jsondata.quoteDate;
                marketdata.RE_Quote_Price__c = jsondata.quotePrice;
                marketdata.RE_Default_Currency__c = jsondata.defaultCurrency;
                marketdata.RE_Default_Per_Unit__c = jsondata.defaultPerUnit;
                marketdata.RE_Unit_of_Measure__c = jsondata.unitofMeasure;
                marketdata.RE_No_Quote_Indicator__c = jsondata.noQuoteIndicator;
                marketdata.RE_Gross_Net_Indicator__c = jsondata.grossNetIndicator;
                mopsdatalist.add(marketdata);
            }           	
        }
        if(!mopsdatalist.isEmpty()){
            try{ 
                Database.insert(mopsdatalist, True);
				res.statusCode = 201;    
                res.responseBody = Blob.valueOf('Success');
            }
            catch(Exception e){     
                res.statusCode = 403;
                res.responseBody = Blob.valueOf('Failure - '+e.getMessage());
                System.debug('Failed Mops load');
            }
        }
        else{
            res.statusCode = 400;
            res.responseBody = Blob.valueOf('Failure');            
        }
    } 
    
    public class jsonWrap{
        String quoteSource;
        String quoteType;
        String quoteNo;
        String quoteDate;
        Double quotePrice;
        String defaultCurrency;
        Double defaultPerUnit;
        String unitofMeasure;
        String noQuoteIndicator;
        String grossNetIndicator;
    }
}