force-app/main/default/objects/BET_BDD_AuthInfo__c/BET_BDD_AuthInfo__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>BET BDD salesforce authentication information and endpoint</description>
    <label>BET_BDD_AuthInfo</label>
</CustomObject>

force-app/main/default/objects/BET_BDD_AuthInfo__c/fields/client_Id__c.field-meta.xml
<CustomField>
    <fullName>client_Id__c</fullName>
    <description>salesforce connect app client ID</description>
    <label>client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BET_BDD_AuthInfo__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <label>client Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BET_BDD_AuthInfo__c/fields/endpointSF__c.field-meta.xml
<CustomField>
    <fullName>endpointSF__c</fullName>
    <label>endpointSF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BET_BDD_AuthInfo__c/fields/password__c.field-meta.xml
<CustomField>
    <fullName>password__c</fullName>
    <description>password and Security Token</description>
    <label>password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BET_BDD_ORBIS_Callout_test.cls
@istest
public class BET_BDD_ORBIS_Callout_test {
    public static void database(){
        BET_BDD_AuthInfo__c betBddAuthInfo=new BET_BDD_AuthInfo__c();
        betBddAuthInfo.client_Id__c = '3210B2948B571';
        betBddAuthInfo.Client_Secret__c= '3MVG9xqN3LZm';
        betBddAuthInfo.username__c='betedp.integration@shell.com';
        betBddAuthInfo.password__c='Integration@12';
        betBddAuthInfo.endpointSF__c='https://test.salesforce.com/services/oauth2/token';
        
        insert betBddAuthInfo;
    }
    static testmethod void test_OrbisApi() {
        database();
        Test.startTest();       
        BET_BDD_ORBIS_Callout.getOrbisData('shell bri b','','');
        Test.setMock(HttpCalloutMock.class, new BET_BDD_MockHttpResp_Orbis());
        BET_BDD_ORBIS_Callout.getOrbisData('shell bri b','','');
        Test.stopTest();
        
    }
}