force-app/main/default/objects/RV_MRC_Header_Staging__c/RV_MRC_Header_Staging__c.object-meta.xml
<CustomObject>
    <label>MRC Header Staging</label>
    <nameField>
        <label>Master Reference Contract number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MRC Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Action_Indicator__c.field-meta.xml
<CustomField>
    <fullName>Action_Indicator__c</fullName>
    <label>Action Indicator</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Customer_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Customer_Credit_Limit__c</fullName>
    <label>Customer (Sold-To) Credit Limit</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <label>Distribution Channel</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Sales_Document_type__c.field-meta.xml
<CustomField>
    <fullName>Sales_Document_type__c</fullName>
    <label>Sales Document type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <label>Ship-To</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Ship_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Name__c</fullName>
    <label>Ship-To Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Ship_To_PO_type__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_PO_type__c</fullName>
    <label>Ship-To PO type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Ship_To_Primary_Sales_Repr__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Primary_Sales_Repr__c</fullName>
    <label>Ship-To Primary Sales Repr.</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Ship_To_Primary_Sales_Repr_Name__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Primary_Sales_Repr_Name__c</fullName>
    <label>Ship-To Primary Sales Repr. Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Ship_To_Sales_Group__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Sales_Group__c</fullName>
    <label>Ship-To Sales Group</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Ship_To_Sales_Group_Description__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Sales_Group_Description__c</fullName>
    <label>Ship-To Sales Group Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Shipping_Condition__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Condition__c</fullName>
    <label>Shipping Condition</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Shipping_Condition_Description__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Condition_Description__c</fullName>
    <label>Shipping Condition Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <label>Sold-To</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Sold_To_Deletion_Flag_at_All_Areas__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Deletion_Flag_at_All_Areas__c</fullName>
    <label>Sold-To Deletion Flag at All Areas</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Sold_To_Deletion_Flag_at_Sales_Area__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Deletion_Flag_at_Sales_Area__c</fullName>
    <label>Sold-To Deletion Flag at Sales Area</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Sold_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Name__c</fullName>
    <label>Sold-To Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Sold_To_National_Account_Partner__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_National_Account_Partner__c</fullName>
    <label>Sold-To National Account Partner</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Sold_To_National_Account_Partner_Name__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_National_Account_Partner_Name__c</fullName>
    <label>Sold-To National Account Partner Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Sold_To_Primary_Sales_Repr__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Primary_Sales_Repr__c</fullName>
    <label>Sold-To Primary Sales Repr.</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Sold_To_Primary_Sales_Repr_Name__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Primary_Sales_Repr_Name__c</fullName>
    <label>Sold-To Primary Sales Repr. Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Sold_To_Sales_Group__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Sales_Group__c</fullName>
    <label>Sold-To Sales Group</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Sold_To_Sales_Group_Description__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Sales_Group_Description__c</fullName>
    <label>Sold-To Sales Group Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Valid_From__c.field-meta.xml
<CustomField>
    <fullName>Valid_From__c</fullName>
    <label>Valid-From</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Header_Staging__c/fields/Valid_To__c.field-meta.xml
<CustomField>
    <fullName>Valid_To__c</fullName>
    <label>Valid-To</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Item_Staging__c/RV_MRC_Item_Staging__c.object-meta.xml
<CustomObject>
    <label>MRC Item Staging</label>
    <nameField>
        <label>MRC Item Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MRC Item Stagings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RV_MRC_Item_Staging__c/fields/Condition_group_2__c.field-meta.xml
<CustomField>
    <fullName>Condition_group_2__c</fullName>
    <label>Condition group 2</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Item_Staging__c/fields/Condition_group_2_Description__c.field-meta.xml
<CustomField>
    <fullName>Condition_group_2_Description__c</fullName>
    <label>Condition group 2 Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Item_Staging__c/fields/Handling_Type__c.field-meta.xml
<CustomField>
    <fullName>Handling_Type__c</fullName>
    <label>Handling Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Item_Staging__c/fields/Incoterms_Part1__c.field-meta.xml
<CustomField>
    <fullName>Incoterms_Part1__c</fullName>
    <label>Incoterms Part1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Item_Staging__c/fields/Incoterms_Part2__c.field-meta.xml
<CustomField>
    <fullName>Incoterms_Part2__c</fullName>
    <label>Incoterms Part2</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Item_Staging__c/fields/Invoicing_date__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_date__c</fullName>
    <label>Invoicing date</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Item_Staging__c/fields/Invoicing_dates_Description__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_dates_Description__c</fullName>
    <label>Invoicing dates Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Item_Staging__c/fields/Master_Reference_Contract_number__c.field-meta.xml
<CustomField>
    <fullName>Master_Reference_Contract_number__c</fullName>
    <label>Master Reference Contract number</label>
    <referenceTo>RV_MRC_Header_Staging__c</referenceTo>
    <relationshipLabel>MRC Item Stagings</relationshipLabel>
    <relationshipName>MRC_Item_Stagings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Item_Staging__c/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <label>Material Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Item_Staging__c/fields/Mode_of_Transport__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Transport__c</fullName>
    <label>Mode of Transport</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Item_Staging__c/fields/Mode_of_Transport_Description__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Transport_Description__c</fullName>
    <label>Mode of Transport Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Item_Staging__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Item_Staging__c/fields/Payment_Terms_Description__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms_Description__c</fullName>
    <label>Payment Terms Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Item_Staging__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <label>Plant</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Item_Staging__c/fields/Plant_Name__c.field-meta.xml
<CustomField>
    <fullName>Plant_Name__c</fullName>
    <label>Plant Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Item_Staging__c/fields/Reason_for_Rejection_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Rejection_Code__c</fullName>
    <label>Reason for Rejection Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Item_Staging__c/fields/Reason_for_Rejection_Message__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Rejection_Message__c</fullName>
    <label>Reason for Rejection Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_MRC_Item_Staging__c/fields/Valuation_Type__c.field-meta.xml
<CustomField>
    <fullName>Valuation_Type__c</fullName>
    <label>Valuation Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RV_MRCInsertWebserviceClass.cls
/*****************************************************************************
@Name:  RV_MRCInsertWebserviceClass
@Purpose: To insert data from mulesoft into MRC staging objects
@History                                                            
@---------                                                            
@VERSION AUTHOR        DATE                DETAIL                                 
@1.0 - Dharmendra      12/9/2020         INITIAL DEVELOPMENT

******************************************************************************/
@RestResource(urlMapping='/createMRC/*')
global class RV_MRCInsertWebserviceClass {
    
	@HttpPost
    global static String createMRCStagings() {
        
        RestRequest req = RestContext.request;
        Blob body = req.requestBody;
        System.debug('-----body----'+body);
        //String requestString = '['+body.toString()+']';
        String requestString = body.toString();
        //String finalRequestString = '['+requestString+']';
        System.debug('-----requestString----'+requestString);
        //List<RV_MRCWrapperClass> rw = (List<RV_MRCWrapperClass>)System.JSON.deserialize(requestString,List<RV_MRCWrapperClass>.class);
        RV_MRCWrapperClass rw = (RV_MRCWrapperClass)JSON.deserialize(requestString, RV_MRCWrapperClass.class);
        System.debug('-----rw----'+rw);
        List<RV_MRC_Header_Staging__c> mrcHeaderList = new List<RV_MRC_Header_Staging__c>();
        List<RV_MRC_Item_Staging__c> mrcItemStgLst = new List<RV_MRC_Item_Staging__c>();
        
        mrcHeaderList.add(createMRCHeader(rw));
         if(rw.MRCItemList != null){
                for(RV_MRCWrapperClass.mrcItemClass mrcItem : rw.MRCItemList){
                     mrcItemStgLst.add(createMRCItem(mrcItem));
                }
         }
        /*
        for(RV_MRCWrapperClass mrcContract : rw){
            System.debug('-----mrcContract----'+mrcContract);
                mrcHeaderList.add(createMRCHeader(mrcContract));
            	System.debug('-----mrcContract----'+mrcContract);
            if(mrcContract.MRCItemList != null){
                for(RV_MRCWrapperClass.mrcItemClass mrcItem : mrcContract.MRCItemList){
                     mrcItemStgLst.add(createMRCItem(mrcItem));
                }
            }
			
        }
		*/
        String responseMsg = 'Record has been inserted.';
        if(!mrcHeaderList.isEmpty()){
            try{
                insert mrcHeaderList;
                responseMsg = 'MRC Header '+mrcHeaderList[0].name+ ' along with line items created successfully!';
                
            }catch(Exception de){
                System.debug('--------------'+de.getMessage());
                responseMsg = 'MRC Header could not be created. Error msg: '+de.getMessage();
            }
        }
        
        List<RV_MRC_Item_Staging__c> mrcItemFinalLst = new List<RV_MRC_Item_Staging__c>();
        
        //String mrcLineItemNames = '';
        System.debug('------mrcItemStgLst--------'+mrcItemStgLst);
        for(RV_MRC_Item_Staging__c mrcItem : mrcItemStgLst){
            mrcItem.Master_Reference_Contract_number__c = mrcHeaderList.get(0).Id;
            mrcItemFinalLst.add(mrcItem);
            //mrcLineItemNames = mrcLineItemNames+', ' + mrcItem.name;
        }
        
        if(!mrcItemFinalLst.isEmpty()){
            System.debug('------mrcItemFinalLst--------'+mrcItemFinalLst);
            try{
                insert mrcItemFinalLst;
                //responseMsg = responseMsg+ '\n' + ' Line Items: '+mrcLineItemNames;
            }catch(Exception de){
                System.debug('-----error---------'+de.getMessage());
                //responseMsg = responseMsg +'\n'+ ' Line Items Rejected dure to: '+de.getMessage();
            }
        }
        return responseMsg;
    }
    
    public static RV_MRC_Header_Staging__c createMRCHeader(RV_MRCWrapperClass mrcContract){
        		RV_MRC_Header_Staging__c mrcHeader 	= new RV_MRC_Header_Staging__c();
            	mrcHeader.Action_Indicator__c 		= mrcContract.actionInd;
            	mrcHeader.Name 						= mrcContract.MRCNo;
            	mrcHeader.Sales_Document_Type__c 	= mrcContract.SalesDoctype;
            	mrcHeader.Ship_To_PO_type__c 		= mrcContract.ShipToPOtype;
            	mrcHeader.Sales_Organization__c 	= mrcContract.SalesOrg;
            	mrcHeader.Distribution_Channel__c 	= mrcContract.DistributionChannel;
            	mrcHeader.Division__c 				= mrcContract.Division;
            	mrcHeader.Valid_From__c 			= mrcContract.ValidFrom;
            	mrcHeader.Valid_To__c  				= mrcContract.ValidTo;
            	mrcHeader.Sold_To__c 				= mrcContract.SoldTo;
            	mrcHeader.Sold_To_Name__c 			= mrcContract.SoldToName;
            	mrcHeader.Ship_To__c 				= mrcContract.ShipTo;
            	mrcHeader.Ship_To_Name__c 			= mrcContract.ShipToName;
            	mrcHeader.Shipping_Condition__c 	= mrcContract.ShippingCondition;
        		mrcHeader.Description__c 			= mrcContract.Description;
        		mrcHeader.Shipping_Condition_Description__c = mrcContract.ShipCondDescription;
        		mrcHeader.Sold_To_Deletion_Flag_at_All_Areas__c = mrcContract.SoldToDelFlgAllArea;
        		mrcHeader.Sold_To_Deletion_Flag_at_Sales_Area__c = mrcContract.SoldToDelFlgSaleArea;
        		mrcHeader.Sold_To_National_Account_Partner__c = mrcContract.SoldToNatiAccPart;
        		mrcHeader.Sold_To_National_Account_Partner_Name__c = mrcContract.SoldToNatiAccPartName;
        		mrcHeader.Sold_To_Primary_Sales_Repr__c = mrcContract.SoldToPrimSalesRep;
        		mrcHeader.Sold_To_Primary_Sales_Repr_Name__c = mrcContract.SoldToPrimSalesRepName;
        		mrcHeader.Sold_To_Sales_Group__c = mrcContract.SoldToSalesGrp;
        		mrcHeader.Sold_To_Sales_Group_Description__c = mrcContract.SoldToSalesGrpDescrp;
        		mrcHeader.Ship_To_Primary_Sales_Repr__c = mrcContract.ShipToPrimrySalesRepr;
        		mrcHeader.Ship_To_Primary_Sales_Repr_Name__c = mrcContract.ShipToPrimrySalesReprName;
        		mrcHeader.Ship_To_Sales_Group__c = mrcContract.ShipToSalesGrp;
        		mrcHeader.Ship_To_Sales_Group_Description__c = mrcContract.ShipToSalesGrpDesc;
        		mrcHeader.Customer_Credit_Limit__c = mrcContract.customerCreditLimit;
        return mrcHeader;
    }
    
    public static RV_MRC_Item_Staging__c createMRCItem(RV_MRCWrapperClass.mrcItemClass mrcItem){
        RV_MRC_Item_Staging__c mrcInsertItem = new RV_MRC_Item_Staging__c();
        mrcInsertItem.Name = mrcItem.MRCItemNo;
        mrcInsertItem.Plant__c = mrcItem.PlantCode;
        mrcInsertItem.Plant_Name__c = mrcItem.PlantName;
        mrcInsertItem.Material_Number__c = mrcItem.MaterialNumber;
        mrcInsertItem.Material_Description__c = mrcItem.MaterialDescription;
        mrcInsertItem.Handling_Type__c = mrcItem.HandlingType;
        mrcInsertItem.Reason_for_Rejection_Code__c = mrcItem.ReasonforRejectionCode;
        mrcInsertItem.Reason_for_Rejection_Message__c = mrcItem.ReasonforRejectionMessage;
        mrcInsertItem.Mode_of_Transport__c = mrcItem.ModeofTransport;
        mrcInsertItem.Mode_of_Transport_Description__c = mrcItem.ExterMOTDesc;
        mrcInsertItem.Incoterms_Part1__c = mrcItem.incoTermsPart1;
        mrcInsertItem.Incoterms_Part2__c = mrcItem.incoTermsPart2;
        mrcInsertItem.Payment_Terms__c = mrcItem.PaymentTerms;
        mrcInsertItem.Payment_Terms_Description__c = mrcItem.PaymentTermsDescrp;
        mrcInsertItem.Valuation_Type__c = mrcItem.ValuationType;
        mrcInsertItem.Condition_group_2__c = mrcItem.CondGroup2;
        mrcInsertItem.Condition_group_2_Description__c = mrcItem.CondGroup2Desc;
        mrcInsertItem.Invoicing_date__c = mrcItem.InvoiceDate;
        mrcInsertItem.Invoicing_dates_Description__c = mrcItem.InvoiceDateDesc;
        mrcInsertItem.Payment_Method__c = mrcItem.Paymentmethod;
        mrcInsertItem.Payment_Method_Description__c = mrcItem.PaymentmethodDesc;
        return mrcInsertItem;
    }
}