force-app/main/default/objects/Account_Contact_Relationship__c/Account_Contact_Relationship__c.object-meta.xml
<CustomObject>
    <description>This junction object connects the Account and Contact standard objects in a many-to-many relationship and houses customized user permission indicators which can be enabled per portal user and can be made unique to a given Account-Contact pair.</description>
    <label>Account Contact Relationship</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Account Contact Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contact Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Contact_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Contact Relationship</relationshipLabel>
    <relationshipName>Account_Contact_Relationship</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Contact_Relationship__c/fields/Portal_User_Contact__c.field-meta.xml
<CustomField>
    <fullName>Portal_User_Contact__c</fullName>
    <description>Related Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Related Accounts</relationshipLabel>
    <relationshipName>Account_Contact_Relationship</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Contact/fields/TCP_Products__c.field-meta.xml
<CustomField>
    <fullName>TCP_Products__c</fullName>
    <inlineHelpText>To select products for CommOps user</inlineHelpText>
    <label>TCP Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Glycol</fullName>
            </value>
            <value>
                <fullName>styrene</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TCP_MyShellContactsCtrl.cls
/**************************************************************************************************
 * Class Name : TCP_TermsandConditionCtrl 
 * Description: To display my shell contacts for end users and commops users
 * Verion     : 1.0
 * **************************************************************************************************/
public with sharing class TCP_MyShellContactsCtrl {

    @AuraEnabled(cacheable=true)
    public static List<ContactWrapper> getShellContacts(string accId){
      List<Id> accIds=new List<Id>();
     
      List<Account_Contact_Relationship__c> acrData = new List<Account_Contact_Relationship__c>();
      List<ContactWrapper> conWrap=new List<ContactWrapper>();
      try {  
          //To fetch associated contacts from customer 
          acrData = [SELECT id, Account__r.name, Account__c,Portal_User_Contact__r.Email,Portal_User_Contact__r.Phone,Portal_User_Contact__r.name,Portal_User_Contact__r.TCP_Products__c FROM Account_Contact_Relationship__c WHERE Account__c=:accId order by CreatedDate ASC];//Portal_User_Contact__r.Email =: us.Email AND 
          if(!acrData.isEmpty()){
              for(Account_Contact_Relationship__c acr:acrData){
                  ContactWrapper wrap=new ContactWrapper();
                  wrap.product=acr.Portal_User_Contact__r.TCP_Products__c;
                  wrap.Name=acr.Portal_User_Contact__r.Name;
                  wrap.Email=acr.Portal_User_Contact__r.Email;
                  wrap.Phone=acr.Portal_User_Contact__r.Phone;
                  conWrap.add(wrap);
              }
              return conWrap;
          }
          
         
      }catch(Exception e){
        system.debug('My Shell Contacts : '+e.getMessage()+'line : '+e.getLineNumber());
        TCP_ExceptionLogClass.insertExceptionRecord('My Shell Contacts',e.getMessage(),'TCP_MyShellContactsCtrl','execute','Exception');
    }
    return null;
  }
 
  public class ContactWrapper{
      @AuraEnabled
      public String Name{get;set;}
      @AuraEnabled
      public String product{get;set;}
      @AuraEnabled
      public String Email{get;set;}
      @AuraEnabled
      public String Phone{get;set;}
  
  }
}