force-app/main/default/objects/Account_Contact_Relationship__c/Account_Contact_Relationship__c.object-meta.xml
<CustomObject>
    <description>This junction object connects the Account and Contact standard objects in a many-to-many relationship and houses customized user permission indicators which can be enabled per portal user and can be made unique to a given Account-Contact pair.</description>
    <label>Account Contact Relationship</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Account Contact Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contact Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Contact_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Contact Relationship</relationshipLabel>
    <relationshipName>Account_Contact_Relationship</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Contact_Relationship__c/fields/Portal_User_Contact__c.field-meta.xml
<CustomField>
    <fullName>Portal_User_Contact__c</fullName>
    <description>Related Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Related Accounts</relationshipLabel>
    <relationshipName>Account_Contact_Relationship</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Contact/fields/TCP_TandC__c.field-meta.xml
<CustomField>
    <fullName>TCP_TandC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TCP TandC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TCP_MyShellContactsCtrlTest.cls
/*****************************************************************************
 * Purpose: Test class for TCP_MyShellContactsCtrl
 * Verion : 1.0
 * **************************************************************************/
@isTest
public class TCP_MyShellContactsCtrlTest {
	/* Data Setup */
    @TestSetup
    static void createTestData() {
         User us=TCP_TestDataUtilities.createAdminUsers();
        System.runAs(us){
        List<Account> testAccounts=TCP_TestDataUtilities.createAccounts(1,false);
        List<contact> testContact=TCP_TestDataUtilities.createContacts(1,testAccounts[0]);
        List<Account_Contact_Relationship__c> testacr=TCP_TestDataUtilities.createACRRecords(testAccounts[0], testContact[0], 1);
        } 
    }
    /* 
     * To test functionality of my shell contacts for portal user
     */
    @isTest 
    static void getShellContactsTest() {
        Account acc=[select id,name from account where name='SampleAccount0' limit 1];
        
        List<Account_Contact_Relationship__c>  acrRecList=[select id, account__c,Portal_User_Contact__c from Account_Contact_Relationship__c where account__c=:acc.id limit 1];
        List<contact> testCons=new List<contact> ([select id,TCP_TandC__c from contact limit 1]);
        List<User> listofusers=TCP_TestDataUtilities.createcustomerUsers(1, 'TCPCustomerCommunityPlusUser', testCons[0]);
        Test.startTest();
            List<Id> accIds=new List<Id>();
            accIds.add(acrRecList[0].id);
            system.assert(accIds.size()>0);
            List<TCP_MyShellContactsCtrl.ContactWrapper> wrapperList = TCP_MyShellContactsCtrl.getShellContacts(acrRecList[0].account__c);
        Test.stopTest();
    }
}