force-app/main/default/objects/SHT_Dave__c/SHT_Dave__c.object-meta.xml
<CustomObject>
    <label>Sales/Hedge Transaction</label>
    <nameField>
        <displayFormat>SHTD-{0000}</displayFormat>
        <label>SHT DAVE Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales/Hedge Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SHT_Dave__c/fields/Mass_MT__c.field-meta.xml
<CustomField>
    <fullName>Mass_MT__c</fullName>
    <label>Mass(MT)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SHT_Dave__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AGO B7</fullName>
            </value>
            <value>
                <fullName>IGO 50ppm</fullName>
            </value>
            <value>
                <fullName>GASOIL</fullName>
            </value>
            <value>
                <fullName>ULG95 E5</fullName>
            </value>
            <value>
                <fullName>ULG98</fullName>
            </value>
            <value>
                <fullName>ULG95 E10</fullName>
            </value>
            <value>
                <fullName>Gasoline</fullName>
            </value>
            <value>
                <fullName>MOGAS</fullName>
            </value>
            <value>
                <fullName>AGO B0</fullName>
            </value>
            <value>
                <fullName>AGO B0 CH</fullName>
            </value>
            <value>
                <fullName>AGO B7 CH</fullName>
            </value>
            <value>
                <fullName>AGO VPD</fullName>
            </value>
            <value>
                <fullName>GTL B0</fullName>
            </value>
            <value>
                <fullName>AVGAS</fullName>
            </value>
            <value>
                <fullName>IGO 10ppm</fullName>
            </value>
            <value>
                <fullName>ULG100 VP</fullName>
            </value>
            <value>
                <fullName>ULG95 E0</fullName>
            </value>
            <value>
                <fullName>ULG95_BOB_E5</fullName>
            </value>
            <value>
                <fullName>IGO 1000ppm</fullName>
            </value>
            <value>
                <fullName>GTL B7</fullName>
            </value>
            <value>
                <fullName>MOGAS 98</fullName>
                <isActive>false</isActive>
                <label>MOGAS 98</label>
            </value>
            <value>
                <fullName>MOGAS E10</fullName>
                <isActive>false</isActive>
                <label>MOGAS E10</label>
            </value>
            <value>
                <fullName>UGL95 E5</fullName>
                <isActive>false</isActive>
                <label>UGL95 E5</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SHT_Dave__c/fields/SHT_Dave_Master__c.field-meta.xml
<CustomField>
    <fullName>SHT_Dave_Master__c</fullName>
    <label>SHT Dave Master</label>
    <referenceTo>SHT_Dave_Master__c</referenceTo>
    <relationshipName>SHT_Dave</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SHT_Dave_Master__c/SHT_Dave_Master__c.object-meta.xml
<CustomObject>
    <label>Total Exposure</label>
    <nameField>
        <label>SHT Dave Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SHT Dave Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RV_SHTDaveTest.cls
@isTest
public class RV_SHTDaveTest {
        
    static testMethod void RV_SHTDaveTestInsert(){//Saved and expired
        
        SHT_Dave_Master__c insertSHTDaveMasterAGOInsert = new SHT_Dave_Master__c();
        insertSHTDaveMasterAGOInsert = RV_TestHelper.insertSHTDaveMasterAGO(insertSHTDaveMasterAGOInsert);
        insert insertSHTDaveMasterAGOInsert;
        
        SHT_Dave_Master__c insertSHTDaveMasterULGInsert = new SHT_Dave_Master__c();
        insertSHTDaveMasterULGInsert = RV_TestHelper.insertSHTDaveMasterULG(insertSHTDaveMasterULGInsert);
        insert insertSHTDaveMasterULGInsert;
        
        SHT_Dave_Master__c insertSHTDaveMasterMOGASInsert = new SHT_Dave_Master__c();
        insertSHTDaveMasterMOGASInsert = RV_TestHelper.insertSHTDaveMasterMOGAS(insertSHTDaveMasterMOGASInsert);
        insert insertSHTDaveMasterMOGASInsert;
        
        SHT_Dave__c insertSHTDaveAGO = new SHT_Dave__c();
        insertSHTDaveAGO = RV_TestHelper.insertSHTDave(insertSHTDaveAGO,insertSHTDaveMasterAGOInsert);
        insert insertSHTDaveAGO;
        
        SHT_Dave__c insertSHTDaveULG = new SHT_Dave__c();
        insertSHTDaveULG = RV_TestHelper.insertSHTDave(insertSHTDaveULG,insertSHTDaveMasterAGOInsert);
        insertSHTDaveULG.Product_Name__c = 'ULG95 E5';
        insertSHTDaveULG.Mass_MT__c = insertSHTDaveULG.Mass_CBM__c * 0.755;
        insert insertSHTDaveULG;
        
        SHT_Dave__c insertSHTDaveHedge = new SHT_Dave__c();
        insertSHTDaveHedge = RV_TestHelper.insertSHTDaveHedge(insertSHTDaveHedge,insertSHTDaveMasterAGOInsert);
        insert insertSHTDaveHedge;
        
        
        RV_SHTDave.getShtDaveMaster();
        RV_SHTDave.getShtDave();
        RV_SHTDave.insertManualEntry('AGO B7',1);
    }
}