force-app/main/default/objects/BET_BDD_Form__c/BET_BDD_Form__c.object-meta.xml
<CustomObject>
    <label>BDD Form</label>
    <nameField>
        <displayFormat>BD-{000}</displayFormat>
        <label>BDD Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDD Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BET_BDD_Form__c/fields/BET_Status__c.field-meta.xml
<CustomField>
    <fullName>BET_Status__c</fullName>
    <label>* BET Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Ready for BDD Approver</fullName>
            </value>
            <value>
                <fullName>Review with BDD Approver</fullName>
            </value>
            <value>
                <fullName>Ready for COF</fullName>
            </value>
            <value>
                <fullName>Review with COF</fullName>
            </value>
            <value>
                <fullName>Ready to Onboard</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BET_BDD_Form__c/fields/GT_Is_Comp_Reg__c.field-meta.xml
<CustomField>
    <fullName>GT_Is_Comp_Reg__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is the Company Registered?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BET_Registration_Details__c/BET_Registration_Details__c.object-meta.xml
<CustomObject>
    <label>BDD Registration Details</label>
    <nameField>
        <displayFormat>RD-{0000}</displayFormat>
        <label>Registration Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDD Registration Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BET_Registration_Details__c/fields/BDD_Form__c.field-meta.xml
<CustomField>
    <fullName>BDD_Form__c</fullName>
    <label>BDD Form</label>
    <referenceTo>BET_BDD_Form__c</referenceTo>
    <relationshipLabel>Registration Details</relationshipLabel>
    <relationshipName>BDD_Registration_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BET_BDD_RegDetailsTriggerHelper.cls
/*************************************************************************************
@Name:  BET_BDD_RegDetailsTriggerHelper     
@=================================================================================
@Purpose: Helper class for BET_BDD_RegDetailsTrigger trigger
@=================================================================================
@History                                                            
@---------                                                            
@VERSION AUTHOR                            DATE                DETAIL                                 
@1.0 - Naveen K N     ```````````````    28-Jan-2021         INITIAL DEVELOPMENT
*************************************************************************************/
public with sharing class BET_BDD_RegDetailsTriggerHelper {
    public static void OnBeforeInsert(List<BET_Registration_Details__c> RegDetailsList){
        BETFormRecordLock(RegDetailsList);
    }
    
    public static void OnBeforeUpdate(List<BET_Registration_Details__c> RegDetailsList){
        BETFormRecordLock(RegDetailsList);
    }
    
    public static void OnBeforeDelete(List<BET_Registration_Details__c> RegDetailsList, Map<Id,BET_Registration_Details__c> RegDetailsMap){
        BETFormRecordLock(RegDetailsList);
        markIsCompanyRegisteredTrue(RegDetailsMap);
        
    }
    
    public static void BETFormRecordLock(List<BET_Registration_Details__c> RegDetailsList){
        List<string> BETFormIds = new List<string>();
        Map<Id, String> BETIdsWithStatus = new Map<Id, String>();
        
        for(BET_Registration_Details__c RegDetail: RegDetailsList){
            BETFormIds.add(RegDetail.BDD_Form__c);
        }
        List<BET_BDD_Form__c> BETForms = [Select Id, BET_Status__c from BET_BDD_Form__c where Id IN :BETFormIds];
        for(BET_BDD_Form__c BETForm: BETForms){
            BETIdsWithStatus.put(BETForm.Id, BETForm.BET_Status__c);
        }
        
        for(BET_Registration_Details__c RegDetail: RegDetailsList){
            string BETStatus = BETIdsWithStatus.get(RegDetail.BDD_Form__c);
            if(BETStatus == 'Ready to Onboard' || BETStatus == 'Submitted'){
                RegDetail.addError('Only ‘BET Status’ is editable at this stage.');
            }
        }
    }
    
    public static void markIsCompanyRegisteredTrue(Map<Id,BET_Registration_Details__c> RegDetailsMap){
        Set<Id> formIdSet = new Set<Id>();
        List<BET_BDD_Form__c> formRecsUpdateList = new List<BET_BDD_Form__c>();
        for(BET_Registration_Details__c regDet : RegDetailsMap.values()){
            formIdSet.add(regDet.BDD_Form__c);
        }
        List<BET_BDD_Form__c> FormRecsList = new List<BET_BDD_Form__c>();
        FormRecsList = [Select Id,GT_Is_Comp_Reg__c,Name,(Select Id,Name,BDD_Form__c from BDD_Registration_Details__r) from BET_BDD_Form__c where Id IN :formIdSet];
        for(BET_BDD_Form__c formRec : FormRecsList) {
            List<BET_Registration_Details__c> regRecList = new List<BET_Registration_Details__c>();
            for( BET_Registration_Details__c regDet : formRec.BDD_Registration_Details__r ) {
                regRecList.add(regDet);
            }
            if(regRecList.size()==1 && RegDetailsMap.containsKey(regRecList.get(0).ID)){
                formRec.GT_Is_Comp_Reg__c = false;
                formRecsUpdateList.add(formRec);
            }}
        database.update(formRecsUpdateList, false);
    }
}