force-app/main/default/objects/BET_BDD_Form__c/BET_BDD_Form__c.object-meta.xml
<CustomObject>
    <label>BDD Form</label>
    <nameField>
        <displayFormat>BD-{000}</displayFormat>
        <label>BDD Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDD Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BET_BDD_Form__c/fields/Assigned_COF__c.field-meta.xml
<CustomField>
    <fullName>Assigned_COF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>* Assigned COF</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Is_COF_User__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>BDD_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BET_BDD_Form__c/fields/BDD_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>BDD_Entity_Type__c</fullName>
    <label>* BDD Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BDD_Line_of_Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Counterparty</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Vessel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BET_BDD_Form__c/fields/BDD_Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>BDD_Line_of_Business__c</fullName>
    <label>* BDD  Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WONA</fullName>
            </value>
            <value>
                <fullName>STUSCO</fullName>
            </value>
            <value>
                <fullName>SENA</fullName>
            </value>
            <value>
                <fullName>GLOBAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BET_BDD_Form__c/fields/BDD_Onboard_Type__c.field-meta.xml
<CustomField>
    <fullName>BDD_Onboard_Type__c</fullName>
    <label>* BDD Onboard Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Onboard</fullName>
            </value>
            <value>
                <fullName>Remediation Update</fullName>
            </value>
            <value>
                <fullName>Related Party Update</fullName>
            </value>
            <value>
                <fullName>Mass Upload - New Onboard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BET_BDD_Form__c/fields/Full_Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Legal_Name__c</fullName>
    <label>* Search Short Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Is_COF_User__c.field-meta.xml
<CustomField>
    <fullName>Is_COF_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is COF User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BulkUploadGTSearchBatchTest.cls
@isTest
public class BulkUploadGTSearchBatchTest {
    public static string recTypeIDWonaCpt = Schema.SobjectType.BET_BDD_Form__c.getRecordTypeInfosByName().get('MASS UPLOAD WONA NEW CPT/BANK FORM').getRecordTypeId(); 
    public static string recTypeIDWonaIndvl = Schema.SobjectType.BET_BDD_Form__c.getRecordTypeInfosByName().get('MASS UPLOAD WONA NEW INDIVIDUAL FORM').getRecordTypeId();
    
	@testSetup static void setup() {
        // Create common test accounts
        List<BET_BDD_Form__c> formList = new List<BET_BDD_Form__c>();
        Profile prof = [select id from profile where name = 'BET User' LIMIT 1];
        User user1 = new User(Alias = 'batman',
                              Email='dwawdiwjdjawiojdij@kaplan.com',
                              EmailEncodingKey='UTF-8',
                              Firstname='Bruce',
                              Lastname='Wayne',
                              profileId=prof.Id,
                              LocaleSidKey='en_US',
                              LanguageLocaleKey='en_US',
                              Is_COF_User__c=true,
                              Username = 'Tsawdwtdwidwaudiawdkkkkk@kiran.com',
                              TimeZoneSidKey='America/Chicago');
        insert user1;
        for(Integer i=0;i<20;i++) {
            BET_BDD_Form__c bddForm=new BET_BDD_Form__c(recordtypeId =recTypeIDWonaCpt,BDD_Entity_Type__c='Counterparty',Full_Legal_Name__c ='Test Name'+i,BDD_Line_of_Business__c='WONA',BDD_Onboard_Type__c='New Onboard',Assigned_COF__c =user1.Id,OwnerId=user1.Id);
        	formList.add(bddForm);
        }
        for(Integer i=0;i<20;i++) {
            BET_BDD_Form__c bddForm=new BET_BDD_Form__c(recordtypeId =recTypeIDWonaIndvl,BDD_Entity_Type__c='Counterparty',Full_Legal_Name__c ='Test Name'+i,BDD_Line_of_Business__c='WONA',BDD_Onboard_Type__c='New Onboard',Assigned_COF__c =user1.Id,OwnerId=user1.Id);
        	formList.add(bddForm);
        }
        insert formList;        
    }
    
    static testmethod void testgetNewBddFormId(){
        test.startTest();
        BulkUploadGTSearchBatch batchc = new BulkUploadGTSearchBatch();
        Database.executeBatch(batchc,50);
        test.stopTest();
        
    }
    
    static testmethod void testbatchMethod(){
        test.startTest();
        BulkUploadGTSearchBatch batchc = new BulkUploadGTSearchBatch(10);
        Database.executeBatch(batchc,50);
        test.stopTest();
        
    }
    
    static testmethod void testscheduler(){
        test.startTest();
        BulkUploadGTSearchBatchScheduler sh1 = new BulkUploadGTSearchBatchScheduler(1);
		String sch = '0 0 23 * * ?'; 
        system.schedule('Test BulkUploadGTSearchBatchScheduler Check', sch, sh1); 
        Test.stopTest();
    }
}