force-app/main/default/objects/BET_BDD_Form__c/BET_BDD_Form__c.object-meta.xml
<CustomObject>
    <label>BDD Form</label>
    <nameField>
        <displayFormat>BD-{000}</displayFormat>
        <label>BDD Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BDD Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BET_BDD_Form__c/fields/BDD_Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>BDD_Entity_Type__c</fullName>
    <label>* BDD Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BDD_Line_of_Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank</fullName>
            </value>
            <value>
                <fullName>Counterparty</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Vessel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BET_BDD_Form__c/fields/BDD_Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>BDD_Line_of_Business__c</fullName>
    <label>* BDD  Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WONA</fullName>
            </value>
            <value>
                <fullName>STUSCO</fullName>
            </value>
            <value>
                <fullName>SENA</fullName>
            </value>
            <value>
                <fullName>GLOBAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BET_BDD_Form__c/fields/BDD_Onboard_Type__c.field-meta.xml
<CustomField>
    <fullName>BDD_Onboard_Type__c</fullName>
    <label>* BDD Onboard Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Onboard</fullName>
            </value>
            <value>
                <fullName>Remediation Update</fullName>
            </value>
            <value>
                <fullName>Related Party Update</fullName>
            </value>
            <value>
                <fullName>Mass Upload - New Onboard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BET_BDD_SearchController_TestDataFactory.cls
@isTest
public class BET_BDD_SearchController_TestDataFactory {
	
    public static BET_BDD_Form__c createBDDForm(String lob,String legalEntity,String onboarding){
        BET_BDD_Form__c bddForm=new BET_BDD_Form__c(BDD_Line_of_Business__c=lob,BDD_Entity_Type__c=legalEntity,BDD_Onboard_Type__c=onboarding);
        return bddForm;
    }
	
   
    public static Object getBankersResult(){
        return BET_BDD_Search_Controller.getEdpData('SBI','WONA','Bank','India','','Primary').BankersResult[0];
    }
    
    public static Object getOrbisResult(){
        //return BET_BDD_Search_Controller.getEdpData('SBI','WONA','Bank','India','','Secondary').orbisResultPayload.Data[0];
        return BET_BDD_Search_Controller.getEdpData('SBI','WONA','Bank','India','','Secondary').OrbisResult[0];
    }
    
    public static Object getGTMIResult(){
     	BET_BDD_Search_Controller.getGTRecordSet('','123','');
        return BET_BDD_Search_Controller.getGTRecordSet('SBI Equity Hybrid Fund','','').ResultPayload[0];
    }
        
    
}