force-app/main/default/objects/RV_Exception__c/RV_Exception__c.object-meta.xml
<CustomObject>
    <description>This object is used in revolution app to create exception records</description>
    <label>RV_Exception</label>
    <nameField>
        <displayFormat>Exception{0}</displayFormat>
        <label>RV_Exception Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RV_Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RV_Exception__c/fields/gsap_Message__c.field-meta.xml
<CustomField>
    <fullName>gsap_Message__c</fullName>
    <label>gsap Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RV_Exception__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TCP_ExceptionLogClass.cls
public with sharing class TCP_ExceptionLogClass {
	public static String insertExceptionRecord(String  getStatusCode,String getMessage,String className,String methodName,String type){
        
        RV_Exception__c rvExcep = new RV_Exception__c();
        
        rvExcep.Status_Code__c = getStatusCode;
        rvExcep.gsap_Message__c = getMessage;//using this field even naming convention is different as exception length will be more than 250 chars
        rvExcep.Apex_Class__c = className;
        rvExcep.Method_Name__c = methodName;
        rvExcep.Type__c = type;
        try{
        	insert rvExcep;
        }catch(Exception e){
            System.debug('^^^^^^^^^^^^^^^^'+e);
        }
        
        if(rvExcep <> null)
       		 return 'Success';
        else{
            return 'Failure';
        }
    }
}