force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/RE_Depot_Pricing_Backbone__c.object-meta.xml
<CustomObject>
    <label>Depot Pricing Backbone</label>
    <nameField>
        <displayFormat>DPB-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depot Pricing Backbone</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Location_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Location_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location Name</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone (Location Name)</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone_CND_Loc</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_TH_Oil_Loss_Percent__c.field-meta.xml
<CustomField>
    <fullName>RE_TH_Oil_Loss_Percent__c</fullName>
    <label>Oil Loss %</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_TH_TP_Premium_HCV1__c.field-meta.xml
<CustomField>
    <fullName>RE_TH_TP_Premium_HCV1__c</fullName>
    <label>TP Premium HCV1</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_TH_TP_Premium_HCV2__c.field-meta.xml
<CustomField>
    <fullName>RE_TH_TP_Premium_HCV2__c</fullName>
    <label>TP Premium HCV2</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/TP_Premium_HCV2_Unit__c.field-meta.xml
<CustomField>
    <fullName>TP_Premium_HCV2_Unit__c</fullName>
    <label>TP Premium HCV2 Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>THB/LTR</fullName>
            </value>
            <value>
                <fullName>THB/KG</fullName>
            </value>
            <value>
                <fullName>THB/TON</fullName>
            </value>
            <value>
                <fullName>USD/BBL</fullName>
            </value>
            <value>
                <fullName>USD/TON</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/recordTypes/Thailand.recordType-meta.xml
<RecordType>
    <fullName>Thailand</fullName>
    <active>true</active>
    <description>Use for Thailand CBU calculation</description>
    <label>Thailand</label>
</RecordType>

force-app/main/default/objects/RE_Location__c/RE_Location__c.object-meta.xml
<CustomObject>
    <label>RE Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Location__c/recordTypes/Thailand.recordType-meta.xml
<RecordType>
    <fullName>Thailand</fullName>
    <active>true</active>
    <label>Thailand</label>
</RecordType>

force-app/main/default/objects/RE_Product__c/RE_Product__c.object-meta.xml
<CustomObject>
    <label>RE Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Product__c/fields/RE_Midday_MC0_Valid_From__c.field-meta.xml
<CustomField>
    <fullName>RE_Midday_MC0_Valid_From__c</fullName>
    <label>Midday MC0 Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_Midday_MC0_Valid_To__c.field-meta.xml
<CustomField>
    <fullName>RE_Midday_MC0_Valid_To__c</fullName>
    <label>Midday MC0 Valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_Midday_MC0_Value__c.field-meta.xml
<CustomField>
    <fullName>RE_Midday_MC0_Value__c</fullName>
    <label>Midday MC0 Value</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_Morning_MC0_Valid_From__c.field-meta.xml
<CustomField>
    <fullName>RE_Morning_MC0_Valid_From__c</fullName>
    <label>Morning MC0 Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_Morning_MC0_Valid_To__c.field-meta.xml
<CustomField>
    <fullName>RE_Morning_MC0_Valid_To__c</fullName>
    <label>Morning MC0 Valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_Morning_MC0_Value__c.field-meta.xml
<CustomField>
    <fullName>RE_Morning_MC0_Value__c</fullName>
    <label>Morning MC0 Value</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_TH_HCV_Quote1_Percent__c.field-meta.xml
<CustomField>
    <fullName>RE_TH_HCV_Quote1_Percent__c</fullName>
    <label>HCV Quote 1%</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_TH_HCV_Quote2_Percent__c.field-meta.xml
<CustomField>
    <fullName>RE_TH_HCV_Quote2_Percent__c</fullName>
    <label>HCV Quote 2%</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_TH_Oil_Loss_Percent__c.field-meta.xml
<CustomField>
    <fullName>RE_TH_Oil_Loss_Percent__c</fullName>
    <label>Oil Loss %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_TH_TP_Premium__c.field-meta.xml
<CustomField>
    <fullName>RE_TH_TP_Premium__c</fullName>
    <label>TP Premium</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_TH_TP_PremiumHCV2__c.field-meta.xml
<CustomField>
    <fullName>RE_TH_TP_PremiumHCV2__c</fullName>
    <label>TH TP PremiumHCV2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_TH_TP_PremiumHCV__c.field-meta.xml
<CustomField>
    <fullName>RE_TH_TP_PremiumHCV__c</fullName>
    <inlineHelpText>Value should be (HCV1:HCV2) EX: 20.46 :2.68, 0:0</inlineHelpText>
    <label>TH TP PremiumHCV1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/TH_15_to_30_factor__c.field-meta.xml
<CustomField>
    <fullName>TH_15_to_30_factor__c</fullName>
    <label>TH 15 to 30 factor</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/TH_TP_PremiumHCV2_UNIT__c.field-meta.xml
<CustomField>
    <fullName>TH_TP_PremiumHCV2_UNIT__c</fullName>
    <label>TH TP PremiumHCV2 UNIT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD/BBL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/TP_Premium_Unit__c.field-meta.xml
<CustomField>
    <fullName>TP_Premium_Unit__c</fullName>
    <label>TP Premium Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RE_Rate_Unit_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Product__c/recordTypes/Thailand.recordType-meta.xml
<RecordType>
    <fullName>Thailand</fullName>
    <active>true</active>
    <label>Thailand</label>
</RecordType>

force-app/main/default/objects/RE_SG_CostPrice__c/RE_SG_CostPrice__c.object-meta.xml
<CustomObject>
    <label>Cost Price - Singapore</label>
    <nameField>
        <displayFormat>RE-SG-C{000000}</displayFormat>
        <label>CostPriceName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Price - Singapore</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_SG_CostPrice__c/fields/RE_Location_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Location_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location Name</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipLabel>Cost Price - Singapore</relationshipLabel>
    <relationshipName>Cost_Price_Singapore</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_SG_CostPrice__c/fields/RE_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipLabel>Cost Price - Singapore</relationshipLabel>
    <relationshipName>Cost_Price_Singapore</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/RE_Rate_Unit_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MYR CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/TON</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>USD/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>USD/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>USD/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>BBL</fullName>
    </customValue>
    <customValue>
        <fullName>LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR</fullName>
    </customValue>
    <customValue>
        <fullName>THB/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>STG/LTR</fullName>
    </customValue>
    <description>Rate Units to be used in  Revolution East Applicaion</description>
    <masterLabel>RE_Rate_Unit_Set</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RE_ProductTriggerHelper.cls
public class RE_ProductTriggerHelper {
    public static void onAfterMC0Dipupdate(List<RE_Product__c> mc0List){
        RE_SOQLController sqldata = new RE_SOQLController();
        List<RE_SG_CostPrice__c> costpricelist = [
            SELECT Id,RE_Pricing_Date__c,RE_Location_Name__c,RE_Product_Name__c,RE_Location_Name__r.Name,RE_Product_Name__r.Name,RE_MC0_Diff__c,RE_IsMidday__c,RE_FX_Marginal_Cost__c
            FROM RE_SG_CostPrice__c 
            WHERE RE_Pricing_Date__c = Today            
            AND RE_IsLatest__c = True            
        	AND RE_Product_Name__r.Name = 'IGO 10ppm'
        ];
        System.debug('@@@costpricelist'+costpricelist);
        for(RE_SG_CostPrice__c costData : costpricelist){
            System.debug('@@@costData'+costData);
            for(RE_Product__c igoprod : mc0List){
                if(costData.RE_IsMidday__c == False){
                    if(igoprod.RE_Morning_MC0_Value__c != null && 
						   igoprod.RE_Morning_MC0_Valid_From__c <= System.today() && 
						   igoprod.RE_Morning_MC0_Valid_To__c >= System.today()){
							costData.RE_MC0_Diff__c = costData.RE_FX_Marginal_Cost__c - igoprod.RE_Morning_MC0_Value__c * sqldata.fetchSGFxData() * 100/Double.valueOf(System.Label.RE_BBL_to_LTR);
						}	
                    else{
                        costData.RE_MC0_Diff__c = costData.RE_FX_Marginal_Cost__c;
                    }        
                }
                else{
                    if(igoprod.RE_Midday_MC0_Value__c != null && 
						   igoprod.RE_Midday_MC0_Valid_From__c <= System.today() && 
						   igoprod.RE_Midday_MC0_Valid_To__c >= System.today()){
							costData.RE_MC0_Diff__c = costData.RE_FX_Marginal_Cost__c - igoprod.RE_Midday_MC0_Value__c * sqldata.fetchSGFxDataforMidDay() * 100/Double.valueOf(System.Label.RE_BBL_to_LTR);
						}	
                    else{
                        costData.RE_MC0_Diff__c = costData.RE_FX_Marginal_Cost__c;
                    }  
                }
            }    
        }
        try{
            if(!costpricelist.isEmpty())
            	update costpricelist;
        }
        catch(Exception ex){
            System.debug('Failed to update RE_SG_CostPrice__c');
        }
    }
    public static void updateTHDepoPricing(List<RE_Product__c> prodList){
        
        Map<Id,RE_Product__c> productMap =  new Map<Id,RE_Product__c>();
        List<RE_Depot_Pricing_Backbone__c> depoDatasets = new List<RE_Depot_Pricing_Backbone__c>();
        try{
            for(RE_Product__c prd :prodList){
                if(prd.recordtype.Name == 'Thailand'){
                    productMap.put(prd.Id,prd);
                }
            }
            for(RE_Depot_Pricing_Backbone__c depos:[SELECT Id,RE_TH_Oil_Loss_Percent__c,TH_15_to_30_factor__c,RE_Product_Name__c FROM RE_Depot_Pricing_Backbone__c WHERE Recordtype.Name='Thailand' AND RE_Product_Name__c IN: productMap.keyset()]){
                if(productMap.containsKey(depos.RE_Product_Name__c)){
                    RE_Product__c pr = productMap.get(depos.RE_Product_Name__c);
                    Double TP_HCV1 = 0.00;
                    Double TP_HCV2 = 0.00;
                    String prodVals = pr.RE_TH_TP_Premium__c!=null ? pr.RE_TH_TP_Premium__c : '0.00';
               		TP_HCV1 = (prodVals != 'EX REF PRICE' && prodVals != 'Actual Purchasing Price' && prodVals != 'Slow moving Price') ? (Double.valueOf(prodVals)) : (pr.RE_TH_TP_PremiumHCV__c != null ? pr.RE_TH_TP_PremiumHCV__c : 0.00);
					TP_HCV2	=	pr.RE_TH_TP_PremiumHCV2__c != null ? pr.RE_TH_TP_PremiumHCV2__c : 0.00;
                    depoDatasets.add(new RE_Depot_Pricing_Backbone__c(Id=depos.Id,RE_TH_Oil_Loss_Percent__c = pr.RE_TH_Oil_Loss_Percent__c,TH_15_to_30_factor__c=pr.TH_15_to_30_factor__c,RE_TH_HCV_Quote1_Percent__c=pr.RE_TH_HCV_Quote1_Percent__c,RE_TH_HCV_Quote2_Percent__c=pr.RE_TH_HCV_Quote2_Percent__c,
                                                                     RE_TH_TP_Premium_HCV1__c =TP_HCV1 , TP_Premium_HCV1_Unit__c=pr.TP_Premium_Unit__c,RE_TH_TP_Premium_HCV2__c=TP_HCV2,TP_Premium_HCV2_Unit__c=pr.TH_TP_PremiumHCV2_UNIT__c));
                }
            }
            
            Database.Update(depoDatasets);
        }
        catch(Exception ex){
            System.debug('Failed to update RE_Depot_Pricing_Backbone__c');
        }
    }
}