force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/RE_Depot_Pricing_Backbone__c.object-meta.xml
<CustomObject>
    <label>Depot Pricing Backbone</label>
    <nameField>
        <displayFormat>DPB-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depot Pricing Backbone</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Depot_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Depot_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Depot Name</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Valid_From__c.field-meta.xml
<CustomField>
    <fullName>RE_Valid_From__c</fullName>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/RE_FX_Rates__c.object-meta.xml
<CustomObject>
    <label>RE FX Rates</label>
    <nameField>
        <displayFormat>FXR-{000000}</displayFormat>
        <label>FX_Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE FX Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Base_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Base_Unit__c</fullName>
    <label>Base Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Conversion_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Conversion_Unit__c</fullName>
    <label>Conversion Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipName>FX_Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Forex_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Forex_Name__c</fullName>
    <label>Forex Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Forex_Rate__c.field-meta.xml
<CustomField>
    <fullName>RE_Forex_Rate__c</fullName>
    <label>Forex Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Pricing_Date__c.field-meta.xml
<CustomField>
    <fullName>RE_Pricing_Date__c</fullName>
    <label>Published Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Name__c</fullName>
    <description>quote display name is stored</description>
    <label>Quote Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Tracker__c.field-meta.xml
<CustomField>
    <fullName>RE_Tracker__c</fullName>
    <label>Tracker</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>D-1</fullName>
            </value>
            <value>
                <fullName>D-2</fullName>
            </value>
            <value>
                <fullName>D+1</fullName>
            </value>
            <value>
                <fullName>MTD</fullName>
            </value>
            <value>
                <fullName>WTD</fullName>
            </value>
            <value>
                <fullName>W-1</fullName>
            </value>
            <value>
                <fullName>W-2</fullName>
            </value>
            <value>
                <fullName>M-1</fullName>
            </value>
            <value>
                <fullName>M-2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_FX_Rates__c/fields/RE_Trade_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Trade_Type__c</fullName>
    <label>Trade Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
            <value>
                <fullName>Exchange Rate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/RE_Market_Quotes__c.object-meta.xml
<CustomObject>
    <label>RE Market Quotes</label>
    <nameField>
        <displayFormat>MarketQuote-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Market Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipName>Market_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Price__c.field-meta.xml
<CustomField>
    <fullName>RE_Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Quote_Name__c</fullName>
    <label>Quote Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_Tracker__c.field-meta.xml
<CustomField>
    <fullName>RE_Tracker__c</fullName>
    <label>Tracker</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>D-1</fullName>
            </value>
            <value>
                <fullName>MTD</fullName>
            </value>
            <value>
                <fullName>WTD</fullName>
            </value>
            <value>
                <fullName>W-1</fullName>
            </value>
            <value>
                <fullName>W-2</fullName>
            </value>
            <value>
                <fullName>M-1</fullName>
            </value>
            <value>
                <fullName>M-2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/RE_MY_Output__c.object-meta.xml
<CustomObject>
    <label>MY Output</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Costing Output Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MY Output</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_Depot_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Depot_Name__c</fullName>
    <label>Depot Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_Job_Run_Count__c.field-meta.xml
<CustomField>
    <fullName>RE_Job_Run_Count__c</fullName>
    <label>Job Run Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_Pricing_Date__c.field-meta.xml
<CustomField>
    <fullName>RE_Pricing_Date__c</fullName>
    <label>Pricing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Name__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_Region__c.field-meta.xml
<CustomField>
    <fullName>RE_Region__c</fullName>
    <label>Region</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RE_MY_Output__c/fields/RE_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Malaysia Output</fullName>
            </value>
            <value>
                <fullName>Singapore Output</fullName>
            </value>
            <value>
                <fullName>MTD Position</fullName>
            </value>
            <value>
                <fullName>SG Temp Gain</fullName>
            </value>
            <value>
                <fullName>SG Midday Output</fullName>
            </value>
            <value>
                <fullName>PH Output</fullName>
            </value>
            <value>
                <fullName>Canada Output</fullName>
            </value>
            <value>
                <fullName>MY Temp Gain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Product__c/RE_Product__c.object-meta.xml
<CustomObject>
    <label>RE Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Product__c/fields/RE_Country__c.field-meta.xml
<CustomField>
    <fullName>RE_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipName>Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_Country_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Country_Name__c</fullName>
    <label>Country Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RT_Revolution_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Sales_Tax__c/RE_Sales_Tax__c.object-meta.xml
<CustomObject>
    <label>Sales Tax</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Sales Tax Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Tax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Sales_Tax__c/fields/RE_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Type__c</fullName>
    <label>Product Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_Sales_Tax__c/fields/RE_Region__c.field-meta.xml
<CustomField>
    <fullName>RE_Region__c</fullName>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Peninsular</fullName>
            </value>
            <value>
                <fullName>Sabah</fullName>
            </value>
            <value>
                <fullName>Sarawak</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Sales_Tax__c/fields/RE_Tax_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Tax_Unit__c</fullName>
    <label>Tax Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RE_Rate_Unit_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Sales_Tax__c/fields/RE_Valid_From__c.field-meta.xml
<CustomField>
    <fullName>RE_Valid_From__c</fullName>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_Sales_Tax__c/fields/RE_Valid_To__c.field-meta.xml
<CustomField>
    <fullName>RE_Valid_To__c</fullName>
    <label>Valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_SG_CostPrice__c/RE_SG_CostPrice__c.object-meta.xml
<CustomObject>
    <label>Cost Price - Singapore</label>
    <nameField>
        <displayFormat>RE-SG-C{000000}</displayFormat>
        <label>CostPriceName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Price - Singapore</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_SG_CostPrice__c/fields/RE_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipLabel>Cost Price - Singapore</relationshipLabel>
    <relationshipName>Cost_Price_Singapore</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/RE_Rate_Unit_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MYR CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/TON</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>USD/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>USD/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>USD/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>BBL</fullName>
    </customValue>
    <customValue>
        <fullName>LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR</fullName>
    </customValue>
    <customValue>
        <fullName>THB/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>STG/LTR</fullName>
    </customValue>
    <description>Rate Units to be used in  Revolution East Applicaion</description>
    <masterLabel>RE_Rate_Unit_Set</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/RT_Revolution_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TU</fullName>
        <label>Turkey</label>
    </customValue>
    <customValue>
        <fullName>MY</fullName>
        <label>Malaysia</label>
    </customValue>
    <customValue>
        <fullName>TH</fullName>
        <label>Thailand</label>
    </customValue>
    <customValue>
        <fullName>PH</fullName>
        <label>Philippines</label>
    </customValue>
    <customValue>
        <fullName>SG</fullName>
        <label>Singapore</label>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
        <label>Canada</label>
    </customValue>
    <masterLabel>Revolution Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RE_TestDataFactory.cls
/* ****************************************************************************************************************
* Class Name 	: RE_TestDataFactory
* Created Date	: 07-Sep-2022
* Purpose		: DataFactory class for test class data creation
* Imporant Note : ***** PLEASE ADD ANY MANDATORY FIELDS AS REQUIRED IN FUTURE FOR THE EASE OF OTHERS *****
* Author        : K. Nandeeswara Raju (n.kondur@shell.com)
* Modification#1: Name  - Date  - Description
* *****************************************************************************************************************/
@isTest
public class RE_TestDataFactory {

    public static User createUser(String frstName, String lastName, Id userRoleId, Id profileId){
        User u	= new User();
        u.LastName		= lastName;
        u.FirstName	    = frstName;
        u.Alias		    = frstName.substring(0, 2)+'t';
        u.Email		    = frstName+lastName+'@mail.com';
        u.Username		= frstName+lastName+'@mail.com.reveast';
        u.CommunityNickname	= frstName+'Nickname';
        u.UserRoleId	= userRoleId;
        u.TimeZoneSidKey    = 'America/Los_Angeles';
        u.EmailEncodingKey  = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey  = 'en_US';
        u.ProfileId	    = profileId;
        return u;
    }

    //Create RE_Product__c records
    public static RE_Product__c createREProduct(String reProdName, Id reProdCountryId, Id reProdRecTypeId){
        RE_Product__c prod = new RE_Product__c ();
        prod.Name           = reProdName;
        prod.RE_Country__c  = reProdCountryId;
        prod.RecordTypeId   = reProdRecTypeId;
        return prod;
    }

    //Create RE_SG_CostPrice__c records
    public static RE_SG_CostPrice__c createRESGCostPrice(Boolean reIsLatestBool, Datetime rePricingDate){
        RE_SG_CostPrice__c sgcp = new RE_SG_CostPrice__c ();
        sgcp.RE_IsLatest__c     = reIsLatestBool;
        sgcp.RE_Pricing_Date__c = rePricingDate;
        return sgcp;
    }

    //Create RE_Market_Quotes__c records
    public static RE_Market_Quotes__c createREMarketQuote(Decimal rePrice, String reQuoteName, Date rePricingDate, String reTracker){
        RE_Market_Quotes__c mq = new RE_Market_Quotes__c ();
        mq.RE_Price__c          = rePrice;
        mq.RE_Quote_Name__c     = reQuoteName;
        mq.RE_Pricing_Date__c   = rePricingDate;
        mq.RE_Tracker__c        = reTracker;
        mq.RE_Country_Name__c   = 'SG;PH;TH;MY';
        return mq;
    }

    //Create RE_MY_Output__c records
    public static RE_MY_Output__c createREMyOutput(String reRegion, Integer reJobRunCount, String reType, String reDepotName, Boolean reIsLatest, Date rePricingDate){
        RE_MY_Output__c op = new RE_MY_Output__c ();
        op.RE_Region__c         = reRegion;
        op.RE_Job_Run_Count__c  = reJobRunCount;
        op.RE_Type__c           = reType;
        op.RE_Depot_Name__c     = reDepotName;
        op.RE_IsLatest__c       = reIsLatest;
        op.RE_Pricing_Date__c   = rePricingDate;
        return op;
    }

    //Create RE_Depot_Pricing_Backbone__c records
    public static RE_Depot_Pricing_Backbone__c createREDepotPricingBackBone(Id reCountryId, Id recordTypeId, Id reDepotId, Id reProdId, Date validFrom, Date validTo){
        RE_Depot_Pricing_Backbone__c dpb = new RE_Depot_Pricing_Backbone__c ();
        dpb.RE_Country__c   = reCountryId;
        dpb.RecordTypeId    = recordTypeId;
        dpb.RE_Depot_Name__c = reDepotId;
        dpb.RE_Product_Name__c  = reProdId;
        dpb.RE_Valid_From__c= validFrom;
        dpb.RE_Valid_To__c  = validTo;
        return dpb;
    }

    //Create RE_FX_Rates__c record
    public static RE_FX_Rates__c createREFxRate(String reForexName, Decimal reForexRate, String reBaseUnit, String reConversionUnit, DateTime rePricingDateTime, String reTradeType, String reTracker){
        RE_FX_Rates__c fr = new RE_FX_Rates__c ();
        fr.RE_Forex_Name__c = reForexName;
        fr.RE_Forex_Rate__c = reForexRate;
        fr.RE_Base_Unit__c = reBaseUnit;
        fr.RE_Conversion_Unit__c = reConversionUnit;
        fr.RE_Pricing_Date__c = rePricingDateTime;
        fr.RE_Trade_Type__c   = reTradeType;
        fr.RE_Tracker__c      = reTracker;
        return fr;
    }

    //Create RE_Sales_Tax__c record
    public static RE_Sales_Tax__c createRESalesTax(String reProdType, String reTaxUnit, String reRegion, Date reValidFrom, Date reValidTo, Date rePublishDate){
        RE_Sales_Tax__c st = new RE_Sales_Tax__c();
        st.RE_Product_Type__c   = reProdType;
        st.RE_Tax_Unit__c       = reTaxUnit;
        st.RE_Region__c         = reRegion;
        st.RE_Valid_From__c     = reValidFrom;
        st.RE_Valid_To__c       = reValidTo;
        st.RE_Publish_Date__c   = rePublishDate;
        return st;
    }

    //Create RE_Rate_Unit_Manager__c record
    public static RE_Rate_Unit_Manager__c createRateUnitManagerCS(String csName, String reRateUnit, String reCurrencyUnit, String reVolUnit){
        RE_Rate_Unit_Manager__c cs = new RE_Rate_Unit_Manager__c ();
        cs.Name                  = csName;
        cs.RE_Rate_Unit__c       = reRateUnit;
        cs.RE_Currency_Unit__c   = reCurrencyUnit;
        cs.RE_Volume_Unit__c     = reVolUnit;
        return cs;
    }
    
}