force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/RE_Depot_Pricing_Backbone__c.object-meta.xml
<CustomObject>
    <label>Depot Pricing Backbone</label>
    <nameField>
        <displayFormat>DPB-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depot Pricing Backbone</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Cost_Price_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>RE_Cost_Price_Adjustment__c</fullName>
    <label>Cost Price Adjustment</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Depot_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Depot_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Depot Name</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Final_Price_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Final_Price_Unit__c</fullName>
    <label>Final Price Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RE_Rate_Unit_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Fixed_Premium__c.field-meta.xml
<CustomField>
    <fullName>RE_Fixed_Premium__c</fullName>
    <label>Fixed Premium</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Location_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Location_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location Name</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone (Location Name)</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone_CND_Loc</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/fields/RE_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipLabel>Depot Pricing Backbone</relationshipLabel>
    <relationshipName>Depot_Pricing_Backbone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_Depot_Pricing_Backbone__c/recordTypes/Singapore.recordType-meta.xml
<RecordType>
    <fullName>Singapore</fullName>
    <active>true</active>
    <label>Singapore</label>
</RecordType>

force-app/main/default/objects/RE_Job_Run_Audit__c/RE_Job_Run_Audit__c.object-meta.xml
<CustomObject>
    <label>Job Run Audit</label>
    <nameField>
        <displayFormat>JR-{00000000}</displayFormat>
        <label>Job Run Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Run Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Exception__c.field-meta.xml
<CustomField>
    <fullName>RE_Exception__c</fullName>
    <label>Exception</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_IsSuccess__c.field-meta.xml
<CustomField>
    <fullName>RE_IsSuccess__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSuccess</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RE_Job_Run_Audit__c/fields/RE_Job_Type__c.field-meta.xml
<CustomField>
    <fullName>RE_Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Malaysia Output</fullName>
            </value>
            <value>
                <fullName>Singapore Output</fullName>
            </value>
            <value>
                <fullName>SG Midday Output</fullName>
            </value>
            <value>
                <fullName>Malaysia AMV Output</fullName>
            </value>
            <value>
                <fullName>Thailand Output</fullName>
            </value>
            <value>
                <fullName>CustomerOps Output</fullName>
            </value>
            <value>
                <fullName>New Contract Pricing Output</fullName>
            </value>
            <value>
                <fullName>Thailand AMV Output</fullName>
            </value>
            <value>
                <fullName>MY Export Report</fullName>
            </value>
            <value>
                <fullName>MY Customer Opps CBU</fullName>
            </value>
            <value>
                <fullName>Philippines Output</fullName>
            </value>
            <value>
                <fullName>Canada Daily Reuters Quote Move</fullName>
            </value>
            <value>
                <fullName>Canada Execute Depo Pricing</fullName>
            </value>
            <value>
                <fullName>Canada Pricing Recalculation</fullName>
            </value>
            <value>
                <fullName>Canada SFJ Record Creation</fullName>
            </value>
            <value>
                <fullName>Canada Live OPIS Spot Ticker Processing</fullName>
            </value>
            <value>
                <fullName>Canada Market Move Calculation</fullName>
            </value>
            <value>
                <fullName>Canada Competitor Data Processing</fullName>
            </value>
            <value>
                <fullName>Canada GSAP Upload</fullName>
            </value>
            <value>
                <fullName>Canada Email Output</fullName>
            </value>
            <value>
                <fullName>MY Data Analysis Report</fullName>
            </value>
            <value>
                <fullName>PH Customer Opps CBU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RE_Market_Quotes__c/RE_Market_Quotes__c.object-meta.xml
<CustomObject>
    <label>RE Market Quotes</label>
    <nameField>
        <displayFormat>MarketQuote-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RE Market Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Market_Quotes__c/fields/RE_IsMidday__c.field-meta.xml
<CustomField>
    <fullName>RE_IsMidday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsMidday</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/RE_Product__c.object-meta.xml
<CustomObject>
    <label>RE Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RE Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_Product__c/fields/RE_Additive_Cost__c.field-meta.xml
<CustomField>
    <fullName>RE_Additive_Cost__c</fullName>
    <label>Additive Cost</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_Midday_MC0_Valid_From__c.field-meta.xml
<CustomField>
    <fullName>RE_Midday_MC0_Valid_From__c</fullName>
    <label>Midday MC0 Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_Midday_MC0_Valid_To__c.field-meta.xml
<CustomField>
    <fullName>RE_Midday_MC0_Valid_To__c</fullName>
    <label>Midday MC0 Valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_Midday_MC0_Value__c.field-meta.xml
<CustomField>
    <fullName>RE_Midday_MC0_Value__c</fullName>
    <label>Midday MC0 Value</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_Morning_MC0_Valid_From__c.field-meta.xml
<CustomField>
    <fullName>RE_Morning_MC0_Valid_From__c</fullName>
    <label>Morning MC0 Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_Morning_MC0_Valid_To__c.field-meta.xml
<CustomField>
    <fullName>RE_Morning_MC0_Valid_To__c</fullName>
    <label>Morning MC0 Valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/fields/RE_Morning_MC0_Value__c.field-meta.xml
<CustomField>
    <fullName>RE_Morning_MC0_Value__c</fullName>
    <label>Morning MC0 Value</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_Product__c/recordTypes/Singapore.recordType-meta.xml
<RecordType>
    <fullName>Singapore</fullName>
    <active>true</active>
    <label>Singapore</label>
</RecordType>

force-app/main/default/objects/RE_SG_Cost_Price_Manager__mdt/RE_SG_Cost_Price_Manager__mdt.object-meta.xml
<CustomObject>
    <label>RE_SG_Cost Price Manager</label>
    <pluralLabel>RE_SG_Cost Price Manager</pluralLabel>
</CustomObject>

force-app/main/default/objects/RE_SG_CostPrice__c/RE_SG_CostPrice__c.object-meta.xml
<CustomObject>
    <label>Cost Price - Singapore</label>
    <nameField>
        <displayFormat>RE-SG-C{000000}</displayFormat>
        <label>CostPriceName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Price - Singapore</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RE_SG_CostPrice__c/fields/RE_Cost_Price_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>RE_Cost_Price_Adjustment__c</fullName>
    <label>Cost Price Adjustment</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_SG_CostPrice__c/fields/RE_Costprice_Marginal_Cost__c.field-meta.xml
<CustomField>
    <fullName>RE_Costprice_Marginal_Cost__c</fullName>
    <label>MC (USD CTS/LTR)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_SG_CostPrice__c/fields/RE_Costprice_Unit__c.field-meta.xml
<CustomField>
    <fullName>RE_Costprice_Unit__c</fullName>
    <label>Costprice Unit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RE_SG_CostPrice__c/fields/RE_FX_Laid_Down_Cost__c.field-meta.xml
<CustomField>
    <fullName>RE_FX_Laid_Down_Cost__c</fullName>
    <label>LDC (SGD CTS/LTR)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_SG_CostPrice__c/fields/RE_Hydrocarbon_Value__c.field-meta.xml
<CustomField>
    <fullName>RE_Hydrocarbon_Value__c</fullName>
    <label>Hydrocarbon Value</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_SG_CostPrice__c/fields/RE_Location_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Location_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location Name</label>
    <referenceTo>RE_Location__c</referenceTo>
    <relationshipLabel>Cost Price - Singapore</relationshipLabel>
    <relationshipName>Cost_Price_Singapore</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RE_SG_CostPrice__c/fields/RE_Mark_Up_Credit_Charge__c.field-meta.xml
<CustomField>
    <fullName>RE_Mark_Up_Credit_Charge__c</fullName>
    <label>Mark-Up &amp; Credit Charge</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_SG_CostPrice__c/fields/RE_Market_Premium__c.field-meta.xml
<CustomField>
    <fullName>RE_Market_Premium__c</fullName>
    <label>Market Premium</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RE_SG_CostPrice__c/fields/RE_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>RE_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>RE_Product__c</referenceTo>
    <relationshipLabel>Cost Price - Singapore</relationshipLabel>
    <relationshipName>Cost_Price_Singapore</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/RE_Rate_Unit_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MYR CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR/TON</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>USD CTS/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD/BBL</fullName>
    </customValue>
    <customValue>
        <fullName>USD/CBM</fullName>
    </customValue>
    <customValue>
        <fullName>USD/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>USD/TON</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>BBL</fullName>
    </customValue>
    <customValue>
        <fullName>LTR</fullName>
    </customValue>
    <customValue>
        <fullName>MYR</fullName>
    </customValue>
    <customValue>
        <fullName>THB/LTR</fullName>
    </customValue>
    <customValue>
        <fullName>STG/LTR</fullName>
    </customValue>
    <description>Rate Units to be used in  Revolution East Applicaion</description>
    <masterLabel>RE_Rate_Unit_Set</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RE_SG_CostCalculation.cls
public class RE_SG_CostCalculation {  
    RE_SOQLController soqldata = new RE_SOQLController();
    //Get latest Depot pricing data  
    public List<RE_Depot_Pricing_Backbone__c> depotpricinglist = soqldata.fetchSGDepotpricingData();
    //Get Market Quotes Data
    public List<RE_Market_Quotes__c> latestmarketquotes;
    //Get Singapore formula data
    public List<RE_SG_Cost_Price_Manager__mdt> sgformulalist = soqldata.fetchSingaporeformulaData();
    //Get Singapore product data
    public List<RE_Product__c> productlist = RE_SOQLController.fetchSingaporeprodData();
    //Get Latest Fx Data
    public Map<String,Double> curConvMap;
    public Double curconvDD = soqldata.fetchLastMondayFxData();
    public Double currencyConversionMultipler;
    public List<RE_MY_FormulaFetchController.formulaWrapperSG> formWrapList = new List<RE_MY_FormulaFetchController.formulaWrapperSG>();

    public RE_UtilitywrapperController.lineitemwraapper finalhcval;
    public RE_UtilitywrapperController.lineitemwraapper finalmpval;
    public RE_UtilitywrapperController.lineitemwraapper finalsahval;
    public RE_UtilitywrapperController.lineitemwraapper finalmasval;
    public RE_UtilitywrapperController.lineitemwraapper finalolval;
    public RE_UtilitywrapperController.lineitemwraapper finalptval;
    public RE_UtilitywrapperController.lineitemwraapper finalacval;
    public RE_UtilitywrapperController.lineitemwraapper finalddval;
    public RE_UtilitywrapperController.lineitemwraapper finalfpval;
    public RE_UtilitywrapperController.lineitemwraapper finalcpaval;

    public Map<Id, Double> finalmccval = new Map<Id, Double>();
    public Map<Id,Double> laiddownCostMap = new Map<Id,Double>();
    public Map<Id,Double> marginalCostMap = new Map<Id,Double>();
    public Map<Id,Double> laiddownCostMapSG = new Map<Id,Double>();
    public Map<Id,Double> marginalCostMapSG = new Map<Id,Double>();
    public String errormessage = '';

    public Boolean lineItemsCalculation(RE_Job_Run_Audit__c jra){
        if(!depotpricinglist.isEmpty()){
            RE_MY_FormulaFetchController ffcntrlr = new RE_MY_FormulaFetchController();
            formWrapList = ffcntrlr.formulaforDepotDataSG(depotpricinglist,sgformulalist);
            system.debug(formWrapList);
            if(jra.RE_Job_Type__c == 'Singapore Output'){
                latestmarketquotes = soqldata.fetchMarketQuotesData();
				curConvMap = soqldata.fetchLatestFxData();				                
            }
            else if(jra.RE_Job_Type__c == 'SG Midday Output'){
                latestmarketquotes = soqldata.fetchMiddayMarketQuotesData();
				curConvMap = soqldata.fetchLatestMidFxData();				
            }
			currencyConversionMultipler = curConvMap.get('SGD-USD');                  
            RE_SG_HCVController hcvcal = new RE_SG_HCVController();
            finalhcval = hcvcal.hcfDataPreparation(formWrapList,curConvMap,latestmarketquotes);
            errormessage = errormessage + finalhcval.errorMessage;
            RE_MY_MarketPremiumController mpval = new RE_MY_MarketPremiumController();
            finalmpval = mpval.marketPremiumPreparationSG(formWrapList,curConvMap,latestmarketquotes);
            errormessage = errormessage + finalmpval.errorMessage;
            RE_MY_StorageAndHandlingTariffController sahval = new RE_MY_StorageAndHandlingTariffController();
            finalsahval = sahval.shtPreparation(depotpricinglist,curConvMap);
            errormessage = errormessage + finalsahval.errorMessage;
            RE_MY_MarketingSellingTariffController masval = new RE_MY_MarketingSellingTariffController();
            finalmasval = masval.mstPreparation(depotpricinglist,curConvMap);
            errormessage = errormessage + finalmasval.errorMessage;
            RE_MY_PrimaryTransportCostController ptcval = new RE_MY_PrimaryTransportCostController();
            finalptval = ptcval.primaryTransportCostpreparation(depotpricinglist,curConvMap);
            errormessage = errormessage + finalptval.errorMessage;
            RE_MY_AdditiveCostController acval = new RE_MY_AdditiveCostController();
            finalacval = acval.additivecostCalculation(depotpricinglist,productlist,curConvMap);
            errormessage = errormessage + finalacval.errorMessage;
            RE_SG_DistDiscController ddval = new RE_SG_DistDiscController();
            finalddval = ddval.distdiscPreparation(formWrapList,curConvMap,latestmarketquotes);
            errormessage = errormessage + finalddval.errorMessage;
            RE_SG_FixedPremiumController fpval = new RE_SG_FixedPremiumController();
            finalfpval = fpval.fixedPremiumPreparation(depotpricinglist,curConvMap);
            errormessage = errormessage + finalfpval.errorMessage;
            RE_SG_OilLossController olval = new RE_SG_OilLossController();
            finalolval = olval.olDataPreparation(formWrapList,finalhcval.finalval,finalmpval.finalval);
            errormessage = errormessage + finalolval.errorMessage;
            RE_SG_CostPriceAdjustmentController cpval = new RE_SG_CostPriceAdjustmentController();
            finalcpaval = cpval.cpaPreparation(depotpricinglist, curConvMap);
            errormessage = errormessage + finalcpaval.errorMessage;
            finalmccval = MarkUpCreditChargeCalculation();
            marginallaidDownCostCalculation(true);
            marginallaidDownCostCalculation(false);
            return finalCostingData(jra);
        }
        return false;
    }


    public Map<Id, Double> MarkUpCreditChargeCalculation(){
        Double mccpercentage = Double.valueOf(System.Label.RE_SG_MarkUp_Credit_Charge_Percentage);
        Double mccminVal = Double.valueOf(System.Label.RE_SG_MarkUp_Credit_Charge_Min_Value);
        for(RE_Depot_Pricing_Backbone__c dpbdata : depotpricinglist){
            Double Markupvalue =0;
            Double finalMarkupCredit =0;
            if(finalhcval.finalval.containsKey(dpbdata.Id))
                Markupvalue = Markupvalue + finalhcval.finalval.get(dpbdata.Id);
            if(finalmpval.finalval.containsKey(dpbdata.Id))
                Markupvalue = Markupvalue + finalmpval.finalval.get(dpbdata.Id);
            if(finalsahval.finalval.containsKey(dpbdata.Id))
                Markupvalue = Markupvalue + finalsahval.finalval.get(dpbdata.Id);
            if(finalmasval.finalval.containsKey(dpbdata.Id))
                Markupvalue = Markupvalue + finalmasval.finalval.get(dpbdata.Id);
            if(finalolval.finalval.containsKey(dpbdata.Id))
                Markupvalue = Markupvalue + finalolval.finalval.get(dpbdata.Id);
            if(finalptval.finalval.containsKey(dpbdata.Id))
                Markupvalue = Markupvalue + finalptval.finalval.get(dpbdata.Id);
            if(finalacval.finalval.containsKey(dpbdata.Id))
                Markupvalue = Markupvalue + finalacval.finalval.get(dpbdata.Id);
            if(finalddval.finalval.containsKey(dpbdata.Id))
                Markupvalue = Markupvalue + finalddval.finalval.get(dpbdata.Id);
            if(finalfpval.finalval.containsKey(dpbdata.Id))
                Markupvalue = Markupvalue + finalfpval.finalval.get(dpbdata.Id);
            finalMarkupCredit = (Markupvalue*mccpercentage*30/365) > mccminVal ? (Markupvalue*mccpercentage*30/365) : mccminVal;
            finalmccval.put(dpbdata.Id,finalMarkupCredit);
        }
        return finalmccval;
    }

    public void marginallaidDownCostCalculation(Boolean Isfxdata){
        for(RE_Depot_Pricing_Backbone__c dpbdata : depotpricinglist){
            Double marginalCost = 0;
            Double laidDownCost = 0;
            if(finalhcval.finalval.containsKey(dpbdata.Id))
                marginalCost = marginalCost + finalhcval.finalval.get(dpbdata.Id);
            if(finalmpval.finalval.containsKey(dpbdata.Id))
                marginalCost = marginalCost + finalmpval.finalval.get(dpbdata.Id);
            if(finalsahval.finalval.containsKey(dpbdata.Id))
                marginalCost = marginalCost + finalsahval.finalval.get(dpbdata.Id);
            if(finalptval.finalval.containsKey(dpbdata.Id))
                marginalCost = marginalCost + finalptval.finalval.get(dpbdata.Id);
            if(finalacval.finalval.containsKey(dpbdata.Id))
                marginalCost = marginalCost + finalacval.finalval.get(dpbdata.Id);
            if(finalolval.finalval.containsKey(dpbdata.Id))
                marginalCost = marginalCost + finalolval.finalval.get(dpbdata.Id);            
            if(finalcpaval.finalval.containsKey(dpbdata.Id))
                marginalCost = marginalCost + finalcpaval.finalval.get(dpbdata.Id);
            if(Isfxdata){                
                if(finalddval.finalval.containsKey(dpbdata.Id)){
                    if(dpbdata.RE_IsDistillisationRate__c)
                 		marginalCost = currencyConversionMultipler * marginalCost + curconvDD * finalddval.finalval.get(dpbdata.Id);   
                    else
                        marginalCost = currencyConversionMultipler * (marginalCost + finalddval.finalval.get(dpbdata.Id));   
                }                    
                if(finalfpval.finalval.containsKey(dpbdata.Id)){
                    if(dpbdata.RE_IsDistillisationRate__c)
                 		marginalCost = marginalCost + curconvDD * finalfpval.finalval.get(dpbdata.Id);  
                    else
                        marginalCost = marginalCost + currencyConversionMultipler * finalfpval.finalval.get(dpbdata.Id);  
                }                	
                marginalCostMapSG.put(dpbdata.Id, marginalCost);
                if(finalmccval.containsKey(dpbdata.Id))
                    laidDownCost = marginalCost + currencyConversionMultipler * finalmccval.get(dpbdata.Id);
                if(finalmasval.finalval.containsKey(dpbdata.Id))
                    laidDownCost = laidDownCost + currencyConversionMultipler * finalmasval.finalval.get(dpbdata.Id);
                laiddownCostMapSG.put(dpbdata.Id,laidDownCost);
            }
            else{
                if(finalddval.finalval.containsKey(dpbdata.Id))
                    marginalCost = marginalCost + finalddval.finalval.get(dpbdata.Id);
                marginalCostMap.put(dpbdata.Id, marginalCost);
                if(finalmccval.containsKey(dpbdata.Id))
                    laidDownCost = marginalCost + finalmccval.get(dpbdata.Id);
                if(finalmasval.finalval.containsKey(dpbdata.Id))
                    laidDownCost = laidDownCost + finalmasval.finalval.get(dpbdata.Id);
                laiddownCostMap.put(dpbdata.Id,laidDownCost);
            }

        }
    }

    public Boolean finalCostingData(RE_Job_Run_Audit__c jra){
        Boolean Issuccess;
        if(String.isEmpty(errormessage)){
            List<RE_SG_CostPrice__c> costingList = new List<RE_SG_CostPrice__c>();
            List<RE_SG_CostPrice__c> updateLatestData = new List<RE_SG_CostPrice__c>();
            Integer jobCount = 0;
            
            if(jra.RE_Job_Type__c == 'Singapore Output'){
                List<RE_SG_CostPrice__c> costDataLatest = [SELECT RE_IsLatest__c FROM RE_SG_CostPrice__c WHERE RE_IsLatest__c = True AND RE_IsMidday__c = False];
                if(!costDataLatest.isEmpty()){
                    for(RE_SG_CostPrice__c costSG : costDataLatest){
                        costSG.RE_IsLatest__c = False;
                        updateLatestData.add(costSG);
                    }
                }
                
                List<RE_Job_Run_Audit__c> costDataToday = [SELECT RE_Job_Run_Count__c FROM RE_Job_Run_Audit__c
                WHERE createddate = Today AND RE_Job_Type__c = 'Singapore Output' ORDER BY RE_Job_Run_Count__c DESC LIMIT 1];
                if(!costDataToday.isEmpty())
                    jobCount = Integer.valueOf(costDataToday[0].RE_Job_Run_Count__c);
            }
            else if(jra.RE_Job_Type__c == 'SG Midday Output'){
                List<RE_SG_CostPrice__c> costDataLatest = [SELECT RE_IsLatest__c FROM RE_SG_CostPrice__c WHERE RE_IsLatest__c = True AND RE_IsMidday__c = True];
                if(!costDataLatest.isEmpty()){
                    for(RE_SG_CostPrice__c costSG : costDataLatest){
                        costSG.RE_IsLatest__c = False;
                        updateLatestData.add(costSG);
                    }
                }
                
                List<RE_Job_Run_Audit__c> costDataToday = [SELECT RE_Job_Run_Count__c FROM RE_Job_Run_Audit__c
                WHERE createddate = Today AND RE_Job_Type__c = 'SG Midday Output' ORDER BY RE_Job_Run_Count__c DESC LIMIT 1];
                if(!costDataToday.isEmpty())
                    jobCount = Integer.valueOf(costDataToday[0].RE_Job_Run_Count__c);
            }
            
            for(RE_Depot_Pricing_Backbone__c dpbdata : depotpricinglist){
                RE_SG_CostPrice__c costData = new RE_SG_CostPrice__c();
                if(jra.RE_Job_Type__c == 'SG Midday Output')
                    costData.RE_IsMidday__c = True;
                else
                    costData.RE_IsMidday__c = False;
                costData.RE_Job_Run_Count__c = jobCount;
                costData.RE_IsLatest__c = True;
                costData.RE_Location_Name__c = dpbdata.RE_Depot_Name__c;
                costData.RE_Product_Name__c = dpbdata.RE_Product_Name__c;
                costData.RE_Costprice_Unit__c = dpbdata.RE_Final_Price_Unit__c;
                costData.RE_Pricing_Date__c = System.today();
                if(finalhcval.finalval.containsKey(dpbdata.Id))
                    costData.RE_Hydrocarbon_Value__c = finalhcval.finalval.get(dpbdata.Id);
                if(laiddownCostMap.containsKey(dpbdata.Id))
                    costData.RE_Costprice_Laid_Down_Cost__c = laiddownCostMap.get(dpbdata.Id);
                if(laiddownCostMapSG.containsKey(dpbdata.Id))
                    costData.RE_FX_Laid_Down_Cost__c = laiddownCostMapSG.get(dpbdata.Id);
                if(marginalCostMap.containsKey(dpbdata.Id))
                    costData.RE_Costprice_Marginal_Cost__c = marginalCostMap.get(dpbdata.Id);
                if(marginalCostMapSG.containsKey(dpbdata.Id))
                    costData.RE_FX_Marginal_Cost__c = marginalCostMapSG.get(dpbdata.Id);
                if(finalmasval.finalval.containsKey(dpbdata.Id))
                    costData.RE_Marketing_Selling_Tariff__c = finalmasval.finalval.get(dpbdata.Id);
                if(finalolval.finalval.containsKey(dpbdata.Id))
                    costData.RE_Oil_Loss__c = finalolval.finalval.get(dpbdata.Id);
                if(finalptval.finalval.containsKey(dpbdata.Id))
                    costData.RE_Primary_Transport_Cost__c = finalptval.finalval.get(dpbdata.Id);
                if(finalsahval.finalval.containsKey(dpbdata.Id))
                    costData.RE_Storage_Handling_Cost__c = finalsahval.finalval.get(dpbdata.Id);
                if(finalmccval.containsKey(dpbdata.Id))
                    costData.RE_Mark_Up_Credit_Charge__c = finalmccval.get(dpbdata.Id);
                if(finalacval.finalval.containsKey(dpbdata.Id))
                    costData.RE_Additive_Cost__c = finalacval.finalval.get(dpbdata.Id);
                if(finalmpval.finalval.containsKey(dpbdata.Id))
                    costData.RE_Market_Premium__c = finalmpval.finalval.get(dpbdata.Id);
                if(finalddval.finalval.containsKey(dpbdata.Id))
                    costData.RE_Distillation_Discount__c = finalddval.finalval.get(dpbdata.Id);
                if(finalfpval.finalval.containsKey(dpbdata.Id))
                    costData.RE_Fixed_Premium__c = finalfpval.finalval.get(dpbdata.Id);
                if(finalcpaval.finalval.containsKey(dpbdata.Id))
                    costData.RE_Cost_Price_Adjustment__c = finalcpaval.finalval.get(dpbdata.Id);
                if(dpbdata.RE_Product_Name__r.Name == 'IGO 10ppm'){
                    RE_Product__c igoprod;
                    for(RE_Product__c productdata : productlist){
                        if(productdata.Name == dpbdata.RE_Product_Name__r.Name)
                            igoprod = productdata;
                    }
                    
                    if(jra.RE_Job_Type__c == 'Singapore Output'){
                        if(igoprod.RE_Morning_MC0_Value__c != null && 
						   igoprod.RE_Morning_MC0_Valid_From__c <= System.today() && 
						   igoprod.RE_Morning_MC0_Valid_To__c >= System.today()){
							costData.RE_MC0_Diff__c = costData.RE_FX_Marginal_Cost__c - igoprod.RE_Morning_MC0_Value__c * currencyConversionMultipler * 100/Double.valueOf(System.Label.RE_BBL_to_LTR);
						}	
                        else{
                            costData.RE_MC0_Diff__c = costData.RE_FX_Marginal_Cost__c;
                        }
                    }
                    else{
                        if(igoprod.RE_Midday_MC0_Value__c != null && 
						   igoprod.RE_Midday_MC0_Valid_From__c <= System.today() && 
						   igoprod.RE_Midday_MC0_Valid_To__c >= System.today()){
							costData.RE_MC0_Diff__c = costData.RE_FX_Marginal_Cost__c - igoprod.RE_Midday_MC0_Value__c * currencyConversionMultipler * 100/Double.valueOf(System.Label.RE_BBL_to_LTR);
						}	
                        else{
                            costData.RE_MC0_Diff__c = costData.RE_FX_Marginal_Cost__c;
                        }
                    }                    
                }
                costingList.add(costData);
            }
            if(!costingList.isEmpty()){
                try{
                    if(!updateLatestData.isEmpty())
                        update updateLatestData;
                    insert costingList;
                    Issuccess = True;
                }
                catch(Exception e){
                    Issuccess = False;
                    System.debug('RE_SG_CostCalculation-finalCostingData-Error-->'+e.getMessage());
                    System.debug('RE_SG_CostCalculation-finalCostingData-Error-LN-->'+e.getLineNumber());
                    RV_ClassException.insertExceptionRecord('finalCostingData',e.getMessage()+'-'+e.getLineNumber(),'RE_SG_CostCalculation','finalCostingData','Exception');
                }
            }
        }
        else{
            Issuccess = False;
        }
        try{
            jra.RE_IsSuccess__c = Issuccess;
            jra.RE_Exception__c = errormessage;
            update jra;
        }
        catch(Exception e){
            System.debug('RE_SG_CostCalculation-finalCostingData-Update JRA-Error-->'+e.getMessage());
            System.debug('RE_SG_CostCalculation-finalCostingData-Update JRA-Error-LN-->'+e.getLineNumber());
            RV_ClassException.insertExceptionRecord('finalCostingData-Update JRA-',e.getMessage()+'-'+e.getLineNumber(),'RE_SG_CostCalculation','finalCostingData','Exception');
        }
        return Issuccess;
    }
}